### ISSUE TITLE
Reduce methods in the Node namespace

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida-core#1004]
Breakout from #201 

> We should redesign the node class (and its subclasses) to avoid that there are too many methods 'cluttering' the namespace for every node (to discuss)

**Comment by sphuber** [comment]
After the `Node` class is moved to the new backend interface implementation (see #2233), which should happen for `v1.0.0`, then the new methods can be added and the old deprecated for `v1.1.0`. In `v2.0.0` the deprecated methods can be removed

**Comment by sphuber** [comment]
This issue is too broad. The `Node` class is the main class of AiiDA and will always have a large interface. If we want to address this we should probably come up with a detailed description of the maximum number of methods and attributes in the namespace
