### ISSUE TITLE
documentation on tests creation is outdated

### ISSUE THREAD

**Issue by nmounet** [aiidateam/aiida-core#1071]
The documentation on tests is outdated.
For instance, `db_test_list` is not where indicated, but in `aiida.backends.tests.__init__.py`.

**Comment by giovannipizzi** [comment]
Check if this is still true and fix this

**Comment by ltalirz** [comment]
After the move to pytest, the original issue no longer applies.
We'll still need to update the test writing docs (now on the [wiki](https://github.com/aiidateam/aiida-core/wiki/Writing-tests)) but that's another story.
