### ISSUE TITLE
Use of lists as arguments to a workfunction

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#1172]
Currently it is not possible to submits a workfunction with a list, containing aiida type objects. Here is a simple example which does not work:

```
from aiida.work.workfunctions import workfunction as wf
from aiida.orm.data.base import Float

n1 = load_node(3746)
n2 = load_node(3735)

l = [n1, n2]


@wf
def average_ener(*args):
    res = 0.0
    i=1
    for item in args:
        res += item.out.output_parameters.dict.energy

    return Float(res/i)

print average_ener(*l) 

```

The average_ener() function should return an average energy of two calculations, however, now it returns  0. That means that function does not receive the arguments. It does not raise an error either.

Therefore, we need to decide whether we want to implement handling the arrays, or we do not allow it and raise an error.

**Comment by sphuber** [comment]
I just tried this out on the latest version of `workflows` and for me it works. Take this example:

```
from aiida.orm.data.float import Float
from aiida.orm.data.int import Int
from aiida.work.workfunctions import workfunction

def average(*args):
    count = 0
    sum = 0.0

    for arg in args:
        count += 1
        sum += arg

    return Float(sum.value / count)

result = average(*[Int(2), Int(3)])
print result
```

will print `2.5` for me. I also tested this on `develop` with small adaptations only to the imports and that also worked. Can you try and run my code and see if that works for you?

**Comment by muhrin** [comment]
Currently this gives a `ValueError: variadic arguments are not supported` exception.  But it would definitely be nice to be able to do this, the only real issue IMHO is how to indicate that this was a variadic argument i.e. what the call the links and how to make sure this doesn't clash with any potential keyword arguments.  One way could be just to use numbers of the arguments but then these wouldn't be accessible as attributes of the inputs dictionary (but dictionary `[]` notation would be fine).  Additionally we need to check if there are currently any restrictions on the names of links (I don't think so).

**Comment by ltalirz** [comment]
Just to give an update on this:

1. Using `args` still does not work on aiida-core 1.0.1 (not sure why it worked for @sphuber but your code example is also missing the decorator)
```python
from aiida.engine import calcfunction

@calcfunction
def average(*args):
    count = 0
    sum = 0.0

    for arg in args:
        count += 1
        sum += arg

    return Float(sum.value / count)

result = average(*[Int(2), Int(3)])
print(result)
```
yields
```
    raise ValueError('variadic arguments are not supported')
ValueError: variadic arguments are not supported
```

2. Using `kwargs` instead works fine:
```python
from aiida.engine import calcfunction

@calcfunction
def average(**kwargs):
    count = 0
    sum = 0.0

    for k,v in kwargs.items():
        count += 1
        sum += v

    return Float(sum.value / count)

result = average(**{'v1': Int(2), 'v2': Int(3) })
print(result)
```
yields
```
$ verdi run cde.py
uuid: 1775972e-78e3-46e9-91e2-c19a684be582 (pk: 27684) value: 2.5
```

I.e. I think
 - [ ] we should fix the behavior for lists
 - [ ] we need to document how to use this (people have been asking about this)
