### ISSUE TITLE
Sphinx extension for workchains should support documenting the outline

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#1198]
The new sphinx extension to auto document `WorkChain` classes currently does not support printing of the outline, which would be a very useful feature to have

**Comment by greschd** [comment]
I've started implementing this, currently looks as follows:

![image](https://user-images.githubusercontent.com/5692808/70757769-1b84f700-1d41-11ea-98fb-55b976fd15c7.png)

Maybe it would be nicer to format it as  "pseudo-python", e.g.
```python
start
while(some_check):
    do_something
    if(another_check):
        do_something_else
finalize
```
Or, to make it clear that these are functions being run:
```python
start()
while(some_check()):
    do_something()
    if(another_check()):
        do_something_else()
finalize()
```
or even 
```python
self.start()
while(self.some_check()):
    self.do_something()
    if(self.another_check()):
        self.do_something_else()
self.finalize()
```
@sphuber @ltalirz, opinions?

**Comment by sphuber** [comment]
I think here it would actually nice to get rid of as much as unnecessary formatting that is just necessary in the real outline to make it work. So I prefer the first example of pseudo-python. Just pure logic as much as possible. Since all statements will always be methods that are called, the `()` is redundant I feel. Not sure about the numbering though.

**Comment by ltalirz** [comment]
@greschd I've taken the liberty to label the 4 options in your comment.

I'm with @sphuber in that I would prefer pseudocode but without numbering, i.e. something like
```python
start
while(some_check)
    do_something
    if(another_check)
        do_something_else
finalize
```

**Comment by greschd** [comment]
So, (B) minus the colon?

**Comment by ltalirz** [comment]
yes

**Comment by greschd** [comment]
In terms of font / styling, do you prefer the code-like one as above, or "normal text" (A without numbers)?

**Comment by ltalirz** [comment]
Do you have screenshots?
I think it's not super important as long as there is some visual hint that that the pseudocode is not part of the regular text

**Comment by sphuber** [comment]
I think a(ny) mono-spaced font would be quite nice though
