### ISSUE TITLE
REST API: instructions unclear when dependencies are missing

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-core#1393]
If a user didn't install aiida with the [REST] extra, and doesn't already have all the required packages, they will receive an import error when attempting to start the "verdi restapi" server. They might then attempt to install the required packages, one by one, until all the dependencies are satisfied. It would be better to tell the user to install aiida with the [REST] extra via pip.

**Comment by ltalirz** [comment]
Apropos: Since people can now use Materials Cloud to browse their AiiDA database, Giovanni suggested we might want to install the `[rest]` extra by default, when installing the `aiida` meta package.

That seems sensible to me as well.

**Comment by ltalirz** [comment]
@giovannipizzi 
1. Regarding improving the error message: Should we try to catch the missing imports?
  We can do that in a few files (api.py, run_api.py) of course, and for a few imports (flask, flask_cors, ...) and cover most use cases, but I wonder whether there is a better way...
2. Should we make the `rest` extra a default or not?
