### ISSUE TITLE
StructureData: Add export to PDB files

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida-core#157]
Originally reported by: **Tiziano Müller (Bitbucket: [dev-zero](https://bitbucket.org/dev-zero), GitHub: [dev-zero](https://github.com/dev-zero))**

----------------------------------------

some codes can (and should use) PDB files as source for coordinates.
Add a method to generate those using `export`/`_prepare_pdb` functions.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/157

**Comment by sphuber** [comment]
Since we haven't had a follow-up on this feature request in 7 years, I am closing this. If there is still a need, this can be reopened
