### ISSUE TITLE
Allow function as default values for WorkChain input.

### ISSUE THREAD

**Issue by mottetm** [aiidateam/aiida-core#1604]
Would it be possible to allow the runtime generation of the default node of a Worchain input.

This would allow to have, for example, random seeds stored in inputs node allowing better reproduciblity:
 
```python
cls.input('seed', valid_type=Int, default=lambda: Int(np.random.randint(2**32 - 1)))
```

**Comment by ltalirz** [comment]
Isn't this more an issue of convenience rather than of better reproducibility?
At the moment, I guess you simply generate the random number outside the workchain and pass it in when you run it, right? I don't see how this affects reproducibility.

Also, what about
```python
cls.input('seed', valid_type=Int, default=Int(np.random.randint(2**32 - 1)))
```

Anyhow, mentioning the experts @muhrin and @sphuber .

**Comment by mottetm** [comment]
Yes the current best way is to generate the seed outside. I just don't find it very convenient.

Concerning:
```python
cls.input('seed', valid_type=Int, default=Int(np.random.randint(2**32 - 1)))
```
If you run the process several time without reloading the module, the seed will be the same.
```python
return ToContext(p1=self.submit(ProcessWithSeed, options=opt1), 
                 p2=self.submit(ProcessWithSeed, options=opt2))
```
But you probably want two seeds and them to be stored in an input node for your calculation.

**Comment by mottetm** [comment]
And the solution seems quite simple.
```python
if callable(default):
    default = default()
```
If it is added before the checks, it shouldn't cause any issues.
