### ISSUE TITLE
Modes for StructureData.get_composition()

### ISSUE THREAD

**Issue by zooks97** [aiidateam/aiida-core#1643]
Currently, StructureData.get_composition() returns a dictionary of the composition without reducing with the greatest common divisor.

e.g. BaZrO3 returns `{'Ba': 1, 'Zr': 1, 'O': 3}`
e.g. Ba2Zr2O6 returns `{'Ba': 2, 'Zr': 2, 'O': 6}`

It could be useful to add a `modes` kwarg or similar and add functionality for:

- `direct` as the default
- reducing with the smallest common divisor (`reduced`)
  - e.g. BaZrO3 and Ba2Zr2O6 return `{'Ba': 1, 'Zr': 1, 'O': 3}`
- reducing to fractional composition totaling 1 (`fractional`)
  - e.g. BaZrO3 and Ba2Zr2O6 return`{'Ba': 0.20, 'Zr': 0.20, 'O': 0.60}`

**Comment by JPchico** [comment]
I was thinking in tackling this, unless someone has some objections. I basically agree with the `reduced` and `fractional`. I think that this should somehow be included for alloys right?

Something that might be interesting is also how this could be used in the REST-API, or in the querybuilder itself, as querying by these different types of representation of the composition can be quite interesting.

**Comment by sphuber** [comment]
Fixed in #5926
