### ISSUE TITLE
[django] querybuilder projections very inefficient

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#1700]
Can somebody explain to me why these two queries differ so wildly in performance?

### query 1
```
from aiida.orm.data.parameter import ParameterData
inp_x='density'
inp_y='deliverable_capacity'
inp_clr='surface_area'
projections=['attributes.'+inp_x, 'attributes.'+inp_y, 'attributes.'+inp_clr, 'uuid', 'attributes.name',  'extras.cif_uuid']
qb=QueryBuilder()
qb.append(ParameterData, project=projections)
qb.all()
```
This query takes 2.7s on a really small dataset (300 parameterdata objects [test-db.tar.gz](https://github.com/aiidateam/aiida_core/files/2145695/test-db.tar.gz)).

```
        1389530 function calls (1338695 primitive calls) in 2.722 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     2701    0.735    0.000    0.763    0.000 {method 'execute' of 'psycopg2.extensions.cursor' objects}
     9300    0.134    0.000    0.241    0.000 query.py:240(clone)
     2700    0.119    0.000    0.231    0.000 compiler.py:275(get_default_columns)
```
Note the >1M function calls and, in particular, 2701 calls to `psycopg2.extensions.cursor.execute`.

### query 2
If I remove the projections,
```
projections='*'
qb=QueryBuilder()
qb.append(ParameterData, project=projections)
qb.all()
```
the otherwise unchanged query now takes 50ms.

In particular, there is now just a single call to `psycopg2.extensions.cursor.execute`:
```
      51193 function calls (51008 primitive calls) in 0.112 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      300    0.053    0.000    0.056    0.000 base.py:360(__init__)
...
        1    0.001    0.001    0.001    0.001 {method 'execute' of 'psycopg2.extensions.cursor' objects}
```

Something must be wrong here...

P.S. This is an issue of the django implementation only.
In sqla, the timings are actually the other way around, with `project='*'` taking (still acceptable) 92ms, while the query with the projections takes just 30ms

**Comment by giovannipizzi** [comment]
@ltalirz it would be interesting to see if this is still valid on develop

**Comment by ltalirz** [comment]
Updated script:
```python
from aiida.orm import Dict
inp_x='density'
inp_y='deliverable_capacity'
inp_clr='surface_area'
projections=['attributes.'+inp_x, 'attributes.'+inp_y, 'attributes.'+inp_clr, 'uuid', 'attributes.name',  'extras.cif_uuid']
qb1=QueryBuilder()
qb1.append(Dict, project=projections)

qb2=QueryBuilder()
qb2.append(Dict, project='*')
```

So, the original issue is resolved in aiida-core 1.0 - query 1 (`qb1`) now has only one call to `psycopg2.extensions.cursor.execute` and runs in 25ms
```
In [13]: %timeit qb1.all()
10 loops, best of 5: 25.8 ms per loop
```

Interestingly, query 2 (`qb2`) with `project='*'` is now significantly slower than the performance reported above for the sqla implementation:
```
In [5]: %timeit qb2.all()  # with project='*'
1 loop, best of 5: 312 ms per loop
```

One issue might be that now, for some reason, it does 301 calls to 'execute' that's one call plus one call for every node:
```
         331286 function calls (327233 primitive calls) in 0.428 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      301    0.068    0.000    0.069    0.000 {method 'execute' of 'psycopg2.extensions.cursor' objects}
     9000    0.017    0.000    0.017    0.000 {method 'match' of 're.Pattern' objects}
     1500    0.016    0.000    0.025    0.000 query.py:266(clone)
     7800    0.011    0.000    0.036    0.000 entrypoint.py:18(parse)
      600    0.010    0.000    0.011    0.000 decoder.py:376(raw_decode)
      600    0.010    0.000    0.014    0.000 base.py:473(__init__)
        1    0.009    0.009    0.027    0.027 {method 'fetchall' of 'psycopg2.extensions.cursor' objects}
     8100    0.006    0.000    0.045    0.000 jsonbackend.py:80(iter_group)
      300    0.005    0.000    0.248    0.001 base.py:661(refresh_from_db)
      300    0.005    0.000    0.006    0.000 genericpath.py:69(commonprefix)
     1500    0.004    0.000    0.032    0.000 query.py:1105(_clone)
      600    0.004    0.000    0.007    0.000 posixpath.py:331(normpath)
     7800    0.004    0.000    0.004    0.000 {method 'groupdict' of 're.Match' objects}
    10220    0.004    0.000    0.004    0.000 {built-in method builtins.hasattr}
      300    0.004    0.000    0.023    0.000 convert.py:152(_)
      300    0.004    0.000    0.020    0.000 query.py:1122(build_filter)
    15386    0.004    0.000    0.005    0.000 {built-in method builtins.isinstance}
```

**Comment by ltalirz** [comment]
There seem to be some issues with the implementation of the converter from the backend implementation to the ORM one:

https://github.com/aiidateam/aiida-core/blob/cc94a1e0127cd9cab0a4049e69a9fa31cb82941c/aiida/orm/convert.py#L80-L84

 1. there seems to be no caching of the node class, i.e. it is loaded (from entry points) over and over again
 1. (I believe) the `.from_backend_entity` function seems to access the `DbNode.node_type` at some point, and every call to a model attribute (including the node type) triggers a call to `_ensure_model_updtodate`, which triggers a database query

https://github.com/aiidateam/aiida-core/blob/45c167717bf84446393fd4e141d923227bf3bd48/aiida/orm/implementation/django/utils.py#L48-L58

**Comment by ltalirz** [comment]
Mentioning @szoupanos here since I guess you've been doing performance analyses on the django backend for the paper.
The comment above points out some inefficiencies in the implementation when using  `project='*'`.

**Comment by ltalirz** [comment]
After adding `'node_type'` to the `IMMUTABLE_MODEL_FIELDS`, the timing for the django query already goes down to ~100ms
```
In [2]: %timeit qb2.all()  # with project='*'
10 loops, best of 5: 109 ms per loop
```

Run time is now dominated by the calls to entry point loading.
