### ISSUE TITLE
Serialization of dictionary with integer keys

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida-core#1720]
Using integer keys in any dictionary stored in the *context*  of `WorkChain` will raise an exception caused by deserialization where the `key.startswith()` is called in https://github.com/aiidateam/aiida_core/blob/develop/aiida/utils/serialize.py. This only happens when using `submit` to run the `WorkChain` on 0.12.1 but not when `run` is used.

This behavior is not expected and took me a while to realize - WorkChain fails without report being fired. I would recommend:

1. Warn user about using integer keys in documentation.
2. Add type check in the code in _serialize.py_.

I am not familiar with the daemon/workflow code, otherwise I am happy to open a pull request myself for option 2.

**Comment by giovannipizzi** [comment]
Hi, thanks, indeed things should be 'json'-serializable, so only strings are allowed as keys.
PR very welcome!

**Comment by sphuber** [comment]
Note that this was fixed for `1.0.0` by #2017
