### ISSUE TITLE
Allow import of subsets of AiiDA graphs

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#1842]
## Use case
I want to share some results with a colleague but I don't want to share the full provenance (perhaps it contains confidential info, perhaps it's too large, perhaps it's simply unnecessary). 
I put the nodes that I want to share in a group and export them (currently possible [1]). 
I give the export file to my colleague and he or she imports it (currently not possible in general).

[1] E.g. `verdi export create --groups 1 --no-parents test-par.aiida`

## Problem
The export file contains links to non-existing parent nodes, which causes the import to fail with a message like
```
> There has been an exception during the import of file
> test-par.aiida
> Do you want to continue (c) or stop (S, default)?
```
I attach an example db [test-db.tar.gz](https://github.com/aiidateam/aiida_core/files/2262213/test-db.tar.gz)

## Solution
Either
A) Don't export links to non-existing nodes, or
B) Don't import links to non-existing nodes, or
C) Import links to non-existing nodes (perhaps not a good idea)

The current modus of being able to create export files that are not importable by other people does not make sense and needs to change.

P.S. This was tested with the latest `release_v0.12.2` branch.

**Comment by giovannipizzi** [comment]
> The current modus of being able to create export files that are not importable by other people does not make sense and needs to change.

Well, it does make sense (but maybe one can decide to change the logic).
The logic here is that if you already know what you have in the destination DB, in this way you can do incremental transfers. Moreover, it ensures (it was a requirement some time ago, probably now we want to lift this, at least as an option to the users) that it is _impossible_ to import a node without importing its history).

Of course it's not super-easy to use as is - it will with the work of @szoupanos - but it is needed to allow incremental or delta transfers if a code on top of it can detect and decide which nodes to transfer.

**Comment by ltalirz** [comment]
> it is _impossible_ to import a node without importing its history

This requirement is what does not make sense to me.

> Of course it's not super-easy to use as is - it will with the work of @szoupanos - but it is needed to allow incremental or delta transfers if a code on top of it can detect and decide which nodes to transfer.

Could you please expand a bit on this?
Are you saying, the requirement that it is impossible to import a node without its history is needed?

**Comment by ltalirz** [comment]
Hi Spyros, let me know if you need to discuss concerning this.

For me, the default export rules are perfectly fine, but I am firmly convinced that we need to *allow* users to share part of their graph without sharing all the provenance, if they wish to do so.

There can be a number of reasons for this:
  * You just need to share a few results. By selecting the result nodes, the export file is a few MB instead of many GB
  * You can't share some of the provenance yet (paper not yet published / license issues / ...)
  * ... I'm sure there are more

Currently, we already allow users to *export* part of their graph without provenance, but then we don't allow other users to *import* these files.
This is what needs to change.

**Comment by giovannipizzi** [comment]
To be discussed if this can fit into the 1.0 timeline (putting 1.0 for now)

**Comment by ltalirz** [comment]
Not quite sure why this was scheduled for v1.1.0 - I believe this has been fixed when applying the  appropriate import/export logic rules.

Importing the archive linked at the top now works, see [import.log](https://github.com/aiidateam/aiida-core/files/3830932/import.log)
