### ISSUE TITLE
Write documentation or a tool to help people manage separate AiiDA environments

### ISSUE THREAD

**Issue by DropD** [aiidateam/aiida-core#1895]
## Problem: A major usability feature is mostly unknown and undocumented

Recent (development) versions of AiiDA have the ability to
 * run daemons for multiple profiles in parallel
 * use a custom location for the .aiida folder

Combined with virtualenvs this makes it possible to manage completely isolated AiiDA environments per-project, allowing experimentation with new versions without risk of messing up production data.

However, outside the core developers not many people seem to know this, and it is not documented.

## Partial solution: document the feature

The following is my approach to creating such a project environment
* a project root folder with
  - `.aiida/` folder
  - `activate_aiida_project.sh` script which exports AIIDA_PATH, sets up verdi completion
  - [optional] the relevant aiida and plugin repos if dev installs are preferred
  - [optional] a standalone virtualenv if no manager is being used
* a separate virtualenv if conda or virtualenvwrapper etc is used
* modifications to the virtualenv activation script to call `activate_aiida_project.sh`
* modifications to the virtualenv activation script to `cd` to the project root folder

This may serve as a starting point for documentation of this awesome feature.

## Pie in the sky solution: automate environment creation

It would further enhance usability of AiiDA if there was a commandline tool to create such a project environment (preferrably able to work with all of virtualenv / virtualenvwrapper / conda).

The next step from this would then be to make it simple to clone a profile from a different project (with separate db and repo of course) as well as computers and codes (including configuration).

With cloning of profiles and compute resources across projects integrated in said commandline tool, the user experience would be unparalleled in scientific software.

**Comment by sphuber** [comment]
I am closing this as this is now fully documented: https://aiida-core.readthedocs.io/en/latest/howto/installation.html#isolating-multiple-instances
If the need arises for an actual tool to provide more automation, a new feature request can be opened specifically for this purpose
