### ISSUE TITLE
Questions/suggestions on documentation page about workflows

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-core#1927]
I have a few questions / suggestions about [this page of the documentation](https://aiida-core.readthedocs.io/en/latest/concepts/workflows.html) that discusses workflows.

- Can the `ctx` member of a WorkChain be equivalently accessed as a dictionary (`self.ctx['key']`) and with the dot notation (`self.ctx.key`)? This seems implied but is not made explicit.

- The use of the `agglomerate` argument is not super clear to me, especially in the case of `exposed_outputs()`. They name of the argument itself also doesn't seem very intuitive. Maybe I just need to make use of the feature in order to understand its necessity.

- To better understand the last complex example, I took the liberty of making a graph: feel free to use it (or not). Note however that, in order to make the graph clearer, I had to slightly change the `ChildWorkChain` so that it creates new outputs, rather than simply passing the inputs along:

```python
    def do_run(self):
        self.out('d', Int(self.inputs.a*2))
        self.out('e', Float(self.inputs.b*2))
        self.out('f', Bool(not self.inputs.c))
```

[57665.pdf](https://github.com/aiidateam/aiida_core/files/2340331/57665.pdf)

**Comment by unkcpz** [comment]
Hi @borellim, could you check the current documentation is good enough for your questions mentioned above? I think it is safe to close this issue @mbercx correct?

**Comment by borellim** [comment]
Thanks Jason. I don't use AiiDA any more now, so I'm not sure that my input would be valuable. But I do appreciate your following up.

**Comment by unkcpz** [comment]
Thanks Marco! To me, the problem you mentioned is now nicely documented thanks to their efforts on documentation ;-)
Will close this for now.
