### ISSUE TITLE
Computer configuration

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#1974]
The walk through for the computer configuration could be improved:

- Look for keys (what do we answer and what does this really mean?), passing false here still leads to the request of the SSH key file
- SHH key file (is this loaded, or does Aiida use this...security concerned users would just abort here unless one is a bit more specific)
- Allow ssh agent (what does this mean and what kind of agent is used?)
- SSH proxy command (this is fine, maybe mention a default, like disabled if you just press enter?)

**Comment by ltalirz** [comment]
Assigning @giovannipizzi  as he worked on the [computer setup migration to click](https://github.com/aiidateam/aiida_core/pull/1735) (for configure, it was actually @DropD...).

I actually have a few more questions concerning `verdi computer configure`:

 #. why is it necessary to pass local/ssh if the computer stores this information anyhow? This introduces makes the cli more difficult to use
 #. why is it necessary to have a separate `verdi computer configure show` command? why can't we just show all the necessary information with `verdi computer show`?

**Comment by giovannipizzi** [comment]
Is this partially related to the discussion on #1893?

**Comment by giovannipizzi** [comment]
To answer @ltalirz - the reason for the current design is to allow us to implement also the configure commands as plugins (they actually use - as parameters - the content of what is in the transport plugin). We didn't find a proper way to define a single command (e.g. `verdi computer configure`) that was allowing to define, at module load time (as click wants) and not at runtime which *interactive* options each of the two `configure` commands wants (they are different for every transport, we wanted to have both interactive and non-interactive behaviour, and define the options at the click level).
Of course if good ideas are available, happy to discuss/implement them!

Also - the idea is that things in the `configure` are connection/authorization specific, while in `setup` are needed just to set up a code that you don't necessarily want to connect to (e.g. the case when you import a code - it's set up, but not configured).

About the original questions, I agree, I think some of these are being tackled in #1893 - @waychal can you take into account also of Espen's comments here?

**Comment by giovannipizzi** [comment]
Some of these points, if still valid, could be addressed in the revamped docs?

**Comment by sphuber** [comment]
The main part of this issue, the looking for keys, will be addressed by #4387 . The other points are mostly requests to improve the help string of `verdi computer configure`. @espenfl is this still relevant, or can this be closed?

**Comment by espenfl** [comment]
@sphuber Have not checked the remaining points. Please close and then I can reopen on specifics if I detect something on next install.
