### ISSUE TITLE
CifData: while importing coordinates from ase one should allow to define the name of the stored cif file.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#2029]
It would be very useful to allow to define the name of the cif file that is stored for CifData, as it gives more flexibility to the developers.

To be more specific, the function [set_ase()](https://github.com/aiidateam/aiida_core/blob/9335c6546326e6d71ce982bf370ccc2d149c6fa7/aiida/orm/data/cif.py#L540) should be changed from:
```
    def set_ase(self, aseatoms):
        """
        Set the contents of the CifData starting from an ASE atoms object
        :param aseatoms: the ASE atoms object
        """
        import tempfile
        cif = cif_from_ase(aseatoms)
        with tempfile.NamedTemporaryFile() as f:
            with HiddenPrints():
                f.write(pycifrw_from_cif(cif, loops=ase_loops).WriteOut())
            f.flush()
            self.set_file(f.name)
```
To something like:

```
    def set_ase(self, aseatoms, filename=None):
        """
        Set the contents of the CifData starting from an ASE atoms object
        :param aseatoms: the ASE atoms object
        """
        import tempfile
        cif = cif_from_ase(aseatoms)
        if filename is None:
            structure_file = tempfile.NamedTemporaryFile()
        else:
            structure_file = open(tempfile.mkdtemp() + '/' + filename, 'w')
        with structure_file as f:
            with HiddenPrints():
                f.write(pycifrw_from_cif(cif, loops=ase_loops).WriteOut())
            f.flush()
            self.set_file(f.name)
```

**Comment by yakutovicha** [comment]
@sphuber and @ltalirz  if you think it is fine - I would be happy to make a PR for that.

**Comment by ltalirz** [comment]
Instead of creating a folder, you could use this
https://github.com/aiidateam/aiida_core/blob/9335c6546326e6d71ce982bf370ccc2d149c6fa7/aiida/orm/data/singlefile.py#L70

**Comment by yakutovicha** [comment]
Ok, this is a good idea.

I would then replace call of `set_file()` function here
https://github.com/aiidateam/aiida_core/blob/9335c6546326e6d71ce982bf370ccc2d149c6fa7/aiida/orm/data/cif.py#L642
with the call of `super(CifData, self).add_path(filename, dst_fname="some_fname")` defined here
https://github.com/aiidateam/aiida_core/blob/9335c6546326e6d71ce982bf370ccc2d149c6fa7/aiida/orm/data/singlefile.py#L70

**Comment by ltalirz** [comment]
sounds good to me!

**Comment by sphuber** [comment]
After discussion at the coding week on December 3rd, we decided that this is really a documentation issue. The filename of a file in the AiiDA repository has no meaning and is hidden to the user. If the original filename of the cif has semantic meaning that the user wants to keep and query for, the best  solution is to use the `label`. This is a first class `Node` column and therefore queryable. We should just document very clearly that for any `Node` the `label` column is the place to attach human readable labels that should be queryable

**Comment by sphuber** [comment]
PR #3517 made it possible to set the filename of a `SinglefileData` and since `CifData` is a subclass there as well. I think that accomplishes the desired feature of this issue after all, so I will close this.
