### ISSUE TITLE
Change tests that mock the submission process

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#2103]
Some tests (like the one changed in #2087) mock the submission procedure.
However, these tests are fragile when/if we change the internals of how things are done in the submission engine.
Therefore, the suggestion is to:

- [ ] Check in the code all tests that call `._set_state()` or similar (this includes the test of #2087 but there are probably more)
- [ ] Convert these to unit tests that just check the underlying functionality and do not try to replicate the submission/parsing process

Exception: tests that actually test the submission process

**Comment by sphuber** [comment]
Closing this, as this pertains to the control of `JobCalculations` before `v1.0.0`. Now that is fully changed and no longer depends on the state of the `CalcJobNode`s
