### ISSUE TITLE
Add optional `TransportTask` for `CalcJob` to stash files on the remote after the job has finished

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2150]
A common use case, is that after a `JobProcess` has finished, one might want to copy some files from the work directory, which is often on a scratch space, to a more durable location and attach them through a `RemoteFolder` to the `JobCalculation` node. This is different from the files that are already retrieved for parsing, as often these additional files are big, and one wants to keep them on the remote computer. A typical example are big files that are necessary to restart a calculation from, that are too big to retrieve but also too costly to lose and have to recompute. There is a simple and naive solution of just running an inline calculation that will open transport to the remote computer and use `copy_from_remote_to_remote` to copy the files and create a `RemoteFolder` object to attach to the computer, but this can be dangerous. If an exception occurs, the entire process, most likely the `WorkChain` that launched the `JobCalculation` will except as well. Of course one can catch the exceptions but then the files will not be copied. The `JobProcess` infrastructure has a rich architecture to deal with tasks that require transport and can fail. The best option would be to leverage this functionality for this particular purpose by creating an optional `TransportTask` to copy files after the job has finished, but before going over to the retrieval and parse step.

**Comment by espenfl** [comment]
@sphuber In addition to this it would be nice to have some infrastructure to be able to at the end of `prepare_for_submission` to check that required files are indeed present. If we use a remote folder to restart from, some copy operations might fail (or remote directory might have disappeared) for different reasons and it would be nice to check at the very minimum that the files at least are present.

**Comment by sphuber** [comment]
@espenfl what you are referring to is more suited for issue #3477 . This particular issue is more to transfer files _procuded_ by a calculation. Of course there is the `retrieve_list` but sometimes you want to keep the files on the remote machine and simply move them from the scratch to a more permanent storage location. This is what this feature request is about. You seem to suggest having a functionality that allows one to check files on a remote while still in `prepare_for_submission`, i.e. when the calculation has not even run yet.

**Comment by espenfl** [comment]
@sphuber Indeed, moving it.
