### ISSUE TITLE
pylint and absolute imports

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2205]
The `provenance-design` branch flagged up a couple of prospector warnings such as these:
```
aiida/orm/implementation/querybuilder.py
  Line: 143
    pylint: import-error / Unable to import 'sqlalchemy.sql.elements' (col 8)
    pylint: no-name-in-module / No name 'sql' in module 'sqlalchemy' (col 8)
  Line: 144
    pylint: import-error / Unable to import 'sqlalchemy.orm.attributes' (col 8)
    pylint: no-name-in-module / No name 'orm' in module 'sqlalchemy' (col 8)
  Line: 145
    pylint: import-error / Unable to import 'sqlalchemy.sql.expression' (col 8)
    pylint: no-name-in-module / No name 'sql' in module 'sqlalchemy' (col 8)
  Line: 146
    pylint: import-error / Unable to import 'sqlalchemy.types' (col 8)
    pylint: no-name-in-module / No name 'types' in module 'sqlalchemy' (col 8)
```

The reason they show up is because pylint (somewhat [1]) incorrectly treats these as relative imports (there are `django` and `sqlalchemy` subfolders in `aiida/orm/implementation`).
There is an open issue for this (https://github.com/PyCQA/pylint/issues/1931) but no workaround as of now.

Since this is a pylint problem, I will disable the corresponding warning in affected files, together with a link to the bug report, with the idea that the pylint directives can be removed again in the future.

Mentioning @muhrin @sphuber @giovannipizzi 

[1] "Somewhat" because trying to run the file individually (i.e. `python aiida/orm/implementation/querybuilder.py`) will fail. Only running it as part of a package (`python -m aiida.orm.implementation.querybuilder` will cause python to honour the absolute import. One can argue, however, that python submodules of packages are not meant to be executed individually.

**Comment by giovannipizzi** [comment]
The simplest probably is to refactor the code at this stage, renaming our django + sqlalchemy folders to something else, like `backend_django`, `backend_sqlalchemy`?

**Comment by ltalirz** [comment]
While it might be safer, I don't find this simpler. Why should a package like aiida that contains backends for sqlalchemy and django not container subfolders named sqlalchemy and django?

Also, keep in mind that this applies to all dependencies, not just django and sqla.
What if someone decides we need a package named `utils` ?

**Comment by giovannipizzi** [comment]
Actually this is a prospector problem and not a pylint problem, reopening

**Comment by giovannipizzi** [comment]
Waiting for feedback or for a suggestion of a workaround from prospector

**Comment by ltalirz** [comment]
Since this is not an AiiDA issue, and there seems to be no action on the pylint/prospector side, I'm closing this.
Whoever ends up here from the aiida-core source code, please continue to
https://github.com/PyCQA/pylint/issues/1931
https://github.com/PyCQA/prospector/issues/294
