### ISSUE TITLE
add performance tests on jenkins

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2215]
from @giovannipizzi 

add tests to check performance of
 * creating 10k nodes
 * running 10x a simple verdi command that requires `load_dbenv`
 * running 10x a simple verdi command that does not require `load_dbenv`

If you want to include any actual asserts (test failing, if it takes too long), then it might be better to include these only on jenkins where we are sure to always use the same hardware.

**Comment by sphuber** [comment]
This has been addressed by the adding of the benchmarking workflow to GHA. The normal CI workflow already has a test for the loading speed of `verdi`.
