### ISSUE TITLE
The function exposed_inputs returns a regular dict

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#2245]
It seems `exposed_inputs` returns a regular `dict`. Given the heavy use of `AttributeDict()` (and its usefulness), could we return this instead?

**Comment by muhrin** [comment]
Yes, sounds reasonable.  It should be fairly easy to add - I'll try and fit in 30 mins this week to quickly implement and try.

**Comment by sphuber** [comment]
This was actually already fixed in #3079
