### ISSUE TITLE
JobProcess task_retrieve_job is not idempotent which can cause failures

### ISSUE THREAD

**Issue by muhrin** [aiidateam/aiida-core#2265]
The retrieval task can fail if it is executed for a second time.  This happens when a the retrieved files node is attached to the job for a second time causing a uniqueness violation.

If we know that, by the time the link is being created, the retrieved files node is correctly set up then we could just reuse the one we find from last time, effectively ignoring the uniqueness violation and using the current node.

**Comment by sphuber** [comment]
This was addressed in #3142
