### ISSUE TITLE
Implement `Data.tools.*` to access methods defined by a plugin

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#2327]
Similarly to the `.tools.*` for Calculations (see #2322) we can implement the same concept for Data, to e.g. cover the tools that are already in `aiida.tools.*` (e.g. kpoint list generation, structure exporting, ...) and we could move there also other things that now live in the classes (e.g. UPF parsers etc.).

Mentioning also #2311 for the meaning of what will be in `aiida.tools`.

**Comment by ltalirz** [comment]
We now have an `aiida.tools.data` entry point
https://github.com/aiidateam/aiida-core/blob/9ff07c166a559f98b5b2be71537814ec00d3f18d/setup.json#L211-L214

@giovannipizzi If that is not what you had in mind (it's not entirely clear to me from the description), feel free to reopen.
