### ISSUE TITLE
REST API should be updated to reflect the changes in provenance redesign

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2384]
An overview of name changes can be found in issue #2152

**Comment by waychal** [comment]
- [ ] Move code endpoint under Data to match it with ORM hierarchy
- [ ] Create Node module as top hierarchy with Data and Process
- [ ] Implement Process hierarchy and update Calculation endpoint accordingly
- [ ] In translator classes, remove hard coded type string from query help and replace it with ORM class
- [ ] Find alternate way to get subclasses of translator class and remove hard coded node type string used there
- [ ] Use click interface to get rest api command line parameters
- [ ] Remove load_dbenv setup from run_api code
