### ISSUE TITLE
Calculation stuck on waiting

### ISSUE THREAD

**Issue by mottetm** [aiidateam/aiida-core#2388]
Some calculations get stuck in `Waiting` state with the process status: `Waiting for transport task: update`.
All the calculations are however complete on Daint. There's no particular error in the daemon log and restarting the daemon sometimes retrieves one or two calculations but not always.

Edit:
version 1.0.0a4

**Comment by Tseplyaev** [comment]
I think I experience the same problem.
I use aiida version 1.0.0a4 installed on my laptop. 
Let's say I need to submit a workflow which submits a calculation to a cluster via ssh. Sometimes it can take a day for a job to stay in a queue, run and finish; thus I switch my laptop off for overnight after the calculation is successfully submitted to the cluster. Next day I switch my laptop on, start RabbitMQ server and daemon but the calculation gets stuck in `Waiting` state. A manual check e.g. via `verdi calculation gotocomputer xxxx` shows that the calculation is finished.
Moreover, if I just restart RabbitMQ server or daemon without a system reboot calculations seem to not stuck and the workflow finishes successfully.

**Comment by fBert31** [comment]
I also obtain this problem. I work with `aiida_core` version `1.0.0a4` on my MacBook.
Sometimes restarting the daemon several times does work to retrieve the calculation. The workflow that submitted the calculation, however, always gets stuck and does not proceed with further steps.

**Comment by sphuber** [comment]
Thanks for all the reports. As you may know we are working towards the release of `1.0.0b1`, development is taking place in the `provenance_redesign` branch. Since `v1.0.0a4` I have already fixed quite a few problems that are related to what you have been experiencing. I cannot say for sure, but I think these problems are already fixed in `provenance_redesign`. Once we merge it to `develop` and release the beta, I would ask you to update your installation and if these problems persist, to please mention it in this issue. Thanks a lot

**Comment by unkcpz** [comment]
I experience the same problem when using aiida_core `v1.0.0b4`.
I find this issue happened only when I running calculations at a specific remote computer(The rest of computers are fine).
Interestingly, the computer also have the problem that when manually ssh to it, the computer stuck(nothing show up on screen while typing) after about one minutes.
Therefore I did the following steps to try to fix the issue:

-  Add `ClientAliveInterval 30` and `ClientAliveCountMax 3` in file `/etc/ssh/sshd_config`. (This fix the stuck while manually ssh to the computer)
- Decrease `timeout` field and increase `safe_interval` in `verdi computer configuration` command.
- Set  job poll interval to 30 second. (https://aiida.readthedocs.io/projects/aiida-core/en/latest/get_started/computers.html#on-not-bombarding-the-remote-computer-with-requests)

I don't know which one take effect, but it is really fixing the issue.

**Comment by ireaml** [comment]
Using aiida-core 1.6.5, my calculations are stuck in 'Waiting' state. The process status incorrectly states "Monitoring scheduler: job state RUNNING'" while there are no running jobs in the HPC.  
When I try to kill the processes, it doesn't (it gets stuck and I have to manually abort).
When I try to upload a new calculation, it also gets stuck in 'Waiting' state while the process status states 'Waiting for transport task: upload'.

Reading previous issues, seems like it could be related to a laptop reboot that didn't properly stop the daemon?
Tried restarting the daemon with "--reset" but it runs into a TIMEOUT error. Then proceeded with a "--no-wait" restart, but no improvements.

Thanks!

**Comment by sphuber** [comment]
Thanks for the report. The fact that any new calculations that you submit also get stuck, suggests that it is not a problem with an unclean reboot of the machine, but rather there is a more general problem. Is there any information in the daemon log? `verdi daemon logshow`?  What is the output from `verdi process report <PK>` where you replace `<PK>` with the pk of the calculation that you recently submitted and got stuck.

**Comment by ireaml** [comment]
Seems to be fixed now (submitted calculations go in fine). 
I restarted the terminal, rabbitmq-server and the daemon and manually killed the stuck processess (so cannot check `verdi process report` for the stuck calc).
Sorry and thanks for the reply!

**Comment by sphuber** [comment]
Ok, great, thanks for letting us know. I suspect it was a problem with RabbitMQ, so having restarted that probably fixed things.
