### ISSUE TITLE
rest api: print link to endpoint

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2403]
When starting the REST API using `verdi restapi`, the output should contain a link to the actual endpoint of the API (including `/api/v2`), i.e. a line like

`Connect to the AiiDA REST API at http://127.0.0.1:5000/api/v2`

**Comment by asle85** [comment]
This issue was fixed through PR #3106. 
Follow-up discussion in issues #2964 and #3270.
