### ISSUE TITLE
define policies for plugins for aiida 0.12 and 1.0

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2477]
We should provide guidelines to plugin developers on:

 1. how to specify the dependency on aiida in their plugin (for 0.12 & for 1.0)
 1. how to handle support for both aiida 0.12.x and 1.0 (one plugin version supporting both, different "branches", ...)
 1. how long we will support aiida 0.12.x with bug fixes

**Comment by ltalirz** [comment]
Re 1. @giovannipizzi proposes:
 * for 0.12: `aiida<1.0a0` 
 * for 1.0: `aiida>=1.0,<1.1` 

Re 2. Unfortunately, the provenance redesign makes it hard to provide one plugin that works with both versions of AiiDA. I would therefore suggest to increase the major version number for aiida 1.0 support.
Example: `aiida-quantumespresso` 2.x supports aiida 0.x; `aiida-quantumespresso` 3.x supports aiida 1.0

Re 3. I suggest we should provide bug fixes for aiida 0.12.x at least for 12 months after the official release of aiida 1.0

**Comment by ltalirz** [comment]
decision at the AiiDA meeting: 6 months after the release of 1.0

**Comment by sphuber** [comment]
This should be added to the documentation that describes how to develop and maintain plugins

**Comment by ltalirz** [comment]
Support for aiida-core 0.12.x is documented in the [AiiDA release roadmap](https://github.com/aiidateam/aiida-core/wiki/AiiDA-release-roadmap).

How to depend on AiiDA-core is described in the corresponding [AEP 2](https://github.com/aiidateam/AEP) + in the [aiida-diff demo plugin](https://github.com/aiidateam/aiida-diff).
