### ISSUE TITLE
Improve documentation (missing pages, adding links and apply some fixes)

### ISSUE THREAD

**Issue by elsapassaro** [aiidateam/aiida-core#2479]
I checked the documentation, to check the following points:

- [x] Add paragraph to explain what Quantum Mobile is and a link to the download page in Quick installation page

- [ ] MISSING page about calculations in Concepts (https://aiida-core.readthedocs.io/en/provenance_redesign/concepts/calculations.html)

- [ ] Empty list of Calculations classes in https://aiida-core.readthedocs.io/en/provenance_redesign/developer_guide/core/orm_overview.html#orm-documentation-calculations

- [ ] Not clear if the `workfunction` decorator is `@calcfunction` in the code snippets? (https://aiida-core.readthedocs.io/en/provenance_redesign/concepts/workflows.html#workfunctions)

- [ ] At https://aiida-core.readthedocs.io/en/provenance_redesign/querying/querybuilder/usage.html#working-with-edges, in the "Working with edges" section: in the explanation it says the keyword is preceded by 'link', but it's actually 'edge' in the snippet

- [ ] In https://aiida-core.readthedocs.io/en/provenance_redesign/restapi/index.html the links to Wikipedia pages on Restful and API are not working (remove trailing slashes)

**Comment by sphuber** [comment]
It should be checked in the upcoming docs revamp coding days which of these are still relevant and if there are remaining items, they should be fixed.
