### ISSUE TITLE
Implement remaining abstract methods of the `BackendNode` interface class

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2495]
In PR #2481 the `Node` class was moved to the new backend interface. For this a new abstract interface `BackendNode` was designed. Especially the interface to retrieve and set attributes/extras was redesigned. Existing functionality was migrated but the interface also defined some new methods that have not yet been implemented. These should be implemented and tested independent of the front end ORM.

**Comment by ramirezfranciscof** [comment]
After manually verifying that all abstract methods of `BackendNode` were indeed implemented in the `SqlaNode` and `DjangoNode`, and also checking that setting the former to `metaclass=abc.ABCmeta` didn't break the testsuite, I concluded that this issue could be closed.

It will be done automatically once the PR #4310 gets accepted: this PR makes the `BackendNode` properly abstract by setting the mentioned `metaclass=abc.ABCmeta`, and also removes some redundant methods in the child classes. We may want to check these classes for further redundancies in methods in the future, but this could require a more significant re-organization.
