### ISSUE TITLE
`verdi status`: file repo + version information

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2522]
* When the file repository does not exist, AiiDA currently creates a new folder automatically and without any warning. This makes the current "file repository status" rather meaningless, since it only checks whether the folder exists. I would suggest to provide a warning, when AiiDA has to create it from scratch and to add _some_ info to the status, e.g. whether the folder is empty or not (open to suggestions)
* could consider adding version information that helps as reports on mailing lists (e.g. aiida version, postgres version, rmq version)

**Comment by sphuber** [comment]
We should think careful how we want things to work if we change the current behavior of having the repository folder being created automatically. Even now that we have migrated to using the DOS (disk object store) it is still initialized automatically when `Profile.get_repository_container` is called. If we change this to expect the container to be there, and only have it created through `verdi setup` (and `verdi quicksetup` by extension) than current mechanism that work will start to fail. For example, now it is possible to create a profile by hand in the config file with a repository path pointing to an empty folder, or to change the repository path of an existing config file. In both cases, when the profile is loaded, the repository is automatically loaded without any problems.

We could add a warning to the `get_repository_container` method if it needs to initialize it, but then this may arrive at any point, not just when `verdi status` is called.

To make the repository status more useful, we can now actually print its UUID, which is a new feature provided by the DOS. I will open a PR for this.

**Comment by ltalirz** [comment]
> We could add a warning to the `get_repository_container` method if it needs to initialize it, but then this may arrive at any point, not just when `verdi status` is called.

On reflection, I think what I would really like to be informed about is  the creation of the `.aiida` folder.
Issuing a warning for this would be useful and informative (many new users now don't know where on the hard disk AiiDA stores data) and can help diagnose issues with the `AIIDA_PATH`.

If that warning is there, I take back my request for a warning for creating a repository folder.

> To make the repository status more useful, we can now actually print its UUID, which is a new feature provided by the DOS. I will open a PR for this.

Great!

**Comment by sphuber** [comment]
> On reflection, I think what I would really like to be informed about is the creation of the .aiida folder.
Issuing a warning for this would be useful and informative (many new users now don't know where on the hard disk AiiDA stores data) and can help diagnose issues with the AIIDA_PATH.

Shall we split that off in a separate issue as it is quite different from what we discussed here?

**Comment by ltalirz** [comment]
Opened https://github.com/aiidateam/aiida-core/issues/4884
