### ISSUE TITLE
linking two nodes "by hand"

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2548]
this is a use case from Berend's group (@danieleongari).

Imagine you've run a set of workflows and you notice afterwards that, at some point in the workflow a link is missing (in this example it was using an `@optionalinline` without putting `store=True`).

Is there a way to manually add a custom link between the end of one tree and the beginning of another tree?

The reason we ask this is because the lack of a link can make querying very tedious, and the alternative would be to re-run all calculations.
(in the meantime we'll be looking into enabling caching).

Perhaps @sphuber or @giovannipizzi could comment on this?

**Comment by sphuber** [comment]
In principle this would be possible, as there is nothing stopping a user from calling `add_incoming` from one the nodes to add a link, however, these nodes will probably be sealed, which is done as soon as the process terminates and so it will raise `ModificationNotAllowed`. I don't think we should currently add an option to add links with built in link types in the ORM. However, in this case, they can temporarily comment out the check in the `Sealable.validate_incoming` and `Sealable.validate_outgoing` in the source code, apply the changes and then reenable the checks.

**Comment by ltalirz** [comment]
Question answered.
