### ISSUE TITLE
verdi graph generate should create a pdf by default

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2585]
Of all people I've seen using `verdi graph generate`, 0% wanted to edit/work with the .dot file and 100% wanted the pdf.
To me, this means we should provide the PDF by default.

**Comment by sphuber** [comment]
The only problem is that if we want to keep the current pathway, i.e. with `dot` to produce the pdf, we should require it to have been installed through `graphviz`. At least that is for Linux, not even sure what package installs it for Mac.

**Comment by ltalirz** [comment]
Not necessarily - we could easily produce the PDF directly, if `dot` is found in the `PATH`.
If it isn't, we can still print the command that people need to run.
