### ISSUE TITLE
verdi export not storing full provenance

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2586]
We have an example of a workflow (see [verdi graph](https://github.com/aiidateam/aiida_core/files/2946116/103481.pdf) ) where we would like to export the full provenance.

Starting from the final `CifData` (PK 132944), we created an AiiDA export file (with all options enabled to get as much of the provenance as possible: `verdi export create -I -R -X -C`).

We then imported the export file in a different profile and generated [the graph](https://github.com/aiidateam/aiida_core/files/2946229/3.pdf):

 * the provenance is broken at the inline calculation (PK 131351)
 * not a single Work-type node was exported

The [export file](https://github.com/aiidateam/aiida_core/files/2946525/export16000N2_fromtest3ddec.zip) was prepared on aiida-core 0.12.2 & imported on aiida-core 0.12.3.

**Comment by ltalirz** [comment]
I find this curious in a number of ways 

 * how is this not caught by the tests?
 * how can `verdi graph generate` work but `verdi export` not? Is the logic (incorrectly) duplicated?

**Comment by giovannipizzi** [comment]
First question: are the Work nodes in the export file or not? (I.e. is the problem in exporting or in importing?)

**Comment by ltalirz** [comment]
Sorry, export file is attached above now.
No Work nodes are in the export file as far as I can tell.

**Comment by szoupanos** [comment]
This should have been solved at the issue #1758 and PR #1764. I will look what goes wrong. Thanks Leo

**Comment by szoupanos** [comment]
Fixed by PR  #2637 for .12

**Comment by szoupanos** [comment]
There will be a new PR for this for 1.0 since the same problem should exist there too

**Comment by ltalirz** [comment]
To do: check whether this indeed still exists in `develop` (I would hope not?).
If not, close this issue.

**Comment by sphuber** [comment]
Have you had the chance to look at this @ltalirz ? Since this should be fixed in `0.12.*` and anyway we are no longer supporting it, I removed the label

**Comment by sphuber** [comment]
If there really is still a problem with the provenance being broken in `v1.*` when exporting/importing we should find a MWE and open a new issue. Closing this as the problem was identified in `0.*` and fixed there.
