### ISSUE TITLE
Add support to filter by process type in `verdi process list`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2600]
Often one wants to filter for specific `WorkChain` or `CalcJob` instances in `verdi process list.`
It is not yet clear what values the option should expect, but consider the following example output:
```
  PK  Created    State             Process label               Process status
----  ---------  ----------------  --------------------------  -----------------------------------
 815  4D ago     ⏹ Finished [0]    multiply
 820  4D ago     ☠ Killed          AddAndMultiplyWorkChain     Killed through `verdi process kill`
 821  4D ago     ⏹ Finished [0]    add
 826  4D ago     ⏸ Running         AddAndMultiplyWorkChain    
 827  4D ago     ⏹ Finished [0]    add
 832  5h ago     ⨯ Excepted        PwCalculation
 842  5h ago     ⏹ Finished [0]    PwCalculation
 858  59m ago    ⏹ Finished [120]  CifCellContentsCalculation
 862  58m ago    ⏹ Finished [0]    CifCellContentsCalculation

```
There are instances of `CalcJob`, `WorkChain`, `calcfunctions` and `workfunctions` in here. The process label is determined by the class name or function name. One could imagine that one would filter for all work chains, or just all calculation jobs. Or get all workflow processes, so work chains *and* work functions. Or all calculation processes. In a sense I think the type is a combination of the actual process base class: i.e. `WorkChain`, `CalcJob` etc. and the actual sub class, so the actual class or function name. We could use entry point categories and names:
```
verdi process list -t aiida.calculations
```
would match all calculations and
```
verdi process list -t aiida.calculations:quantumespresso.pw
```
would match all `PwCalculation` instances. However, this does not answer what to do with those classes or functions that do not have a registered entry point.

**Comment by ltalirz** [comment]
To me, for all practical purposes so far this feature is available via the `-L` filter on the process label.
@sphuber can this be closed?

**Comment by sphuber** [comment]
It can indeed be used for quite a number of cases, but won't always work. If you really just need the `WorkChain`s you are beholden to those classes actually all using the `WorkChain` suffix for their name, which is not required. Still, so far we haven't had others request this feature, so we can close it for now I guess. If the need ever comes up, we can reopen the request
