### ISSUE TITLE
script 'backup_postgresql.sh' - clarification

### ISSUE THREAD

**Issue by d-tomerini** [aiidateam/aiida-core#2603]
On the "Create database backup" section in the documentation, the backup folder is assumed to be in the ~/.aiida folder, while a user is allowed to have created only a local folder ~/virtualenv/.aiida and not a global one. 

A naive user that did not create the global ~/.aiida folder will end up not back-upping anything, since the folder might not exist, and no warning is given. 

An mkdir -p command could be added for safety; a warning in the documentation section, or use of the $AIIDA_PATH, if configuring when in the virtual environment

**Comment by unkcpz** [comment]
Rather than provide the file `backup_postgresql.sh` for download and run in documentation (https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/installation.html#database-backup).
I think it would be better to show the code for the user to copy and paste and modify.
