### ISSUE TITLE
verdi graph - Use UUIDs instead of pks

### ISSUE THREAD

**Issue by szoupanos** [aiidateam/aiida-core#2636]
When generate an AiiDA graph print the UUIDs instead of the pks of the nodes. Try to print a shortened version of the pks if there are no UUID collisions.

This is very useful when comparing graphs created before and after verdi export (since UUIDs remain the same and PKs change).

A shortened UUID version is used at
`verdi node show -u ea70cc12`
and we can follow a similar syntax and be inspired by that implementation.

To change to (non-shortened) UUIDs the following change is enough

```
diff --git a/aiida/common/graph.py b/aiida/common/graph.py
index f1103aea3..d0f4b4618 100644
--- a/aiida/common/graph.py
+++ b/aiida/common/graph.py
@@ -61,7 +62,7 @@ def draw_graph(origin_node, ancestor_depth=None, descendant_depth=None, format='
             additional_string = "\n {}".format(node.get_desc())
             label_string = ""
         labelstring = 'label="{} ({}){}{}"'.format(
-            node.__class__.__name__, node.pk, label_string,
+            node.__class__.__name__, node.uuid, label_string,
             additional_string)
         return "N{} [{},{}{}];".format(node.pk, shape, labelstring,
                                        additional_params)
@@ -184,8 +185,12 @@ def draw_graph(origin_node, ancestor_depth=None, descendant_depth=None, format='
         fout.write("}\n")
```

**Comment by ltalirz** [comment]
This functionality was added in #2596
