### ISSUE TITLE
Remove prospector

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2647]
Prospector keep introducing backwards incompatible changes in *their own* dependencies and do not update their version requirements. Since we are only running pylint through it anyway, we may as well get rid of it and run pylint ourselves directly through pre-commit and save ourselves a lot of headaches.

**Comment by ltalirz** [comment]
I guess prospector also runs pep8 and mccabe. Recently (since we've dropped python2.7 support) things have seem to become a bit more quiet.
I'd still be fine with removing prospector and moving to pylint.

**Comment by sphuber** [comment]
Fixed in PR #4190
