### ISSUE TITLE
Store version of core and plugin in `ProcessNode` attributes

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#2664]
@sphuber as discussed, I expect this will be wrapped up in a more general `Process` versioning issue soon. But I wanted to note that, because the `Parser` is decoupled from the `CalcJob`, and potentially could come from a different plugin, it would probably be good to store the version of both

**Comment by sphuber** [comment]
The current idea would be the following.
Whenever a node get stores, the engine will try to retrieve a version number from the package in which the class is defined. For the data classes this will go through the entry points and for the process nodes, it should go through the entry points of the process class that created it. The interpreter should build an internal map in a cache that maps the class to a version number of the plugin that it belongs to. This version number is then stored as an attribute. For `CalcJobs`, as @chrisjsewell rightfully mentioned, the `Parser` version should also be explicitly mentioned as it is decoupled and does not have to be in the same plugin.

For the moment, we will not allow to override the version number on a per-class basis. This approach is simple enough with respect to the required implementation in `aiida-core` as well as what is required from plugins. The developers of the latter will just have to be aware of this mechanism and update the version number and release it whenever a change in any of the relevant classes merits a different version number on the nodes. If this is the case, then it would be more than reasonable to also expect a bump in the plugin version.

A downside of this approach is that this would only work if the plugin is not used from a local copy that has unstored changes or unreleased commits. A potential solution would require the core code to start dynamically inspecting the packages to see if they are from repositories and then need to use git libraries to fetch current commits and/or even local changes. This will open a whole can of worms. Besides, this should only happen in development environments, in which case it is not wholly unreasonable that the provenance cannot be perfectly kept.

**Comment by sphuber** [comment]
See also #126

**Comment by sphuber** [comment]
The minimal required functionality for `v1.0.0` is the following:
* All `ProcessNodes` get a `version_core` and `version_plugin` attribute
* The value of these two attributes is based on the version of the package, i.e. `aiida.__version__` and e.g. `aiida_quantumespresso.__version__`
* If the plugin does not specify this property, no attribute is set at all
* The properties on the node for retrieving this value will simply return `None` if it does not exist.
* The runner responsible for creating the `ProcessNodes` will lazily build a mapping of objects (`CalcJob` and `WorkChain` classes, and `calcfunction` implementations) to the corresponding module version.
