### ISSUE TITLE
Make connection details for RabbitMQ configurable

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2685]
Currently the hostname is hardcoded to `127.0.0.` and the port is probably defaulted by either `pika` or maybe RabbitMQ itself. Some installations may require this information to be configurable

**Comment by zhubonan** [comment]
Also, 127.0.0.1 is IPv4 specific, perhaps we should use `localhost` by default? RabbitMQ by default binds to both v4 and v6. I would suggest allowing it to be customized via an environmental variable.

**Comment by sphuber** [comment]
The IPv4 specificity is done on purpose now due to this issue #1142
When we implement the possibility of configuring connection details, this workaround, if still applicable, should be documented. I don't think we should go through an environmental variable, most likely we should just expose it through the profile, just like the database. It is just an external dependency as Postgres after all.

**Comment by zhubonan** [comment]
I see. The default is probably version specific. I was trying to get the ubuntu RabbitMQ to work inside the Windows Subsystem to Linux but seems it only listen to v6 and not 127.0.0.1. I have to manually set the listener to 127.0.0.1 by editing the configuration files. I agree this should be documented.

**Comment by odarbelaeze** [comment]
https://github.com/aiidateam/aiida_core/blob/develop/aiida/manage/external/rmq.py#L36

We should make that URL a default config option instead of making it hard coded, since, that would make the RabbitMQ configuration dependent of the profile, we might want to pass it in through dependency injection.

**Comment by chrisjsewell** [comment]
I believe this was closed via 755fe479a77d201a1fe5b34e4659bf563fdc390e
(@sphuber re-open if not)

**Comment by sphuber** [comment]
Yes indeed it was: fixed in #4341
