### ISSUE TITLE
deprecated Group.get_or_create does not work when used inside pytest

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2696]
This is a rather peculiar bug discovered by @DanielMarchand:

When using the (deprecated) `Group.get_or_create` inside a pytest fixture, you get an error
```
*** aiida.backends.djsite.db.models.DoesNotExist: DbUser matching query does not exist.
```

The new method `Group.objects.get_or_create` works just fine.

Replacing the following line:
https://github.com/aiidateam/aiida_core/blob/f9618189af9fb400fc923a289634d5944d986967/aiida/orm/groups.py#L386
with
```
return cls.objects.get_or_create(**kwargs)
```
also solves the issue for `Group.get_or_create`. 

It is unclear to me, however, *why* this changes anything.
In principle, the `objects` property does nothing but this:
https://github.com/aiidateam/aiida_core/blob/f9618189af9fb400fc923a289634d5944d986967/aiida/orm/entities.py#L144-L153

I.e. `backend=None` is already the default (and we are not passing a backend by hand).

**Comment by ltalirz** [comment]
@sphuber any ideas?

**Comment by ltalirz** [comment]
For clarification: I've stopped the debugger right above line 386 (return statement shown above).

```
-> return cls.objects.get_or_create(**kwargs)
(Pdb) p backend
None
(Pdb) p cls.objects(None)
<aiida.orm.groups.Group.Collection object at 0x1100f7940>
(Pdb) p cls.objects(None).backend
<aiida.orm.implementation.django.backend.DjangoBackend object at 0x11039f128>
(Pdb) p cls.objects
<aiida.orm.groups.Group.Collection object at 0x110391c50>
(Pdb) p cls.objects.backend
<aiida.orm.implementation.django.backend.DjangoBackend object at 0x11039f128>
(Pdb) p cls.objects(None)
<aiida.orm.groups.Group.Collection object at 0x1100f7940>
```

So:
 * for some reason, `cls.objects(None)` and  `cls.objects` return different `Collection`s
 * both collections point to the same backend

**Comment by sphuber** [comment]
I would have thought the problem might have been that the collections have a different backend, where in one there would be a user and the other not. But they seem to have the same backend, so I am at a loss. I would need to debug locally to say something more useful, but not sure if this bug has the highest priority. Maybe we should get rid of the deprecated method in any case. From `0.12.*` to `1.0.0` we have removed a lot of stuff without deprecating it. Does not really make sense to keep these things around for `Group`. Likewise with all the deprecations for `type` and `name`. I would just delete them for `1.0.0` and add them to the wiki of backwards-incompatible changes

**Comment by ltalirz** [comment]
I think we should start to be a bit careful removing things now - the promise we gave at the plugin migration workshop was, essentially, that we would only change things that really needed changing.

Anyhow, I have no strong feelings about this and I agree that this bug is not very important.
I would still like to understand what is going on here, since I don't understand what the code is doing and it might affect other uses of the `.objects`

**Comment by DanielMarchand** [comment]
Ah PS what is the supported equivalent of Group.get_or_create, is Group.objects.get_or_create supported? The underlying functionality is quite nice, and I would like to switch to the supported version

**Comment by ltalirz** [comment]
@DanielMarchand Yes, as mentioned at the top of the issue `Group.objects.get_or_create` is supported and works fine.

**Comment by sphuber** [comment]
Closing this as `Group.get_or_create` has already been removed from `develop` at the time of writing
