### ISSUE TITLE
little bug in _prepare_gnuplot

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida-core#2756]
The second last line of the function _prepare_gnuplot in orm/nodes/data/array/bands.py is:
extra_files = {dat_filename: raw_data.encode('utf-8')}
However raw_data is already "bytes" object as it comes from _prepare_dat_blocks where .encode('utf-8') is applied to the returning string. So AttributeError: 'bytes' object has no attribute 'encode' is risen when the function is called.
Solution is to remove one of the two .encode('utf-8'), but I don't know which one is better...

**Comment by yakutovicha** [comment]
Thanks @bosonie, the bug should now be fixed in #2838 

In Python2 this did not cause any problem as raw_data.encode('utf-8') was basically converting from bytes to bytes
