### ISSUE TITLE
Calculation upload fails

### ISSUE THREAD

**Issue by mottetm** [aiidateam/aiida-core#2796]
I've been working on a Calculation plugin and run into an issue using it.
The [_prepare_for_submission](https://github.com/zrl-aiida-toolbox/zrl-aiida-toolbox/blob/dev/zrl_aiida_toolbox/fitter/calculations/fitter.py#L88) method works well and creates all the files needed. The files are then uploaded to the remote computer (I can find them in the folder there) but AiiDA throws an exception at that point:

```
Traceback (most recent call last):
  File "/dataP/jupyter/aiida/aiida_core/aiida/work/transports.py", line 106, in request_transport
    yield transport_request.future
  File "/dataP/jupyter/aiida/aiida_core/aiida/work/job_processes.py", line 88, in do_upload
    raise Return(execmanager.upload_calculation(node, transport, calc_info, script_filename))
  File "/dataP/jupyter/aiida/aiida_core/aiida/daemon/execmanager.py", line 170, in upload_calculation
    transport.put(src_abs_path, dest_rel_path)
  File "/dataP/jupyter/aiida/aiida_core/aiida/transport/plugins/ssh.py", line 668, in put
    raise OSError("The local path {} does not exist".format(localpath))
OSError: The local path /dataP/jupyter/aiida/repository/sandbox/tmpwTaL4M/aiida.yml does not exist
```

And after that, the folder indeed has disappeared from the filesystem.

Other calculations such as pw calculations run without issues on the instance. Any idea what could be the issue?

Thanks in advance

**Comment by sphuber** [comment]
Is the `aiida.yml` file one that you create in the `_prepare_for_submission`? Also just for verification, you are on `v1.0.0a4`?

**Comment by mottetm** [comment]
Yes still on v1.0.0a4. `aida.yml` is indeed created in `_prepare_for_submission` and uploaded, despite the error.

**Comment by sphuber** [comment]
can you perhaps share the implementation of `_prepare_for_submission` or send it to me by email?

**Comment by mottetm** [comment]
Link in the first post

**Comment by sphuber** [comment]
I am on a holiday so cannot debug in depth, but looking at the code, it seems that the problem might be that you are writing the file in the `./data` sub folder but you are telling the engine to look for it in the top level folder. Try to move line 95  (where you define the path of `aiida.yml`) after the creation of the sub folder on line 97

**Comment by mottetm** [comment]
No, the `aiida.yml` file is written in the root of the temporary directory, and the other `npy` files in the `./data` folder. 

I added
```python
import os
for root, dirnames, filenames in os.walk(tempfolder.abspath):
    print root, dirnames, filenames
```
at the end of the `_prepare_for_submission` method to make sure of it and indeed, I get:
```
/dataP/jupyter/aiida/repository/sandbox/tmpUEPHZK [u'data'] [u'aiida.yml']
```

**Comment by sphuber** [comment]
Closing due to this being reported for alpha version 4. Please reopen if this is still a problem in recent versions of `aiida-core`.
