### ISSUE TITLE
Rest api: add endpoint to download ArrayData

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida-core#2809]
Currently the endpoint is provided to get general information of ArrayData but there is no endpoint available to download the raw data (numpy array) stored in ArrayData.

Add endpoint for ArrayData to get the size of the raw data and also to download it.

**Comment by chrisjsewell** [comment]
Heya, we are working on a whole new rest api: https://github.com/aiidateam/aiida-restapi

**Comment by JPchico** [comment]
That is great! For what I understand it seems to be based in GraphQL? Should we move this discussion there? Would be very good to be able to access information stored in the `ArrayData` as `JSON` or similar formats so that one can visualize data from a calculation in a webservice.

**Comment by JPchico** [comment]
@chrisjsewell there is a PR now (with passing tests) that addresses this issue. Basically a `_prepare_json` function that works for the `orm.ArrayData`. It is nothing fancy but it gets the job done :) .

**Comment by JPchico** [comment]
Hi @sphuber I think that this issue can be closed as your PR #5425 should resolve it.
Thanks for the merge BTW!

**Comment by chrisjsewell** [comment]
Cheers @JPchico, you just reminded me to email you 😅
