### ISSUE TITLE
Database environment needs to be properly "unloadable"

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2813]
If we want profiles to be switchable in a single interpreter, the database environment needs to be switchable as well. However, currently for Django, once the `aiida.backends.djsite.settings` file is imported, the variables for example the database connection, which are based on the currently loaded profile, will be locked in. So even if the profile would be swapped for another django profile, with a different database, the original database will be used anyway.

**Comment by giovannipizzi** [comment]
A comment to be taken into account: the purpose of `recreate_after_fork()` is to be called as a callback when the process is forked (e.g. by a demoniser - this was the case with celery), here:
```
https://github.com/aiidateam/aiida-core/blob/0644e7d9ff492fdb2c94d608c575c697daee6d32/aiida/backends/sqlalchemy/__init__.py#L78
```
By the way, I realise now that probably:
1. We should dispose of the passed engine, and not the global one
2. When switching backend, probably we should deregister the callback if it was registered

**Comment by sphuber** [comment]
Closing as it is a sub problem required for fixing #2759
