### ISSUE TITLE
test coverage - worst offenders

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2835]
Despite the, still, rather unhelpful coveralls bot, I have the impression we're [overall making good progress in terms of test coverage](https://coveralls.io/github/aiidateam/aiida_core?branch=develop).

There aren't actually many **files with zero test coverage** left anymore. This is a complete list - perhaps we can make some progress on this together?

engine: 
- [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/engine/daemon/runner.py ~~@sphuber is this difficult to test?~~ Already tested; coverage report will be fixed automatically once we start using `pytest.cov` #2771

REST API:
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/restapi/common/config.py @waychal I guess you're using a different config in the tests. One way to make sure the config is tested would be to load this config but then redefine some values
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/restapi/run_api.py @waychal I think it should be possible to test at least part of this code. Also it's argparse and should be moved to click (I'll look into that)

plugins: 
There is a whole codebase for interacting with the online registry (listing plugins, installing plugins, ...) that I was unaware of and that was apparently never used. We need to decide what to do with this. On the one hand, querying the plugin registry from the cli might be convenient. On the other hand, the web site is just one click away and we should definitely avoid reimplementing pip.
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/plugins/registry.py
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/plugins/info.py
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/plugins/utils.py
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/plugins/entry.py
SPH: I also raised this point elsewhere recently and am strongly in favor of deleting the code. It does not do anything at the moment and like you say we should be careful with reimplementing our own package manager.

cmdline:
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/cmdline/utils/ascii_vis.py
   @sphuber apparently this is currently only used in `verdi process status`
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/cmdline/utils/repository.py
   @sphuber e.g. used in `calcjob inputls`

misc:
 - [ ] https://github.com/aiidateam/aiida_core/blob/develop/aiida/backends/sqlalchemy/manage.py
   @szoupanos another argparse script that could probably be tested once moved to click (I'll look into that part) [SPH: I already migrated this to click script some time ago. Did not add tests though since it is a utility script for developers and not for normal `aiida-core` use.]
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/tools/ipython/aiida_magic_register.py
   looks possible to test
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/tools/ipython/ipython_magics.py
   looks possible to test

Below are the 5 worst offenders in terms of **lines uncovered**:
 - [ ] https://github.com/aiidateam/aiida_core/blob/develop/aiida/tools/data/array/kpoints/legacy.py (490)
   @giovannipizzi were there perhaps tests that were moved to a new implementation and now no longer cover this code? should this be tested or do we just not care if it breaks?
 - [ ] https://github.com/aiidateam/aiida_core/blob/develop/aiida/orm/nodes/data/array/bands.py (237)
   Untested: `find_bandgap` as well as the `_prepare_...` functions. @giovannipizzi I guess the `_prepare_...` functions should go into tools anyhow, right?  This seems straightforward to test, perhaps suitable for @d-tomerini ?
 - [ ] https://github.com/aiidateam/aiida_core/blob/develop/aiida/orm/nodes/data/array/trajectory.py (237)
   Untested: `get_cif`, `_parse_xyz_...`, `show_mpl_...`, `plot_position_XYZ`. @giovannipizzi again, some of these probably don't belong in the node.
 - [ ] https://github.com/aiidateam/aiida_core/blob/develop/aiida/orm/querybuilder.py (211)
   Some functions untested, I could look into that
 - [x] https://github.com/aiidateam/aiida_core/blob/develop/aiida/orm/importexport.py (210)
   Given the monster that this file is, 210 uncovered lines is actually pretty good. I don't think it makes sense to advance on this before it has been split up.

**Comment by sphuber** [comment]
The daemon runner *is* tested, because I run a test that launches a daemon in a sub process in `aiida.cmdline.commands.process` but I guess exactly for that reason, coverage doesn't record those lines. Unless we can find a way to test this directly, I am not sure we can have coverage pick it up.

The `ascii_vis` was also still used for `verdi node tree` although there have been discussion before about dropping it. For any tree bigger than direct descendants the overview becomes hard to understand. The `verdi process status` is very important I would say, but probably the code required for that is a subset and could be made more efficient and smaller.

The `utils/repository` utiltiy should be easy to fix. I can add some simple tests.

**Comment by ltalirz** [comment]
> The daemon runner is tested, because I run a test that launches a daemon in a sub process in aiida.cmdline.commands.process but I guess exactly for that reason, coverage doesn't record those lines.

It seems there [are some tweaks to make this work](https://coverage.readthedocs.io/en/coverage-4.2/subprocess.html#configuring-python-for-sub-process-coverage).

**Comment by ltalirz** [comment]
> The ascii_vis was also still used for verdi node tree although there have been discussion before about dropping it. For any tree bigger than direct descendants the overview becomes hard to understand. The verdi process status is very important I would say, but probably the code required for that is a subset and could be made more efficient and smaller.

Up to you - you could also just add a simple test for `verdi process status` and see how much this covers.

**Comment by astamminger** [comment]
> > The daemon runner is tested, because I run a test that launches a daemon in a sub process in aiida.cmdline.commands.process but I guess exactly for that reason, coverage doesn't record those lines.
> 
> It seems there [are some tweaks to make this work](https://coverage.readthedocs.io/en/latest/subprocess.html#configuring-python-for-sub-process-coverage).

What about adressing this in #2771 and using ``pytest-cov`` (i think it supports coverage in subprocesses)

**Comment by ltalirz** [comment]
@astamminger Ah, [you are right](https://github.com/pytest-dev/pytest-cov), thanks for the hint!
#2771 will probably still take some time but indeed there is no rush here, so let's not waste efforts on things we will get for free :-)

**Comment by ltalirz** [comment]
Just wanted to mention that it seems to me that `coverage` is also missing (all?) tests that run the cli in interactive mode.

Since I was working on `verdi code` cli, I wanted to check whether there were any parts not covered by tests.

Coveralls seems to be convinced that `verdi code duplicate` is untested:
https://coveralls.io/builds/26934950/source?filename=aiida/cmdline/commands/cmd_code.py#L111

But there is clearly a test for it:
https://github.com/aiidateam/aiida-core/blob/cc94a1e0127cd9cab0a4049e69a9fa31cb82941c/aiida/backends/tests/cmdline/commands/test_code.py#L257-L268

Coveralls also reports the `get_default` function as untested
https://coveralls.io/builds/26934950/source?filename=aiida/cmdline/commands/cmd_code.py#L33
which, I guess, will be used only in "interactive" tests.

**Comment by giovannipizzi** [comment]
I guess the reason is that the `cli_runner` runs a new unix process, and this is not run with `coverage` in front? Maybe there is a way to ask the cli_runner to use coverage and append to the file? (Not sure, though, to what happens since this happens concurrently to our tests also writing the coverage - maybe we should have a .coverage-cli_runner file and merge them at the end?

**Comment by ltalirz** [comment]
as @astamminger mentioned [just above](https://github.com/aiidateam/aiida-core/issues/2835#issuecomment-489308546), after switching to `pytest`, this should come for free with `pytest-cov`

**Comment by ltalirz** [comment]
Just a quick update:

 * coverage reports are back (now at 77%): https://codecov.io/gh/aiidateam/aiida-core/list/8156bb14a6da241d4e9ad7d2508ab80bb1a7df22/
 * almost all files with zero coverage have been crossed off the list (only "misc" files remaining)
 * @CasperWA is working on running the daemon test through pytest
 * @unkcpz is increasing test coverage in `BandsData`

There are still 16 files with >100 lines uncovered, so there is still some way to go
<img width="951" alt="Screenshot 2020-03-04 at 00 20 13" src="https://user-images.githubusercontent.com/1053245/75829251-fe931980-5dad-11ea-891b-3202d0cacb40.png">

but overall I would say we're making good progress!

**Comment by ltalirz** [comment]
All but one of the original files with zero test coverage have been crossed off the list - new ones have come along in the meanwhile but also seem of somewhat minor importance 

![image](https://user-images.githubusercontent.com/1053245/110523945-11ec6980-8113-11eb-996b-3f3c49adde17.png)

Most of the original files with lots of uncovered lines remain - and the discussion concerning the legacy k-points module (still worst offender in terms of lines uncovered) continues in https://github.com/aiidateam/aiida-core/issues/4391 - but I feel this issue has served its purpose of taking a closer look at what code coverage tells us.

We're approaching 80% test coverage now, i.e. we're on a good trajectory. I'm closing this issue now; feel free to reopen whenever suitable.
