### ISSUE TITLE
REST API tests succeeding on travis but failing locally

### ISSUE THREAD

**Issue by elsapassaro** [aiidateam/aiida-core#2850]
REST API unit tests on getting computer nodes ordered by a combination of columns, namely `test_computers_orderby_mixed1` and `test_computers_orderby_mixed2` are failing locally in a python3 environment. 

The mentioned tests are instead passing in python2 and on Travis (both in python2 and python3).

**Comment by sphuber** [comment]
I cannot reproduce this, python 3 env on [commit 04e80d2ead00aeb6b7626dd109120295f8787db6](04e80d2ead00aeb6b7626dd109120295f8787db6). Do you still have this problem @asle85 ?

**Comment by danielhollas** [comment]
Since this issue was not reproduce and is very old I'll close this.
