### ISSUE TITLE
Update `verdi import`

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#2857]
As mentioned [here](https://github.com/aiidateam/aiida_core/pull/2820#pullrequestreview-235910419):

Suggestions to update `verdi import` code (by @ltalirz):
- [ ] archives should simply be processed one by one (there is no need to create and validate the full list of archives before you even start. e.g. `rm file1 file2 file3` also will start removing files and only stop when it encounters a file that isn't there)
- [ ] when you look at an archive you figure out whether it's a url or not. if url, validate URL and call function to download. you replace url by path to downloaded file and the following code runs inside a sandbox folder
- [ ] from now on all code is shared...

**Comment by chrisjsewell** [comment]
I think this was all addressed in #4532, but feel free to re-open if you think there is room for improvement 😄
