### ISSUE TITLE
Too many files open during tutorial

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#2895]
Reporting here an issue encountered during the May tutorial.

A user had two processes open (`verdi restapi` and a jupyter notebook).

- While trying to get data from the TCOD, for some reason the `rabbitmq` server died and we started getting errors from tornado saying the connection was closed (we tried to run a few commands)
- we restarted rabbitmq with `sudo /etc/init.d/rabbitmq-server restart`
- after this, in the jupyter notebook, we started getting `too many files open`
- we fixed this by restarting the jupyter kernel

While I think the death of rabbitmq is independent of AiiDA, I'm reporting this here because next time we should check why there was a "leak" of open files.

My bet: the rabbitmq server was not up, and at every command that tried to connect to it, one (or more) files were opened, hitting the limit. But we couldn't test this. Next time we could try to save a dump of `sudo lsof` or some similar command to see which files are open.

**Comment by giovannipizzi** [comment]
Mentioning to #2386 in case this is related?

**Comment by ltalirz** [comment]
thanks for providing the report, now we have a record of the issue
if we don't manage to reproduce this, fine to close after the tutorial

**Comment by sphuber** [comment]
Fixed in PR #4307
