### ISSUE TITLE
BandsData refers to deprecated property of KpointsData

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-core#2900]
`BandsData` refers to deprecated property `bravais_lattice` of class `KpointsData`, which generates a warning:
```
/home/aiidatests/repos/aiida_1.0/aiida-core/aiida/orm/nodes/data/array/kpoints.py:516: AiidaDeprecationWarning: the bravais_lattice method has been deprecated, see http://aiida-core.readthedocs.io/en/latest/datatypes/kpoints.html#deprecated-methods
  AiidaDeprecationWarning)
```

This is the offending line: https://github.com/aiidateam/aiida_core/blob/6d2e2dbdc95b1c4b759e6f486b10af829e84d330/aiida/orm/nodes/data/array/bands.py#L246

**Comment by mbercx** [comment]
Fixed in https://github.com/aiidateam/aiida-core/pull/3114
