### ISSUE TITLE
Eagerness of `verdi setup --help` is overruled by interactiveness

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2907]
The `--help` option is defined to be eager, as it should be, however, for interactive commands like `verdi setup`, this is overruled. This means that calling `verdi setup --help` does *not* show the usage information, but rather starts prompting for all values.

**Comment by ltalirz** [comment]
this is an important issue. how did this slip through our tests?

**Comment by ltalirz** [comment]
and when was this introduced? I hope it wasn't me with my changes to the help option ... hm

**Comment by ltalirz** [comment]
was definitely introduced *after* 1.0.0b3

**Comment by ltalirz** [comment]
Ok, it was 366771aa729a7f2752268af46ba802accc504851 (PR https://github.com/aiidateam/aiida_core/pull/2906)

**Comment by ltalirz** [comment]
@sphuber So, the problem is actually not interactiveness but the fact that we've introduced *another* eager option, namely the `--profile`.
It turns out [you are not supposed to do this in click](https://github.com/pallets/click/issues/50#issuecomment-42007728).

As suggested in the same thread, is it not possible for us to [just rely on the order of defining the options](https://github.com/pallets/click/issues/50#issuecomment-42053926) ?
Or does this not solve the issue in #2906 ?

**Comment by sphuber** [comment]
> As suggested in the same thread, is it not possible for us to just rely on the order of defining the options ?

I think this is exactly what I tried, but thought that did not work. It was still not parsing profile option in time, meaning that one of the contextual defaults which try to access it excepted. But I will have another gander

**Comment by ltalirz** [comment]
> Not sure if this is a generic problem in click or if we changed the parsing behavior with our interactive options and contextual defaults

If I understand the comments in the click issue correctly, then the using the standard `callback` to set the right value should work.
I guess it makes sense that the "contextual default" needs to be evaluated together with the parameter - it's meant for interactive prompting. In the case of interactive prompting, however, we are already guaranteed the right order: the profile will always be asked for first (if not already set).

So, perhaps the solution is something like the following:
 * restrict validation of the contextual default to when prompting interactively for a parameter 
 * use the callback to set the value of a parameter if not already provided
