### ISSUE TITLE
Missing step on macports documentation

### ISSUE THREAD

**Issue by odarbelaeze** [aiidateam/aiida-core#2915]
According to the documentation, we can install postgresql via macports successfully using the command:

```bash
sudo port install posgresql96
```

That command seems to install posgres, however the following command does not work after that:

```bash
sudo su postgres
pg_ctl -D ...
```

Bash claims that `pg_ctl` does not exist.

We need to add instructions to select the postgres version and activate the postgres port,

```bash
# sudo port select --list postgresql
sudo port select --set postgresql postgresql96
```

We might also need to add instructions to initialize a database, as described [here](https://qiita.com/yunarsoa/items/ed6c27b8655ab55e46f9).

This issue was found during the aiida workflows tutorial by @Infant83.

**Comment by chrisjsewell** [comment]
I am going to close this since macports is no longer a recommended installation path (https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/install_system.html#system-wide-installation on gives instruction for Homebrew)
