### ISSUE TITLE
create an aiida plugin/core development mailing list?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2917]
participants were asking which channel to use to discuss about plugin development (not problems of aiida-core but questions, design choices etc.)

**Comment by sphuber** [comment]
I would be in favor of this, but I personally would not have a problem with directing this over the normal user list. Currently, it is used very infrequently so I think more traffic won't be problematic and the subject matter matches just fine. If people would like to keep a low traffic base mailing list, I am also fine with having a second one dedicated to plugin development

**Comment by ltalirz** [comment]
we now have `@aiidateam/plugin-developers` - let's see how it goes
