### ISSUE TITLE
Bug in Django database migration updating group type string

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2938]
The bug will arise if the change in `type_string` will violate the uniqueness constraint of the `type_string` and `label` pair. Imagine the following rows in an existing database:
```
aiida_jsonb=# select id, label, type_string from db_dbgroup where label = 'mpds_structure_primitive';
   id   |          label           | type_string 
--------+--------------------------+-------------
 206424 | mpds_structure_primitive | 
 206467 | mpds_structure_primitive | user
```
The first row will have its `type_string` updated to `user`, which will trigger the uniqueness violation. This example comes from an old Django database that imported two export archives, one which was generated in a host database with a version where the `type_string` was always empty, and the second with a more modern version of `aiida-core` where this `type_string` is `user`. At import, there was no problem, because the uniqueness was not violated. But migrating the database will trigger the problem.

Note that this situation is a bit artificial, because the export archives could not be imported the normal way, because they had a newer archive version and the importer could not update the software, so we manually hacked the archive to make it work. I am therefore not sure how probable it is that we find more of these examples in the wild. @giovannipizzi do you think we should fix it and if so how? We would need to detect these problems and iteratively generate new names within the migration itself? Seems less than trivial

**Comment by giovannipizzi** [comment]
I see. Indeed, this shouldn't happen if people stay with "stable" export files, right?
I think it's ok, maybe the ideal thing to do (if feasible) is to check when this happens, and provide instructions on how to fix this "by hand" changing the DB content (e.g. with PSQL or with Django/SQLA or with the BackendEntities; the latter the better, if possible).
If not easy, at least let's open a doc page in the troubleshooting sections (if this is not there anymore, let's create it, and let's create a subsection about "import/export") and explain this (also for us, in case someone writes us, so we have the instructions at hand). What do you think?

**Comment by sphuber** [comment]
Since we haven't had any report about this for a year and a half, I think it is fine to close
