### ISSUE TITLE
Guarantee that order is preserved when using `append_` in `WorkChains`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2961]
Currently, the `append_` implementation does *not* guarantee that the completed futures will be added to the target list in the same order as the futures are added in the `to_context` call. This may be counter-intuitive and users actually may want to be able to rely on this. We should see if this is possible to implement.

**Comment by ConradJohnston** [comment]
@sphuber - Am I right in thinking that other than this feature, orm.List works as expecting with respect to ordering?

**Comment by sphuber** [comment]
I am not sure what `List` has to do with this feature, but if you are asking if the `List` data class maintains order, then yes, that should be the case.

**Comment by ConradJohnston** [comment]
Great, thanks! Sorry for the thread pollution.

**Comment by sphuber** [comment]
Not to worry. Just was worried I might not have understood correctly :)
