### ISSUE TITLE
REST API - docs still mention v2

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#2964]
See e.g. https://aiida.readthedocs.io/projects/aiida-core/en/latest/restapi/index.html#

I guess this should be v3 now?

@asle85 @waychal Can one of you please fix this?

**Comment by ltalirz** [comment]
As mentioned before, it would also be very useful if `verdi restapi` would show the actual URL that people need to use (including the /api/v<x>)  suffix.

**Comment by ltalirz** [comment]
Finally, this is also **the** place to advertise the provenance browser.

In addition to the `.../api/v2` link, include a link to https://www.materialscloud.org/explore/connect

BONUS: If you implement https://github.com/materialscloud-org/frontend-explore/issues/142 first, then you can display a link that you can click and it will work directly

**Comment by asle85** [comment]
The message with the base url printed when running ``verdi restapi`` comes from ``werkzeug.serving.run_simple`` and cannot be customized in a simple way.

What we can do is to print a message with the url prefix **before** the default messages, e.g.

    verdi restapi
    * Add the suffix api/v3 to form the base url
    * Serving Flask app "aiida.restapi.run_api" (lazy loading)
    * Environment: production
      WARNING: Do not use the development server in a production environment.
      Use a production WSGI server instead.
    * Debug mode: off
    * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

**Comment by ltalirz** [comment]
That's fine as well - why don't you construct the full URL there already?
E.g.
`REST API running on http://127.0.0.1:5000/api/v3`

**Comment by CasperWA** [comment]
This issue was fixed through PR #3106
