### ISSUE TITLE
Should process functions be made submittable

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2965]
Currently, it is not possible to `submit` process functions. This means that they will always "run" blockingly in the current interpreter, be it a local interpreter or one of a daemon worker. However, this also means that when a daemon worker is shutdown while it is working on a process function, that will be interrupted. Any calling processes will most likely than also fail. The fact that process functions always run blockingly means that shutting down the daemon becomes dangerous, because one risks killing active process functions. I am not sure yet if it would even be possible to make process functions submittable like other processes and make them restartable when the daemon is shutdown

Pinging @muhrin for input

**Comment by muhrin** [comment]
I just spoke with @unkcpz about this as he may be interested in such a feature for his work.  Looking at it, it *should* be quite doable (and I definitely agree that it's useful).  Maybe using the `ProcessFunction.build()` to create the process class inside the `submit()` call (where we now assert that we're not being passed a process function) could be enough.  The rest of the `submit()` call is just expecting a `Process` class so it could be good to go.

I've left it up to @unkcpz if he has enough time to attempt this but I'm happy to look over any WIP PRs that open up about this.

**Comment by unkcpz** [comment]
I guess it is safe to close this. @sphuber

**Comment by sphuber** [comment]
Fixed in PR #4539
