### ISSUE TITLE
Store CalcFunction module version in the CalcFunctionNode attributes

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#2988]
As discussed in [function provenance](https://aiida-core.readthedocs.io/en/develop/working/functions.html#provenance), currently to aid reproducibility, the source code file containing a `calcfunction` is stored with every `CalcFunctionNode`. However, this can bloat the size of the repository, and I'd question how useful it will be in practically reproducing any results. It would be nice if this behavior could be configured on/off.

In general, for any  `calcfunction`s I use, they will be *stored* in a version controlled module. I would prefer if the module version was saved, instead of the actual source file, similar to what is proposed for `calcjobs` (see #2664). 

At present the attributes stored for a `CalcFunctionNode` are:

```python
{'process_label': 'func_name',
 'function_name': 'func_name',
 'function_starting_line_number': 1,
 'function_namespace': 'module_top_level.module_sublevel',
 'exit_status': 0,
 'process_state': 'finished',
 'sealed': True}
```

The simplest solution I envision, would be to check if `module_top_level.__version__` exists and, if so, this is stored as an additional attribute, e.g. `'module_version': '1.0.0'`

**Comment by sphuber** [comment]
This is similar to #2664 but really this goes for all the processes, like work functions and work chains. Ideally for all processes the engine should keep a mapping of each process class to a corresponding version that is built lazily. It would then set these versions on the node when executed. It is then up to the developer to properly use versioning in the module or even better in a plugin.
