### ISSUE TITLE
Formalization of meaning of exit code ranges

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#2997]
This issue will be a design document to agree on a guideline for the meaning of certain exit code ranges to be used by plugins and potentially even reserve some for internal use in `aiida-core`.
The proposal in this message will be updated as the discussion progresses:

* `0 - 99` Reserved for internal use by the engine of `aiida-core`
* `100 - 199` Reserved for exit codes by scheduler parsers (This only applies to `CalcJobs` and the scheduler parsing is not yet implemented)
* `200 - 299` Suggested for compound (not automated by engine based on process spec) input validation errors
* `300 - 399` Suggested for unrecoverable errors
* `400 - ...` Suggested for recoverable errors

**Comment by sphuber** [comment]
Note this very rough initial draft is what I have currently been working with in rewriting the `aiida-quantumespresso` calculations and workflows. My thinking is that (settings aside the scheduler errors for now), any process typically has two stages:
1. Parsing and validation input
2. Parsing the results of a sub-process (in case of work chain) or external executable (case of calculation job)
In the second case, there can be errors that are really critical, such as corrupt or missing output in case of a calculation job and so this communicates to a parent, that a critical error occurred.
Alternatively, there can be more mild errors, for example a calculation job running out of wall time, but shutting down cleanly. In this case a more mild error may be appropriate as the results are likely to still be usable.

**Comment by espenfl** [comment]
Okey, this is a nice start. I am not yet sure if we should base the grouping on unrecoverable versus recoverable etc. But maybe this is the way to go.

In my view, when you run a code, the only thing we really do is input and output parsing (or maybe, for some codes, inspect the exit code directly) as you say. In addition, we should in the future do parsing to monitor a calculation of some sort. This is currently not implemented. I believe we should set the exit codes for each of these three (the monitoring might be just output parsing, or stdout parsing of a system or code command), then further down the line we act on them and end up with something that is e.g. unrecoverable. As such, I believe the pool of recoverable errors should be very large as they would contain all possible error codes users could define at the plugin level, including overrides of standard Python errors etc.

**Comment by sphuber** [comment]
> As such, I believe the pool of recoverable errors should be very large as they would contain all possible error codes users could define at the plugin level, including overrides of standard Python errors etc.

Agreed, that is also why I put this category "last" in the range, so the rightmost boundary can be open.
The reason why I split the recoverable versus unrecoverable is that I think a "strict" adherence to this will make it easy to spot for both machine and human whether a failed process has a chance of having useful outputs and being usable.

For example a work chain wrapping a calculation job could do something like:
```
def handle_failure(self, calculation):
    if calculation.exit_status < 400:
        self.report('Unrecoverable error, forget about it...')
        return
     # Else we have a recoverable error, so we can check for specific errors and act accordingly
```

**Comment by espenfl** [comment]
Yes. We also do output validation, so we should add that as well. I could not edit it.

**Comment by sphuber** [comment]
Output validation (just as input validation) is done by the engine based on the spec on process termination and process creation, respectively. If the input validation fails an exception will be thrown and the process node won't even be created. For the output validation, the node will of course already exist and I believe if the outputs validation fails, we currently set a "built-in" exit code in the reserved range `0 - 99`. This asymmetry maybe confusing, but I don't think that having the process except if output validation fails is desirable. Nor the other option, to have failed input validation create a process node and have it stop immediately with a built-in exit code. What do you think?

The category for input validation I included in the original post, is where the current validation tools of the spec, don't suffice. You can specify a valid type and a validator function, but this is not always sufficient. Because sometimes the validator requires more than just the input for the port for which it was defined. I have been solving this by having an initial step in the outline e.g. `validate_inputs`.

Thinking about it though, the `PortNamespace` also can have an optional validator. I could use that, and I think that will give access to the entire set of inputs passed to the process. If not, I could probably add this so that, just as in `click`, in the validator, you get a "context" which contains all this information.
We should think what it should return. If it can return an `ExitCode` the work chain will abort with that status.

**Comment by espenfl** [comment]
I was thinking more of output validation of the output itself, not necessarily that its type and presence is okey. This is also necessary for some of the input, sometimes. E.g. to check its content and if that is valid, say if there is some conflict etc.

**Comment by sphuber** [comment]
For that there is the `validator` keyword of the `spec.input` or `spec.output`. You can define a function that will be called and gets the node that is passed to that port. You can then exactly do what you suggest and validate its contents. This is already there and is built into the engine

**Comment by espenfl** [comment]
Okey, nice, this I did not know. But when we detect some anomalies during the execution of the `validator`, how to we throw a specific message, can we override the internal message? In my view this would typically be messages defined as input and output validation messages.

**Comment by espenfl** [comment]
We also need to make a design decision on the following. If for instance we raise `ERROR_NOT_ABLE_TO_PARSE_QUANTITY`, should that also contain a more useful message (as it already has that attribute), or should we also issue a `self.report`. If the former, we should allow to pass at least an extra string to the error, in the case above let the user know which quantity. Right now I have made a wrapper that changes the message, but seems this should be a property of `aiida_core`. Either we should change the whole message, but maybe more ideally, we could supply a list of arguments that is unpacked in `format`. Thoughts?

**Comment by sphuber** [comment]
There is already an open issue for this feature request #2644 . The only worry I would have is that it will be abused. I can totally see the use case, where there is a relatively general exit code, that has slight variations, which you want to reflect in the message. I am afraid that people will then end up defining a single exit code and reusing it all the time with wildly varying messages. If there is enough demand for the feature, I will gladly implement it however. Let's continue this discussion in that issue and give it thumbs up if you would like to see it.
