### ISSUE TITLE
Fill in documentation for "working with CalcJobs"

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3016]
Fill in the explanation for the various options in [this section](https://aiida.readthedocs.io/projects/aiida-core/en/latest/working/calculations.html#options): name of things to document are there, documentation is missing

**Comment by ltalirz** [comment]
will be fixed by #3314

**Comment by d-tomerini** [comment]
@italirz I re-assigned myself to it a few days ago, and I was about to submit a PR. Do I leave it?

**Comment by ltalirz** [comment]
oh! very sorry about this - can you check out #3314 and see whether you have some things that should be added there?

essentially, #3314 simply replaces the current docs by an autogenerated doc of the calcjob from the aiida sphinx extension

**Comment by ltalirz** [comment]
basics dealt with in #3314  - further additions by @d-tomerini welcome.
