### ISSUE TITLE
Check documentation for "working with AiiDA/Command Line interface"

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3020]
Check if it the section is updated to AiiDA 1.0, if it is correct, and if remove possible redundancies

https://aiida.readthedocs.io/projects/aiida-core/en/latest/working_with_aiida/index.html#

**Comment by ltalirz** [comment]
@sphuber @giovannipizzi 
There are currently two lists for verdi commands here:
https://aiida.readthedocs.io/projects/aiida-core/en/latest/working_with_aiida/index.html#

Can we simply delete the first one?

**Comment by CasperWA** [comment]
I think one is auto-generated? Don't know which one though.

**Comment by sphuber** [comment]
They are both autogenerated. The first is an index with the top level sub commands and a short help string. The second page is a list of each sub command with its complete help message printed. I feel the index is useful to get a quick overview, especially since it gives a link to more detailed information for that command

**Comment by giovannipizzi** [comment]
I agree one should be removed, I also feel we should remove the second one that doesn't have the short description (but the remaining one should still point to the same link with the longer description)

**Comment by sphuber** [comment]
Just for clarification: the "second" one is a mere side effect of how that index page is created. It creates a tree index of all the pages in that section. The same index that you see in the side column, but there it is an accordion. If you remove the second list then, you remove the actual content as well. What we really should do is change the way that big index page for `working with aiida` is displayed. Probably just something like show only top level entries (something like maxdepth=1 or whatever it is in sphinx)
