### ISSUE TITLE
Check documentation for "working with AiiDA/Troubleshooting"

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3029]
Check if it the section is updated to AiiDA 1.0, if it is correct, and if remove possible redundancies

See also if there is (partial or total) overlap with the [section on Troubleshooting under 'installation'](https://aiida.readthedocs.io/projects/aiida-core/en/latest/install/troubleshooting.html) and, if it makes sense, have a single 'troubleshooting' section.

https://aiida.readthedocs.io/projects/aiida-core/en/latest/working_with_aiida/index.html#troubleshooting

**Comment by yakutovicha** [comment]
@giovannipizzi, @sphuber  I would actually move the Troubleshooting section from the "Installation" (keeping the reference) to "Working with AiiDA".

Let me know if it makes sense. If yes - I will do it.
