### ISSUE TITLE
Check and revisit the section for AiiDA developers

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3034]
This includes the following sections under "for AiiDA developers":

- [ ] AiiDA internals
- [ ] Transport plugins
- [ ] Database schema
- [ ] Modifying the schema
- [ ] How to extend the AiiDA REST API
- [ ] Caching: implementation details
- [ ] Developing The Plugin System
- [x] Sphinx cheatsheet (@CasperWA)
- [ ] Design evolution

We need to check if they are updated to 1.0, remove them if they don't make much sense, or update them if appropriate, add missing content or remove stale one.

**Comment by CasperWA** [comment]
This is a bit more work than I thought - I have assigned almost everyone now, but maybe instead this issue should be split into separate issues for each of the documents?

**Comment by CasperWA** [comment]
Up to now, I have gone through:

- Sphinx cheatsheet

**Comment by giovannipizzi** [comment]
Ideally yes, if multiple people should go through it, better to make individual issues

**Comment by CasperWA** [comment]
> Ideally yes, if multiple people should go through it, better to make individual issues

Okay, I'll create the issues.

**Comment by CasperWA** [comment]
Closing this.
See instead issues: #3173 #3174 #3175 #3176 #3177 #3178 #3179 #3180 #3182
