### ISSUE TITLE
Check installation instructions for MacOS

### ISSUE THREAD

**Issue by borellim** [aiidateam/aiida-core#3050]
The current 'installation' and 'quick_installation' pages need to be tested with MacOS (both Macports and Homebrew). In particular, the instructions to install pip and virtualenv are simply a link to two external tutorials. We may want to incorporate them into our docs.

**Comment by Yash1256** [comment]
Sir I am Yash Shukla , I want to work on on your project So would you tell me where to start from

**Comment by ltalirz** [comment]
Hi @Yash1256 -  I see you've probably already found the "good first issue" labels.

This issue concerns the following part of the installation instructions:
https://aiida.readthedocs.io/projects/aiida-core/en/latest/install/prerequisites.html#mac-os-x-homebrew

**Comment by ltalirz** [comment]
Thanks anyhow for testing the installation instructions @Yash1256 , much appreciated!
