### ISSUE TITLE
Refactor the SqlAlchemy and Django `QueryBuilder` implementation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3082]

**Comment by muhrin** [comment]
@sphuber Is this issue still being tracked?  It is clear what needs to be done?

**Comment by sphuber** [comment]
Not sure, but I think the original idea was that there was quite some overlap in the implementations that could just be moved to `aiida.orm.querybuilder.QueryBuilder` instead

**Comment by muhrin** [comment]
Ok, then it sounds related to #3632 which I just opened.  My perferred route would be to have something like a `RelationalBackendQueryBuilder` that is a base class for both.
