### ISSUE TITLE
Direct scheduler in combination with `SshTransport` hangs on submit command

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3094]
The ssh transport command to execute the scheduler submit will not return until the actual job is completed if the `direct` scheduler is used. The command that is executed is:
```
cd '/scratch/aiida/c7/13/9099-ea09-4914-b24f-524e0f4b586c' && bash -e '_aiidasubmit.sh' > /dev/null 2>&1 & echo $!
```
However, the `SshTransport.exec_command_wait` hangs at the line:
```
output_text = stdout.read().decode('utf-8')`
```
It seems that even though the launching of the submit script is backgrounded, the `stdout.read` will not finish until the background process has terminated. As soon as that happens, the command returns and the `CalcJob` continues from the `SUBMIT` task to the `UPDATE` task, at which point it is already finished of course.

**Comment by giovannipizzi** [comment]
Just adding a script to reproduce this, so it's easier to find a fix:

1. create a computer in AiiDA using ssh+direct (e.g. here `localhost-ssh`) 
2. on the remote computer (might of course be localhost), create a folder (in the example here `/Users/pizzi/tmp`) and a file in it (here `submit.sh`). Make it executable and the content in my case was simply:
   ```bash
   #!/bin/bash
   sleep 5
   ```
3. Use this script to check - it will hang for 5 seconds if you use ssh+direct:
   ```python
   computer = Computer.get(label='localhost-ssh')
   scheduler = computer.get_scheduler()
   transport = computer.get_transport()
   scheduler.set_transport(transport)
   with transport:
       print(scheduler.submit_from_script('/Users/pizzi/tmp', 'submit.sh'))
   ```

Note: when using local+ssh, this does not hang instead.
