### ISSUE TITLE
Unify zip/tar archive format export functions

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3100]
When performing the refactoring of the import/export file (PR #3052), it became apparent that the compression pathway for zip and tar should be unified.
As it is now, zip has a separate function.

Furthermore, the classes `ZipFolder` and `MyWritingZipFile` should be moved to common or the implementation should be rewritten.

**Comment by CasperWA** [comment]
Since working on PR #3242 (that brings more power to the `Archive` class), it seems to me that we do not need the `ZipFolder` class at all. Especially, since all is done via the regular `zipfile` module's `ZipFile` class.

**Comment by CasperWA** [comment]
Ah, I see now the difference and reason behind the functions.
Concerning zip, the archive is written directly in a zipped folder using a StringIO in-memory stream, while for tar, the archive is created first as a folder on the filesystem, before being added to a tar-file and afterwards compressed.
So for zip, there is no step of first creating the archive on the filesystem - instead all is written directly to the zip file.
Perhaps this can be done as well for tar, however?

**Comment by ltalirz** [comment]
Fixed in #4510
