### ISSUE TITLE
Fix `Unrecognized job_state '?'` warning

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#3107]
Just a minor annoyance, but when I use `engine.run` in an interactive terminal, if the process takes more than a few minutes, I start getting a lot of warnings printed:

```
07/01/2019 05:56:01 PM <26394> aiida.scheduler.direct: [WARNING] Unrecognized job_state '?' for job id 8399
```

**Comment by sphuber** [comment]
This is with the `direct` scheduler on a `localhost` computer?

**Comment by chrisjsewell** [comment]
> This is with the `direct` scheduler on a `localhost` computer?

Yep. There doesn't seem to be any issue with the runs completing.

**Comment by ltalirz** [comment]
Confirmed; e.g. using the script from https://github.com/aiidateam/aiida-core/issues/4298#issue-677561470
(to set up the code, do `verdi code setup --config config/add.yaml`).

It does not need to be in an interactive terminal, I've also seen it happen simply with `verdi run script.py`
