### ISSUE TITLE
Transport params are unicode in sqlalchemy backend, but dictionaries when using Django-BE

### ISSUE THREAD

**Issue by lekah** [aiidateam/aiida-core#311]
The execution of the daemon depends on DbComputer.get_transport_params returning a dictionary
This is not the case in the SQLAlchemy backend, where a string is returned:
  
File "/home/kahle/git/aiida/aiida/daemon/execmanager.py", line 313, in submit_jobs
    submitted_calcs = submit_jobs_with_authinfo(authinfo)
  File "/home/kahle/git/aiida/aiida/daemon/execmanager.py", line 362, in submit_jobs_with_authinfo
    with authinfo.get_transport() as t:
  File "/home/kahle/git/aiida/aiida/backends/sqlalchemy/models/authinfo.py", line 72, in get_transport
    params = dict(Computer(dbcomputer=self.dbcomputer).get_transport_params().items() +
AttributeError: 'unicode' object has no attribute 'items'

**Comment by lekah** [comment]
I should add that the computer is imported, so maybe upon import that json-string is not decoded?

**Comment by szoupanos** [comment]
So what is the (full) scenario?

You import some data and you also import a computer. Then you try to run a calculation with an already imported computer? If yes, I am not sure if the imported computers should be used to launch new calculation (I should check).

Could you also provide a small import file that demonstrates the problem - if this causes the deamon to crash.

The behaviour should be the same in both backends. I am just trying to understand how the daemon is affected (in order to fix it in the proper way).

**Comment by lekah** [comment]
Yes, as you describe it. To launch a calculation with a computer that was just imported, you have to configure it. 

[start.zip](https://github.com/aiidateam/aiida_core/files/696621/start.zip)

**Comment by szoupanos** [comment]
The problem appears when you import a computer in SQLA that has been exported using Django. SQLA expects the transport_params (and the metadata) to be exported as dictionaries and not as strings containing the JSON that corresponds to these structures.

I will change the import/export of SQLA to conform to the Django export format.

**Comment by szoupanos** [comment]
I see that the commit related to this issue it is mentioned automatically by GitHub here even if it was committed at my personal repository (!!! - I am impressed). 

In general, there is some progress (mainly all the needed tests for this problem) at https://github.com/szoupanos/aiida_core/commit/f732e9dfae14a64768d7796cf1e3e95bcabe7ce5

The code import/export code needs to change too (to work as expected and to stop breaking the added tests).

**Comment by sphuber** [comment]
This is no longer relevant as the mentioned code has long since been refactored
