### ISSUE TITLE
rename repository to aiida-core

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3127]
This is a minor change but in view of the 1.0 release I suggest to rename the repository to `aiida-core`, so that the core repository is no longer deviating from the naming scheme we suggest for plugins.

The nice forwarding by github means that this should not break anything - everything should keep working via the old URL as well.

**Comment by ltalirz** [comment]
@giovannipizzi @sphuber Do you agree?

**Comment by sphuber** [comment]
I would definitely like this change, my only fear was breaking things. If that really will not happen due to the forwarding, I am on board

**Comment by sphuber** [comment]
@ltalirz seems we have a green light

**Comment by ltalirz** [comment]
Then I shall proceed!

**Comment by ltalirz** [comment]
Brace yourselves!
