### ISSUE TITLE
Use `get_all_same_nodes` with unstored nodes

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#3151]
Since #3108, `get_all_same_nodes` can no longer be used from unstored nodes. This is useful, for example, when setting up inputs for a calculation, to check if a required data node already exists, i.e. basically implementing caching (without cloning) for data nodes.

A fix might look something like this:

https://github.com/aiidateam/aiida-core/blob/dcea08154a021572d2233bd23c88bf49beaf7c5d/aiida/orm/nodes/node.py#L1145

```python
from aiida.orm.utils.node import clean_value

    def get_all_same_nodes(self, allow_before_store=False):
        if not self.is_stored and allow_before_store:
            self.set_attribute_many(clean_value(self.attributes))
            return list(self._iter_all_same_nodes(allow_before_store=True))

        return list(self._iter_all_same_nodes())
```

**Comment by sphuber** [comment]
The example implementation would perhaps be correct for `Data` nodes, but I think it would be incorrect for `ProcessNodes`, wouldn't it? The attributes are not the only thing that are not finalized before storing. Doesn't the same go for inputs that are not (yet necessarily) finalized when the node is not yet stored. To me, the whole reason we don't allow matching identical nodes before storing is for this reason. So it feels dangerous to me to circumvent this rule. Closing this therefore until we found a real use case where this is necessary
