### ISSUE TITLE
Streamline and clean files related to export archive migration tests

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3156]
The tests can be simplified, if

- the current `remove_fields` utility function is remade into `replace_or_remove_fields`, and make it agnostic to whether metadata or data was supplied or not;
- ~`arithmetic.add_old.aiida` export archive is not needed;~ and
- tests for migrations are split up into smaller tests, similar to the way the migrations are now split.

_Edit_: The test `test_calcjob_inoutputcat_old` under `aiida.backends.tests.cmdline.commands.test_calcjob.TestVerdiCalculation` is the only test that uses the `airthmetic.add_old.aiida` archive, and for a specific purpose at that.

**Comment by danielhollas** [comment]
Closing this since the new archive format in #5145 made this irrelevant

> the current remove_fields utility function is remade into replace_or_remove_fields, and make it agnostic to whether metadata or data was supplied or not;

`remove_fields` function no longer exists.
