### ISSUE TITLE
`ToContext` does not wait for the sub-process to finsih

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#3158]
We (with @danieleongari) just discovered that the following [WorkChain](https://github.com/danieleongari/aiida-cp2k/blob/aa1f16d2805c02f70858a93d6271b06516459807/aiida_cp2k/workchains/multistage.py#L67-L122) does not wait till the subprocess is completed:

![Screenshot from 2019-07-12 12-28-37](https://user-images.githubusercontent.com/13118485/61121875-a155fb00-a4a0-11e9-982b-0b709ad5b7de.png)

The problem seems to be in the `return ToContext(..)` which (according to the [docs](https://aiida.readthedocs.io/projects/aiida-core/en/develop/working/workflows.html#to-context)) is **supposed to wait** until the sub-process is done.

To fix the problem we introduced another step of the workchain that uses the `self.ctx.workchains` variable.

To me it looks like a bug.

**Comment by yakutovicha** [comment]
Related question: how to kill the sub-processes?

![Screenshot from 2019-07-12 12-37-17](https://user-images.githubusercontent.com/13118485/61122340-d9117280-a4a1-11e9-8769-bc1fda15c0ba.png)

**Comment by sphuber** [comment]
Well it waits for the thing to finish if it makes sense to wait for it. For example if there is another step after the step that returns the `ToContext`. However, the spec only defines two steps. So as far as the spec of the `WorkChain` is concerned, after `run_stage0` there are no more steps so the workchain must be done. If you want it to wait, simply add another step to the outline

**Comment by sphuber** [comment]
Regarding the killing of processes. The error you are getting means the corresponding task no longer exists at all, or it is with a daemon runner that fails to respond in time. The latter should be unlikely, so I expect the task was already gone. What was the output of `verdi process list` at the time?

**Comment by yakutovicha** [comment]
> Well it waits for the thing to finish if it makes sense to wait for it. For example if there is another step after the step that returns the `ToContext`

But this means if one runs the `Cp2kMultistageWorkChain` using the `run` method [as we did](https://github.com/danieleongari/aiida-cp2k/blob/aa1f16d2805c02f70858a93d6271b06516459807/test/test_workchain/test_multistage.py#L106), the `run` won't wait until the workchain and its sub-workchains are completed, right? At least in our case it didn't.

I might be wrong, but I would expect `run` to wait for all of them to finish.

Moreover, it looks to me the daemon has lost control over the sub-processes (the "lowest" cp2k process is not proceeding further and none of the sub-processes can be killed)

> What was the output of `verdi process list` at the time?

I remains like this forever:
```
$ verdi process list -a 
  PK  Created    Process label                Process State    Process status
----  ---------  ---------------------------  ---------------  --------------------------------
 438  3h ago     Cp2kMultistageWorkChain      ⏹ Finished [11]  <---- code 11 means no results were returned, this has nothing to do with the current problem
 439  3h ago     Cp2kBaseWorkChain            ⏵ Waiting        Waiting for child processes: 440
 440  3h ago     Cp2kCalculation              ⏹ Created
```

If I submit the new job, keeping the 'DEBUG' log level, I get the following output:

```
$ verdi run test_multistage.py  cp2k@localhost 
Testing CP2K multistage workchain on H2O (DFT)...
Submitted Multistage workchain...
07/12/2019 02:33:37 PM <15038> aiida.engine.persistence: [DEBUG] Persisting process<455>
07/12/2019 02:33:37 PM <15038> aiida.engine.persistence: [DEBUG] Persisting process<455>
07/12/2019 02:33:37 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:37 PM <15038> aiida.engine.persistence: [DEBUG] Persisting process<455>
07/12/2019 02:33:37 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:37 PM <15038> aiida.engine.persistence: [DEBUG] Persisting process<456>
07/12/2019 02:33:37 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:37 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [455|Cp2kMultistageWorkChain|run_stage0]: submitted Cp2kBaseWorkChain<456> for settings_0/stage_0
07/12/2019 02:33:38 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:38 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:38 PM <15038> aiida.engine.persistence: [DEBUG] Persisting process<456>
07/12/2019 02:33:38 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:38 PM <15038> aiida.engine.persistence: [DEBUG] Persisting process<456>
07/12/2019 02:33:38 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:38 PM <15038> aiida.engine.persistence: [DEBUG] Persisting process<457>
07/12/2019 02:33:38 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:38 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [REPORT] [456|Cp2kBaseWorkChain|run_calculation]: launching Cp2kCalculation<457> iteration #1
07/12/2019 02:33:38 PM <15038> aiida.engine.persistence: [DEBUG] Persisting process<456>
07/12/2019 02:33:38 PM <15038> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'
07/12/2019 02:33:38 PM <15038> aiida.orm.nodes.process.calculation.calcjob.CalcJobNode: [DEBUG] Broadcast message 'None' received with communicator '<kiwipy.rmq.communicator.RmqSubscriber object at 0x7f1511a45d30>'

```

**Comment by sphuber** [comment]
The fundamental problem is that you do not define another step after `run_stage0`. The engine sees that as soon as the work chain returns from that step `run_stage0` that there are no further steps to be done, so the process is "done". It then checks the outputs, according to the spec and sees that the required outputs (defined because you used `expose_outputs`) are not there, so the validation fails and exit status 11 is set. The solution is simply to add one more step to your outline. Call it `results` because in any case you will have to attach the outputs of the sub process you launched. Remember, the `expose_outputs` call in the spec is just declaring the output _ports_. You still have to attach the _actual_ outputs using `self.out`. As soon as you add another step in the outline after `run_stage0`, the workchain will properly wait for the sub process to finish

**Comment by sphuber** [comment]
Regarding the `Cp2kCalculation` not starting, that is a direct consequence of the problem described above.  "Running" a process will create a `Runner` in your local interpreter and it will run everything inside that runner. So sub processes that will be launched will _not_ be sent to the daemon, but the runner itself will run those. I am not sure what happens to the runner in this scenario, but it might be that it just stops. Do you regain control of the terminal soon after having called `run(Cp2kMultistageWorkChain)`?

**Comment by yakutovicha** [comment]
> Do you regain control of the terminal soon after having called `run(Cp2kMultistageWorkChain)`?
yes, immidiately

**Comment by sphuber** [comment]
Just add a last `results` step to your outline and it will work

**Comment by yakutovicha** [comment]
> Just add a last `results` step to your outline and it will work

This is perfectly clear. And we did exactly this to fix the problem (see my very first comment: "... To fix the problem we introduced another step of the workchain that uses the self.ctx.workchains variable.")

My main concern is the following. If I define a workchain that (a) does not return any outputs (I assume it is allowed. It is useful for the development) (b) has two steps: `prepare` and `run`. If I run this workchain using the `run` method, it will exit immediately and won't wait till all its sub-processes are completed. Do you agree that this is not exactly what a user expects?

This is why I would suggest that engine does exactly what is written [in the documentation](https://aiida.readthedocs.io/projects/aiida-core/en/develop/working/workflows.html#to-context), meaning waits for the sub-processes  to finish independently of what is going to happen afterwords in the workchain. The sentence in the docs I am referring to is: "...Returning an instance of `ToContext` signals to the engine that it has to wait for the futures contained within it to finish execution, store their nodes in the context under the specified keys and then continue to the next step in the outline."

Or, if you disagree, I am happy to add a couple of sentences to the documentation about the necessity of having additional WorkChain step after returning `ToContext`

**Comment by sphuber** [comment]
> then continue to the next step in the outline

This is the critical part of that sentence. If there is no next step, than there is no point to wait for it, because apparently you are not going to do anything with its outputs anyway. And again, `expose_outputs` just declares the outputs the workchain will or can emit, depending on the `required` attribute. If you are not calling `self.out` explicitly, the work chain will have no outputs.

I agree that the documentation could be more clear on this, so I added a warning in PR #3160

**Comment by yakutovicha** [comment]
> And again, `expose_outputs` just declares the outputs the workchain will or can emit, depending on the required attribute. If you are not calling `self.out` explicitly, the work chain will have no outputs.

sure, perfectly clear. It is anyways unrelated to the topic of the issue. I should have removed the line ` spec.expose_outputs(Cp2kBaseWorkChain)` before posting the issue, to not cause additional confusions.

> I agree that the documentation could be more clear on this, so I added a warning in PR #3160

thanks a lot!

**Comment by ltalirz** [comment]
I tend to agree with @yakutovicha that users may expect a WorkChain to wait for its sub-WorkChains to finish before it finishes itself. @sphuber @giovannipizzi Wouldn't you agree with this?

**Comment by yakutovicha** [comment]
According to @sphuber the workchain will wait for its sub-processes to finish only if there is an additional step after the one that calls the sub-processes:
```
future = self.submit(MyWorkChain, **inputs)
return ToContext(results=future)
```
so having the line `return ToContext(results=future)` is not enough.

My suggestion was to let `return ToContext(results=future)` be *the only* condition that let's the workchain to wait the sub-processes to finish.

**Comment by giovannipizzi** [comment]
I also agree that the user would expect the workchain to wait.
If it's too complex to fix this, we should at least mark in the docs that we plan to change this (if also @sphuber agrees on the logic) so people don't rely on the behaviour.
Also, is it possible to add something to the report in case there is a `return ToContext` but nothing is waiting for them?

**Comment by sphuber** [comment]
I will take a look to see how much work it will take to change this behavior. But I still want to stress that even if we do, the workchain example of Sasha would still have failed with exit code 11, since no outputs would have been registered.

**Comment by sphuber** [comment]
> If it's too complex to fix this, we should at least mark in the docs that we plan to change this (if also @sphuber agrees on the logic) so people don't rely on the behaviour.

I already updated the docs to warn users about this behaviour

**Comment by yakutovicha** [comment]
> But I still want to stress that even if we do, the workchain example of Sasha would still have failed with exit code 11, since no outputs would have been registered.

Yes, this is true. I should have removed the line `spec.expose_outputs(Cp2kBaseWorkChain)` from the workchain to not diverge people's attention from the main topic of the issue.
