### ISSUE TITLE
Check documentation for "for AiiDA developers/How to extend the AiiDA REST API"

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3177]
Check if the section is updated to AiiDA 1.0, if it is correct, and if it should be merged with other documentation or moved/removed.

https://aiida.readthedocs.io/projects/aiida-core/en/latest/developer_guide/core/extend_restapi.html

**Comment by d-tomerini** [comment]
Hi @waychal,
I checked the script in this section and it does not work. I've seen what the problem is; I can work on it, and put you as a reviewer if you haven't started already
