### ISSUE TITLE
verdi help has calculation descriptions that are too long

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3196]
When running `verdi`, one gets a list of available commands with a short description.

Now, some of them have a too-long description that is truncated:
```
$ verdi 
Usage: verdi [OPTIONS] COMMAND [ARGS]...

  The command line interface of AiiDA.

Options:
  -p, --profile PROFILE  Execute the command for this profile instead of the
                         default profile.
  -v, --version          Show the version and exit.
  -h, --help             Show this message and exit.

Commands:
  calcjob            Inspect and manage calcjobs.
  code               Setup and manage codes.
  comment            Inspect, create and manage node comments.
  completioncommand  Return the bash code to activate completion.
  computer           Setup and manage computers.
  config             Set, unset and get profile specific or global...
  daemon             Inspect and manage the daemon.
  data               Inspect, create and manage data nodes.
  database           Inspect and manage the database.
  devel              Commands for developers.
  export             Create and manage export archives.
  graph              Create visual representations of part of the
                     provenance...
  group              Create, inspect and manage groups.
  import             Import one or multiple exported AiiDA archives The...
  node               Inspect, create and manage nodes.
  plugin             Inspect installed plugins for various entry point...
  process            Inspect and manage processes.
  profile            Inspect and manage the configured profiles.
  quicksetup         Setup a new profile where the database is
                     automatically...
  rehash             Recompute the hash for nodes in the database The set
                     of...
  restapi            Run the AiiDA REST API server Example Usage: verdi
                     -p...
  run                Execute an AiiDA script.
  setup              Setup a new profile.
  shell              Start a python shell with preloaded AiiDA environment.
  status             Print status of AiiDA services.
  user               Inspect and manage users.
```
I think we should fix this to avoid `...`

**Comment by giovannipizzi** [comment]
More generally, we should check also subcommands and help strings critically for all CLI commands

**Comment by sphuber** [comment]
These are formatted automatically by `click` with a default width of 80 characters I believe. Do you want to change the width or just shorten the messages of the commands? In any case, if you were to do `verdi rehash --help` you would see the full message of course, so I honestly don't think it is that big of a problem.

**Comment by giovannipizzi** [comment]
I think I have two points I'd like to address:
- read all of them together and check that the way they are written is consistent (now some of them are not, and/or might be improved)
- Use [this](https://click.palletsprojects.com/en/7.x/documentation/#command-short-help) to have a short text when the docstring should be longer (example: for `rehash` I would set a short text to `Recompute the hash for nodes in the database` only and then have instead the full docstring for `verdi rehash --help`)

**Comment by sphuber** [comment]
If PEP 257 is respected and the docstring starts with a short description on a single line, terminated by a full stop (!important) then that is used as the short help and the rest of the docstring won't be shown in the help overview. This is easier to use and maintain than using the `short_help` keyword since that will duplicate a lot of the text in the code
