### ISSUE TITLE
compatibility issue with new_calc command

### ISSUE THREAD

**Issue by mguarrasi** [aiidateam/aiida-core#3211]
Dear All,

after updating the Aiida core and the Q.E. plugin, I'm adapting my scripts to the new commands.
Usually I create a new calculation from the parameters I have using the following command:
...
code = Code.get_from_string(codename
calc = code.new_calc()
...
but actually this command is no more supported. Can you give me a suggestion about the method to replace it? 
Currently I have seen that on the PW tutorial (https://aiida-quantumespresso.readthedocs.io/en/latest/user_guide/get_started/examples/pw_tutorial.html) this is still the method used to create a calculation.

Thanks,
M.

**Comment by d-tomerini** [comment]
Dear M.,

The documentation of the Quantum ESPRESSO plugin is still being updated to the latest version.

You can find instructions on how to prepare the required input for a calculation in this section of our latest tutorial, that is compatible with the latest version of AiiDA:

https://aiida-tutorials.readthedocs.io/en/latest/pages/2019_MARVEL_Psik_MaX/sections/calculations.html#creating-a-new-calculation
