### ISSUE TITLE
UX issues with `verdi data structure import`

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3214]
There are a number of user-experience issues with `verdi data structure import`, like:
- the default format is None, so the user will get a weird exception saying None is not a valid format
- not storing by default seems unexpected to me; rather, we can use an optional `dry-run` mode just to check if the parser worked
- I don't think it  makes sense to have a `--view` option in there (there is already a `verdi data structure show`)
- there is some confusion between "format" and "parser" (the same list contains xyz, a format, ase, a parser, etc.)
- the command-line options only apply to some of the formats (probably we will need to define multiple subcommands, one per parser)
- there is a lot of copy-paste code in the actual importers that can be de-duplicated

**Comment by sphuber** [comment]
Fixed in PR #3216
