### ISSUE TITLE
Many printing routines print time in UTC instead of local time

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3225]
Try e.g. `verdi comment show` or `verdi show` (but I don't have a full list).

The solution is to use, e.g.,
```python
entity.ctime.astimezone(tzlocal.get_localzone()).strftime('%Y-%m-%d %H:%M')
```
instead of
```python
entity.ctime.strftime('%Y-%m-%d %H:%M')
```

(I don't know if there is a more automated way of doing it).

**Comment by d-tomerini** [comment]
@giovannipizzi in principle there is the ``timezone.localtime`` in aiida.common, if that is the same. Maybe it is more clear to use that?

By the way, you mean only in printing? I found some other instances, like in the autogroup command, where the name is not given in local time, but U guess i should not change that

**Comment by CasperWA** [comment]
> By the way, you mean only in printing? I found some other instances, like in the autogroup command, (...)

I think you're right - times should _only_ be in local time for printing, i.e. when retrieving a list using `verdi` or similar. For group labels/names and similar UTC should be used, in order to make it more ... universal :smile:
