### ISSUE TITLE
Verdi code setup: add `withmpi` or `mpi_support` option

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#3236]
When setting up a code on a given computer it is already known to the user whether the code has been compiled with MPI support or not.

However, an AiiDA lab app that was build on top of AiiDA does not know this. Therefore, it does not know whether the option `withmpi` should be set to `True` or to `False` and can accidentally specify something like `mpirun -n 2 code.x` while the code was not compiled with an mpi support.

Of course this could be bypassed by using `mpirun -n 1 code.x`, which works also with the codes that are not compiled with mpi. But such a solution looks sub-optimal to me. Imagine an automated tool that automatically determines the number of cpus needed. How could it know that the code was not compiled with mpi support?

**Comment by yakutovicha** [comment]
It might be possible to add such an option into extras, see #420

**Comment by ltalirz** [comment]
I think this should become part of the attributes of a code.

For serial codes, AiiDA should also assume default values for resources settings (pseudocode):
```
'metadata.options.resources' = {
                      'num_machines': 1,
                       'num_mpiprocs_per_machine': 1,
                       'tot_num_mpiprocs': 1,
}
```
and warn users if they explicitly request something different.

Mentioning @danieleongari for info

**Comment by sphuber** [comment]
See this original comment by @ltalirz on the original PR on the hierarchy of the various ways of specifying `withmpi` for a `CalcJob`: https://github.com/aiidateam/aiida-core/pull/5152#issuecomment-1410401414

The final desired behavior is described below.

There are 4 ways that influence whether a code in a `CalcJob` is run with MPI:

1. `option_value`: The value of the `metadata.options.withmpi` input if explicitly defined
2. `option_default`: The default of the `metadata.options.withmpi`. Is set to `False` by the `CalcJob` base class, but can be switched by plugins.
3. `plugin`: The value of the `CodeInfo.withmpi` attribute which is set by the `CalcJob` plugin.
4. `code`: The value set by the code input.

The `option_default` is essentially a bit superfluous and should not really be used. The first problem is that it doesn't account for the fact that a `CalcJob` can run multiple codes, and so can take multiple `Code` inputs, each of which could have a different MPI requirement. However, the `option_value` is a single boolean, and doesn't take a list of booleans. Therefore, if the plugin really wants to enforce certain codes to be run with or without MPI, it should use the `CodeInfo.withmpi` (i.e. `plugin`) attribute instead.

The `code` value is the new feature that is proposed. It is an optional boolean defined on a `AbstractCode` instance. If not specified, i.e. `None`, it means the code does not enforce whether it is run with or without MPI. When set to `True` or `False`, it means this code _has_ to be run with or without MPI, respectively.

The logic for evaluating these various controls to determine whether to run the code with MPI or without is as follows:

* The `option_default` is only used if none of `option_value`, `plugin` and `code` are used.
* An explicitly defined `option_value` will override `option_default` without any checking.
* The final value is defined by the union of `option_value`, `plugin` and `code`, exluding `None`.
* If multiple values are defined, they all _have_ to be equivalent or an exception is raised.

**Comment by ltalirz** [comment]
Thanks a lot for the summary @sphuber ! 

I agree with the 4 rules listed at the end concerning the logic to be implemented.

There is just one aspect of the writeup I want to comment on, which is relevant to what we recommend plugin developers to do going forward:

> The `option_default` is essentially a bit superfluous and should not really be used. The first problem is that it doesn't account for the fact that a `CalcJob` can run multiple codes, and so can take multiple `Code` inputs, each of which could have a different MPI requirement. However, the `option_value` is a single boolean, and doesn't take a list of booleans. Therefore, if the plugin really wants to enforce certain codes to be run with or without MPI, it should use the `CodeInfo.withmpi` (i.e. `plugin`) attribute instead.

It is true that the single boolean does not take into account the possibility of multiple codes, but to my knowledge it still covers the vast majority of plugins out there (say >90%) which only use one code per CalcJob.
I would also point out that this criticism applies not just to the default value of the option, but also to the case where a user sets the option explicitly.
I'm therefore not convinced that we should dissuade plugin developers from changing this default value in cases where it makes sense (one `CodeInfo`).

One advantage of using an `option_default` over implementing a default in the `CodeInfo` is that it is explicit in the spec and accessible programmatically for documentation purposes (although `verdi plugin list` output currently does not descend into the `metadata` input).

**Comment by sphuber** [comment]
> One advantage of using an `option_default` over implementing a default in the `CodeInfo` is that the default value is explicit in the process spec and accessible programmatically for documentation purposes (although `verdi plugin list` output currently does not descend into the `metadata` input).

This is a fair point. However, what should the logic be for multiple code calcjobs where the default conflicts with the value set on the `CodeInfo`. Should we just ignore the default, or raise as in the other cases? In that case, the plugin should explicitly set the default to `None`.

**Comment by ltalirz** [comment]
I see, another problem here is the default value set by the `CalcJob` base class in aiida-core, which prevents us from determining whether the default value is an intentional choice of the plugin developer or just the default coming from AiiDA.

I believe this currently forces us to entirely ignore the `option_default` in cases where there are more than one `CodeInfo` (I don't see another option?).

One could imagine modifying the `CalcJob` class to _not_ set a default value for the `withmpi` option, and just fall back to `False` at the point where the different mpi-related settings are evaluated, if nothing else is set.
While this would be backwards compatible in terms of MPI behavior, however, it _would_ change the calcjob `metadata` inputs, and plugin developers may already be relying on the fact that `metatdata.options.withmpi` is always defined. 


If this thinking is correct, then let's not make changes here, and let's ignore the the `option_default` when multiple `CodeInfo` objects are seen.

As for what to tell plugin developers... I still feel that using the `option_default` value is a sensible thing to do in most cases, but I guess both approaches are fine (just no need to do both, as I mistakenly do [here](https://github.com/aiidateam/aiida-plugin-cutter/blob/3d03ff0a374e70cb6e05b9bb5ea6f59497f30f0f/%7B%7Bcookiecutter.plugin_name%7D%7D/%7B%7Bcookiecutter.module_name%7D%7D/calculations.py#L74)).
