### ISSUE TITLE
problems with click: `verdi setup` and `verdi quicksetup`

### ISSUE THREAD

**Issue by d-tomerini** [aiidateam/aiida-core#3243]
I think ``verdi setup`` has some issues. Tested with python 2.7 / 3.6 on my installation.

- ``-h`` or ``--help`` are accepted. Nonetheless, I'm first prompted to insert ``profile name``, and after I do, it quits the setup, showing the help;
-  With additional flag ``--profile`` passed to it, it shows directly the help: ``verdi setup --profile xyz -h``;
-  ``verdi setup --email xyz@xyz -h`` still asks for ``profile name``, and it quits after I comply, showing the help;
-  ``verdi setup zzz`` lets me go to the end of the setup, and THEN it complains  ``Error: Got unexpected extra argument (zzz)``. Non-existing option works as expected (it complains immediately)
-  ``verdi setup zzz -h `` does not complain about ``zzz`` . Should it?

Quicksetup is affected by the same issues, of course.

**Comment by sphuber** [comment]
Thanks Daniele. All of these are known and already have other issues:

- [#2907] ``-h`` or ``--help`` are accepted. Nonetheless, I'm first prompted to insert ``profile name``, and after I do, it quits the setup, showing the help;
- [#2907] With additional flag ``--profile`` passed to it, it shows directly the help: ``verdi setup --profile xyz -h``;
- [#2907] ``verdi setup --email xyz@xyz -h`` still asks for ``profile name``, and it quits after I comply, showing the help;
- [#1938]  ``verdi setup zzz`` lets me go to the end of the setup, and THEN it complains  ``Error: Got unexpected extra argument (zzz)``. Non-existing option works as expected (it complains immediately)
- [#1938] ``verdi setup zzz -h `` does not complain about ``zzz`` . Should it?

Let's continue the main discussion there

**Comment by sphuber** [comment]
Opened a PR for #2907  and added more details to #1938 and will continue discussion there, so closing this.
