### ISSUE TITLE
Update prefix message printed for `verdi restapi`

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3270]
From issue #2964

Comment by @asle85:

The message with the base url printed when running ``verdi restapi`` comes from ``werkzeug.serving.run_simple`` and cannot be customized in a simple way.

What we can do is to print a message with the url prefix **before** the default messages, e.g.

    verdi restapi
    * Add the suffix api/v3 to form the base url
    * Serving Flask app "aiida.restapi.run_api" (lazy loading)
    * Environment: production
      WARNING: Do not use the development server in a production environment.
      Use a production WSGI server instead.
    * Debug mode: off
    * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

Answer from @ltalirz:

That's fine as well - why dont you construct the full URL there already?
E.g.
`REST API running on http://127.0.0.1:5000/api/v3`

**Comment by sphuber** [comment]
This seems to have been fixed in PR #3106 in commit 19ed82e6b2a2c43be300edcf61e291665115ebf0
