### ISSUE TITLE
self.exposed_outputs() does not work with CalcJobs

### ISSUE THREAD

**Issue by danieleongari** [aiidateam/aiida-core#3272]
I wonder why `exposed_outputs()` works to parse the results from WorkChains (as the documentation describes) but not for CalcJobs.

On the contrary `expose_outputs()` works for both.

An example is in the `PwBaseWorkChain`, where the outputs from the `PwCalculation` are specified with `expose_output()`
```
             spec.expose_outputs(PwCalculation, exclude=('retrieved_folder',))  
```
but then they are extracted without using  `exposed_outputs()`:
```
        for name, port in self.spec().outputs.items():

            try:
                node = calculation.get_outgoing(link_label_filter=name).one().node
            except ValueError:
                if port.required:
                    self.report("required output '{}' was not an output of {}<{}>".format(
                        name, self.ctx.calc_name, calculation.pk))
            else:
                self.out(name, node)
                if self._verbose:
                    self.report("attaching the node {}<{}> as '{}'".format(node.__class__.__name__, node.pk, name))
```

In my case I was using the same protocol for a WorkChain and the DdecCalculation, and in the second case `exposed_outputs()` returns and empty AttributeDict.

Nothing very problematic because I can obtain my outputs in the "old, explicit" way, but @ltalirz and  I were wondering what is the reasoning behind this different behavior.

Thanks,

Daniele

**Comment by sphuber** [comment]
This problem should have been fixed by PR #3258 that was merged yesterday. I think if you update to the latest `develop` it should work.

**Comment by ltalirz** [comment]
Ah - thanks @sphuber !
Daniele said he wants to stick with released versions for the moment, but in this case I assume this is fixed (reopen, if the issue persists).

**Comment by danieleongari** [comment]
This works fine to me, thanks @sphuber !
