### ISSUE TITLE
Failing test for job state

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#3280]
For instance:

```
verdi process list -a
10290  1m ago     VaspCalculation    ⏹ Finished [0]
verdi shell
test = load_node(10290)
test.get_last_job_info()
JobInfo({..., 'job_state': <JobState.RUNNING: 'running'>, ...})
```
Job is obviously completed. Due to this, e.g. this snippet in `engine.processes.calcjobs.manager`:

```

            for job_id, job_info in iteritems(scheduler_response):
                # If the job is done then get detailed job information
                detailed_job_info = None
                if job_info.job_state == schedulers.JobState.DONE:
                    try:
                        detailed_job_info = scheduler.get_detailed_jobinfo(job_id)
                    except exceptions.FeatureNotAvailable:
                        detailed_job_info = (
                            'This scheduler does not implement '
                            'a command and/or parser for obtaining '
                            'detailed job information'
                        )
 
                job_info.detailedJobinfo = detailed_job_info
                jobs_cache[job_id] = job_info
```

fails as JobState.DONE will never be present. This should most likely be changed to JobState.RUNNING. In some scenarios this fails. Say that the job is queued and completes before the next cycle, then `JobState.QUEUED` should be used. In fact, I am a bit tempted to fetch the detailed job info regardless and strip it as much as possible (so there is limited overlap).

Discovered this while fiddling with https://github.com/aiidateam/aiida-core/pull/3261. On a fresh `develop` from today.

**Comment by sphuber** [comment]
If this code is intended to get a dictionary of detailed job info from the scheduler, than this is the wrong place in the code. It was originally written by @muhrin . If that is the goal, it should rather be put in one of the transport tasks, or get its own transport task even for added granularity. For example we could add it to the `UPDATE` task, that when it find the job is terminated, it queries the scheduler once more for detailed info that is then directly stored on the node, or optionally even parsed if that functionality is provided by the scheduler plugin. Alternatively, this could be done after the `RETRIEVE` task, at which point the scheduler stdout and stderr content will also be available for parsing.

**Comment by espenfl** [comment]
Okey. My personal view of this now is that we should remove the pulling of `detailed_job_info` during the regular execution. It was simply not used. In case anyone needs it, we can put it back in. Then we only pull `detailed_job_info` in the accounting step when the job is done. Also, I am not really sure how useful that `get_last_job_info` is. We should maybe simply replace it with `get_job_info`, which basically returns the more detailed stuff from `sacct`, e.g. the accounting. Then we avoid overlap.

**Comment by sphuber** [comment]
This should already have been addressed so I am closing it. Please reopen if it is still actually relevant
