### ISSUE TITLE
verdi data bands show broken

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3283]
This is on the latest develop branch
```
$ verdi data bands show 247
Traceback (most recent call last):
  File "/home/max/.virtualenvs/aiida/bin/verdi", line 10, in <module>
    sys.exit(verdi())
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/max/codes/aiida_core/aiida/cmdline/utils/decorators.py", line 68, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/max/codes/aiida_core/aiida/cmdline/commands/cmd_data/cmd_bands.py", line 99, in bands_show
    show_function(fmt, data)
  File "/home/max/codes/aiida_core/aiida/cmdline/commands/cmd_data/cmd_show.py", line 228, in _show_xmgrace
    tempf.write(text)
  File "/home/max/.virtualenvs/aiida/lib/python3.6/tempfile.py", line 624, in func_wrapper
    return func(*args, **kwargs)
TypeError: write() argument must be str, not bytes
```

One could fix this issue by switching from `w+` to `w+b` here
https://github.com/aiidateam/aiida-core/blob/d2f710922cdbde6a8c0d48a3242cece14bef185d/aiida/cmdline/commands/cmd_data/cmd_show.py#L227
but I'm a bit puzzled by the fact that the `_exportcontent` function of `BandsData` returns `bytes` instead of `str`.

Looking through the code, this is clearly by design, but to me it seems like the common practice would be to use strings within AiiDA, and to encode to binary representation only when writing to file.
When using strings, these functions could be used for purposes other than direct export without having to worry about de/encoding.

@giovannipizzi Is there a reason why this is not the case here?
Is there anything preventing us from switching the return values of these export functions to `str`?

**Comment by giovannipizzi** [comment]
We've been discussing this with @sphuber today. we still have mixed feelings on the right thing to do, but here I would be tempted to say that using binary is better

**Comment by ltalirz** [comment]
Perhaps a short explanation would be useful here, also to keep for the future.

One argument I could see is if some of these functions directly return the output of external programs that one anyhow gets in binary format.
Also, since the functions are aiming at preparing exports (and mainly used for that) I guess there is not much of a difference.
Still, it seems a bit strange that every function by itself converts its return values to binary first.

Finally, is the decision to switch to `w+b` as described above?
There might be a few more cases than the line mentioned above where this would be necessary.

**Comment by sphuber** [comment]
This is an often occurring problem, see #3277 and #3237 for example. Also [Sasha's PR](https://github.com/aiidateam/aiida-core/pull/2838) is attempting to solve the same problem in another place, but he is decoding the bytes returned by `_exportcontent` which is not the correct solution. Looking through the code, there are a lot of places where the return value of `_exportcontent` is being written to a non-binary file handle. This suggest that the tests are also lacking severely here, because none of those problems are caught.

**Comment by ltalirz** [comment]
Even if we don't fix this right now, could we reach a conclusion on what the could *should* do ideally?

I realized just now that in my comments above I once wrote `_exportcontent` where I wanted to write `_prepare_...`. What I meant to say is:
> I'm puzzled that all the `_prepare_...` functions seem to return bytes instead of strings. Shouldn't this better be left to `_exportcontent`?

Re 
> This suggest that the tests are also lacking severely here, because none of those problems are caught.

Yes - it's spot 2 among the [worst offenders](https://github.com/aiidateam/aiida-core/issues/2835) by number of lines uncovered.

**Comment by sphuber** [comment]
So you propose that we change the spec that the `_prepare` functions just return strings. The `_exportcontent` calls the `_prepare` method and encodes that into bytes?

As far as I can tell `export` is the only one who calls `_exportcontent` and is the one that is finally responsible to writing the content to file. Should we not make `export` then responsible for encoding? And if we get strings, there is no need to open in binary mode and encode first. But if we want to give the option to users to encode in specific encoding, we can expose `encoding` argument.

**Comment by ltalirz** [comment]
> As far as I can tell export is the only one who calls _exportcontent and is the one that is finally responsible to writing the content to file. Should we not make export then responsible for encoding? 

Sure, the further down the line, the better.

> And if we get strings, there is no need to open in binary mode and encode first. But if we want to give the option to users to encode in specific encoding, we can expose encoding argument.

Makes sense.

>  I find it a bit weird that _exportcontent is a private member. Why should this also not be a public method if one just wants the raw export content string and then they can do with it as they please.

I don't really have objections - except that making it public forces us to keep the interface stable from that point onwards.

**Comment by giovannipizzi** [comment]
As already noted, when we change this we should also check a few more things.
Just as an example, also `verdi data structure show` has similar problems (for sure the `--format=xcrysden` format, but I guess/fear most of them).

**Comment by ltalirz** [comment]
@giovannipizzi so should I have a stab at this?
I.e. the idea would be:

 * the `_prepare_...` functions should return strings
 * conversion to binary happens as close to writing as possible (or as convenient - might be more convenient to do somewhere else)
 * add tests, tests, tests

**Comment by sphuber** [comment]
I believe this has since been fixed, but I cannot find the PR anymore. Please reopen if the problem persists
