### ISSUE TITLE
verdi shell imports deprecated module

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3293]
The following happens in the tutorial VM:

```
$ verdi shell
/home/max/codes/aiida-core/aiida/backends/profile.py:23: AiidaDeprecationWarning: this module is deprecated
  warnings.warn('this module is deprecated', AiidaDeprecationWarning)  # pylint: disable=no-member
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
```

I really wonder why... I've searched throughout the codebase and don't really understand what triggers the import of `aiida.backends.profile`.

Note: This does not happen with other `verdi` commands that use the database, e.g. `verdi process list`...

**Comment by ltalirz** [comment]
Interesting... the deprecation warning is triggered exactly on this line:
https://github.com/aiidateam/aiida-core/blob/91715883b30409397cc034704b41908fa2e42fb6/aiida/cmdline/utils/shell.py#L146

**Comment by ltalirz** [comment]
Renaming the file from `profile.py` to  `profiles.py` makes the problem go away (but of course also breaks compatibility)

**Comment by ltalirz** [comment]
Tracking it further to here:
https://github.com/ipython/ipython/blob/8971c8e5f31d20768609e20f60870d627eb33bd0/IPython/__init__.py#L46

For some reason, this ends up adding `aiida/backends` to `sys.path`

**Comment by ltalirz** [comment]
There are a couple of `sys.path.insert` in the AiiDA codebase, and I'm not sure these are really needed.

https://github.com/ltalirz/aiida_core/blob/a500d2b2801efa393ce6f567dc9893a62696b8f1/aiida/cmdline/commands/cmd_run.py#L113
Is this really needed? Won't the current directory in the sys.path anyhow?

https://github.com/aiidateam/aiida-core/blob/d750d513f7adf5126d43a230c9fb378de02f0772/aiida/sphinxext/tests/workchain_source/conf.py#L32
This looks dangerous...

https://github.com/aiidateam/aiida-core/blob/cc94a1e0127cd9cab0a4049e69a9fa31cb82941c/utils/validate_consistency.py#L190
Ok... this script is just called by pre-commit hooks. Still, do we need to insert at position 0?

https://github.com/aiidateam/aiida-core/blob/cc94a1e0127cd9cab0a4049e69a9fa31cb82941c/aiida/common/files.py#L194
This function is supposedly copied from `shutil.which`, and the branch only occurs when `sys.platform == 'win32'`. Still, this looks nasty - we're calling `which` and, as a side effect, `sys.path` changes?

**Comment by ltalirz** [comment]
and here is the real perpetrator
https://github.com/aiidateam/aiida-core/blob/91b205bcdeebc3d6f9a019c77c38ffdf6fc95321/aiida/backends/djsite/settings.py#L31
importing the `settings.py` rewrites `sys.path`!

**Comment by ltalirz** [comment]
@sphuber @giovannipizzi Would you mind letting me know whether you believe any of these 5 path manglings are really needed?

If not, I would try to make a PR that either removes them or makes them append to the path (if really necessary).

**Comment by sphuber** [comment]
I don't think I am responsible for any of those lines. Not to duck responsibility, but just to say that I do not really know if they are really needed. So if they _can_ be removed without changing functionality, then I would say why not

**Comment by giovannipizzi** [comment]
I also don't know/remember if they are needed and why they are there.
I agree that if removing them does not break anything, we can go ahead. Maybe don't do it before the tutorial ;-) even if I guess you will use b6, so if you do this in develop this will not affect your tutorial, and we have time to test this before the release of 1.0.
