### ISSUE TITLE
Error:could not determine the current profile

### ISSUE THREAD

**Issue by 1976114031** [aiidateam/aiida-core#3302]
when i run the code shown in tutorial, i encounter this Error
`from aiida.engine import calcfunction
from aiida.orm import Int

@calcfunction
def add(x, y):
    result = Int(x + y).store()
    return result

result = add(Int(1), Int(2))`

and the error is 
`Traceback (most recent call last):
  File "test.py", line 9, in <module>
    result = add(Int(1), Int(2))
  File "/home/wangl/anaconda3/envs/aiida/lib/python3.6/site-packages/aiida_core-1.0.0b5-py3.6.egg/aiida/orm/nodes/data/base.py", line 46, in __init__
    super(BaseType, self).__init__(**kwargs)
  File "/home/wangl/anaconda3/envs/aiida/lib/python3.6/site-packages/aiida_core-1.0.0b5-py3.6.egg/aiida/orm/nodes/node.py", line 111, in __init__
    backend = backend or get_manager().get_backend()
  File "/home/wangl/anaconda3/envs/aiida/lib/python3.6/site-packages/aiida_core-1.0.0b5-py3.6.egg/aiida/manage/manager.py", line 129, in get_backend
    self._load_backend()
  File "/home/wangl/anaconda3/envs/aiida/lib/python3.6/site-packages/aiida_core-1.0.0b5-py3.6.egg/aiida/manage/manager.py", line 86, in _load_backend
    raise ConfigurationError('could not determine the current profile')
aiida.common.exceptions.ConfigurationError: could not determine the current profile`

but i have setup the profile 
`verdi profile show
Info: Configuration for: aiida2
----------------------  -------------------------------------------
aiidadb_backend         django
aiidadb_engine          postgresql_psycopg2
aiidadb_host            localhost
aiidadb_name            aiidadb
aiidadb_pass            1q2w3e
aiidadb_port            5432
aiidadb_repository_uri  file:///home/wangl/.aiida/repository/aiida2
aiidadb_user            aiida
default_user_email      1976114031@qq.com
options                 {}
profile_uuid            8ff48a0aeac74a209361580f788fd02c
----------------------  -------------------------------------------
`
where is wrong?

**Comment by ltalirz** [comment]
@1976114031 did you run this code using `verdi run`?

Also, I notice you have aiida-core 1.0.0b5 installed, while the tutorial should have been using 1.0.0b6. This should not be the cause of the problem, but just leads me to ask where are you running this code?

**Comment by 1976114031** [comment]
Thank you for your reply! It's my first time using github.
I run this code in jupyter.  I have solved this problem when i add the following code: 
`from aiida import load_profile
load_profile()`
I find this solution from github issues, but i must complain that i have carefully read the tutorial, nowhere tells me to firstly add  the two lines code above~ ╥﹏╥
I am a newer python user, may be some underlying rule I didn't know?  I hope the tutorial can be more friendly that at least copying the code from tutorial can run well.

**Comment by 1976114031** [comment]
@ltalirz 
Thank you for your reply! It's my first time using github.
I run this code in jupyter. I have solved this problem when i add the following code:
`from aiida import load_profile`
 `load_profile()`
I find this solution from github issues, but i must complain that i have carefully read the tutorial, nowhere tells me to firstly add the two lines code above~ ╥﹏╥
I am a newer python user, may be some underlying rule I didn't know? I hope the tutorial can be more friendly that at least the code copied from tutorial can run well.

**Comment by ltalirz** [comment]
@1976114031 thanks for your feedback.
I guess you are referring to code from the aiida-core documentation, e.g. [here](https://aiida.readthedocs.io/projects/aiida-core/en/latest/working/functions.html), correct?

Indeed, it seems this section is written with the assumption that the user is already familiar with the concept of an AiiDA profile (and e.g. that you can always use `verdi run <script>` or the `verdi shell` to execute these snippets).

Still, I think the error message you received should be more user friendly and have adde PR #3306 to improve it.
