### ISSUE TITLE
Graph consistent/recursive exploration tool

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#3331]
Both the delete (#3296) and export (#3295) functionalities need to take a list of nodes and get a second list where all connections of a given list of types have been exhausted.
The idea would be to define an interface that both features could use and create a simple engine for it that could later be improved upon.
So in principle this function would take not the optional keywords that delete and export use (since we could later add others that turn on or off multiple of them at the same time), but the ones for the exact kind of links that are optional ("translation" would be in charge of delete/export). That is:

* INPUT_CALC_FORWARD
* CREATE_FORWARD
* CREATE_REVERSED
* RETURN_REVERSED
* INPUT_WORK_FORWARD
* CALL_CALC_FORWARD
* CALL_CALC_REVERSED
* CALL_WORK_FORWARD
* CALL_WORK_REVERSED

I was thinking as implementing it literally as a single function that takes a list of nodes and those logicals and returns the requested list that exhaust all possible paths. I would call it something like `exhaustive_explore` maybe? Comments welcome.

**Comment by CasperWA** [comment]
Sounds like a good idea :+1:

**Comment by sphuber** [comment]
Things that have be improved/merged:
- #3262 `aiida.tools.importexport.dbexport._retrieve_linked_nodes_query` should be moved to generic AGE
- #3262 `aiida.tools.importexport.dbexport.retrieve_linked_nodes` data structures of `links_uuid_dict` are probably unnecessarily complex and should be simplified
- #3262 `aiida.tools.importexport.dbexport.retrieve_linked_nodes` is building queries with redundant information. In principle just knowing the pk of the starting node and the link type to follow is enough. Adding filters on the source and target node type is already encoded perfectly in the link type. The future AGE can leverage this to make this query efficient. It will only have to query the `DbLink` table as all information needed is contained in there.
- #3262 definition of `togglable_link_rules` is done in multiple places and should be put close to or even merged with the `aiida.tools.importexport.common.config.LINK_FLAGS` dictionary.

**Comment by CasperWA** [comment]
>     * #3262 definition of `togglable_link_rules` is done in multiple places and should be put close to or even merged with the `aiida.tools.importexport.common.config.LINK_FLAGS` dictionary.

This I actually already did originally, but it was thought to be too complex.
