### ISSUE TITLE
Docs: Remove `--pre` for PyPI installation documentation (when releasing v1.0.0)

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3339]
When releasing the final AiiDA v1.0.0, the `--pre` flag should be removed from [these](https://github.com/aiidateam/aiida-core/blame/ab4571e9edf06b591518324fe78a2bfeddddf81e/docs/source/install/installation.rst#L59) kind of lines in the documentation, i.e.:

```shell
pip install --pre aiida
```

**Comment by sphuber** [comment]
Also we should consider replacing the metapackage with `aiida` with `aiida-core`.

**Comment by ltalirz** [comment]
Fine for replacing `aiida` with `aiida-core`.

Also fine for removing `--pre` but only once aiida-1.0 release is imminent.
