### ISSUE TITLE
extras randomly disappearing

### ISSUE THREAD

**Issue by Zeleznyj** [aiidateam/aiida-core#3388]
I'm running into a strange issue, where I set up some extras for a WorkChainNode, which in some cases randomly vanish shortly after setting them. This doesn't happen always but quite frequently. Sometimes all extras vanish and sometimes only few. This may be because I'm doing something wrong, but I cannot figure out where the problem could be and it seems like a bug.

The code, which I'm using to submit calculations and set extras is: 

```python
def submit_mp_fplo(material_ids,run_kwargs=None):
    pks = []
    for mid in material_ids:
        pk = run_fplo_plus_wannier(mid,**run_kwargs)
        node = load_node(pk)
        pks.append(pk)
        node.set_extra('project','mp-testing')
        node.set_extra('material_repository','mp')
        node.set_extra('id',mid)
        node.set_extra('production','testing')
        node.set_extra('calculation','fplo+wannier')

    return pks

```
Here run_fplo_plus_wannier is a function that runs aiida.engine.submit to submit a workchain and returns pk of the corresponding workchain node. This is using our plugins to run FPLO calculations. Apart from the extras everything seems to be running fine. I run this function from verdi shell.

I've seen the extras disappear within seconds to perhaps a minute after running this function, never later.

I've tried verifying that the extras are set correctly within the function and in most cases  they are, which mean, they vanish after the function is finished.

The code I'm using in practice is a bit more complicated and has more extras, which are obtained, for example, from the inputs of the WorkChainNode. The problem is much more common with the more complicated code, where the extras disappear very frequently (maybe 1 in 5 cases). In the simpler code included here, it's less common, but still occurs. 

The problem seems to be random, if I repeat a calculation, sometimes no extras disappear and sometimes different ones than previously disappear.

I'm using aiida-core 1.0.0b6.

**Comment by sphuber** [comment]
Are you using the django backend by chance? If you are not sure you can run `verdi profile show <PROFILE_NAME>`. If that is the case, you might be affected by a very subtle bug I fixed two weeks ago, which is not yet released: https://github.com/aiidateam/aiida-core/commit/1cdf73793fda5da62f0269210ff492d23eb2dd31
If you are in fact running django, would you be willing to checkout the `develop` branch and run your workchain again, to see if the problem persists? Upgrading should be safe because there are no backwards incompatible changes in `develop` since `aiida-core==1.0.0b6`.

**Comment by Zeleznyj** [comment]
Yes, I'm using django. I tried the develop branch and the problem seems to be gone. Hard to be 100% sure, because it was quite random before, but I've done quite a few test calculations now and didn't see the problem, so most likely it's fixed.

Thank you for your help.

**Comment by sphuber** [comment]
Great. Thanks for the initial report and follow up. I will close this for now then, but if the problem crops up again, feel free to reopen it.
