### ISSUE TITLE
Exception raised "no computer specified" when submitting a `CalcJob`

### ISSUE THREAD

**Issue by mrlixuec** [aiidateam/aiida-core#3395]
I want to try run a calcjob,however it always note me that i has not specified a computer.But the verdi computer test and verdi status is good.Below is my code:
```
from aiida.engine import run,submit
from aiida.orm import load_code,Int,load_computer
from aiida.plugins import CalculationFactory
from aiida import load_profile

load_profile()

ArithmeticAddCalculation = CalculationFactory('arithmetic.add')

inputs = {
        'code':load_code(label='add1'),
        'x':Int(1),
        'y':Int(2),
        'metadata':
             {'options':
                 {'resources':{'num_machines':1,'num_mpiprocs_per_machine':1},
                  'computer':load_computer(label='localhost'),
                     }
              },
         }

submit(ArithmeticAddCalculation,**inputs)
```

**Comment by sphuber** [comment]
In principle your `code` object already has a connected computer.
You can make sure by doing the following in a `verdi shell`:
```
from aiida.orm import load_code
code = load_code('add1')
code.computer
```
This should print the computer that is configured for that code.
This always means you don't have to specify the computer in the inputs of the calculation.
Just specifying the `code` is enough. So try removing `computer` from the `metadata.options` and submit again

**Comment by sphuber** [comment]
Also, could you please report what version of `aiida-core` you are using? Thanks

**Comment by mrlixuec** [comment]
> Also, could you please report what version of `aiida-core` you are using? Thanks

Thank you very much!!! I will try your solution,and the version of my aiida-core is 1.0.0b6

**Comment by mrlixuec** [comment]
> Also, could you please report what version of `aiida-core` you are using? Thanks
I'm so sorry!! I find it's i hadn't connect my code to a conputer,so the mistake was made .
The code could running normally withou `code.computer`.
Again,I'm so sorry make a problem for you .And thank for your effort on aiida!Thank you very much .

**Comment by sphuber** [comment]
No problem. So I take it you are able to run the example now?

I will keep this issue open because I am a bit surprised that it is possible to store a `Code` without a `Computer`. I will investigate how this is possible and whether we should consider it as a bug.
