### ISSUE TITLE
Required restart of daemon to pick up changes in workchain

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#3403]
Upon creating a workchain, a call script (which calls the workchain) and running the call script, for every change of this workchain the daemon needs to be restarted for it to pick up the changes. Is the previously submitted workchain somehow cached? Seems possibly like something that can confuse users.

This example workchain was created outside of entry points and from this I notice that it is not required to set `PYTHONPATH` as long as the workchain module reside in the directory where the call script is executed. Most likely a relative import will also work, but I have not tried that.

**Comment by sphuber** [comment]
> This example workchain was created outside of entry points and from this I notice that it is not required to set `PYTHONPATH` as long as the workchain module reside in the directory where the call script is executed. Most likely a relative import will also work, but I have not tried that.

What will have happened in this situation is that the path in which the launch script and workchain definition reside, are itself within a directory that is already included in the path. If not, it should really be impossible to import at all. You can verify by opening an ipython shell in complete other directory and try to import the workchain. My guess is that that should also work, so the path is included somehow. For example, the same works if you place your workchain within the aiida source tree. Since that is in the path, all relative directories within it will also be.

> Upon creating a workchain, a call script (which calls the workchain) and running the call script, for every change of this workchain the daemon needs to be restarted for it to pick up the changes.

So you are changing the work chain code _while_ the chain is running?! I don't think that is ever going to work. What if it already passed the point where you made a change?

**Comment by espenfl** [comment]
> What will have happened in this situation is that the path in which the launch script and workchain definition reside, are itself within a directory that is already included in the path. If not, it should really be impossible to import at all. You can verify by opening an ipython shell in complete other directory and try to import the workchain. My guess is that that should also work, so the path is included somehow. For example, the same works if you place your workchain within the aiida source tree. Since that is in the path, all relative directories within it will also be.

But I think this should anyway work as nothing happens with the daemon before `submit`. And at that point the definitions are in place after the import in the call script. Importing the workchain anywhere does not work of course.

> So you are changing the work chain code _while_ the chain is running?! I don't think that is ever going to work. What if it already passed the point where you made a change?
> 

No, that would be a nice feature but we are not there yet I guess. Just perform some modification and then relaunch etc.

> Cached the code or the work chain instance itself (i.e. "caching" in the AiiDA sense). For the latter, workflows are not cacheable so no and for the former, the code should not be cached. Once the daemon restarts and picks up the work chain to continue it, it imports the corresponding class (with the code change) and resume execution. That is also the reason the daemon has to be restarted. There is no hot-code reloading in python

So I first submit a workchain, wait for it to finish, modify it and submit again. Should the daemon then pick up the change or do I have to also restart the daemon? Since I import the modified workchain in the call script, the updated definitions should be in place even without restarting the daemon.

However, maybe I should mention that I also have another issue that might be related to this, or causing all this confusion on my end. Say I do not do any changes. Then I submit the workchain, it is stuck in `Created`. If I resubmit, it starts. Waiting for it to finish, the same can be repeated again. Pretty sure this is not standard feature and that there is something more going on here.

**Comment by sphuber** [comment]
I will paste my response from slack here:

No, there is no direct "passing" of the workchain code to the daemon. When you "submit" a process, it is instantiated locally and its checkpoint saved to the database on the corresponding node. This _does not_ contain the source code of the classes. The daemon on the other side will get the task from RabbitMQ, which is just the pk, it will load the process instance from the database, but the checkpoint only contains the class name. The daemon will then import the corresponding implementation. If it already has imported it, it will not reimport it. This is just a python limitation and not something we control. This is why you _always_ have to restart the daemon when having made changes to your code, even when you submit a new process.

**Comment by espenfl** [comment]
Thanks for confirming this. I will document this clearly on the plugin side. I suggest we close the issue.
