### ISSUE TITLE
`Computer.default_mpiprocs_per_machine` weirdly named

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3406]
The `default_mpiprocs_per_machine` property of the `Computer` seems to suggest that the value means the number of MPI processes to launch per machine (node). This is _not_ however what the property docstrings say; namely it is the number of processors (CPUs) per machine. The latter makes much more sense as a property of a computer, i.e. a machine. This is further corroborated by the fact that this property is set during computer setup and the label states: "Default number of cpus per machine". @giovannipizzi did the two get mixed up at some point? Is the original intended definition of this property indeed the "number of CPUs (or cores) per machine (node)"?

**Comment by giovannipizzi** [comment]
This goes back in history, probably 2014 or so.
I had changed this to mpiprocs because this is the actual behaviour (what to do in `mpirun -n XXX`). I see your reasoning, though (the property that makes more sense is the number of cores per node). However, in the end this is used to choose the default number of mpiprocs per machine=node, so I would see the property name (and possibly change the docs? Even if I think it's ok to ask for the number of CPUs (in the end it's more intuitive) and then use it as a default # of MPI process

**Comment by sphuber** [comment]
After some more diving it seems like the property name is correct and actually means the "default number of MPI processes to use per node", but the docstring and the label in the `verdi computer show` output is incorrect, which refer to number of CPUs per node.

What we often would need for efficient parallelization in addition to this information (which can be overridden with `number_mpiproces_per_machine` on a per-calculation basis) is to know the number of CPUs per machine, as in just its architecture. The reason is that, based on the number of MPI processes requested, we need to compute the number of CPUs per MPI proc and set it explicitly. If not, schedulers like SLURM will set the default, which is 1, running the risk of having many CPUs idling on the node. Would it be advisable to add a property to `Computer` detailing the number of CPUs each node has? Would this give problems with machines that have inhomogeneous node layouts/architectures? Maybe we can make it optional?

**Comment by ltalirz** [comment]
Corresponding adding the number of CPUs per node, I think this makes sense and the discussion on this should continue in #3503 .

Staying with MPI, however, there is also the question of whether MPI (`mpirun` or similar) is available on a computer at all. I don't think this can currently be configured at the computer level, but I think it should.
This affects e.g. the AiiDA docker container, see https://github.com/aiidateam/aiida-core/pull/3732#issuecomment-579293358

**Comment by ltalirz** [comment]
As of AiiDA 2.2, this is the status quo:

Output in `verdi code show` looks fine:
```
...
Default #procs/machine       1
...
```

Help message in `verdi computer setup` looks fine:
```
  --mpiprocs-per-machine INTEGER  The default number of MPI processes that
                                  should be executed per machine (node), if
                                  not otherwise specified.Use 0 to specify no
                                  default value.
```

I am therefore closing this issue.

The question whether we need a separate property to define the number of cores continues in https://github.com/aiidateam/aiida-core/issues/3503

**Comment by sphuber** [comment]
> think this can currently be configured at the computer level, but I think it should.

I think technically at least this can be achieved by simply setting the `mpirun_command` to an empty string. This might not be the most intuitive and may need more documentation, but it _is_ possible, isn't it?
