### ISSUE TITLE
Importing a workchain module outside entry points results in a stuck in created state

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#3407]
First, make sure the `PYTHONPATH` containing the workchain and its call script is seen by the daemon. The import the workchain in the call script as:

`from my_local_workchain_file import my_local_workchain`

And then later:

`submit(my_local_workchain, ...)`

This yields spurious stalled processes that are stuck in a `Created` state. In fact it seems, every second submission starts normally and vice versa.

Moving the definitions and imports to the entry point system seem to remedy these issues.

**Comment by greschd** [comment]
Interesting.. does it depend on the number of workers how many processes get stuck?

Just tried reproducing this, and with  ``local_workchain.py``:
```python
from aiida.orm import Int
from aiida.engine import WorkChain

class Echo(WorkChain):
    @classmethod
    def define(cls, spec):
        super(Echo, cls).define(spec)
        spec.input('x', valid_type=Int)
        spec.output('x', valid_type=Int)
        spec.outline(cls.run)

    def run(self):
        self.out('x', self.inputs.x)
```
and ``run.py``:
```python
#!/usr/bin/env runaiida

from aiida.orm import Int
from aiida.engine.launch import run, submit
from local_workchain import Echo

for _ in range(10):
    submit(Echo, x=Int(1))
```
all works as expected (``aiida-core`` commit ``91715883b30409397cc034704b41908fa2e42fb6``).

Can you try if the above also works for you, and / or if you can reduce the failing workchain to a minimal example?

**Comment by sphuber** [comment]
If I understand correctly from our debugging session over Slack it was just some rogue `verdi devel run_daemon` instances that were still running that were picking up the tasks but still had old work chain definitions loaded and could not advance them. Cleaning all daemon processes and restarting fixed the issue. I let @espenfl to confirm and close the issue if this assessment is correct.

**Comment by espenfl** [comment]
@sphuber This is correct and confirmed for this particular case as well. In fact it caused quite a bit of confusion. @greschd Thanks for the suggestion of running a minimal workchain. Fortunately the issues are now gone. Closing this now.
