### ISSUE TITLE
Incompatible version requirement for seekpath (spglib)

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3423]
Slightly related to #3184 (in that this also addresses incompatible version requirements).

The following error is now present when installing `aiida-core`:

```shell
ERROR: seekpath 1.9.3 has requirement spglib>=1.14.1, but you'll have spglib 1.12.2.post0 which is incompatible.
```

**Comment by sphuber** [comment]
Also reported per email by @borellim . I will run a dependency update script
