### ISSUE TITLE
Another unicode issue in SinglefileData

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#3437]
In `SinglefileData.get_content()`, shouldn't we instead return bytes (and fix all places where this method is used, e.g. also in `UpfData` and the tools reading it?
https://github.com/aiidateam/aiida-core/blob/dfd616ff78a574fa218bfc25eb3b7dfa80cb325c/aiida/orm/nodes/data/singlefile.py#L59-L65

Otherwise it means we are assuming this is a `SingleutfstringData`

Mentioning @sphuber

**Comment by sphuber** [comment]
Not sure. The `SinglefileData` correctly writes the file using binary mode to just copy over bytes wholesale. The `open` method will by default open in text mode, but not specify any encoding so the default encoding of the OS is used. Is this not what we want? Should we always return byte strings and leave it up to the caller to do something with it. I am not sure if this would not cause unexpected things for users calling these methods, as they are top-level node API methods after all.

**Comment by ltalirz** [comment]
I would tend to agree with @sphuber here in that `get_content` is a shorthand for opening the file with default settings and reading.
Perhaps it would make sense to document this in the help string?

**Comment by sphuber** [comment]
For the REST API, if they know they want a byte string, they can always replace `get_content` with:
```
with node.open(mode='rb') as handle:
    return handle.read()
```
I think `get_content` should be a shortcut if we want human readable content. If one knows it can be binary or they want bytes, just use the `open` method

**Comment by greschd** [comment]
I have a related question: Is there a better way to copy a ``SinglefileData`` out of the repository (via the CLI) than ``verdi node cat PK filename > new_file``? This command currently suffers from the same error, namely

```
Critical: failed to get the content of file `filename`: 'utf-8' codec can't decode byte 0xac in position 10: invalid start byte
```

**Comment by sphuber** [comment]
Not really I am afraid. Some of the sub classes such as `CifData` have a specific endpoint `verdi data cif content` but that will most likely from the same problem

**Comment by giovannipizzi** [comment]
About this last comment:
- Wouldn't it better to have the default as byte stream here for `get_object_content`? https://github.com/aiidateam/aiida-core/blob/8456116d1a210b62f7194aa45cf3d6f6787b05e4/aiida/orm/utils/repository.py#L129
- If we don't think this is the right default, still probably we should pass 'b' as the mode in https://github.com/aiidateam/aiida-core/blob/8456116d1a210b62f7194aa45cf3d6f6787b05e4/aiida/cmdline/commands/cmd_node.py#L45 and then let `click` do its job in echo, however passing `nl=False` as indicated here: https://click.palletsprojects.com/en/7.x/utils/
