### ISSUE TITLE
resetting default User cache

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3462]
Since the default user of an AiiDA profile is requested a lot, we've introduced a cache for this property:

https://github.com/aiidateam/aiida-core/blob/cc94a1e0127cd9cab0a4049e69a9fa31cb82941c/aiida/orm/users.py#L51-L70

However, short of resetting the manager, there currently doesn't seem to be a way to reset this cache, as one might want to do, for example, after setting a new default user programmatically, deleting the default user, etc.

Resetting this cache could be done at two levels:
 1. A specific command for the `User.objects` collection that resets its `_default_user` property
 2. A generic `reset()` method for `objects` - `objects` are loaded lazily and so you can add a generic method 
    ```python
        @classmethod
        def reset(cls):
            cls._COLLECTIONS = datastructures.LazyStore()
    ```
     to `aiida.orm.entities.Collection`
     This would allow to do `User.objects.reset()` (same for `XXX.objects.reset()`).

I'm leaning towards the second option - what do you guys think?

@sphuber 
@giovannipizzi

**Comment by sphuber** [comment]
The second solution you proposed, as implemented, will not only reset the collection of that particular entity and backend, but of _all_ collections that have been instantiated. This is not what we want. I would for now go for a specific reset on the default user on the User collection. Anyway, that is the only collection with real state I think.

**Comment by ltalirz** [comment]
> The second solution you proposed, as implemented, will not only reset the collection of that particular entity and backend, but of all collections that have been instantiated.

Oops -  you're right ;-)

Instead of hacking a specific solution for the user, one could probably still do something like this (seems to work)?
```python
    def reset(self):
        """
        Remove lazily constructed collection instance.

        Removes lazily constructed collection instance from internal cache (constructed again upon next request).
        Useful to clear any internal caches of the collection.
        """
        self._COLLECTIONS.pop((self.entity_type, self.backend))

```
