### ISSUE TITLE
Remove coveralls

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3508]
The last few weeks it has been behaving pretty erratically to the point where now pretty much every commit and PR get's a red cross because apparently the coverage drops, even though it clearly doesn't (it seems). Since anyway we ignore it, is it perhaps better to just drop it?

@giovannipizzi and @ltalirz for discussion

**Comment by giovannipizzi** [comment]
I've just set on the web interface of coveralls the threshold to 70% and the relative threshold to 3%. Let's see for the next PRs (we can just force push somewhere to see if anything changes).
Still, I agree that I'm not sure why it says every time that the coverage changed so much. Do we have any 'random' code that changes path based on some real-time conditions?

**Comment by sphuber** [comment]
I pushed PR #3504 and it indeed passes now, despite it reporting a 2% decrease. Still not sure if this is trustworthy and therefore makes sense to keep

**Comment by ltalirz** [comment]
[According to coveralls](https://coveralls.io/github/aiidateam/aiida-core), there are 98k relevant lines of code, i.e. a 2% change in coverage corresponds to adding tests for ~2k lines of *existing* code.
I think I'm still waiting for such a PR :-)

Of course, I share the frustration about having notifications in the PRs that can be very inaccurate - but I still feel that the coverage information can be rather valuable (e.g. to inform issues like https://github.com/aiidateam/aiida-core/issues/2835 ).

So, until we figure out how to fix this, raising the threshold to 3% could be a reasonable solution.

By the way, I also briefly looked back into codecov, who [might be doing a better job in merging reports](https://docs.codecov.io/docs/merging-reports) but it seems the issue that caused us to switch is still not resolved: https://github.com/codecov/codecov-python/issues/125

**Comment by sphuber** [comment]
OK, I will close it then for now
