### ISSUE TITLE
Possibly unused QueryBuilder code

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3518]
Poking around in the front-end QueryBuilder code, it seems a function is never used.
I found this since it also calls the now obsolete attribute `self._imp` in it.

The function is `except_if_input_to` and can be found [here](https://github.com/aiidateam/aiida-core/blob/develop/aiida/orm/querybuilder.py#L1924).
A search through the whole repository for the function name only reveals a single hit - the definition of it.

@lekah is this function a leftover from a previous rewrite of the class, or the beginning of an addition to the QueryBuilder? And are there more of these dead-code-methods around that either need a purpose in a grander scheme or should simply be sent to oblivion?

**Comment by lekah** [comment]
Is this function a leftover from a previous rewrite of the class, or the beginning of an addition to the QueryBuilder? This function was part of some utility, in this specific case it would remove all results that fit the criterion of being used as an input to some Calc class. I think it could still be quickly fixed to do this. But I would suggest to remove it, to avoid there being more functionality than maintenance. Also, it seems that there was no test for this which is my fault.

Are there more of these dead-code-methods around that either need a purpose in a grander scheme or should simply be sent to oblivion? ¯\_(ツ)_/¯

**Comment by ltalirz** [comment]
> Are there more of these dead-code-methods around that either need a purpose in a grander scheme or should simply be sent to oblivion?

There definitely are - I just stumbled upon another one in #3522 

The QueryBuilder is one of the [worst offenders in terms of uncovered lines](https://github.com/aiidateam/aiida-core/issues/2835) 
Here they are: https://coveralls.io/builds/26743225/source?filename=aiida/orm/querybuilder.py

**Comment by CasperWA** [comment]
> > Are there more of these dead-code-methods around that either need a purpose in a grander scheme or should simply be sent to oblivion?
> 
> There definitely are - I just stumbled upon another one in #3522
> 
> The QueryBuilder is one of the [worst offenders in terms of uncovered lines in a file](https://github.com/aiidateam/aiida-core/issues/2835) (it is also a rather long file..).

I guess most of these dead functions/methods have been lost in translation, i.e., left unused when updating the QueryBuilder to the new ORM (or similar).
The question is: Will it be worth it to update the dead function/methods to work again (and use them where applicable) or is it easier to simply cut it all off and later re-build it if the specific function or method is ever needed in the future?

**Comment by CasperWA** [comment]
> This function was part of some utility, in this specific case it would remove all results that fit the criterion of being used as an input to some Calc class. I think it could still be quickly fixed to do this. But I would suggest to remove it, to avoid there being more functionality than maintenance. Also, it seems that there was no test for this which is my fault.

Thanks for the quick and detailed reply! I will make a PR, where I will remove it and possibly keep it open for anyone else who wants to remove more from the QB that has no purpose anymore in the code base :sweat_smile:
