### ISSUE TITLE
The not operator ("!" prefix) for QueryBuilder

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3519]
For which operators do the not operator (`!` prefix) work?

It does not seem to work for `has_key`:
With a db of 4000+ `StructureData` entries, a little less than half of them have a specific extras key, while the rest do not.
Writing `QueryBuilder().append(StructureData, filter={"extras": {"has_key": "specific_key"}}).count()` correctly returns an integer little less than 2000, as expected.
However, writing `QueryBuilder().append(StructureData, filter={"extras": {"!has_key": "specific_key"}}).count()` incorrectly returns `0`, whereas I would have expected 4000+ minus little less than 2000.

If the queries I want to perform are as simple as the above, the solution is clear - simply count all and subtract the result from the first, correct, query.
However, if I want to also query for sub-keys within extras (or attributes) and make conditions within this frame, there isn't a simple solution to this anymore (although there are hoops one can jump through).

I would expect `has_key` to be a valid operator for the use of the not operator, i.e., `!has_key` should be valid - I believe this should be either fixed or implemented.

Finally, it seems to me that the not operator is also the least well-defined concept in the QueryBuilder documentation, which should be remedied.

Tagging @lekah here for some hopefully useful insight :)

**Comment by lekah** [comment]
The not operator, given by !, should work for all operators. In the original implementation, ! just triggered a not statement in sql, and nothing else, there was no operator-specific logic. 
I did a quick check in the develop branch (of a couple of days ago).
The query 
`QueryBuilder().append(StructureData, project='id', filters={'extras':{'!has_key':'foo'}})`
results in the SQL statement 
`SELECT db_dbnode_1.id FROM db_dbnode AS db_dbnode_1 
WHERE CAST(db_dbnode_1.node_type AS VARCHAR) LIKE 'data.structure.%%' AND NOT CAST((db_dbnode_1.extras #> '{}') AS JSONB) ? 'foo'` 
which is correct!
I also created a little example where I set the extras of some structures, and it works as it should. Can you reproduce this error in a unit test?

**Comment by CasperWA** [comment]
> which is correct!
> I also created a little example where I set the extras of some structures, and it works as it should. Can you reproduce this error in a unit test?

So you're receiving a list of `StructureData` `id`s, where they do _not_ have the extra `foo`?
Or are you receiving an empty list?

**Comment by CasperWA** [comment]
What doesn't work is the following:

```python
QueryBuilder().append(StructureData, project='id', filters={'extras.foo': {'!has_key': {'bar'}})
```

This returns a count of 0, even though the following produces correct results:

```python
QueryBuilder().append(StructureData, project='id', filters={'extras': {'!has_key': {'foo'}})
```

Count is <total> - <`StructureData` with key `foo`>.

Furthermore, the following does not work:

```python
QueryBuilder().append(StructureData, project='id', filters={'extras': {'!has_key': {'foo.bar'}})
```

Even though some `StructureData` do indeed have the nested key `bar` under the extras key `foo`, this will return a count equal to the total number of `StructureData` in the DB.

**Comment by CasperWA** [comment]
It should be noted that the top query works fine and finds the `StructureData` with nested keys `bar` in the extras `foo` when the not-operator is left out.

The latter one doesn't work for `has_key`, i.e., without the not-operator either, which I guess can be tolerated, but I would've expect it to work.

**Comment by CasperWA** [comment]
Hmm... maybe I'm too fast concerning the first query. Maybe it _is_ working. It just simply going through the `StructureData` _with_ the extras key `foo` and checking how many do _not_ have the `bar` key, which would be 0 in my particular case - is that true?

**Comment by CasperWA** [comment]
With this little check and verification, I believe this issue can be closed. Thanks for the response above @lekah :)
