### ISSUE TITLE
dump computer/codes in YAML format

### ISSUE THREAD

**Issue by adegomme** [aiidateam/aiida-core#3521]
Sometimes when using another environment, or setting up a new aiida for a new user, we have to setup the same computers/codes over and over again. For this, loading from YAML is quite practical. 

But I can't find a way to generate these YAML files from an existing installation directly. 
"verdi computer show" output is quite close to yaml and can be converted rather simply, but a "dump" command, or a --yaml switch for show would be useful (maybe I missed something and it's already possible, apologies in this case).

**Comment by ltalirz** [comment]
very good point - it does not exist and would be very useful (and easy to implement)

**Comment by adegomme** [comment]
This would actually make it possible to provide a library of ready-to-use configurations for known HPC systems and codes, this could be interesting.

**Comment by ltalirz** [comment]
> This would actually make it possible to provide a library of ready-to-use configurations for known HPC systems and codes

This is already possible: simply set up the computers and codes and create an AiiDA export file.
This has the added advantage that computers / codes will be uniquely identified when used by multiple people.

**Comment by sphuber** [comment]
This was addressed in #6389 and #5860
