### ISSUE TITLE
verdi import chokes on `_return` link label

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3527]
Both @danieleongari and me independently have AiiDA databases, potentially migrated along from 0.12 that contain links labeled `_return`:

```
# select * from db_dblink WHERE label LIKE '\_%';
 id  |  label  | input_id | output_id |  type
-----+---------+----------+-----------+--------
  21 | _return |       63 |        64 | return
  33 | _return |      107 |       108 | return
  35 | _return |      245 |       246 | return
 227 | _return |      272 |       273 | return
 235 | _return |      112 |       113 | return
 271 | _return |      114 |       115 | return
 307 | _return |      270 |       271 | return
 337 | _return |       66 |        67 | return
 362 | _return |      240 |       119 | return
 438 | _return |      158 |       159 | return
 478 | _return |      190 |       191 | return
 512 | _return |       60 |        61 | return
 593 | _return |      222 |       223 | return
```

These end up in the AiiDA export file; and when one then tries to import the export file you get:

```
...
NEW Group: 063bf003-ed66-4a94-927a-f31129ba1824 (333->309)
NEW Group: 35db6bab-b93c-4bce-b44d-7989b86d27de (334->310)
STORING NODE LINKS...
Error: an exception occurred while importing the archive export_v1.aiida
Traceback (most recent call last):
  File "/home/daniele/aiida1/aiida_core/aiida/tools/importexport/dbimport/backends/django/__init__.py", line 553, in import_data_dj
    validate_link_label(link['label'])
  File "/home/daniele/aiida1/aiida_core/aiida/common/links.py", line 108, in validate_link_label
    raise ValueError('cannot start with an underscore')
ValueError: cannot start with an underscore
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/daniele/aiida1/aiida_core/aiida/cmdline/commands/cmd_import.py", line 67, in _try_import
    import_data(file_to_import, group, **kwargs)
  File "/home/daniele/aiida1/aiida_core/aiida/tools/importexport/dbimport/__init__.py", line 76, in import_data
    return import_data_dj(in_path, group=group, silent=silent, **kwargs)
  File "/home/daniele/aiida1/aiida_core/aiida/tools/importexport/dbimport/backends/django/__init__.py", line 555, in import_data_dj
    raise exceptions.ImportValidationError('Error during Link label validation: {}'.format(why))
aiida.tools.importexport.common.exceptions.ImportValidationError: Error during Link label validation: cannot start with an underscore
do you want to continue? [y/N]:
```

We checked that the link label in the error message is `_return`.

Is this a bug in the migrations?

Please advise on how to proceed as we need to produce working export files.
@giovannipizzi @sphuber

**Comment by ltalirz** [comment]
In my case, the `_return` links come out of what is now a `WorkChainNode` (was a `@workfunction` in 0.12, see [explore link](https://www.materialscloud.org/explore/curated-cofs/details/4f28e253-0b20-43ad-b673-3363f85fa310?nodeType=NODE)):
```
$ verdi node show 107
Property     Value
-----------  ------------------------------------
type         merge_ParameterData
pk           107
uuid         4f28e253-0b20-43ad-b673-3363f85fa310
label
description
ctime        2019-02-15 20:02:51.358780+00:00
mtime        2019-11-07 16:24:24.778870+00:00

Called by      PK  Type
-----------  ----  -------------
CALL          117  WorkChainNode

Inputs      PK  Type
--------  ----  ------
p1         106  Dict
p2         119  Dict

Outputs      PK  Type
---------  ----  ------
_return     108  Dict
```

**Comment by sphuber** [comment]
> In my case, the `_return` links come out of what is now a `WorkChainNode`:

this should now be a `WorkFunctionNode`, not a `WorkChainNode`.
That aside, I looked at the migrations and I don't think that there are migrations for this change. The default link label for processes (such as `workfunctions`) that only returned a single node used to be `_return`. This was changed to `result` but no migration was put in place. This will have to be done. For the time being you can either already run a quick migration manually on your database
```
UPDATE db_dblink SET label='result' WHERE label = '_return';
```
or do it in the `data.json` generated by the export.

**Comment by ltalirz** [comment]
> actually this should now be a WorkFunctionNode, not a WorkChainNode.

Ah right - I just saw `WorkChainNode` but that's the one calling the function.
I find it a little confusing that the actual node type is shown nowhere in the output above

> The default link label for processes (such as workfunctions) that only returned a single node used to be _return. This was changed to result but no migration was put in place.

I see - thanks for checking!

And thanks for the quick fix as well!

**Comment by sphuber** [comment]
> Naively, I would expect to see `type WorkFunctionNode` instead of `type merge_ParameterData`

I see. The reason we chose this form though, is that often the base node type says very little. If you have lots of various calculations jobs for example, seeing `CalcJobNode` doesn't tell you what you want to see most often. Seeing `PwCalculation` or `VaspCalculation` however is. So "type" is now the interpreted combination of the `node_type` plus `process_type`. If you think these should be displayed separately as well, we can add that

**Comment by ltalirz** [comment]
> If you think these should be displayed separately as well, we can add that

Probably better, also because `type` is used in the same output with a different meaning:
```
Called by      PK  Type
-----------  ----  -------------
CALL          117  WorkChainNode
```

**Comment by zhubonan** [comment]
I also got stuck with this - I was trying to import a v3 archive from 0.12.1. 
Manual changing the label in `data.json` works. However, the link is deleted during the import as it violates database integrity. Looks like there is no option to turn off the enforcement?

**Comment by giovannipizzi** [comment]
This is something we might want to fix in the coding week? mentioning also @sphuber @CasperWA @ramirezfranciscof @csadorf

**Comment by sphuber** [comment]
This will be an easy fix. Just have to add the database migration (which should be trivial) and the corresponding export archive migration which likewise should not be complicated.
