### ISSUE TITLE
Kinds are not preserved when using structure.get_ase()

### ISSUE THREAD

**Issue by bonfus** [aiidateam/aiida-core#3529]
I wanted to repeat a simulation after having shifted all atoms by a given vector (don't ask why :-) ).

In doing so I first tried to do this operation with ASE and I discovered that kind names are not preserved, while the correct behaviour is obtained with pymatgen. Here's how to reproduce the problem, given a calculation that have kind names different from elements name.

        # ASE VERSIION
        # not working, not preserving kinds
        atms = restart_builder.structure.get_ase()
        atms = atms.translate(-atms[-1].position)
        StructureData     = DataFactory("structure")
        restart_builder.structure = StructureData(ase=atms)

        # PYMATGEN
        atms = restart_builder.structure.get_pymatgen_structure()
        atms.translate_sites(range(atms.num_sites),-atms[-1].coords, frac_coords=False)
        StructureData     = DataFactory("structure")
        restart_builder.structure = StructureData(pymatgen=atms)

I  tested this with aiida-quantumespresso but it looked like a problem of the Structure class so I posted the issue here. I'm using AiiDA version 1.0.0b6.

**Comment by sphuber** [comment]
Thanks for the report. Unfortunately I am not able to reproduce this. I tried the following snippet which passes the asserts:
```
from aiida import orm

structure = orm.StructureData(cell=[[1, 0, 0], [0, 1, 0], [0, 0, 1]])
structure.append_atom(position=(0., 0., 0.), symbols='Si', name='Si1')
structure.append_atom(position=(0.5, 0.5, 0.5), symbols='Si', name='Si2')

atoms = structure.get_ase()
atoms.translate(-atoms[-1].position)
roundtrip_ase = orm.StructureData(ase=atoms)
assert [kind.name for kind in roundtrip_ase.kinds] == [kind.name for kind in structure.kinds]

atoms = structure.get_pymatgen()
atoms.translate_sites(range(atoms.num_sites), -atoms[-1].coords, frac_coords=False)
roundtrip_pymatgen = orm.StructureData(pymatgen=atoms)
assert [kind.name for kind in roundtrip_pymatgen.kinds] == [kind.name for kind in structure.kinds]
```

Your code snippet contains a mistake. The command `atms.translate` does the transformation inline and returns `None`. So when you assign that to `atms` in your snippet, `atms` will be `None` when you construct a new `StructureData`. It will then contain no sites whatsoever. Is that maybe the problem you encountered?

**Comment by bonfus** [comment]
That was it, I was misled by the error reported when submitting the calculation.
Sorry for the noise and thanks!
