### ISSUE TITLE
Database integrity issue

### ISSUE THREAD

**Issue by pzarabadip** [aiidateam/aiida-core#3539]
Recently, I had an issue resulted from power shortage and after restarting the `rabbitmq-server` and `postgres`, out of curiosity I checked the integrity of my database using `verdi database integrity detect-invalid-links` where I got a huge log which looks like:
```
Warning: detected calculation nodes with outgoing `call` links:
    ID  Input node                            Output node                           Type       Label
------  ------------------------------------  ------------------------------------  ---------  -------
    43  3eae25c2-8212-4192-aeed-7508831ba771  f79320bd-7c16-484e-b433-6ec0a6e62129  call_work  CALL
   152  5eaff866-0543-4967-b2c0-c3c2f1590bf7  1b6c7a90-1161-4de4-b9f5-a11fdab774dd  call_work  CALL
   486  7ce0002d-ed44-4bcb-bf4a-a1d5bda52c97  fcaacf07-21bd-4995-8bd2-7ce8ace7466e  call_work  CALL
   590  df0ce225-343a-4713-b521-c13794871043  fb1d1487-e784-4cb3-bc61-bc5c0694638e  call_work  CALL
  1384  ae00c8b1-5488-4986-8662-5f9eee7e902d  370c6661-6fdd-4825-84fa-cce34e3f8d00  call_work  CALL
.
.
.
Critical: one or more integrity violations detected
```
We (@yakutovicha and I) checked few things and so far realized that in the aforementioned log,  `Input node` is a parent workchain and `Output node` is the called `BaseWorkChain` within the parent. For instance, `Cp2kMultiStageWorkChain` and `Cp2kBaseWorkChain`. The same behavior is observed for our other workchains where the highest level work chain calls the `BaseRestartWorkChain`. 
We also have tested direct submission of `BaseRestartWorkChain` to the daemon and we have not observed similar integrity violation report. 
At this point, I am not sure if:
1. It is an issue with the workchain design combined with a bug in `aiida-core` which cannot catch it at the spot. 
2. It is a bug in `aiida-core` that wrongly flags these links as the violation of database integrity. 

Therefore, I thought to open an issue for further discussion.

**Comment by sphuber** [comment]
If they really are work chains, as you say, then it should simply be a false positive by the integrity checker, because call links from `WorkflowNode` to `WorkflowNode` are perfectly legal. Could you load the input and output nodes of a few of these violations and print their `node_type` and `process_type` and report them here? So something like:
```
for uuid_in, uuid_out in [('3eae25c2', 'f79320bd), ...]:
    node_in = load_node(uuid_in)
    node_out = load_node(uuid_out)
    print(node_in.node_type, node_in.process_type, node_out.node_type, node_out.process_type)
```

**Comment by pzarabadip** [comment]
Thanks @sphuber . 
Here are few examples from my different AiiDA databases: 
```
process.workflow.workchain.WorkChainNode. aiida_cp2k.workchains.multistage.Cp2kMultistageWorkChain process.workflow.workchain.WorkChainNode. aiida_cp2k.workchains.base.Cp2kBaseWorkChain
process.workflow.workchain.WorkChainNode. aiida_ddec.workchains.cp2k_ddec.Cp2kDdecWorkChain process.workflow.workfunction.WorkFunctionNode. aiida_ddec.workchains.utils.merge_Dict
process.workflow.workchain.WorkChainNode. aiida_ddec.workchains.cp2k_ddec.Cp2kDdecWorkChain process.workflow.workchain.WorkChainNode. aiida_cp2k.workchains.base.Cp2kBaseWorkChain
process.workflow.workchain.WorkChainNode. aiida_ddec.workchains.cp2k_ddec.Cp2kDdecWorkChain process.workflow.workchain.WorkChainNode. aiida_cp2k.workchains.base.Cp2kBaseWorkChain
process.workflow.workchain.WorkChainNode. aiida_ddec.workchains.cp2k_ddec.Cp2kDdecWorkChain process.workflow.workfunction.WorkFunctionNode. aiida_ddec.workchains.utils.extract_core_electrons
process.workflow.workchain.WorkChainNode. aiida_lsmo.workchains.smart_hts.SmartHTSWorkChain process.workflow.workchain.WorkChainNode. aiida_raspa.workchains.base.RaspaBaseWorkChain
process.workflow.workchain.WorkChainNode. aiida_lsmo.workchains.smart_hts.SmartHTSWorkChain process.workflow.workchain.WorkChainNode. aiida_raspa.workchains.base.RaspaBaseWorkChain
```
I hope it helps.

**Comment by sphuber** [comment]
Thanks @pzarabadip . Those all look fine, so I think these are just false positives. I will see if I can reproduce the behavior.

**Comment by sphuber** [comment]
I have confirmed the false positives and created a PR with a fix. Thanks for the report
