### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3562]

**Comment by greschd** [comment]
Relevant link: https://packaging.python.org/guides/dropping-older-python-versions/

**Comment by sphuber** [comment]
I think we can even be a bit more specific and set `>=3.5` since `3.4` is [EOL since March 2019](https://devguide.python.org/devcycle/)

**Comment by greschd** [comment]
Yeah, whichever version we decide to support, of course.
