### ISSUE TITLE
QueryBuilder and multiple append() runs

### ISSUE THREAD

**Issue by mkotiuga** [aiidateam/aiida-core#3565]
Using AiiDA version 1.0.0b6. When I run multiple append lines, I either an unexpected output. For example, when running the same line twice, I get either no output or a number that is not twice the entries of just running it once. If i keep running the same append line I eventually get no entries. (The first returned value of qb.count() is correct, as far as I know)
_________________________________________________________
Example 1:
 In [2]: qb = QueryBuilder()
   ...: qb.append(Node, project=['id'], filters={'label': {'==': 'HFO test'}})
   ...: qb.count()
Out[2]: 9

In [3]: qb = QueryBuilder()
   ...: qb.append(Node, project=['id'], filters={'label': {'==': 'HFO test'}})
   ...: qb.append(Node, project=['id'], filters={'label': {'==': 'HFO test'}})
   ...: qb.count()
Out[3]: 0
___________________________________________________________
Example 2: 

In [6]: qb = QueryBuilder()
   ...: qb.append(
   ...:     Node, project=['id'],
   ...:     filters={'ctime': {'<': datetime.now() - timedelta(days=90)}})
   ...: qb.count()
   ...: 
   ...: 
Out[6]: 1980

In [7]: qb.append(
   ...:     Node, project=['id'],
   ...:     filters={'ctime': {'<': datetime.now() - timedelta(days=90)}})
   ...: qb.count()
   ...: 
Out[7]: 2387

In [8]: qb.append(
   ...:     Node, project=['id'],
   ...:     filters={'ctime': {'<': datetime.now() - timedelta(days=90)}})
   ...: qb.count()
   ...: 
Out[8]: 8164

In [9]: qb.append(
   ...:     Node, project=['id'],
   ...:     filters={'ctime': {'<': datetime.now() - timedelta(days=90)}})
   ...: qb.count()
   ...: 
Out[9]: 0

In [10]: qb.append(
    ...:     Node, project=['id'],
    ...:     filters={'ctime': {'<': datetime.now() - timedelta(days=90)}})
    ...: qb.count()
    ...: 
Out[10]: 0

In [11]: qb.append(
    ...:     Node, project=['id'],
    ...:     filters={'ctime': {'<': datetime.now() - timedelta(days=90)}})
    ...: qb.count()
    ...: 
Out[11]: 0

**Comment by sphuber** [comment]
This is the expected the behavior. If you call `append` you are _implicitly_ saying that there is a connection between that node and the one specified in the previous append. So when you say:
```
qb.append(Node, project=['id'], filters={'label': {'==': 'HFO test'}})
qb.append(Node, project=['id'], filters={'label': {'==': 'HFO test'}})
```
you are saying: get me all nodes with the label `HFO test` that are directly linked to another node that _also_ has a label `HFO test`. It _doesn't_ mean give me twice the nodes that have a label `HFO test`. Or maybe I have misunderstood your examples

**Comment by mkotiuga** [comment]
No, I think you understood my example correctly. I think I am a little fuzzy on append(). 

So running one append command queries the database. If you want to run another query (that does not depend on links to the first query), one should either use some logic in "filters" of the first append command or create another instance of query builder?

If a second append command is used, it queries links to the nodes that were the result of the first query? even if "with_incoming"  is not used?
