### ISSUE TITLE
Input / output validation for calcfunctions and workfunctions

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#3569]
Since we're dropping py2 support in #3566, we can make use of glorious new features.

One possibility would be to add (optional) input / output validation for calcfunctions and workfunctions through _type hints_.

Example:

```python
from aiida import orm
from aiida.engine import calcfunction

@calcfunction
def add(x: orm.Float, y: orm.Float) -> orm.Float:
    return x + y
```

Should be quite straightforward to implement. Opinions on whether this would be desirable?

**Comment by chrisjsewell** [comment]
+1 from me

to elaborate on the implementation (copied from #3724):

From python 3.6 onward I believe, type annotations are stored in `__annotations__`, e.g.

```python
@calcfunction
def my_calcfunction(structure: StructureData):
    pass

my_calcfunction.__annotations__ == {"structure": StructureData}
```

This could be used here, to set a more specific `valid_type` than just `orm.Data`:

https://github.com/aiidateam/aiida-core/blob/5790d0db5d080fb755ae408d7cdbb4cf6ba55ef4/aiida/engine/processes/functions.py#L261

**Comment by greschd** [comment]
Just checked on 3.5, works there as well.

**Comment by chrisjsewell** [comment]
If you wanted to get really fancy, you could also use [`TypedDict`s](https://docs.python.org/3/library/typing.html#typing.TypedDict), to set output validation on multiple outputs, but that's only available from python 3.8

**Comment by greschd** [comment]
I guess the user can always specify that as return value, and we just need to make sure it works out with the ``isinstance`` check, right? If some user code only supports 3.8+, that shouldn't bother us.

**Comment by ltalirz** [comment]
Just mentioning that we will drop python 3.5 support with the next release , following the [compatibility timeline](http://www.aiida.net/download/)
