### ISSUE TITLE
Possibility to bundle Groups

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#3589]
Having the possibility to bundle Groups would be convenient.

**Comment by sphuber** [comment]
Can you expand a bit more on what you mean exactly @espenfl ? Do you want to be able to put `Group` instances in a `Group`? Or something else?

**Comment by espenfl** [comment]
@sphuber Yes, something like that, `Group` in `Group`. Would make it easier to bundle up different domains regardless of purpose (e.g. export or for instance easy tag'ing when visualizing).

**Comment by sphuber** [comment]
To have this really implemented on the database level will require a significant change in schema and migrations. However, @chrisjsewell has been working on a different approach, that should achieve more or less the same effect, that works on the "software" level. There is an open PR #3613 that should be merged soon. This allows you to use nesting in the group names themselves to create virtual hierarchies. For example, imagine you have two groups called `structures/orthorhombic` and `structures/cubic` that each contain some `StructureData` nodes, you could do the following:
```
group = GroupPath(`structures`)
group.nodes  # will get all nodes in both `structures/orthorhombic` and `structures/cubic` 
group_orthorhombic = group['orthorombic'].group  # will be Group('structures/orthorhombic')
structures_orthorhombic = group_orthorhombic.nodes
```
The actual syntax may differ a bit. Would this be acceptable for your use case?

**Comment by espenfl** [comment]
Well, I think, given the complexity such a change would yield it might not be worth it as this point as long as we can for with points on the software level. How is this on export and then import?

**Comment by sphuber** [comment]
Not sure what you mean with the last question. But the feature added by #3613 would not affect it, since nothing at all changes on the _actual_ data in the database. It is just a tool that operates on top of the data to provide a virtual hierarchy. What I am interested in, is whether this was the functionality that you were looking for when you opened that issue. Because if the case, we can close this once the PR is merged.

**Comment by espenfl** [comment]
What we ultimately would be interested in is that if you export a `Group` of `Group`, either virtual or actual, that the important can also utilize the grouping. Say reuse the data, or enrich it. But I guess this will not be realized with #3613.

**Comment by greschd** [comment]
#3613 is just a convention for how to name groups, and some tooling around it.

So, if you have groups `myproject/structures` and `myproject/bands` they would be accessible through the ``myproject`` `GroupPath`. 

I think this should not be affected by exporting / importing the groups, as long as all the relevant groups are included in the export.

**Comment by sphuber** [comment]
As long as the importer also has the version of AiiDA that provides this new functionality, the same group hierarchy will apply and can be used. So I think that this will in fact be solved by the PR.

**Comment by espenfl** [comment]
@sphuber If that is indeed the case, then we need no more. It is a feature needed to increase user friendliness / mental order in the chaos and then we do not care that much what happens in the backend. So agreed, please close it upon merging the PR.
