### ISSUE TITLE
Consider separate hashing type specifiers for str / bytes

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#3595]
So far, ``str`` and ``bytes`` were given the same "type prefix" when hashing. The reason for that was py2 compatibility, because it could be unreliable which of the two types are obtained avross versions. 

Since this is no longer a concern, ``bytes`` could be given a separate prefix. The benefit of this would be that these (different) types no longer produce hash collisions for the "same" content.

Note that this invalidates current hashes.

See comment in #3562.

**Comment by sphuber** [comment]
I think the chances for collissions are marginal and the downside of invalidating all hashes (again) would be non-negligible. So I am closing this as a wont-fix.
