### ISSUE TITLE
Reinstate `coverage` to CI when testing is migrated to `pytest`

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3602]
@sphuber Is it correctly understood that coverage/codecov has disappeared in the process of moving to GitHub Actions?

**Comment by sphuber** [comment]
Yes as mentioned in PR #3571 I omitted it on purpose. It was often buggy so we did not actually pay any attention to what it was saying. We put a big threshold on it just to prevent it from giving false positives. In addition, it was not even correctly registering all paths we were running. The move to `pytest` will allow us to run `pytest-cov` which should fix it. Maybe we look into it then again

**Comment by CasperWA** [comment]
Cool. I'll just put in a link to [codecov-action](https://github.com/codecov/codecov-action) here for the future implementation of this.

**Comment by ltalirz** [comment]
we might actually want to give it a try even before - if the information is usable, then it could be very helpful for improving test coverage for the "data/tools" commands during the coding week.

**Comment by CasperWA** [comment]
From short discussion at the coding week 2019 between @dev-zero, @giovannipizzi, and me:

- Move to codecov.
- Create GH Actions job to run on pushes to `master` and `develop` branches (on `aiidateam/aiida-core`) and for all PRs.
- Make sure to properly exclude test files and folders, and consider which other files/folders should be excluded.
