### ISSUE TITLE
BackendNode has `process_type` property

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3641]
While looking through the code with @muhrin, we discovered that the abstract `BackendNode` implementation  has a `process_type` property.
https://github.com/aiidateam/aiida-core/blob/0e17ac1d35d3e90b7277fbfe2fa0edabc9732b53/aiida/orm/implementation/nodes.py#L52
That doesn't seem to make any sense.

Mentioning @sphuber for comment

**Comment by sphuber** [comment]
Why not? The `process_type` is currently a separate column on the `Node` schema class so each db model instance has it.

**Comment by ltalirz** [comment]
Of course the thought was that the process type doesn't really make sense for Data nodes.
Anyhow, if it's in the database, I guess one can just as well expose it here.
