### ISSUE TITLE
Python 3.8 compatibility issues

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida-core#3662]
* [x] IPython 5.8.0, see #3559 
* [x] pylint 2.3.1, https://github.com/PyCQA/pylint/issues/2976 , seeing this on `functools` import

**Comment by sphuber** [comment]
`ipython` problem has been solved because we could update the requirement after `circus` could be updated: https://github.com/aiidateam/aiida-core/commit/982b089f6bd6b0258af70cee365db19fbae56ec1
