### ISSUE TITLE
Various deprecation warnings

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3672]
* `aiida.restapi.translator.nodes.node.NodeTranslator._get_subclasses` uses the deprecated `imp` module.
* `aiida.orm.nodes.data.structure.ase_refine_cell` passes ASE object to `spglib.refine_cell` which is deprecated.
* `aiida/backends/tests/test_dataclasses.py::TestKpointsData::test_path_wrapper_legacy` gets warning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by ltalirz** [comment]
As for the warning
```
 /opt/hostedtoolcache/Python/3.8.2/x64/lib/python3.8/site-packages/spglib/spglib.py:895: DeprecationWarning: ASE Atoms-like input is deprecated.
    warnings.warn("ASE Atoms-like input is deprecated.",
```
See 
https://atztogo.github.io/spglib/python-spglib.html#ase-atoms-like-input-is-deprecated

**Comment by CasperWA** [comment]
There was another deprecation warning in the REST API module `aiida.restapi.common.identifiers`:

```sh
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
```

This will be fixed in #3974.

**Comment by DirectriX01** [comment]
I'm not sure on how to work on the  `aiida.orm.nodes.data.structure.ase_refine_cell` warning, the ASE structure is used by various functions, such as https://github.com/aiidateam/aiida-core/blob/dc9ec6f91e0b23608c58ece6e3283a13780dcf47/aiida/orm/nodes/data/cif.py#L49

**Comment by ltalirz** [comment]
thanks @DirectriX01  

> I'm not sure on how to work on the aiida.orm.nodes.data.structure.ase_refine_cell warning

Haven't looked into it in detail, but I guess you'll need to extract the "tuple input data" 
described in https://atztogo.github.io/spglib/python-spglib.html#ase-atoms-like-input-is-deprecated

here 
https://github.com/aiidateam/aiida-core/blob/4b7febe8264da5c49ec0125c31f7ca8dd0713b2c/aiida/orm/nodes/data/structure.py#L636

**Comment by unkcpz** [comment]
To show the deprecated message, just run the correspondence test cases. After having aiida environment set, run:

```
$ pytest -v tests/test_dataclasses.py::TestCifData::test_get_structure
$ pytest -v tests/test_dataclasses.py::TestKpointsData::test_path_wrapper_legacy
$ pytest -v pytest tests/restapi/test_translator.py
```

There are more deprecated message outputs than you can find as described in this issue.
Better to fix them all.

**Comment by sphuber** [comment]
This is very outdated. Some reported have since been addressed, many others have been added. No point in keeping this around
