### ISSUE TITLE
Caching and the configuration of caching is broken

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3673]
The problem went undetected because the caching configuration and the methods that change it replaced the type from node classes to entry points. For example the `enable_caching` method deprecated that `node_class` argument in favor of `identifier` however, when `node_class` was passed it was effectively ignored. When properly used the `engine/test_calcfunctions` unit tests will fail.

**Comment by ltalirz** [comment]
Notifying @greschd about this

**Comment by greschd** [comment]
Wait, wasn't this fixed in https://github.com/aiidateam/aiida-core/pull/3327? Or is that a slightly different issue?

**Comment by ltalirz** [comment]
I'll leave this to you two to figure out ;-)

**Comment by sphuber** [comment]
No it has to with the fact that the old `enable_caching` and other related interfaces used `node_class` as argument to specify what types to target, which has been deprecated in favor of the more generic `identifier`. However, the implementation no longer properly considers `node_class` and unit tests did not catch this since they pass by keyword instead of positional argument. I can fix this when I come back in a week

**Comment by ltalirz** [comment]
We would really like to start taking advantage of caching at the LSMO, so it would be really valuable to have that fix in aiida-core 1.1 (and to understand why it was possible to break caching without failing tests)

**Comment by greschd** [comment]
If you can enable caching globally, that definitely still works.

As for why this was broken, I guess we didn't have a test that re-loaded the config file - although I guess we should.

**Comment by greschd** [comment]
The title is a bit misleading, it's more like "class-specific caching config broken".

**Comment by greschd** [comment]
Wrap-up of the discussion with @sphuber: We settled on supporting identifiers which are exactly the `process_type` attribute. For processes with an entry point this is the entrypoint string, and for others it is the `module_name:object_name`.

We also support globbing, e.g. `aiida.calculations:aiida_quantumespresso.*` would affect all entry points which start with `aiida.calculations:aiida_quantumespresso`.
