### ISSUE TITLE
Make importing into a `Group` completely optional

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3680]
Currently both the API `import_data` as well as the CLI `verdi import` do not provide an option to not have the imported nodes put into a group at all. I would like this to be completely optional.

**Comment by CasperWA** [comment]
I don't see a reason why not, but just to give you an opportunity to justify yourself: Why? :) Making a group does not take up a lot of memory, and it will not show up on a normal `verdi group list` or similar, since it's not a user-made Group.

**Comment by sphuber** [comment]
Because there are currently other group types in use, especially `data.upf` for UPF family. In order to show them, I have to use the `-a` flag (which I already find annoying but that is another question) which will now also show all the `auto.*` type groups. I don't care about these and they clutter my view

**Comment by CasperWA** [comment]
So it's a matter of the interface for how to show/hide Groups using `verdi` and not about automatically creating import Groups?

**Comment by sphuber** [comment]
No I just don't want those automatically created groups to exist at all.

**Comment by CasperWA** [comment]
So this issue should really be called something like: "Remove all _automatic_ opague Group generation"

**Comment by sphuber** [comment]
> So this issue should really be called something like: "Remove all _automatic_ opague Group generation"

Not necessarily because there is also automatic group generation when calling `verdi run`, which I also am not a fan off, but that is explicitly not the target of this issue

**Comment by CasperWA** [comment]
> > So this issue should really be called something like: "Remove all _automatic_ opague Group generation"
> 
> Not necessarily because there is also automatic group generation when calling `verdi run`, which I also am not a fan off, but that is explicitly not the target of this issue

Sure. My point was simply that your reason for submitting this issue/feature request, is to systematically get rid of automatically generated Groups in AiiDA, although be it one type of automatically generated Group at a time ;)

**Comment by sphuber** [comment]
I am fine with their being automatically generated groups, however, there should at the very least be an opt-out. In the current interface of `verdi import` and `import_data` as explained in the OP there is no way to _not_ use a group, which I think is too restrictive

**Comment by CasperWA** [comment]
In the end, making it optional is surely a good idea from a transparency and usability point-of-view. We should just make sure nothing is reliant on these Groups being produced.

> I am fine with there being automatically generated groups, however, there should at the very least be an opt-out. In the current interface of `verdi import` and `import_data` as explained in the OP there is no way to _not_ use a group, which I think is too restrictive

I agree.

**Comment by chrisjsewell** [comment]
Closed by #5145 (can't link it to the PR, because the limit is 10!)
