### ISSUE TITLE
verdi export create - performance of file repo export

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3684]
As part of the performance testing of `verdi export create` I've looked into the performance of the part that deals with exporting the file repository.

The numbers actually look quite good and I just wanted to report my findings here so that they are not lost.

### Test set
 ~20k nodes, 100k files/folders in the repository, running on MacBook Pro Mid 2015 (SSD)
```bash
$ find quicksetup/repository/node | wc -l
98266
```
```python
In [3]: qb=QueryBuilder()

In [4]: qb.append(Node)
Out[4]: <aiida.orm.querybuilder.QueryBuilder at 0x1125fec88>

In [5]: qb.count()
Out[5]: 20667
```

### Python implementation
Copied straight from `aiida.tools.importexport.dbexport.export_tree`

```python
from aiida.common.folders import SandboxFolder, RepositoryFolder, export_shard_uuid
from aiida import orm

section_name = 'node'
def make_repo(all_nodes_pk, nodesubfolder):
   if all_nodes_pk:
        # Large speed increase by not getting the node itself and looping in memory in python, but just getting the uuid
        uuid_query = orm.QueryBuilder()
        uuid_query.append(orm.Node, filters={'id': {'in': all_nodes_pk}}, project=['uuid'])
        for res in uuid_query.iterall():
            uuid = str(res[0])
            sharded_uuid = export_shard_uuid(uuid)

            # Important to set create=False, otherwise creates twice a subfolder. Maybe this is a bug of insert_path?
            thisnodefolder = nodesubfolder.get_subfolder(sharded_uuid, create=False, reset_limit=True)

            # Make sure the node's repository folder was not deleted
            src = RepositoryFolder(section=section_name, uuid=uuid)  # pylint: disable=protected-access
            if not src.exists():
                raise exceptions.ArchiveExportError(
                    'Unable to find the repository folder for Node with UUID={} in the local repository'.format(uuid)
                )

            # In this way, I copy the content of the folder, and not the folder itself
            thisnodefolder.insert_path(src=src.abspath, dest_name='.')

qb = orm.QueryBuilder().append(orm.Node, project=['id'])
pks = [ r[0] for r in qb.all() ]
folder = SandboxFolder()
print(folder.abspath)
```

Timings with `%prun make_repo(pks, folder)`
```
         10688100 function calls (10517736 primitive calls) in 43.262 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    67522    7.044    0.000    7.044    0.000 {method 'read' of '_io.BufferedReader' objects}
    66677    5.274    0.000    5.274    0.000 {built-in method posix.mkdir}
   487666    3.773    0.000    3.773    0.000 {built-in method posix.stat}
    62928    3.726    0.000    3.726    0.000 {built-in method io.open}
    31464    3.612    0.000   15.592    0.000 shutil.py:96(copyfile)
    80167    2.635    0.000    2.635    0.000 {built-in method posix.utime}
    80167    2.429    0.000    2.429    0.000 {built-in method posix.chmod}
    48703    1.955    0.000    1.955    0.000 {built-in method posix.listdir}
    80167    1.682    0.000    1.682    0.000 {built-in method posix.chflags}
      213    0.813    0.004    0.902    0.004 {method 'fetchmany' of 'psycopg2.extensions.cursor' objects}
   222335    0.707    0.000    1.090    0.000 posixpath.py:75(join)
    41334    0.694    0.000    0.755    0.000 genericpath.py:69(commonprefix)
    80167    0.624    0.000    8.595    0.000 shutil.py:173(copystat)
48703/20667    0.595    0.000   35.632    0.002 shutil.py:273(copytree)
    82668    0.576    0.000    0.902    0.000 posixpath.py:331(normpath)
    59500    0.551    0.000    0.551    0.000 {built-in method posix.lstat}

```

I wrote another implementation that was essentially just `shutil.copytree` on the right paths and got a timing that was within 10% of this timing (negligible speedup).

### Unix utilities
Copying the full folder in one go: 13s
```
$ time cp -r quicksetup/repository/node  abc

real    0m13.263s
user    0m0.728s
sys    0m10.743s
```

Copying each subfolder individually: 20s
```
$ time cp -r quicksetup/repository/node/* cde/

real    0m19.985s
user    0m0.812s
sys    0m13.622s
```
This is probably the fairer comparison, since in practice we cannot simply copy the full folder in one go but need to select the subset of subfolders we need.

### Conclusion
We are roughly within a factor 2 of `cp`. I think this is good enough.

Mentioning @sphuber and @giovannipizzi for info.

**Comment by ltalirz** [comment]
Note: using [pyfastcopy](https://pypi.org/project/pyfastcopy/) does not make any difference.
What would make a big difference, of course, is if we were to create node repository folders lazily and not have empty folders for so many nodes.

**Comment by giovannipizzi** [comment]
Thanks for the report! One comment, often the procedure takes a lot of time mostly to read many files from disk. Once the file system tables are read they are cached in memory, so subsequent reads are (much) faster. So if you run your tests in the order you present them, cp might look faster than python but maybe it's not fully true. For a fully fair comparison, if you want, you could flush the caches and then run first the cp test and then the python one to see if results are the same or reversed.

**Comment by ltalirz** [comment]
I tried with the `purge` command on MacOS
```
purge(8)                  BSD System Manager's Manual                 purge(8)

NAME
     purge -- force disk cache to be purged (flushed and
     emptied)
```

It turns out it actually doesn't matter whether you `cp -r dir/*` or `cp -r dir`.
The overall timing is in the same ballpark as before :
```
$ sudo purge
$ time cp -r tmpvludf1bz/* def/

real	0m22.915s
user	0m0.816s
sys	0m14.386s

$ sudo purge
$ time cp -r tmpvludf1bz/* sdf/

real	0m19.609s
user	0m0.810s
sys	0m12.468s

$ sudo purge
$ time cp -r tmpqsmcq2dp new

real	0m23.305s
user	0m0.819s
sys	0m14.434s
$ sudo purge
$ time cp -r tmpqsmcq2dp new2

real	0m20.205s
user	0m0.804s
sys	0m13.123s
```
This is in line with what I read [on SO](https://stackoverflow.com/a/28129677/1069467) (that `shutil` does a few more operations)

**Comment by CasperWA** [comment]
Thanks for making these tests @ltalirz !

**Comment by ltalirz** [comment]
Seeing very slow export creation on machine with magnetic disk (order of 6h for 1.4M nodes); completely dominated by "STORING REPOSITORY FILES" part.

Note to self: 
 * repeat small-scale test above on that machine 
 * check time impact of zipping (replacing `SandboxFolder()` with `ZipFolder()`)
