### ISSUE TITLE
missing import from ``urllib`` in several files

### ISSUE THREAD

**Issue by d-tomerini** [aiidateam/aiida-core#3698]
While testing the ``CODimporter`` on ``verdi shell``

```
from aiida.tools.dbimporters.plugins.cod import CodDbImporter
importer = CodDbImporter()
s = importer.query(formula = "Si")[0].get_aiida_structure()
```
 I encountered the issue below:

``NameError: name 'urllib' is not defined``

 ``urllib`` does not seem to be imported in the following files:

-  tools/dbimporters/baseclasses.py
- tools/dbimporters/plugins/icsd.py
- tools/dbimporters/plugins/nninc.py
- tools/dbimporters/plugins/oqmd.py
- tools/dbimporters/plugins/mpod.py

Tested on
AiiDA 1.0.1 a34b3566b5e98ebedb58f0f142cbf54808
python 3.7

full stack:

```
NameError                                 Traceback (most recent call last)
<ipython-input-3-b488fdbb71ac> in <module>()
      1 from aiida.tools.dbimporters.plugins.cod import CodDbImporter
      2 importer = CodDbImporter()
----> 3 s = importer.query(formula = "Si")[0].get_aiida_structure()

/home/dtomerini/git/aiida-core/aiida/tools/dbimporters/baseclasses.py in get_aiida_structure(self, converter, store, **kwargs)
    302         :return: AiiDA structure corresponding to the CIF file.
    303         """
--> 304         cif = self.get_cif_node(store=store, parse_policy='lazy')
    305         return cif.get_structure(converter=converter, store=store, **kwargs)
    306 

/home/dtomerini/git/aiida-core/aiida/tools/dbimporters/baseclasses.py in get_cif_node(self, store, parse_policy)
    287 
    288         with tempfile.NamedTemporaryFile(mode='w+') as f:
--> 289             f.write(self.cif)
    290             f.flush()
    291             cifnode = CifData(file=f.name, source=self.source, parse_policy=parse_policy)

/home/dtomerini/git/aiida-core/aiida/tools/dbimporters/baseclasses.py in cif(self)
    247         Returns raw contents of a CIF file as string.
    248         """
--> 249         return self.contents
    250 
    251     @cif.setter

/home/dtomerini/git/aiida-core/aiida/tools/dbimporters/baseclasses.py in contents(self)
    223             from hashlib import md5
    224 
--> 225             self._contents = urllib.request.urlopen(self.source['uri']).read().decode('utf-8')
    226             self.source['source_md5'] = md5(self._contents.encode('utf-8')).hexdigest()
    227         return self._contents

NameError: name 'urllib' is not defined

```

**Comment by ramirezfranciscof** [comment]
I just tried it and, as @d-tomerini  says, adding `import urllib.request` to `tools/dbimporters/baseclasses.py` seems to solve the error for me. I'm not sure why, but the 'request' package is not recognized by just importing `urllib`. I also didn't need to add the import to the other files for this command to work, but maybe we should anyways just to be sure?

@sphuber let me know if I can make a PR with the fix for this or if I'm patching this the wrong way.

**Comment by sphuber** [comment]
I think it is better to put a specific import in the plugin classes and not rely on it being imported in the base class. A grep for `urllib` shows that almost only `urllib.request.urlopen` is used and mostly in the `contents` property. I would simply add `from urllib.request import urlopen` in those methods and use the function directly.
