### ISSUE TITLE
Allow for 'help' on exposed inputs / outputs which have a namespace

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#3701]
When exposing inputs with the `namespace` keyword, a new `PortNamespace` is created. To document the purpose of this namespace, the `help` currently needs to be set "manually" - not really using an official interface.

This could be improved by allowing a `help` keyword on the `expose_inputs` / `expose_outputs` methods.

Drawback: The `help` does not really make sense if _no_ namespace is used, making the logic slightly more complicated (`help` can be set only if `namespace` is also set).

Example: currently written as

```python
spec.expose_inputs(
    SubWorkChain,
    namespace='sub'
)
spec.inputs['sub'].help = 'Inputs passed to the sub-workchain.'
```

Proposed syntax:
```python
spec.expose_inputs(
    SubWorkChain,
    namespace='sub',
    help='Inputs passed to the sub-workchain.'
)
```

Mentioning @sphuber for comment.

**Comment by sphuber** [comment]
This is already possible:
```
spec.expose_inputs(PwRelaxWorkChain, namespace='relax',
    namespace_options={
        'required': False,
        'populate_defaults': False,
        'help': 'Inputs for the `PwRelaxWorkChain`, if not specified at all, the relaxation step is skipped.'
    }
)
```

**Comment by greschd** [comment]
Cool, thanks! Somehow forgot about the namespace options 😅
