### ISSUE TITLE
Question: How is AiiDA different from Apache Ray?

### ISSUE THREAD

**Issue by dclong** [aiidateam/aiida-core#3706]
I'm looking for a general purpose but lightweight distributed computing framework in Python. I'm curious about the difference between AiiDA and Apache Ray.

**Comment by broeder-j** [comment]
Hi @dclong, I do not know Apache Ray, but from a quick look I can tell you the following:

AiiDA and Ray are quite different. It depends on what you want to do and care about.

1. AiiDA implements the open provenance model, (see http://www.aiida.net, or materbialscloud.org) so tracking (meta)data of your applications is very important for AiiDA and its users. (It looks to me Apache Ray does not do any of this)
2. AiiDA is used to run 'other also non python' codes and complex chains of calculations (workchains). These codes might be executed on different machines in different ways and is meant to scale in the number of calculation it can handle at time (HTC). All this through one python API. For a list of calculation plugins for see https://aiidateam.github.io/aiida-registry/
(Also Ray does not supports something like this it looks to me).

3. Ray allows you to write python code which 'might' be deployable/scalable like this on any machine (machine agnostic code), especially focused on machine learning. So ray probably takes care of dealing with schedulers and communication with the computing resources.

AiiDA allows you to abstract from the machine and scheduler a certain code is executed on and takes care of communication with computing resources and schedulers for these jobs.

If you just want to deploy in a distributed way your pure python application (and do not care about 1. or 2.) especially for machine learning consider using Ray. 
If you have an application you want to deploy on different machines and track its (meta)data or write workchains for, consider using AiiDA. Through you might have to write a plugin for your application.

I hope this helped for a start

**Comment by dclong** [comment]
@broeder-j Thank you very much for the comprehensive answer! It makes a lot of sense.
