### ISSUE TITLE
Allow invalidating cache for a specific node / process

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#3710]
In addition to implementing a way of invalidating cache on a per-exit-code level or on the level of the process class, I think there should be a way to mark a specific node / process as invalid.

The use case for this is when a workflow fails with a random calculation failure. If the calculation remains a valid cache, re-running the workflow would just immediately fail.
Previously I would just delete the offending calculation, but due to the new traversal / deleting rules, this now deletes the entire workflow tree.

The obvious "correct" way of solving such issues is through marking exit codes and using restart workchains, but it's difficult to get this right in 100% of cases - making this escape hatch very useful.

This could probably be implemented fairly easily through an updatable attribute.

Mentioning @sphuber for comment.

**Comment by sphuber** [comment]
This feature was added in #5207
