### ISSUE TITLE
verdi graph: reintroduce highlight of selected node

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3718]
`verdi graph generate` used to highlight the node that was used to generate the graph.
This got lost in introducing the new color scheme - we should simply reintroduce it

One simple way of highlighting could be to add a red border.

**Comment by chrisjsewell** [comment]
FYI this should be pretty easy:

After here: https://github.com/aiidateam/aiida-core/blob/5790d0db5d080fb755ae408d7cdbb4cf6ba55ef4/aiida/cmdline/commands/cmd_node.py#L436

You should just be able to do something like `graph.add_node(root_node, style_override={'color': 'red'})`: https://github.com/aiidateam/aiida-core/blob/5790d0db5d080fb755ae408d7cdbb4cf6ba55ef4/aiida/tools/visualization/graph.py#L430

**Comment by ramirezfranciscof** [comment]
Solved by #4081
