### ISSUE TITLE
Add annotated input type validation to `calcfunction` and `workfunction`

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#3724]
Quick thought, now we are in the shiny new age of python 3.
For python 3.6 onward I believe, type annotations are stored in `__annotations__`, e.g.

```python
@calcfunction
def my_calcfunction(structure: StructureData):
    pass

my_calcfunction.__annotations__ == {"structure": StructureData}
```

This could be used here, to set a more specific `valid_type` than just `orm.Data`:

https://github.com/aiidateam/aiida-core/blob/5790d0db5d080fb755ae408d7cdbb4cf6ba55ef4/aiida/engine/processes/functions.py#L261

**Comment by greschd** [comment]
Heh, I've had the same idea: #3569

**Comment by chrisjsewell** [comment]
Great minds think alike 😂
