### ISSUE TITLE
`verdi daemon status` should return non-zero exit code, if daemon is not running

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3728]
currently, it always returns exit code 0.

**Comment by ConradJohnston** [comment]
In the spirit of exit codes, isn't it already doing the correct thing?
The command `verdi daemon status` is successful and so returns 0. 
That the daemon isn't running isn't ideal, but I think this would be the wrong way to check for it a shell script.

**Comment by ltalirz** [comment]
I also wondered about this when I made the change, but I think what I'm suggesting here is actually the default behavior on unix systems.

E.g. for systemd services, calling `sudo service apache2 status` will return a non-zero exit status if apache2 is not running (otherwise 0).

In practical terms, I also think this makes the exit code more useful.

**Comment by greschd** [comment]
Just checked the same for postgresql:
```
a-dogres@A-DOGRES-082219:/mnt/c/Users/a-dogres$ service postgresql status
10/main (port 5432): down
a-dogres@A-DOGRES-082219:/mnt/c/Users/a-dogres$ echo $?
3
```
Found this guide on exit code numbers, and I think it should _not_ be 1, though: http://www.tldp.org/LDP/abs/html/exitcodes.html

**Comment by ltalirz** [comment]
Right, also for systemd it was 3.
Happy to make it 3 if people prefer

**Comment by greschd** [comment]
Yeah, that might've just been systemd's choice for ``postgresql`` on my machine. I'm not an expert on unix conventions by any means, but at least from looking at that description 3 would be a better choice.

**Comment by greschd** [comment]
That convention doesn't appear _too_ strong though, with a tiny bit of poking around I haven't managed to get anything but 1 exit codes from the GNU coreutils 😄

**Comment by ConradJohnston** [comment]
Ha, I'm convinced. I do agree it would be more useful, assuming it's well doc'd. There's a need to differentiate what happens if `verdi` fails though, vs. where `verdi` is successful, but the daemon is down.
