### ISSUE TITLE
cleanup of top-level dir

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3730]
Some ideas for reducing files at the top level

 - [x] move `conftest.py` to `tests`
 - [x] ~~remove `bin/runaiida` (is this needed?)~~ Move to `console_scripts` in `setup.json`
 - [x] remove `examples/`  (@sphuber should these go to the docs?)
 - [x] remove `utils/plugin_tpl` (ok, that's not top-level but seems outdated)

**Comment by greschd** [comment]
>     * [ ]  move `conftest.py` to `tests`

Agreed - I think this should just work.
>     * [ ]  remove `bin/runaiida` (is this needed?)
I think this should remain. My current workflow doesn't use it much, but it is a convenient shorthand for script shebangs.

**Comment by giovannipizzi** [comment]
> * [ ]  remove `bin/runaiida` (is this needed?)
> I think this should remain. My current workflow doesn't use it much, but it is a convenient shorthand for script shebangs.

I agree, I would keep it. But maybe one could move it somewhere else? Or add it via the console_scripts?

**Comment by sphuber** [comment]
I actually use the `#!/usr/bin/env runaiida` shebang a lot, so I would be in favor of keeping it. If it is indeed possible to install this through the `console_scripts` entry point instead, that would be an even better solution
