### ISSUE TITLE
Make sure threads are handled correctly for the REST API

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#3743]

**Comment by giovannipizzi** [comment]
I imagine this is related to #3708, and means applying the changes for the REST API?
I can confirm that I am using the REST API on a Django profile, using the materials cloud feature "browse your own explore section". After a few clicks, I get 500 errors and if I go directly to the REST API, I get 
```
{"message":"QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)"}
```
(AiiDA develop branch commit 617b2df6569b6ed0ff0aa1807b621ccbc28c1869)

@CasperWA is this something that can be investigated, maybe with the help of @asle85 ?
We wanted to use the REST API for the tutorial on Wannier90+AiiDA on March 25th, but if there is this problem I fear this is not usable...

**Comment by ltalirz** [comment]
Just ran into this issue myself as well...

**Comment by CasperWA** [comment]
> Just ran into this issue myself as well...

"Good" to hear... I'm still creating a test to reproduce it locally and eventually make sure my fix works as intended.

**Comment by ltalirz** [comment]
hooray!
thanks @CasperWA and @sphuber !
