### ISSUE TITLE
Modify options in `verdi database migrate`.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#3789]
When I was migrating AiiDA lab I discovered the following problem: the `-f` option which is described as 'Do not ask for confirmation' is not working as one would expect. I was thinking that it should never ask for a confirmation, while in practice the behaviour is 'start migration, without asking for confirmation'. 

For example at the step [0024_dblog_update.py](https://github.com/aiidateam/aiida-core/blob/a2bebb422f4a7b75e8ef65fd797f128abf12c6cc/aiida/backends/djsite/db/migrations/0024_dblog_update.py) it asks you the following:
https://github.com/aiidateam/aiida-core/blob/a2bebb422f4a7b75e8ef65fd797f128abf12c6cc/aiida/backends/djsite/db/migrations/0024_dblog_update.py#L167
This makes troubles when performing automatic aiida database update (such as the one of AiiDA lab).

[PROPOSITION 1]

- I would suggest to not modify the behaviour of `-f` option, but adapt the description to something like 'do not ask for confirmation to start the migration'.

- I would add `-y/--yes` that would not ask confirmation during the process of migration.

[PROPOSITION 2]

Another possibility would be to do exactly what the description says: never ask for a confirmation if the `-f` option is set.

**Comment by sphuber** [comment]
This only affects two very old legacy migrations. We should no longer be using prompts in migrations, so this is no longer relevant.
