### ISSUE TITLE
Caching messes with 'verdi code duplicate'

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#3802]
When caching is globally enabled (``default: True``), trying to exactly duplicate a Code but changing its label results in another Code with the _same_ label being created. 

The reason for this is that the ``label`` is a mutable attribute of the ``Code``, and thus not taken into account when creating the hash. As a result, the ``Code`` is stored from cache and gets the old label.

A simple fix would just be setting ``_cachable = False`` on the ``Code`` class. Tagging @sphuber @giovannipizzi for comment.

Example output below:

```bash
(aiida) a-dogres@A-DOGRES-082219:~/programming/aiida/aiida-core$ verdi code list
# List of configured codes:
# (use 'verdi code show CODEID' to see the details)
[...]
* pk 578 - pw-6.4.1@localhost

(aiida) a-dogres@A-DOGRES-082219:~/programming/aiida/aiida-core$ verdi code duplicate pw-6.4.1
Info: enter "?" for help
Info: enter "!" to ignore the default and set no value
Label [pw-6.4.1]: pw-new-label
Description [QE 6.4.1 pw.x]: 
Default calculation input plugin [quantumespresso.pw]: 
Installed on target computer? [True]: 
Computer [localhost]: 
Remote absolute path [/home/a-dogres/codes/qe-6.4.1/bin/pw.x]: 
Success: Code<666> pw-6.4.1@localhost created

(aiida) a-dogres@A-DOGRES-082219:~/programming/aiida/aiida-core$ verdi code list
# List of configured codes:
# (use 'verdi code show CODEID' to see the details)
[...]
* pk 578 - pw-6.4.1@localhost
* pk 666 - pw-6.4.1@localhost
```

**Comment by sphuber** [comment]
I think we should just disable caching on `Data` nodes as a whole as it never makes sense with what caching means in AiiDA's context. If we consider a `Data` node for storing, what is the point of searching for an identical one and then storing that one instead. The result will always be exactly the same because with data nodes only the node itself and none of its neighbors are considered.

**Comment by greschd** [comment]
Yeah, agreed. The only reason I can think of is if we want to "battle-test" the hashing of Data nodes before implementing repository deduplication. And that's.. not a very good reason 😄

**Comment by greschd** [comment]
Currently, ``_cachable`` class attributes are set by:

- ``Node``: sets it to ``True``
- ``ProcessNode``: sets it to ``False``, with the comment "Specific sub classes should be marked as cacheable when appropriate"
- ``WorkChainNode``: ``False`` (redundantly, because ``ProcessNode`` already sets it)
- ``CalculationNode``: ``True``

I guess the most consistent way of changing this would be

- ``Node``: ``False``
- ``CalculationNode``: ``True``
