### ISSUE TITLE
remove pip's --editable flag on CI tests

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3806]
During the hackathon, @yakutovicha suggested to remove the --editable flag for pip installs during CI tests.
The reasoning: with a regular install you also test whether all files are included (which otherwise might be present just in the git repo but not in the distribution that is later uploaded to PyPI).

**Comment by ltalirz** [comment]
Unfortunately, there is a problem with this in practice - the setup to measure test coverage becomes complicated, since we need to point coverage to directories *outside* the git repo where the python files of the package are installed.

I'm closing this for the moment - happy to move further in this direction if the coverage issue can be addressed.

**Comment by greschd** [comment]
Would creating two separate jobs for the different installs be feasible, or too much additional run-time for the build?

**Comment by ltalirz** [comment]
Running another job just to test the regular install would be possible but I'm wondering a bit whether it's worth the effort...

Anyhow, we should re-enable coverage reports ;-)

**Comment by greschd** [comment]
Yeah, might not be. I've gotten tired of manually testing the regular install before release, so in some plugins I've added that.. but the ration of builds to releases is a very different one there 😄

By the way, do you know if there's a difference between
```bash
python setup.py sdist
pip install dist/<package>.tar.gz
```
and
```
pip install .
```

I've always done the former to check that the package I'm about to upload is valid, but now I'm wondering if ``pip install .`` might be just a shortcut to do the same.

**Comment by ltalirz** [comment]
Good question - I don't know
