### ISSUE TITLE
Problem with inputs and expose_inputs

### ISSUE THREAD

**Issue by danieleongari** [aiidateam/aiida-core#3808]
I have a work chain (`WC1`) that exposes the parameters of a calculations.
```
spec.expose_inputs(ZeoppCalculation, namespace='zeopp', exclude=['parameters', 'structure'])
```
I excluded the `parameters` because they are set as "required" by the calculations, but I simply want to set them as defaults in my outer chain but let the user change them. 
```
        spec.input('parameters',
                   valid_type=NetworkParameters,
                   default=lambda: NetworkParameters(dict=ZEOPP_PARAMETERS_DEFAULT),
                   required=False,
                   help='parameters for zeo++')
```
Now, I want to expose the inputs of `WC1` in another workchain (`WC2`):
```
        spec.expose_inputs(WC1,
            include=[
                'zeopp',  
                'zeopp.parameters',
            ])
```
but the builder gets confused because `builder.zeopp.parameters` returns:
```
  File "test_nanoporous_screening_2.py", line 96, in <module>
    builder.zeopp.parameters = NetworkParameters(dict={'vol': [0.0, 0.0, 100]}) # quick parameters for testing purpose
  File "/home/daniele/aiida1/aiida_core/aiida/engine/processes/builder.py", line 84, in __setattr__
    raise AttributeError('Unknown builder parameter: {}'.format(attr))
AttributeError: Unknown builder parameter: parameters
```
and I was not expecting that also `builder['zeopp.parameters']` returns an error:
```
  File "test_nanoporous_screening_2.py", line 96, in <module>
    builder['zeopp.parameters'] = NetworkParameters(dict={'vol': [0.0, 0.0, 100]}) # quick parameters for testing purpose
  File "/home/daniele/aiida1/aiida_core/aiida/engine/processes/builder.py", line 110, in __setitem__
    self.__setattr__(item, value)
  File "/home/daniele/aiida1/aiida_core/aiida/engine/processes/builder.py", line 84, in __setattr__
    raise AttributeError('Unknown builder parameter: {}'.format(attr))
AttributeError: Unknown builder parameter: zeopp.parameters
```
Also I can not put an input in a `namespace`, e.g., the same namespace of the calculation.
Am I missing something and there is a way to do this?
I find pretty common the need to exclude one parameter from the exposure and set it as an input with `required=False`, but then it is creating this problem with `expose_inputs`.

**Comment by sphuber** [comment]
When you define `parameters` on `wc1` its full path is not `zeopp.parameters` but simply `parameters`. This is why `builder.zeopp.parameters` raises, because that port does not exists (you have excluded it when exposing the inputs of `ZeoppCalculation` after all).
So when you do:
```
spec.expose_inputs(ZeoppCalculation, namespace='zeopp', exclude=('parameters'))
spec.input('parameters')
```
The inputs that `wc1` expects has the structure:
```
inputs = {
    'zeopp': { .... }  # calculation inputs
    'parameters': NetworkParameters()
}
```

**Comment by danieleongari** [comment]
Sorry I made a mistake in writing, the input (not `parameters` but `zeopp.parameters`):
```
        spec.input('zeopp.parameters',
                   valid_type=NetworkParameters,
                   default=lambda: NetworkParameters(dict=ZEOPP_PARAMETERS_DEFAULT),
                   required=False,
                   help='parameters for zeo++')
```
I understand that I can call it `zeopp_parameters` and there would be no problems, but by calling like that I would like to enforce that it is the same as the zeopp input.

**Comment by sphuber** [comment]
Ah ok, I see now what you are trying to do. If it really is just the default for the `parameters` input of the `ZeoppCalculation` that you want to change, why not do so directly:

```
spec.expose_inputs(ZeoppCalculation, namespace='zeopp')
spec.inputs['zeopp.parameters'].default = lambda: NetworkParameters(dict=ZEOPP_PARAMETERS_DEFAULT)
```
I have never done this myself, but I think that should work. Please give that a try

**Comment by danieleongari** [comment]
This sounds as an elegant solution to my problem, I will try it.
Thank you very much!

**Comment by danieleongari** [comment]
It does work, thanks, the only difference is that  I need to write it as:
```
        spec.inputs['zeopp']['parameters'].default = lambda: NetworkParameters(dict=ZEOPP_PARAMETERS_DEFAULT)
```
and I also added:
```
        spec.inputs['zeopp']['parameters'].required = False
```
Thanks!

**Comment by ltalirz** [comment]
Closing this, feel free to reopen in case something is still unresolved here.
