### ISSUE TITLE
Isolated `BandsData` will raise exception when running `verdi data bands list`

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#3811]
```
bands = load_node(<bands_node>)
bands_clone = bands.clone()
bands_clone.store()
```
will cause `verdi data bands list` break.

```
File "/home/unkcpz/pyProject/aiida_core/aiida/backends/djsite/queries.py", line 178, in get_bands_and_parents_structure
    struc_pks = [structure_dict[pk] for pk in pks]
File "/home/unkcpz/pyProject/aiida_core/aiida/backends/djsite/queries.py", line 178, in <listcomp>
    struc_pks = [structure_dict[pk] for pk in pks]
KeyError: 230
```

Although I have no idea whether it is reasonable to have `BandsData` node without structure as its ancestor, this is still a case to consider. but I don't know which of the following measures is more reasonable

1. forbid users from creating `BandsData` instance without set a `StructureData` as its ancestor node.
2. when running `verdi data bands list` show `None` as its formula value.

I am in favor of the second personally.

**Comment by ltalirz** [comment]
Thanks @unkcpz for pointing this out. I agree with your assessment and would vote for 2.

Mentioning @giovannipizzi and @sphuber for comment.

**Comment by greschd** [comment]
Agree with #2, I'm fairly certain I've created `BandsData` without associated `StructureData` in some places.

**Comment by sphuber** [comment]
This really depends on the original design of `BandsData`. If it really needs an associated `StructureData` then option 2 would be a bit of a workaround. But given that one can already created a separate `BandsData` object, interfaces should not except, so I would also vote for option 2

**Comment by ltalirz** [comment]
Thanks for the input - @unkcpz this is the "go" signal ;-)

**Comment by unkcpz** [comment]
I make a PR. but one thing need to be discussed, when a bands object is cloned, its `StructureData` should also be cloned? Maybe this behavior is what users expected when calling the `.clone()` function.

**Comment by greschd** [comment]
I don't think it should clone the `StructureData`. Looking at the code, the "linked structure" is anyway just determined through a query for the closest ancestor, and `.clone()` definitely shouldn't do any node linking - the graph relationships of the clone should be up to the calling code (e.g. in the caching code).

That makes me wonder, though, if that linked structure is always the right one. It looks for the closest parent, but for example if a calculation creates both structure and bands in one step, the correct structure might be a sibling node.
