### ISSUE TITLE
QueryBuilder: add shortcut to EXPLAIN ANALYZE

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3845]
When optimizing SQL queries, using the [EXPLAIN ANALYZE](https://www.postgresql.org/docs/11/sql-explain.html) functionality of postgres can be very useful in understanding how table indices are used and how much time is spent in different aspects of a query.

Currently, it is quite cumbersome for users to provide the output of `EXPLAIN ANALYZE` to developers (they need to print the Querybuilder, log on to psql, paste it after `EXPLAIN ANALYZE`, put a semicolon and run).
It would be useful if the QueryBuilder had a shortcut to simply run `EXPLAIN ANALYZE` on its internal query and return the result as a string.

**Comment by giovannipizzi** [comment]
Here is a possible implementation:

```python
from sqlalchemy.ext.compiler import compiles
from sqlalchemy.sql.expression import Executable, ClauseElement, _literal_as_text

# Adapted from http://www.wmmi.net/documents/SQLAlchemy.pdf
class ExplainAnalyze(Executable, ClauseElement):
    def __init__(self, stmt):
        self.statement = _literal_as_text(stmt)

@compiles(ExplainAnalyze, 'postgresql')
def pg_explain(element, compiler, **kw):
    text = "EXPLAIN ANALYZE "
    text += compiler.process(element.statement, **kw)
    return text

# I already call it self - this is what needs to be put as a new method of the QueryBuilder class
def get_queryplan(self):
    queryplan = self._impl.get_session().execute(ExplainAnalyze(self.get_query())).fetchall()

    queryplan_string = "\n".join(row.values()[0] for row in queryplan)

    return queryplan_string

from aiida.orm import Node, QueryBuilder

qb = QueryBuilder().append(Node).limit(10)
print(get_queryplan(qb))
```

If you like the idea, it's just a matter of copy-pasting the code into `aiida/orm/querybuilder.py` (putting the `get_queryplan()` function as a method of `QueryBuilder`, and then the final call would become simply `print(qb.get_queryplan())`.

@lekah do you see issues with this or it's ok to implement? It's very Postgres specific, but at the moment anyway we only support that...

Another option (maybe better?) is to push this into the `_impl` classes, then have the `get_queryplan` method in the top class call through, and have the default base class implementation return a NotImplementedError?

**Comment by giovannipizzi** [comment]
Note that probably #3844 needs to  be fixed first before this will work, I think - maybe they could be fixed at the same time?

**Comment by lekah** [comment]
The explain is implemented in the sqlalchemy-utils (that are already a dependency of AiiDA). See https://sqlalchemy-utils.readthedocs.io/en/latest/database_helpers.html for details.
A minimal working example is:

from sqlalchemy_utils import analyze
qb = QueryBuilder().append(Node, filters={'id':{'<':100}})
analysis = analyze(qb._impl.get_session(), qb.get_query())
print(analysis.plan)

analysis.plan is a dictionary of the query plan. The example above gives me
`{u'Actual Loops': 1,
 u'Actual Rows': 99,
 u'Actual Startup Time': 0.009,
 u'Actual Total Time': 0.188,
 u'Alias': u'db_dbnode_1',
 u'Filter': u"((type)::text ~~ '%'::text)",
 u'Index Cond': u'(id < 100)',
 u'Index Name': u'db_dbnode_pkey',
 u'Local Dirtied Blocks': 0,
 u'Local Hit Blocks': 0,
 u'Local Read Blocks': 0,
 u'Local Written Blocks': 0,
 u'Node Type': u'Index Scan',
 u'Parallel Aware': False,
 u'Plan Rows': 95,
 u'Plan Width': 116,
 u'Relation Name': u'db_dbnode',
 u'Rows Removed by Filter': 0,
 u'Rows Removed by Index Recheck': 0,
 u'Scan Direction': u'Forward',
 u'Shared Dirtied Blocks': 0,
 u'Shared Hit Blocks': 12,
 u'Shared Read Blocks': 18,
 u'Shared Written Blocks': 0,
 u'Startup Cost': 0.43,
 u'Temp Read Blocks': 0,
 u'Temp Written Blocks': 0,
 u'Total Cost': 103.57}
` which tells me that the index db_dbnode_pkey is used, as expected.

This would be straightforward to implement for the QueryBuilder. A function called get_analysis would just need to wrap the sqlalchemy_utils.analyze call. Easier to implement than above and does not

**Comment by giovannipizzi** [comment]
Note: analyze has been removed in SQLAlchemy-utils > 0.36. See comments [here](https://github.com/kvesteri/sqlalchemy-utils/pull/408). We're going to upgrade to this version soon (see #4723) so we won't be able to rely on @lekah's suggestion - we should probably use (a modification of) my suggestion above
