### ISSUE TITLE
Suggest data format supporting for PGF/TikZ and discard supporting for xmgrace. 

### ISSUE THREAD

**Issue by hongyi-zhao** [aiidateam/aiida-core#3861]
Hi,

I noted AiiDA supporting Xmgrace's data format.  I don't think it's good idea considering that this tool has already stopped actively developing for many years.

IMHO, why not support the  [PGF/TikZ](https://github.com/pgf-tikz/pgf), which is powerful and always manitained latex macro and vector graph language.

Regards

**Comment by giovannipizzi** [comment]
I don't think it's a bad idea to support a format.

I'm ok supporting new formats, so feel free to create a PR to support any format you like. (Note however that PGF would not be an alternative to XMgrace: PGF is for nice plotting with LaTeX, XMgrace is for interactive plotting, zooming, data analysis, ...

(Note that there is already a PDF format via python/matplotlib that also support LaTeX labels. If this is enough, feel free to close this issue).

**Comment by hongyi-zhao** [comment]
It seems python/matplotlib is more suitable for this type of job than PGF.
