### ISSUE TITLE
Add `--verbose` flag to `verdi quicksetup`

### ISSUE THREAD

**Issue by hongyi-zhao** [aiidateam/aiida-core#3864]
Hi,

It seems the logic of setting a profile for aiida is complicated to some extent.
I tried manually with psql command but failed.  Fortunately, the ``verdi quicksetup'' save me from doing the trick.

As a result, the internal logic is encapsulated, I want to know could  you please give some options like 
--verbose|-v to verdi, so that I or other users who want to understand the inner operations can see detailed commands / steps really executed.  This is more valuable for understanding aiida than the trial-and-error method based on the instructions given [here](https://aiida.readthedocs.io/projects/aiida-core/en/latest/install/installation.html).  
 
Regards

**Comment by ltalirz** [comment]
PR https://github.com/aiidateam/aiida-core/pull/5085 added global verbosity control to the `verdi` commands.
Released in v2.0.0b1 on 2022-03-15
