### ISSUE TITLE
What's the origin of the name for the command line tool verdi?

### ISSUE THREAD

**Issue by hongyi-zhao** [aiidateam/aiida-core#3865]
Hi,

I cannot figure out this: what's the origin of the name for command line tool verdi?

Any hints?

Regards

**Comment by sphuber** [comment]
It is an homage to the Italian composer [Giuseppe Verdi](https://en.wikipedia.org/wiki/Giuseppe_Verdi). Take a look at the list of his most well-known operas to try and figure out why ;)

**Comment by hongyi-zhao** [comment]
Thanks a lot for your hints.
