### ISSUE TITLE
Inconsistent use of InteractiveOption & OverridableOption?

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3895]
We are currently using two click option classes widely in the codebase:
https://github.com/aiidateam/aiida-core/blob/58bace313a7dffdd576679feae87fb2a029bd4cf/aiida/cmdline/params/options/interactive.py#L22
and
https://github.com/aiidateam/aiida-core/blob/5d9ade372ef8a2bfa5b88d1a8d10150f94b23bf1/aiida/cmdline/params/options/overridable.py#L20

As you can see, they don't inherit from each other; however the handling of the `!` and `? ` characters for empty values / help string prompting is done only in the `InteractiveOption`.
For this reason, options using the `OverridableOption` do not behave as documented.

@sphuber and @giovannipizzi is there any reason for not combining the two?

Should I simply make the `OverridableOption` return an `InteractiveOption` here:
https://github.com/aiidateam/aiida-core/blob/5d9ade372ef8a2bfa5b88d1a8d10150f94b23bf1/aiida/cmdline/params/options/overridable.py#L65
or do you want an OverridableInteractiveOption?

**Comment by ltalirz** [comment]
I realize now that one requirement of the `InteractiveOption` is to have a prompt defined, which I would then need to define for every cli option.

I wonder whether we can relax this constraint and just construct the prompt out of the option name (as it is done already by click otherwise)?

**Comment by sphuber** [comment]
The `!` and `?` also don't apply whatsoever to the `OverridableOption` option. Those characters only make sense for interactive options.

The `OverridableOption` is a very basic class to be able to allow basic options that can be reused in many commands, with some possibility for customization, but not everything. For example flag names are fixed and cannot be overridden. This is the mechanism we use to keep the flag labels for recurring options consistent. So the `OverridableOption` has nothing to say about the behavior of the option from the user's but purely from the developer's point of view.

The `InteractiveOption` is more specific than this and should only be used for options that also really need to behave interactively. This class then really implements code that changes how the option behaves from the user's perspective.

> Should I simply make the OverridableOption return an InteractiveOption here:

I would say no, simply because the `OverridableOption` is not only used for interactive options. Can you point me to the code that made you think there is a problem here? I.e. where there is an option that should behave as interactive, but doesn't?

**Comment by ltalirz** [comment]
> The ! and ? also don't apply whatsoever to the OverridableOption option. Those characters only make sense for interactive options.

> The `InteractiveOption` is more specific than this and should only be used for options that also really need to behave interactively.

I think we need to define what we mean by "interactive" here.
If "interactive" means that entering `?` gives me the help string and entering `!` allows me to leave the reply empty (unless the option requires a non-empty value), then I would argue that *all* of our options should be interactive for consistency.

> Can you point me to the code that made you think there is a problem here? I.e. where there is an option that should behave as interactive, but doesn't?

E.g. all of those:
https://github.com/aiidateam/aiida-core/blob/5f50f0335761386ddacbb5de4a6934b659b20e2d/aiida/cmdline/params/options/commands/setup.py#L219-L281

**Comment by ltalirz** [comment]
P.S. I see that, instead of changing the `OverridableOption`, one can also specify the interactivity via `cls=InteractiveOption` - but if it turns out that this is something we essentially want everywhere, it would be better not to have to do this for each option.

**Comment by sphuber** [comment]
> reply empty (unless the option requires a non-empty value), then I would argue that _all_ of our command line options should be interactive for consistency.

we might just have a problem of definition of terms, but I don't think all options should be interactive. If with interactive we mean options that will prompt, then there is a ton of options that are not and should not be interactive. Just as an example all the options in `verdi process list` are not interactive and should never be.

> P.S. I see that, instead of changing the OverridableOption, one can also specify the interactivity via cls=InteractiveOption like here

This is what I was trying to point out in my original response, the `OverridableOption` has nothing to do with interactiveness.

**Comment by sphuber** [comment]
The options you have highlighted for the quicksetup use `OverridableOption` use that only to make them reusable for multiple commands while guaranteeing they have the same flag. How they should _behave_ has nothing to do with the overridableness. As you discovered this can be configured through the `cls` argument.

**Comment by ltalirz** [comment]
Ah my bad, somehow I overlooked that it's about prompting vs not prompting ;-) Hehe, that makes sense!
I'll now check back to see whether there actually are any issues as mentioned in https://github.com/aiidateam/aiida-core/issues/3534

**Comment by ltalirz** [comment]
I think the current usage of `OverridableOption` and `InteractiveOption` is fine.
I've just adjusted the docstring of one a bit to potentially reduce confusion in the future
