### ISSUE TITLE
InteractiveOption always allows to skip setting value

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3897]
The `InteractiveOption` of the CLI, currently always allows users to pass `!` in order to avoid setting a value, bypassing any further validation that may be provided by the `type`.
https://github.com/aiidateam/aiida-core/blob/5da7120645b6cdb751d6db54431ead38417d2345/aiida/cmdline/params/options/interactive.py#L179-L199

I propose this to be changed such that entering `!` results in an empty string being passed further to the `type`.
Only if conversion by the type passes as well should a `None` value be returned.

**Comment by sphuber** [comment]
I agree that `!` means simply "ignore the current default set in the prompt and set an empty value". This should indeed still be allowed and so should pass through validation.
