### ISSUE TITLE
PGSU not available for conda

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#3900]
The pgsu dependency cannot be installed with conda: https://github.com/aiidateam/aiida-core/runs/566297364?check_suite_focus=true !

@ltalirz Can you create a conda-forge package, please?
@sphuber Can you make sure to add me as a reviewer when dependencies are changed? I'm not sure why the codeowner file did not trigger my review.

**Comment by chrisjsewell** [comment]
This is what I mentioned in https://github.com/aiidateam/aiida-core/pull/3613#issuecomment-609731745. I still feel you shouldn't be "allowed" to merge to develop until `.github/workflows/test-install.yml` passes, rather than these tests only being triggered after the merge?

**Comment by csadorf** [comment]
@chrisjsewell It actually should have been triggered: https://github.com/aiidateam/aiida-core/blob/5da7120645b6cdb751d6db54431ead38417d2345/.github/workflows/test-install.yml#L4-L11

I assume it didn't because it was a pull request? I'm still a bit confused about the github actions `push` trigger.

**Comment by chrisjsewell** [comment]
> I assume it didn't because it was a pull request?

Yep exactly `push` only trigger when a commit is made to a branch of `aiidateam/aiida-core` (not forks), rather than `pull-request` trigger when commits are made to any forks/branches associated with open PRs.

**Comment by ltalirz** [comment]
the PR is open since 2 days ago https://github.com/conda-forge/staged-recipes/pull/11226
waiting for it to be merged

**Comment by csadorf** [comment]
> > I assume it didn't because it was a pull request?
> 
> Yep exactly (as I understand it) `push` only trigger when a commit is made to a branch of `aiidateam/aiida-core` (not forks), rather than `pull-request` trigger when commits are made to any forks/branches associated with open PRs.

@chrisjsewell So no other way than to just duplicate everything? Or should we just replace `push` with `pull_request` considering the use case here?

**Comment by chrisjsewell** [comment]
> @chrisjsewell So no other way than to just duplicate everything? Or should we just replace push with pull_request considering the use case here?

Given that its also be run as a `cron` job anyway, I'd just replace with pull_request.

FYI here's a related [GitHub Forum Post](https://github.community/t5/GitHub-Actions/How-to-prevent-running-actions-on-push-when-pull-request-is-also/td-p/47013), that I've looked at before in relation to other projects. Its annoying that if you make a PR from a branch (not fork), you end up with duplicates of all the tests, but it looks like there is no good solution for that.

**Comment by ltalirz** [comment]
fixed https://github.com/conda-forge/pgsu-feedstock
