### ISSUE TITLE
About the path specification used under the work_dir.

### ISSUE THREAD

**Issue by hongyi-zhao** [aiidateam/aiida-core#3917]
Hi,

For the folders generated under the work_dir, the path specification is as follows:

`xx/xx/uuid`

Where x is a hex-decimal character, i.e., 0-9a-f, but I still cannot figure out why use this path specification, considering that the uuid itself is enough for distinguish all of the folders' names there.

Any hints?

Regards

**Comment by ltalirz** [comment]
hi @hongyi-zhao  - actually, the first two levels are also part of the UUID, the general concept is called "sharding".

One reason for sharding the file repository in AiiDA is that if you have millions of nodes and no sharding, it will take the files system a long time to even *list* all the directories in your repository.
I hope this answers your question,
Best,
Leo

**Comment by ltalirz** [comment]
See also https://github.com/aiidateam/aiida-core/blob/cc49ee924bdef3be346f8ad1b6c578ebd48d0beb/aiida/common/folders.py#L523-L538

**Comment by hongyi-zhao** [comment]
Thanks, got it.

Regards,
HY
