### ISSUE TITLE
backup script contains custom prompting implementation

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#3933]
This custom prompting implementation (built around `input()`) could easily be replaced by `click.prompt`:
https://github.com/aiidateam/aiida-core/blob/0e17ac1d35d3e90b7277fbfe2fa0edabc9732b53/aiida/manage/backup/backup_utils.py#L19-L126

At least it seems well tested, though
https://codecov.io/gh/aiidateam/aiida-core/src/develop/aiida/manage/backup/backup_utils.py

**Comment by ltalirz** [comment]
Thanks, much appreciated!

**Comment by unkcpz** [comment]
the code has been removed entirely. Close.
