### ISSUE TITLE
Unexpected ports {'submit_script_filename': '_aiidasubmit.sh'}, for a non dynamic namespace

### ISSUE THREAD

**Issue by TsumiNa** [aiidateam/aiida-core#3964]
Hi! When I updated my aiida-core installation to v1.2.1, I always get this error.

```
Excepted <ValueError: Error occurred validating port 'inputs.metadata.options': Unexpected ports {'submit_script_filename': '_aiidasubmit.sh'}, for a non dynamic namespace
```
![image](https://user-images.githubusercontent.com/6410921/80276383-5d786d80-8723-11ea-8508-07ae8ef5f961.png)

My aiida running environment:
* OS: macOS Catalina 10.15.4
* Python: 3.3.7 (installed by miniconda)
* aiida-core: v1.2.1
* aiida-quantumespresso: v3.0.0a6

I suspect that this is related to the new feature implemented in #3948.

**Comment by sphuber** [comment]
You probably forgot to restart the daemon. Note that when updating the code, you should _always_ make sure to finish all running calculations and workflows and then stop the daemon.

**Comment by TsumiNa** [comment]
@sphuber Thanks for your quick reply! Will check it when the calculations are done.

**Comment by TsumiNa** [comment]
Everything works well after restarting the daemon. Thank you so much.
