### ISSUE TITLE
Docs: Provide pathways for users after finishing the tutorial

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#3982]
After they finish the tutorial, we want to guide the user to the most pertinent HowTo's to continue learning, or other parts of the documentation that might be immediately relevant (e.g. how to install AiiDA if they have run the tutorial in Quantum Mobile, Binder, ...). Here we can discuss which parts of the documentation should be linked to at the end of the tutorial.

One idea was to provide different pathways depending on the type of user:

- Users who want to only analyze existing AiiDA data.
- Users who want to run calculations and workflows already existing/implemented.
- Users that want to write new workflows (or develop new calculation plugins to support a new code).

With perhaps some of initial links that can be shared by all pathways.

**Comment by mbercx** [comment]
Below is a preliminary list of some of the HowTo's and other parts of the documentation we would like to guide the users towards after they have completed the tutorial. We've roughly structured them in the 3 use cases mentioned in my previous comment, but as raised by @ramirezfranciscof, users that e.g. want to write workflows will probably first want to know how to run them.

---
* **Intro - Installation**: In case the user has run the tutorial in e.g. a Quantum Mobile VM or Binder, the next step will probably to install AiiDA on their system.

* **Demo Page** (#4010)

* **Running existing calculations and workflows**
  - *How to run external codes* (#3987): AiiDA already interfaces with many popular codes (link to the [plugin registry](https://aiidateam.github.io/aiida-registry/) for a full list).
  - *How to run a predefined workflow* (#3992)

* **Analyzing AiiDA data**
  - *How to import data* (#3994)
  - *How to find data* (#3996)
  - *How to add support for custom data types* (#3995)

* **Writing workflows or plugin Development**
  - *How to write workflows* (#3991)
  - *How to develop a plugin package* (#4008)

* (Possibly) **Extensive tutorials** directed at a specific audience (Mat Science, QE, ...).
----
Any comments on links to add or remove are welcome! I'll update the list as we proceed.

**Comment by mbercx** [comment]
@csadorf Shouldn't we add this to the first version? I've can quickly copy @chrisjsewell's panels at the end of the "Getting started" page to the "How to continue from here" section of the tutorial and do a PR.

**Comment by csadorf** [comment]
Could you *move* them instead of copying them? I don't think it makes much sense to have them in both places.

**Comment by chrisjsewell** [comment]
bear with 2 secs, I'm just making a draft PR to try out the docs with section level indexes, and moving the tutorial into getting started

**Comment by chrisjsewell** [comment]
See #4130, where I have moved tried also moving the tutorial into the introduction section
