### ISSUE TITLE
Docs: How to interface external codes

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3986]

**Comment by ltalirz** [comment]
Note: #4078 adds some content to this section from the old "plugin development" section

**Comment by ltalirz** [comment]
Just a reminder to take into account the discussion on the development guidelines that took place in #4078 , in particular:

 - [ ] make a distinction between these more demanding guidelines (which could e.g. come towards the end of the howto section) and the part of the howto focussed on the problem at hand https://github.com/aiidateam/aiida-core/pull/4078#discussion_r427174042
 - [ ] check whether the formulation on reproducibility can be clarified https://github.com/aiidateam/aiida-core/pull/4078#discussion_r427319416
 - [ ] check whether the formulation on trying not to limit the scope of the plugin can be clarified https://github.com/aiidateam/aiida-core/pull/4078#discussion_r427324764

**Comment by ramirezfranciscof** [comment]
@ltalirz So, I read the comments but I'm not sure exactly what you would expect me to incorporate from those into this howto. So I'm trying to focus as much as possible into doing a minimalistic base that allows you to get a code wrapped, but most of the options (and thus correct usage of features) would be on the `Topics/Processes/Usage`, no? (ex-[this](https://aiida.readthedocs.io/projects/aiida-core/en/latest/working/processes.html))

**Comment by ltalirz** [comment]
> I'm trying to focus as much as possible into doing a minimalistic base that allows you to get a code wrapped

I think that's absolutely the right approach.
Once you're done, you can then decide what to do with the design guidelines that currently reside in this section (whether to keep them as an "addendum" to the howto or whether to move it somewhere else0

**Comment by sphuber** [comment]
Fixed in PR #4093
