### ISSUE TITLE
Docs: How to organize data - Group path

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#3997]
This will describe the new functionality and already has an open PR #3952

**Comment by chrisjsewell** [comment]
What is the general aim/scope of this how-to?

**Comment by sphuber** [comment]
The scope is quite broad and we might want to split this up in a critical-blocking issue and a future one. As I see it, this will discuss the `Group` and its basic functionality, with then a more advanced how-to on how they can be used efficiently, giving some real examples. Then there would be a section on the `GroupPath`. Finally, the more advanced section. that is not pressing now and we could break off into a separate issue, is to describe the new functionality of subclassing `Group`.

**Comment by chrisjsewell** [comment]
Just to note this relevant on-hold PR #3952
