### ISSUE TITLE
Docs: How to configure your installation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4001]

**Comment by bosonie** [comment]
I would like to comment here.
I never understood why in the documentation the "installation" part was before the "Configure AiiDA" part. For me it seems more logic the opposite. I want to take actions to "Isolate AiiDA environments" before to set up a new profile. Of course the part " Using AiiDA in Jupyter" is instead better after the installation

**Comment by sphuber** [comment]
Fair point, and I myself also first configure the environment before doing the actual install. But that is because we are more experienced AiiDA users. However, the installation should also be accessible for beginning users and we fear that if we start with too much information about virtual environments, configuration, multiple profiles and what have you, we are going to scare off beginning users. Since these configuration tricks are more advanced options, they will be somewhere else in the documentation. We can however of course think to put a link somewhere in the beginning so it is easy to find for those who _do_ want to configure early on. As you see, it is a bit a tradeoff between simplicity and completeness for the different users on the spectrum

**Comment by bosonie** [comment]
The creation of a virtual environment (using virtualenv) is the first step of the installation. As a first step of the AiiDA profile setup I would add the suggestion to insert the two lines:

    export AIIDA_PATH='~/.virtualenvs/aiida2'  # use .aiida configuration in this folder
    eval "$(_VERDI_COMPLETE=source verdi)"  # e.g. set up tab completion

in the activate file. This would be enough to "enforce" a good practice in beginner users, but also to remind to expert users that this is the moment to configure few stuff if wanted. The `AIIDA_PATH` details might stay in another part of the documentation.
Just my suggestion of course, I know you'll do a great job.

**Comment by sphuber** [comment]
Thanks for the suggestion. We are rewriting the documentation now and we will consider it. We are thinking of suggesting to use conda to install (in which case you don't need to manually create an environment) as it works well across all operating systems and installs the services, like postgres and rabbitmq.

**Comment by giovannipizzi** [comment]
@sphuber I'm going to commit my changes to the rest of the file soon

**Comment by giovannipizzi** [comment]
@sphuber also maybe it's easier if I assign to myself the rest of the issues of this specific section of the how-to? Let me know if this is ok, or if you already started working on them (this would be this issue, #4000, and #4005

**Comment by sphuber** [comment]
For #4000 I actually started working, PR has been already open since few days. That's also why I put it in the "in Progress" column of the project. #4005 is all yours, I never assigned myself

**Comment by giovannipizzi** [comment]
Perfect thanks! What about this PR?

**Comment by sphuber** [comment]
@giovannipizzi this also already has an open PR #4068

**Comment by sphuber** [comment]
Fixed in PR #4068
