### ISSUE TITLE
Docs: How to update your installation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4003]

**Comment by chrisjsewell** [comment]
Note that in #4060 a brief "Updating aiida-core" section has been added https://25-145482568-gh.circle-artifacts.com/0/html/intro/installation.html#updating-aiida-core. This how-to should link to that, or possibly even that section can be removed, when this how-to is completed

**Comment by sphuber** [comment]
Fixed in PR #4074
