### ISSUE TITLE
Docs: How to register new plugins

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4006]

**Comment by ltalirz** [comment]
@ramirezfranciscof just fyi, I'm working on the plugin part of the docs now, and I think we may want to rename this section of the docs.

If I understand correctly, the section of this issue actually refers to how to "announce" a plugin to aiida-core by registering an entry point for it.
I don't think we need a dedicated section on how to register a plugin on the registry (this will be part of "publishing a plugin package")

**Comment by sphuber** [comment]
> I don't think we need a dedicated section on how to register a plugin on the registry (this will be part of "publishing a plugin package")

The idea for having a "separate" section for this is, that although it will be relatively short and almost trivial, the concept will have to be explained in many places, (anywhere we explain how to sub class and create a plugin) and it would be useful, I think, to have one single location that explains it really well with all necessary details, that all others can reference.

**Comment by ltalirz** [comment]
Yes, I've made some progress on the howto section on plugins, and the structure has changed a little bit. Will ping you in the PR once it's ready.

In particular, this section could be called "Adding/registering an entry point" to distinguish from the process of registering a new plugin package on the AiiDA registry

**Comment by ramirezfranciscof** [comment]
Yeah, the only problem is that perhaps "entry point" is a bit too technical if we wanted to keep titles as jargon-free as possible, right?

**Comment by ltalirz** [comment]
Feel free to comment in #4078  - perhaps something in between could work, like "Registering a plugin through an entry point"

**Comment by csadorf** [comment]
Resolved by #4078 .
