### ISSUE TITLE
Docs: Complete new "Reference" section

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4014]
- [x] move verdi autodoc to "Reference"
- [x] move APIDOC to "Reference"
- [x] read through REST API DOC; transfer according to new schema: 1. Available endpoints and responses; 2. Filtering results; 3. Deployment on a web server

**Comment by csadorf** [comment]
@ltalirz The first two points can be checked, correct?

**Comment by ltalirz** [comment]
all of them can.
