### ISSUE TITLE
Docs: Topic plugins

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4023]

**Comment by csadorf** [comment]
Started in #4078 . @ltalirz What do you think is missing?

**Comment by ltalirz** [comment]
I don't know - I've repurposed all content from the old "plugin development" section; I've just not had a deep thought on what the "plugins" topic should cover and whether something is missing.

From my point of view, we can also close this issue and add more whenever issues arise.

**Comment by csadorf** [comment]
> From my point of view, we can also close this issue and add more content to this section whenever open questions come up.

Sounds reasonable to me.
