### ISSUE TITLE
Docs: Consider using CircleCI for documentation CI

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4028]
One thing that I wanted to briefly mention, although it is most probably not something I expect us to implement, is that currently using CircleCI for documentation integration testing has a big benefit over GitHub Actions, because it can provide HTML build artefacts. For example in: https://github.com/executablebooks/sphinx-panels/pull/3, you get a link that directly opens the newly built documentation for review:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/2997570/80796253-a488b780-8b96-11ea-9b83-9c2a7ec00df7.png">

> I'm wondering whether it would be possible to implement something similar in GitHub actions as well though

Unfortunately at the moment no. I would refer you to this issue, roughly tracking the status of this feature in Github actions: https://github.com/spatialaudio/nbsphinx/issues/361

_Originally posted by @chrisjsewell in https://github.com/aiidateam/aiida-core/pull/4011#issuecomment-622323342_

**Comment by sphuber** [comment]
Fixed in PR #4099

**Comment by sphuber** [comment]
Just as an update: the [upload-artifact action](https://github.com/actions/upload-artifact) now supports uploading an entire directory (as of v2), without zipping it, which was the original behavior. This would make it possible to switch back to GHA from CircleCI, where it not for the fact that the GUI currently does not allow to view the files in the browser. So it still doesn't solve our use case. However, support for that is also being [worked on](https://github.com/actions/upload-artifact/issues/14)

**Comment by chrisjsewell** [comment]
Thanks for the update @sphuber, FYI I opened a separate issue for moving back #4104
