### ISSUE TITLE
Docs: Internals: Data storage (Database schema)

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4035]

**Comment by chrisjsewell** [comment]
FYI, something that may be of use here is this auto-generated UML of the ORM: https://github.com/chrisjsewell/aiida-profiling/blob/master/ipy_screenshots/aiida-db.svg

**Comment by ramirezfranciscof** [comment]
Content to consider:

- https://aiida-core.readthedocs.io/en/v1.1.0/developer_guide/core/modifying_the_schema.html
