### ISSUE TITLE
Docs: Internals: Data storage (Export archive)

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4037]

**Comment by ltalirz** [comment]
To recap the discussion from the docs days wrap-up meeting:

We agree on the terms
 *  "AiiDA archive format" for the format 
 * "AiiDA archive files" or just "AiiDA archives" for the individual archive files

We will try to avoid a nameclash with the upcoming new functionality for moving the outputs of CalcJobs to different storage locations (i.e. ideally not use the term "archive"/"archiving" there).
