### ISSUE TITLE
Docs: Enable general CI checks

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#4050]
Reminder to revert PR #4047 before merging the `docs-revamp` branch.

**Comment by sphuber** [comment]
We should also reenable the `-W` flag on the docs build to turn warnings into errors.

**Comment by chrisjsewell** [comment]
Note the command line in .circleci/config.yml would then be: `sphinx-build -b html -nW --keep-going -d docs/_build/doctrees docs/source docs/_build/html`

When re-enabled, these were the noted reasons for possible failures: https://github.com/aiidateam/aiida-core/pull/4099#issuecomment-633469208
