### ISSUE TITLE
Timeout in unit test `tests.cmdline.commands.test_processes.py:test_pause_play_kill` when running locally

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4051]
The test will timeout:
```
(aiida_dev) sph@bastion:~/code/aiida/env/dev/aiida-core$ pytest tests/cmdline/commands/test_process.py  -sv -k test_pause_play_kill
============================================================================================== test session starts ==============================================================================================
platform linux -- Python 3.7.6, pytest-5.4.1, py-1.5.4, pluggy-0.13.1 -- /home/sph/.virtualenvs/aiida_dev/bin/python3.7
cachedir: .pytest_cache
rootdir: /home/sph/code/aiida/env/dev/aiida-core, inifile: pytest.ini
plugins: regressions-1.0.6, timeout-1.3.4, asyncio-0.10.0, datadir-1.3.1, cov-2.8.1
collected 10 items / 9 deselected / 1 selected                                                                                                                                                                  

tests/cmdline/commands/test_process.py::TestVerdiProcessDaemon::test_pause_play_kill ['/home/sph/.virtualenvs/aiida_dev/bin/verdi', '-p', 'test_profile', 'devel', 'run_daemon']
FAILED

=================================================================================================== FAILURES ====================================================================================================
__________________________________________________________________________________ TestVerdiProcessDaemon.test_pause_play_kill __________________________________________________________________________________

self = <tests.cmdline.commands.test_process.TestVerdiProcessDaemon testMethod=test_pause_play_kill>

    def test_pause_play_kill(self):
        """
        Test the pause/play/kill commands
        """
        # pylint: disable=no-member
        from aiida.orm import load_node
    
        calc = self.runner.submit(test_processes.WaitProcess)
        start_time = time.time()
        while calc.process_state is not plumpy.ProcessState.WAITING:
            if time.time() - start_time >= self.TEST_TIMEOUT:
>               self.fail('Timed out waiting for process to enter waiting state')
E               AssertionError: Timed out waiting for process to enter waiting state
```

Note that this happens both when specifying an explicit test profile as well as when letting the test manager generate one on the fly.

**Comment by giovannipizzi** [comment]
After investigating, the problem is that the process excepts with `ImportError: module 'tests.utils.processes' from identifier 'tests.utils.processes:WaitProcess' could not be loaded`. The reason, after further investigation, is that it actually tries to load `tests` from my local `aiida-quantumespresso` installation. We should move the test Workchain in some module inside `aiida_core`, I think.

**Comment by sphuber** [comment]
Correct, the problem is that the `tests` module is not in the `PYTHONPATH` and so the daemon cannot load the process class. The problem here is then twofold:
1. We should make sure the `tests` module is in the `PYTHONPATH`
2. We should pass the current env to the `subprocess` call

For the latter we should change the call:
```
self.daemon_pid = subprocess.Popen(
     self.daemon_client.cmd_string.split(), stderr=sys.stderr, stdout=sys.stdout
).pid
```
into
```
from aiida.cmdline.utils.common import get_env_with_venv_bin
self.daemon_pid = subprocess.Popen(
     self.daemon_client.cmd_string.split(), stderr=sys.stderr, stdout=sys.stdout, env=currenv
).pid
```

**Comment by greschd** [comment]
> 
>     1. We should make sure the `tests` module is in the `PYTHONPATH`

We also need to make sure it's at the _start_ of `sys.path`, to make sure it doesn't get shadowed by another module that might be named `tests`. From the description, I think this might have been the case for Giovanni.

**Comment by sphuber** [comment]
@greschd do you know of a nice way to add a test module at the beginning of `pytest` and remove it at the end. Ideally this messing with `PYTHONPATH` is automatic and undoes the changes after the tests have completed, so that it cannot mess with other programs running in the environment

**Comment by greschd** [comment]
I don't know a ready-made solution, but I've also never searched for it. Maybe the pytest monkey-patching can be used in some way.

What I find a bit curious is that looking at [the import logic of pytest](https://docs.pytest.org/en/latest/pythonpath.html), it _should already_ be prepending the root to ``sys.path``. Maybe the reason it's still shadowed is that it was already in ``sys.path`` (because of the editable install), but not at the first position.

**Comment by sphuber** [comment]
I think the problem is that it is prepending the tests module path, however, this only applies to the current process. Once we spawn a subprocess, that will have the default path. So we would have to foward it to the subprocess environment. I have a working solution to fix it and make a PR but not sure if it is too dirty
