### ISSUE TITLE
Callback concept for the progress bar

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4053]
Rather than wrapping generators returned by internal AiiDA functions in `tqdm` progress bars, I suggest to use a `callback` pattern.
The reason is that, in this way, the internal functions can accept a callback with a pre-decided function signature, that they can call during iterations. This callback parameter would be optional, so if the function is called internally without a callback, there is no printed output.
This is important because the function to export nodes, for instance, is an internal AiiDA function.

As a note, instead, the `aiida.cmdline` module is specific on CLI interaction, so there it would be OK to just wrap tqdm.

To give an idea of what I have in mind, here a possible way to implement a callback pattern:

```python
import random
import time
import tqdm
import contextlib
import functools
import sys

@contextlib.contextmanager
def tqdm_callback():
    def _progress_callback(tqdm_instance, new_processed, total=None):
        if total is not None:
            tqdm_instance.clear()
            tqdm_instance.total = total
            tqdm_instance.refresh()
        if new_processed is not None:
            tqdm_instance.update(new_processed)

    with tqdm.tqdm(total=9e9) as progressbar: # Large number to be later updated, as suggested in tqdm readme
        yielded_function = functools.partial(_progress_callback, progressbar)
        yielded_function.progressbar = progressbar # In this way we make it easy to access it, e.g. for printing
        yield yielded_function

def slow_iteration(num_iter=1000, max_time_per_iter=0.01, callback_every = 1, progress_callback=None):
    def printer(string):
        if progress_callback:
            progress_callback.progressbar.write(string)
        else:
            print(string, file=sys.stderr)

    if progress_callback:
        # Set num_iter
        progress_callback(None, num_iter)

    new_process_count = 0
    for i in range(num_iter):
        time.sleep(random.random()*max_time_per_iter)
        # Call callback with current iteration and total iterations
        if progress_callback:
            if new_process_count % callback_every == 0:
                progress_callback(new_process_count)
                new_process_count = 0
                printer('currently at {}/{}'.format(i, num_iter))
            new_process_count += 1

    if progress_callback and new_process_count:
        progress_callback(new_process_count)

if __name__ == "__main__":
    with tqdm_callback() as callback:
        slow_iteration(num_iter=10, max_time_per_iter=0.1, progress_callback=callback, callback_every=2)
```

In particular, `with tqdm_callback() as callback:` would be in the `aiida.cmdline` module, while the additional logic in `slow_iteration` would be added to the function to export AiiDA nodes.

**Comment by giovannipizzi** [comment]
I suggest anyway to merge #3599 first, and then change the pattern

**Comment by chrisjsewell** [comment]
Maybe I am being naieve here, but why does this have to be so complicated?
Why not just use:

```python
from functools import partial

def export():
	progress_context = partial(tqdm, bar_format=BAR_FORMAT) # or anything with the same signature
	collect_data(progress_context)
	write_data(progress_context)

def collect_data(progress_context):
    with progress_context(desc="do somthing", total=10) as pbar:
       for i in range(10):
          sleep(0.1)
          progress_bar.set_description_str("do something else", refresh=False)
          pbar.update()
```

Then instead of having to do all this logic with `progress_callback=None`, or the current use of `disable=silent`, just create a null version:

```python
class NullProgressBar:
   def update(self, *args, **kwargs):
      pass
   def set_description_str(self, *args, **kwargs):
      pass

@contextmanager
def null_context(*args, **kwargs):
   yield NullProgressBar()

def export(silent):
  if silent:
    progress_context = null_context
  else:
    progress_context = partial(tqdm, bar_format=BAR_FORMAT)
```

This also makes it easier for testing because you can e.g. pass `write_data` a mock `progress_context` and check how it was called.


I really don't get why we need a singleton as well, is there a particularly big cost to closing a tdqm bar and making a new one?

**Comment by chrisjsewell** [comment]
implemented in https://github.com/aiidateam/aiida-core/pull/4504 and works fine 😄

**Comment by chrisjsewell** [comment]
The progress bar implementation has now been completely rewritten in #4504 (and the original implementation of #3599 removed in #4510)
