### ISSUE TITLE
Docs: overlapping boxes

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#4056]
Just decided to have a look at the in-progress docs revamp -- looks very nice!

I did find the following overlapping boxes, when the window is made quite narrow:

![image](https://user-images.githubusercontent.com/5692808/81280785-486fd880-9059-11ea-8c06-53d2053a9ccd.png)

The `conda` box also doesn't fold its text when the window becomes too narrow - while the `pip` box does. I'd guess this is a CSS issue.

**Comment by csadorf** [comment]
Thank's for reporting! We are aware and this issue might be a duplicate, but I couldn't find another issue, so let's keep track of this here.

@chrisjsewell I've assigned you to this, I hope that's ok.

**Comment by chrisjsewell** [comment]
Oh yeh this has all been fixed and improved in the new sphinx-panels version: https://sphinx-panels.readthedocs.io, which I am going to roll out to here

**Comment by csadorf** [comment]
Awesome!

**Comment by chrisjsewell** [comment]
FYI its looking like pandas is also going to use `sphinx-panels` (https://github.com/executablebooks/sphinx-togglebutton/issues/11#issuecomment-625730694), so we will quite literally be achieving the original goal of mimicking pandas intro style lol
