### ISSUE TITLE
update AUTHORS.txt

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4057]
- [x] add marnik to aiida team
- [x] move chris from contributors to aiida team

to do together with updating the changelog for next release

**Comment by sphuber** [comment]
Addressed in the branch [`release/1.3.0`](https://github.com/aiidateam/aiida-core/tree/release/1.3.0) which will be merged and released soon

**Comment by sphuber** [comment]
Fixed in PR #4211
