### ISSUE TITLE
LSF scheduler requires "num_machines" to be not specified

### ISSUE THREAD

**Issue by eimrek** [aiidateam/aiida-core#4061]
Hi, you can see here: 

https://github.com/aiidateam/aiida-core/blob/6220e85578a1e0e30617cbf860f0fbd24e66add4/aiida/schedulers/plugins/lsf.py#L134-L136

that the LSF scheduler gives an error when `num_machines` is specified in the `metadata.options.resources` dictionary. However, in the calcjob resource validator we get an error, when `num_machines` is NOT defined:

https://github.com/aiidateam/aiida-core/blob/6220e85578a1e0e30617cbf860f0fbd24e66add4/aiida/engine/processes/calcjobs/calcjob.py#L87-L88

Up to now, I have just commented out the LSF exception and everything seems to work, but to my knowledge it's true that in LSF you can't really give that number of machines as input, just the number of processes and the `num_machines` in this case does nothing. Therefore, perhaps conceptually it would be better to change the calcjob `validate_resources`.

**Comment by greschd** [comment]
Thanks for the report @eimrek! I think this is a known issue, see #3887. 

I'm not sure if there is a known workaround, besides patching the code.

**Comment by greschd** [comment]
I'm closing this as a duplicate, and changed the priority of #3887 to "important".

**Comment by eimrek** [comment]
Whoops! didn't notice! thanks @greschd
