### ISSUE TITLE
aldjemy version outdated

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4073]
We're currently using aldjemy 0.9.x in AiiDA, while 0.10 has been out since a while.

Furthermore, even the latest version 0.10.1 is actually [incompatible](https://github.com/aldjemy/aldjemy/issues/90) (aldjemy tests failing) with django >= 2.2 (we are using 2.2 in aiida).

We should monitor https://github.com/aldjemy/aldjemy/issues/90 and decide how to proceed.

**Comment by sphuber** [comment]
Pinging @csadorf

**Comment by csadorf** [comment]
Thank's for letting me know, I'll investigate.

**Comment by ltalirz** [comment]
As discussed in https://github.com/aldjemy/aldjemy/issues/90 the breaking changes seem to have been limited to the django test infrastructure.
Might still make sense to check whether it makes sense to upgrade to adjemy 10.x , but it looks like there is no urgent problem after all.

**Comment by ltalirz** [comment]
Looking through the [aldjemy commits](https://github.com/aldjemy/aldjemy/commits/master) there seem to be no critical bug fixes.

As long as we encounter no issues related to aldjemy, there is no need to upgrade. Once we do, we can. Closing.
