### ISSUE TITLE
Installation guide correction

### ISSUE THREAD

**Issue by benjamindjensen** [aiidateam/aiida-core#4076]
Under the "AiiDA profile setup" heading in the installation guide at:
https://aiida.readthedocs.io/projects/aiida-core/en/latest/install/installation.html

the verdi quicksetup takes a profile name argument, resulting in the following error:
"Error: Got unexpected extra argument"

the manual should just read:
`verdi quicksetup`
instead of 
`verdi quicksetup <profile_name>`

**Comment by sphuber** [comment]
Thanks for the report @benjamindjensen , we happen to just be working on a great documentation reorganization and rewrite and we will make sure to include it. @chrisjsewell I guess this goes into the PR you are working on. Could you please make sure this is included

**Comment by chrisjsewell** [comment]
Will do 👍. It will be addressed in #4060

**Comment by csadorf** [comment]
Fixed in #4060.
