### ISSUE TITLE
Update section in docs on generating SSH keys

### ISSUE THREAD

**Issue by ConradJohnston** [aiidateam/aiida-core#4098]
To resolve #3279,  instructions were added on how to generate an SSH key in a legacy format in order to appease a limitation in the Paramiko library.  However, this [limitation](https://github.com/paramiko/paramiko/issues/1548) is now fixed in Paramiko 2.7.1, so the docs need tweaked again, and perhaps also the dependencies.

**Comment by giovannipizzi** [comment]
Indeed! Pinging @csadorf both for the dependencies, and for the docs. If the limitation indeed is removed, I would vote to depend on paramiko >= 2.7.1 and drop the requirement on the SSH key format

**Comment by csadorf** [comment]
I agree with @giovannipizzi , the ability to use non-legacy SSH key formats is a strong enough incentive to increase our minimal required version for paramiko with the next minor release. I'll create a related PR for the dependency and docs.

**Comment by ltalirz** [comment]
This was fixed in https://github.com/aiidateam/aiida-core/pull/4222

**Comment by ltalirz** [comment]
P.S. I just checked - it is already in paramiko 2.7.0 (which is our minimal requirement). If there are reasons to increase the minimal requirement further, let us know.
