### ISSUE TITLE
Move doc builds back to GitHub Actions (when artefacts supported)

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4104]
In #4099, the docs action will be replaced by a build with CircleCI.
When/if GitHub Actions allows for storage of (unzipped) artefacts, we can move back to this action

**Comment by chrisjsewell** [comment]
Note this essentially waiting on https://github.com/actions/upload-artifact/issues/14

**Comment by chrisjsewell** [comment]
Note there is another option that I've just been made aware of, to use RTD as the CI runner: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

Possible cons are that I'm not sure about build limits, and also you would need to make RTD fail on errors, as I discuss here:
https://github.com/executablebooks/MyST-Parser/issues/177

**Comment by csadorf** [comment]
> Note there is another option that I've just been made aware of, to use RTD directly as the CI runner: https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

That's interesting and might be worthwhile to test.

> Possible cons are that I'm not sure about build limits, and also you would need to make RTD fail on errors, as I discuss here:
> [executablebooks/MyST-Parser#177](https://github.com/executablebooks/MyST-Parser/issues/177)

That is an issue that maybe could be fixed on the side of RTD? Surely this would be a problem for many users of that service.

**Comment by chrisjsewell** [comment]
Well I'm implementing in https://github.com/aiidateam/aiida-tutorials/pull/228, so we can use that as a testbed 😄

**Comment by chrisjsewell** [comment]
> maybe could be fixed on RTD side?


https://github.com/readthedocs/readthedocs.org/issues/7240
