### ISSUE TITLE
Check for missing and add useful cross-links.

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#4120]
After merging all sections, we should add cross-links that were previously hard to identify.

**Comment by csadorf** [comment]
@sphuber I was actually trying to imply that this issue cannot be addressed before the other PRs are merged, not that this is blocking.

**Comment by sphuber** [comment]
Ah ok, but that is not what the `pr/blocked` label is intended for. It is to label PRs that are blocked from being merged, as written in the label description.

**Comment by sphuber** [comment]
Did you still want to do this before the merge into `develop` @csadorf ?

**Comment by csadorf** [comment]
@csadorf No, it will have to wait.

**Comment by chrisjsewell** [comment]
Can this issue now be closed?
