### ISSUE TITLE
Docs: How to configure remote computers

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4123]
"Configuring remote computers" should be a subsection of "How to run external codes".

**Comment by ltalirz** [comment]
We just had a question on the AiiDA mailing list on how to configure a code on a remote machine, and it appears there is not a single place in the documentation where we explain how to set up a remote computer.

This needs to be expedited.

**Comment by ltalirz** [comment]
I've assigned myself for the moment, since I am anyhow revising the "How to run external codes" section, but since this howto already has substantial length, I'm actually not convinced we should explain in this section how to set up remote computers and codes.

How about creating a "How to run on remote computers" (we can always link there from "how to run external codes").
@csadorf @sphuber @ramirezfranciscof 

Happy if anybody would be willing to help with this

**Comment by csadorf** [comment]
> Since this is such a major use case, how about creating a "How to run on remote computers" (we can always link there from "how to run external codes")?

I see some risk for duplication (which we can tolerate to some extent as long as there is a different focus), but I'm generally in favor of that. What sub-sections would you envision for it to contain?

- Configuring a remote computer
- Configuring a remote code
- Configuring a transport *?*
- *What else?*

**Comment by sphuber** [comment]
Just wanted to note that we should be a bit careful with the word "remote". Configuring a code on your localhost is just as valid a use-case and actually shares the vast majority of steps. Just the `verdi computer configure` step is different. Whatever we write, I think it is important to note that from AiiDA's perspective, the localhost, is also "just" a computer.

> Configuring a transport ?

What do you mean with this? Using existing transport plugins is trivial as it is just one field to fill in during `verdi computer setup`. Or did you mean "how to create a custom transport plugin"?

**Comment by sphuber** [comment]
> Good point, but I think the idea is to keep the top-level section as goal- and problem-oriented as possible so from a user perspective it might make sense.

That's fair enough, but we should also not start to fill in use-cases. We might think that the majority want to run on a remote computer, but maybe a lot of people just want to run on their own machine where AiiDA is running. Removing the "remote" from the titles caters to both and doesn't make it less clear I feel

**Comment by ltalirz** [comment]
> Removing the "remote" from the titles caters to both and doesn't make it less clear I feel

The reason I put it there is that the tutorial already explains how to set up the localhost computer.
However, I think it's fine to duplicate a bit of information here (which will anyhow be the case).

**Comment by ltalirz** [comment]
Fixed by @chrisjsewell in https://github.com/aiidateam/aiida-core/pull/4216
