### ISSUE TITLE
Docs: final isolated problems and touches before merging revamp

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4133]
List of minor things to fix:

- [x] `intro/about.rst` line 20 malformed link
- [x] `howto/codes.rst` line 64 the link is malformed
- [x] All the items of #3874 
- [x] Fix all incorrect `include` statements
- [x] Hide all remaining stubs with links to outstanding issues
- [x] `intro/tutorial.rst` line 359 `Out[6]:` should be `Out[4]:`
- [x] `intro/tutorial.rst` line 504 update `MultiplyAddWorkChain` to `develop` version

**Comment by csadorf** [comment]
Added "Hide all remaining stubs with links to outstanding issues"

**Comment by mbercx** [comment]
Added some minor issues related to `intro/tutorial.rst`.

**Comment by sphuber** [comment]
Fixed in PR #4135
