### ISSUE TITLE
Graphviz in notebooks may be cropping SVGs

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4139]
In #4138, when I re-run the Jupyter Notebook to in the notebook, it didn't seem to adhere to the size that you can set for the output with e.g.

```
graph = Graph(graph_attr={"size": "8,8!", "rankdir": "LR"})
```

and unless you set the size larger it just crops the output.

This was fine when I initially wrote it, so I don't know if it's just a local issue for me, or a change in a dependency (python-graphviz or graphviz itself?)

**Comment by chrisjsewell** [comment]
Confirmed that this is just a local issue

**Comment by greschd** [comment]
Hm, I'm seeing the same behavior, also when using `.render(format='svg')` to save as SVG. 

Easily fixed on the exported file by removing the `viewBox` attribute from the SVG header, but it still feels like a bug.

@chrisjsewell did you find a workaround for the local issue?
