### ISSUE TITLE
Support tornado >=6.0 for the least JupyterLab >=2.0

### ISSUE THREAD

**Issue by dou-du** [aiidateam/aiida-core#4145]
The least JupyterLab needs tornado > 6.0. While the aiida-core needs tornado < 5.0. 
Is it possible to support the newest version of the tornado package for JupyterLab (>=2.0) ? Thanks.

**Comment by sphuber** [comment]
Hi @dou-du , this is a known problem and as marked in the original issue #3184 we are working on solving this incompatibility. We should have a compatible version somewhere this summer hopefully. I will be closing this issue as it is as duplicate.
