### ISSUE TITLE
`BaseRestartWorkChain`: `unhandled_failure` flag reset

### ISSUE THREAD

**Issue by lorisercole** [aiidateam/aiida-core#4153]
Hello,
I feel the `unhandled_failure` flag should be reset to `False` once a calculation process finished successfully or it was handled correctly, like the comment says. Am I wrong?
@sphuber 
https://github.com/aiidateam/aiida-core/blob/f112cd9d43553bad129550c1331e5208a5362d83/aiida/engine/processes/workchains/restart.py#L241-L243

**Comment by sphuber** [comment]
You are absolutely correct. This behavior isn't tested yet, so it wasn't caught. Thanks for the heads up. I will push a fix and see if I can actually come up with a test.

**Comment by lorisercole** [comment]
Hey Seb, I think I found another bug.
The variable returned here should be `last_report.exit_code`:
https://github.com/aiidateam/aiida-core/blob/a67a625f930b4649b09ba63a75d1c184fa5b9e94/aiida/engine/processes/workchains/restart.py#L258

**Comment by sphuber** [comment]
Great work Mr. Holmes! :wink:  it should indeed fail if `last_report` is set and the last handler returns `None`. In this case it should trigger an `AttributeError` as `None` does not have `exit_code`. This can happen if at least one handler return a process report with `do_break=False` and then at least one other handler is called that returns `None`. Just making a note of this scenario for myself here. Will move this to another issue and create another PR. Thanks a lot for reporting these!

**Comment by lorisercole** [comment]
>  it should indeed fail if `last_report` is set and the last handler returns `None`. In this case it should trigger an `AttributeError` as `None` does not have `exit_code`. This can happen if at least one handler return a process report with `do_break=False` and then at least one other handler is called that returns `None`.

Yes that's what happened in my work chain! :)
I had a handler that returned `ProcessHandlerReport(False)`

One additional question, to be sure I understand: 
in a process handler it is ok to return `None`, for example if a condition is not met, right?

Example - here:
https://github.com/aiidateam/aiida-quantumespresso/blob/5e06a62756cdbae23f287a7ac9abe51a2a0492c6/aiida_quantumespresso/workflows/pw/base.py#L323-L352
The `return` returns `None` because occupations are fixed.
Also, if the `try` does not catch any exception, a `None` will be returned, correct?

**Comment by sphuber** [comment]
> in a process handler it is ok to return `None`, for example if a condition is not met, right?

Yes, returning `None` is the default and means "nothing special to report". If you *do* return something, you are either saying "I found a problem, but it is ok, I fixed it, so just restart" or "I found a problem and there is nothing else we can do, just abort"

**Comment by lorisercole** [comment]
Ok now it is clear. Thanks!!
