### ISSUE TITLE
ModuleNotfoundError for plugins when using submit, works fine with run

### ISSUE THREAD

**Issue by Zausinator** [aiidateam/aiida-core#4178]
### Describe the bug

Dear AiiDA team,

Currently I am working on a plugin that allows us to submit python codes to run on remote computers. When I test the code locally using aiida.engine.run, the code runs without issue, producing the wanted result in the directory of the aiida computer. When I switch to the aiida.engine.submit command however, I get a Modulenotfounderror, very similar to the issue described here:

https://github.com/aiidateam/aiida-core/issues/3624

This error also arises when using the aiida-diff demo plugin.

I am unsure what the suggestion is to solve this issue.

Thank you for your help!

Nicolas Bergmann

### Steps to reproduce

1. Download aiida-diff demo from https://github.com/aiidateam/aiida-diff
2. $ reentry scan
3. $ pip install -e aiida-diff/
4. change from run to submit in examples/example_01.py
5. error can be found by Verdi process report 'pk_node'

### Your environment

- Linux Operating System
- Python 3.8.3
- aiida version 1.2.1

**Comment by sphuber** [comment]
Hi @Zausinator , can you share the exact stacktrace that is reported by `verdi process report`? Also make sure you have read [this FAQ](https://aiida-core.readthedocs.io/en/latest/howto/faq.html#why-would-a-process-that-runs-fine-locally-raise-an-exception-when-submitted-to-the-daemon) on the documentation, which might address your problem

**Comment by Zausinator** [comment]
![aiida_bug](https://user-images.githubusercontent.com/44521403/84769056-8c99b580-afd5-11ea-9ff1-763a25200bf2.JPG)


Ah perfect, the FAQ advice did the trick! Thanks!

**Comment by Zausinator** [comment]
![aiida_bug](https://user-images.githubusercontent.com/44521403/84769159-af2bce80-afd5-11ea-9bf4-f6d0264fdf78.JPG)


Here the original error message

**Comment by Zausinator** [comment]
The advice in the FAQs did the trick! 

Thank you!
