### ISSUE TITLE
Tab completion not working for `CalcJob.res`

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4184]
### Describe the bug

`calcjob.res.<TAB>` should complete the keys of the output dictionary, but it doesn't.

### Steps to reproduce

1. load a CalcJobNode that uses a plugin that supports the `.res` method and has parsed results
2. Try to type `calcjob.res.` and press TAB twice. Nothing happens.

### Expected behavior

Tab completion should work

### Additional context

I addressed this in #3985 for `.inputs`, `.outputs` but I fear I forgot about `.res`.

**Comment by sphuber** [comment]
Same here as for #4185 , if this is supposed to go in `1.3.0` which needs to be released early next week, who will take care of this one? I notice you haven't assigned yourself to this one, does that mean you won't have the time to fix it? @ramirezfranciscof maybe this is a good one for you?

**Comment by ramirezfranciscof** [comment]
Sure, I can take a look at it at the begining of next week and we can discuss any trouble on wednesday!

**Comment by sphuber** [comment]
I don't think we should let it wait that long. The plan was to release 1.3.0 on Monday or Tuesday at the latest, which means that we cannot wait with critical blocking PRs until after.

**Comment by ramirezfranciscof** [comment]
Ah, sorry, I misinterpreted that you were proposing the first issue to tackle for the wednesday meetings.
