### ISSUE TITLE
Formatting of the exporting progress bar is broken on Ubuntu

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4197]
I just ran a rather large export of one of my databases and encountered the recently introduced progress bar and have some questions on the design. The progress bar is quite verbose and feel that this is counterproductive. For example, when exporting node repositories, for each node the description is updated causing a new line to be printed:
```
Exporting repository - UUID=46168d25       0.4%|▋   | 308/7374
Exporting repository - UUID=2c4e6805       0.4%|▋   | 312/7374
Exporting repository - UUID=8fc8bd38       0.4%|▋   | 316/7374
Exporting repository - UUID=3048d46d       0.4%|▋   | 320/7374
Exporting repository - UUID=9c165cf0       0.4%|▋   | 323/7374
Exporting repository - UUID=0e13d4c7       0.4%|▋   | 327/7374
Exporting repository - UUID=430d60f7       0.4%|▋   | 331/7374
Exporting repository - UUID=e6cbe409       0.5%|▋   | 335/7374
Exporting repository - UUID=a04cfdad       0.5%|▋   | 339/7374
Exporting repository - UUID=92eb8e99       0.5%|▋   | 344/7374
Exporting repository - UUID=909e2030       0.5%|▋   | 348/7374
Exporting repository - UUID=49e693d5       0.5%|▋   | 352/7374
Exporting repository - UUID=6d268842       0.5%|▋   | 356/7374
Exporting repository - UUID=26b1fcc6       0.5%|▋   | 360/7374
Exporting repository - UUID=d118348e       0.5%|▋   | 364/7374
Exporting repository - UUID=a5748d97       0.5%|▊   | 369/7374
Exporting repository - UUID=28633f41       0.5%|▊   | 373/7374
Exporting repository - UUID=6c910c1c       0.5%|▊   | 377/7374
Exporting repository - UUID=dc76a026       0.5%|▊   | 381/7374
Exporting repository - UUID=148a5c4f       0.5%|▊   | 385/7374
Exporting repository - UUID=69172a50       0.5%|▊   | 389/7374
Exporting repository - UUID=03207ea8       0.5%|▊   | 393/7374
Exporting repository - UUID=15b65546       0.5%|▊   | 397/7374
```
In my view, this goes against the concept of the progress bar that remains on a single line and gets update each time. The solution would be to simply remove the description update. I don't think having the UUID of the currently exported node is very useful.

Another example occurs right in the beginning:
```
Collecting chosen entities                 5.0%|███████▌                                                                                                                                             | 42
Collecting chosen entities                13.3%|███████████████████▋                                                                                                                         
Collecting chosen entities                22.5%|█████████████████████████████████▎                                                                                             
Collecting chosen entities                31.7%|██████████████████████████████████████████████▊                                                                   
Collecting chosen entities                40.8%|████████████████████████████████████████████████████████████▎                                       
Collecting chosen entities                50.0%|██████████████████████████████████████████████████████████████████████████             
Collecting chosen entities                59.3%|████████████████████████████████████████████████████████████████████████████████
Collecting chosen entities                68.3%|████████████████████████████████████████████████████████████████████████████████
Collecting chosen entities                77.6%|████████████████████████████████████████████████████████████████████████████████
Collecting chosen entities                86.8%|████████████████████████████████████████████████████████████████████████████████
Collecting chosen entities                95.7%|████████████████████████████████████████████████████████████████████████████████
Getting provenance and storing links ... 100.0%|████████████████████████████████████████████████████████████████████████████████1
```
Why is the line `Collecting chosen entities` repeated so many times?
It also seems that the solid bars fill the entire space of the terminal, even though there are numbers that come after it, that therefore seem to kind of get squashed?

Pinging @CasperWA and @ltalirz for comments on reasoning behind the design

**Comment by CasperWA** [comment]
The main reason behind this is when the export fails. In these cases it would be very good to have the specific UUID to understand which Node is "bad".
At least that's my reasoning behind this combined with the experience of handling/fixing bad export archives for users.

**Comment by CasperWA** [comment]
`tqdm` (the package generating the progress bar) uses `/r` and `/n`. If your terminal cannot handle this properly (like, e.g., the GH Actions output terminal) the result will be what you see above with multiple lines, one for each update.

**Comment by CasperWA** [comment]
The numbers at the end is repeated (absolute) information for the (relative) percentages.

**Comment by sphuber** [comment]
> The main reason behind this is when the export fails. In these cases it would be very good to have the specific UUID to understand which Node is "bad".

That is fair enough, but then why not just print the UUID in a warning or exception as soon as a problem crops up. What is the point in printing all of them, even if everything is fine. Your terminal just gets flooded with unnecessary information

> `tqdm` (the package generating the progress bar) uses `/r` and `/n`. If your terminal cannot handle this properly (like, e.g., the GH Actions output terminal) the result will be what you see above with multiple lines, one for each update.

I doubt that is the case, these results come from a normal terminal on linux. I think it comes because you are updating the label in a loop. The same happens for the `click` progress bar and for good reason. It uses carriage returns to update the status by simply redrawing the last drawn line.

> The numbers at the end is repeated (absolute) information for the (relative) percentages.
If you wish to have another format for the progress bar, this can be changed here.

Mostly I would expect the bar not too run over more than one line. That seems like a bug tbh. Not sure if that is in `tqdm` itself or in our application, but the bar pushing onto the next line because it doesn't have enough space, doesn't seem like the intention.

**Comment by CasperWA** [comment]
> > The main reason behind this is when the export fails. In these cases it would be very good to have the specific UUID to understand which Node is "bad".
> 
> That is fair enough, but then why not just print the UUID in a warning or exception as soon as a problem crops up. What is the point in printing all of them, even if everything is fine. Your terminal just gets flooded with unnecessary information
> 
> > `tqdm` (the package generating the progress bar) uses `/r` and `/n`. If your terminal cannot handle this properly (like, e.g., the GH Actions output terminal) the result will be what you see above with multiple lines, one for each update.
> 
> I doubt that is the case, these results come from a normal terminal on linux. I think it comes because you are updating the label in a loop. The same happens for the `click` progress bar and for good reason. It uses carriage returns to update the status by simply redrawing the last drawn line.
> 
> > The numbers at the end is repeated (absolute) information for the (relative) percentages.
> > If you wish to have another format for the progress bar, this can be changed here.
> 
> Mostly I would expect the bar not too run over more than one line. That seems like a bug tbh. Not sure if that is in `tqdm` itself or in our application, but the bar pushing onto the next line because it doesn't have enough space, doesn't seem like the intention.

I have none of these issues you present here in my own setup. At least not when the original PR went in. So I don't know why it crops of for you.
For me it always stays on one line and never duplicates.
But let me try it again using the latest versions of everything...

**Comment by CasperWA** [comment]
> > The main reason behind this is when the export fails. In these cases it would be very good to have the specific UUID to understand which Node is "bad".
> 
> That is fair enough, but then why not just print the UUID in a warning or exception as soon as a problem crops up. What is the point in printing all of them, even if everything is fine. Your terminal just gets flooded with unnecessary information

A reasonable point.
The point of printing all of them, is that normally it shouldn't generate new lines, but stay on the same line, and then it looks "cool" that the UUIDs flashes by, giving the user a feeling of "something's happening", and then when it's stalling on a UUID, you know that it is a heavy Node ... or something. I.e., there is no functional use for it if not errors occur, other than my personal take on a nice UX.

**Comment by CasperWA** [comment]
> > > `tqdm` (the package generating the progress bar) uses `/r` and `/n`. If your terminal cannot handle this properly (like, e.g., the GH Actions output terminal) the result will be what you see above with multiple lines, one for each update.
> > 
> > 
> > I doubt that is the case, these results come from a normal terminal on linux. I think it comes because you are updating the label in a loop. The same happens for the `click` progress bar and for good reason. It uses carriage returns to update the status by simply redrawing the last drawn line.
> > > The numbers at the end is repeated (absolute) information for the (relative) percentages.
> > > If you wish to have another format for the progress bar, this can be changed here.
> > 
> > 
> > Mostly I would expect the bar not too run over more than one line. That seems like a bug tbh. Not sure if that is in `tqdm` itself or in our application, but the bar pushing onto the next line because it doesn't have enough space, doesn't seem like the intention.
> 
> I have none of these issues you present here in my own setup. At least not when the original PR went in. So I don't know why it turns out so badly for you.
> For me it always stays on one line and never duplicates.
> But let me try it again using the latest versions of everything...

UPDATE: I have installed the latest `develop` version and tried to export 41K Nodes. I still don't see this issue of newly created lines, i.e., I believe it is an issue of your terminal. However that said that is still a rather serious issue possibly? One that can be mediated by, e.g., not changing the UUID. However, since you're also seeing this issue for non-changing description labels, I don't see this issue going away for you, instead you'll just have the same number of lines with a static description label, where the new line is generated with every new shift of the progress bar.

The solution then would be to not use `/r` and `/n` but a completely different way of having a progress bar, or maybe something less drastic: Have an easy option to turn off the progress bar, permanently, for an installation?

**Comment by sphuber** [comment]
@CasperWA could you make a quick gif of what it looks like for you? I can try to do the same

**Comment by CasperWA** [comment]
> @CasperWA could you make a quick gif of what it looks like for you? I can try to do the same

Do you know of a quick and painless way to do this in Win 10? 😅

**Comment by sphuber** [comment]
![Peek 2020-06-24 15-33](https://user-images.githubusercontent.com/6992332/85566296-37dae800-b630-11ea-8ccb-3276c37a0664.gif)

Example of the behavior on Ubuntu 18.04. Behavior replicated both in default terminal and in tilix emulator

**Comment by sphuber** [comment]
> Do you know of a quick and painless way to do this in Win 10? sweat_smile

Is that a rhetorical question?

**Comment by CasperWA** [comment]
![cwa_BIG-BLACK-BOX_-__venv_aiida-dev-2020-06-24-15-35-39](https://user-images.githubusercontent.com/43357585/85567277-06165100-b631-11ea-8a04-3f8535984d06.gif)

**Comment by CasperWA** [comment]
> > Do you know of a quick and painless way to do this in Win 10? sweat_smile
> 
> Is that a rhetorical question?

I figurededed it out 🤓

**Comment by CasperWA** [comment]
It seems `tqdm` has an open issue for Debian and Ubuntu: tqdm/tqdm#683

**Comment by sphuber** [comment]
> Edit: The fix in the referenced issue seems to be to downgrade to `tqdm==4.30.0`.
> Can you maybe try to install this one and try again?

Tried, but no dice. Nor with `4.19.4` which was mentioned elsewhere by someone as fixing it for them

**Comment by CasperWA** [comment]
Should we "fix" this momentarily by making it widely accessible to "turn off" the progress bar?

**Comment by greschd** [comment]
Maybe it's https://github.com/tqdm/tqdm/issues/630?

**Comment by sphuber** [comment]
> Maybe it's [tqdm/tqdm#630](https://github.com/tqdm/tqdm/issues/630)?

Don't think so because even in full screen at a terminal of over 3000 pxs wide does it completely overflow

**Comment by CasperWA** [comment]
> > Maybe it's [tqdm/tqdm#630](https://github.com/tqdm/tqdm/issues/630)?
> 
> Don't think so because even in full screen at a terminal of over 3000 pxs wide does it completely overflow

Yeah, the image he puts in the top post seems like the same, but the issue concerns something different I think.
The issue is simply that it doesn't return to the original line and "overwrites", but rather writes to the terminal as if it was "print"ing.

**Comment by sphuber** [comment]
The mystery has been solved. As it turns out the problem was due to a setting of the terminal. For both the default Ubuntu terminal as well as the `tilix` terminal I was using, under the "compatibility" tab of the profile settings, there is the option "ambiguous-width characters" which was set to "wide" instead of "narrow". Now apparently the █ character, that is used by `tqdm` to fill the progress bar _is_ such an ambiguous width character and due to the setting it was being drawn with double the width in my terminal, thus overflowing the bar that was calculated to be the width of the terminal.

This was figured out thanks to tests proposed by @giovannipizzi . First we made sure that the carriage return character `\r` is respected by printing the string `print('a\nb\rc\nd\re')` which should print:
```
a
c
e
```

Then we pasted the following in the terminal
```
██████████
0123456789
```
This should give the same length for both, as there are 9 unicode symbols, but in my terminal it was twice as wide. This led us to the answer.

**Comment by CasperWA** [comment]
> The mystery has been solved. As it turns out the problem was due to a setting of the terminal. For both the default Ubuntu terminal as well as the `tilix` terminal I was using, under the "compatibility" tab of the profile settings, there is the option "ambiguous-width characters" which was set to "wide" instead of "narrow". Now apparently the █ character, that is used by `tqdm` to fill the progress bar _is_ such an ambiguous width character and due to the setting it was being drawn with double the width in my terminal, thus overflowing the bar that was calculated to be the width of the terminal.
> 
> This was figured out thanks to tests proposed by @giovannipizzi . First we made sure that the carriage return character `\r` is respected by printing the string `print('a\nb\rc\nd\re')` which should print:
> 
> ```
> a
> c
> e
> ```
> 
> Then we pasted the following in the terminal
> 
> ```
> ██████████
> 0123456789
> ```
> 
> This should give the same length for both, as there are 9 unicode symbols, but in my terminal it was twice as wide. This led us to the answer.

Amazing! Great work @giovannipizzi and @sphuber :)
