### ISSUE TITLE
Improve aiida.common.Folder objects

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida-core#42]
Originally reported by: **Giovanni Pizzi (Bitbucket: [pizzi](https://bitbucket.org/pizzi), GitHub: [giovannipizzi](https://github.com/giovannipizzi))**

----------------------------------------

* Better method names: 
  * `get_content_list`: use `listdir` as in `os`
  * `insert_path`: e.g. `put`
  * `remove_path`: e.g. `remove`
* Better defaults:
  *  `get_abs_path` should by default take `relpath='.'`
* `get_file_content`:
  * add in `aiida.common.Folder` because it will need to do different things for different storage backends
 * deprecate `get_file_content` in `aiida.orm.folder.FolderData`

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/42

**Comment by ltalirz** [comment]
Deleted "* Think about folders with internal lock?" (no usecase).
Deleted "* allow replacewithfolder object to accept a Folder object, and not only an absolute path" (will be done only if needed)

**Comment by giovannipizzi** [comment]
Adding to 2.0 so we either decide to fix the API, or we close this issue
