### ISSUE TITLE
Process builders and `?` interactive properties

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4207]
### Describe the bug

According to the tutorial, doing `builder.settings??` (here I am using `settings`, but replace with any valid input) should return information on the input. Instead, it prints the following:
```python
In [5]: builder.settings??                                                      
Type:        property
String form: <property object at 0x1476d0176ea8>
Source:     
# builder.settings.fget
def fgetter(self, name=name):
    return self._data.get(name, None)
```

### Steps to reproduce

In the verdi shell:
```python
code = load_code("<YOUR CODE NAME>")                                 
builder = code.get_builder()   
builder.settings??
```

### Expected behavior

I think it used to print information on the inputs (if it was required etc.)
Note that with one question mark only 

### Your environment

- Operating system [e.g. Linux]: Ubuntu, Quantum Mobile 20.06
- Python version [e.g. 3.7.1]: 3.6.9
- aiida-core version [e.g. 1.2.1]: 1.3.0 release branch

### Additional context

Note that with a question mark only it has some of the relevant information:

```python
builder.settings?                                                       
Type:        property
String form: <property object at 0x1476d0176ea8>
Docstring:   {"name": "settings", "required": "False", "valid_type": "<class 'aiida.orm.nodes.data.dict.Dict'>", "help": "Optional parameters to affect the way the calculation job and the parsing are performed.", "non_db": "False"}
```

Mentioning @sphuber and @ramirezfranciscof (Francisco, was this working when you tested the tutorial last week?)

**Comment by sphuber** [comment]
It has always been the case that one should use a single question mark. If the tutorial mentioned double question mark, then that is just a typo. Don't think there is anything to fix here.

**Comment by giovannipizzi** [comment]
Ok. Will adapt the tutorial then, thanks!
