### ISSUE TITLE
Default RabbitMQ installs on Ubuntu can have performance issues

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4215]
Raise by @atztogo on the forum:  https://groups.google.com/forum/#!msg/aiidausers/aK42zE7ACUI/IVyGsbyjCAAJ

> I run AiiDA on ubuntu 18.04 server (64bit). It works, but sometimes,
verdi command (verdi process list, etc) freezes for a few tenths of
seconds. I install RabbitMQ from ubuntu official apt repository, but
postgresql is installed via conda forge. I meet this problem on many
aiida-core versions including v1.2.1 and v1.3.0.

> This problem seems to be solved to install RabbitMQ following the
RabbitMQ official site after purging ubuntu official apt packages (and
'apt autoremove'). I'm not sure if this has been reported before. I
just wanted to report this to ubuntu users. This issue may depend on
upgrading history of ubuntu packages, too.

**Comment by sphuber** [comment]
Closing this as it is likely outdated and not even clear it was really due to the version of RMQ.
