### ISSUE TITLE
Rename verdi code option `--store-in-db`

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#4224]
> I notice that the name `--store-in-db` is not a change of this PR but it seems weird and incorrect. The files are stored in the repository and not the database. I can see how "a user should not have to think about these details", but then why include "db" at all. Anyway, not something we should address here and now. But maybe we should think of a better name. Maybe the two names `--pre-installed` and `--upload` could work, instead of `--on-computer` and `--store-in-db`?

> this choice of name is a bit delicate since there has been quite some confusion about local/remote codes in the past, so any suggestion should be tested on an AiiDA novice, asking them what they associated with that choice of name

_Originally posted by @sphuber in https://github.com/aiidateam/aiida-core/pull/4216/files_

**Comment by sphuber** [comment]
This is part of `verdi code setup` which is deprecated and so no longer relevant
