### ISSUE TITLE
Depreciate `django`

### ISSUE THREAD

**Issue by HaoZeke** [aiidateam/aiida-core#4232]
### Is your feature request related to a problem? Please describe

- Some HPC admins blacklist web-servers
- AiiDA works well without `django` (the `sqlalchemy` backend)

### Describe the solution you'd like

- Make `sqlalchemy` the default
- Allow installations without `django`, but can still be optional, for ease of tinkering

### Describe alternatives you've considered

- As with most human-barriers, a kind SysAdmin can be leveraged to install AiiDA and then remove `django` later

### Additional context

The idea for this came from the historical context Giovanni Pizzi (@giovannipizzi) provided during the AiiDA virtual workshop of 2020.

**Comment by chrisjsewell** [comment]
@HaoZeke it is not necessary that you install Aiida on the HPC though; you would generally have Aiida installed on your own machine, then "communicate" with the HPC *via* SSH (see https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_codes.html#how-to-set-up-a-computer).
Is there an alternative use-case you have where installing on the HPC would be required?

**Comment by HaoZeke** [comment]
No, not off the top of my head. In fact when I think about it, it's probably a good idea to not let users run aiida on the HPC directly, so I'll close this.

Thanks!
