### ISSUE TITLE
Docs: Move up "querying", move down "adding support for custom datatypes"

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4280]
### Describe the current issue

Currently, there is the section "Adding support for custom datatypes" as the second entry, before querying
I advocate that this should be essentially the last section of the section (and maybe even be moved somewhere else?) and Querying should be first (or at worst second after importing - logically you might want to import first, but in practice when you search for the docs you will search much more often how to query rather than how to import that is easy to remember).

### Describe the solution you'd like

I think we should change the order, move the "Adding support" much down, also below the sections like organising and deleting data, and probably also after 'serving data to others', and make sure the query part is first or second.

Pinging @csadorf @ltalirz @chrisjsewell for feedback

(This originated from a user that contacted me and couldn't easily find that section, and more generally the second part of this comment):

> Aiida is on version 1.3, which broke most of the Google results as they return Documentation for 1.2 <https://aiida-core.readthedocs.io/en/stable/restapi/index.html>, which can be viewed cached but can be outdated). The documentation is heavily documented for *running* jobs, but much lighter from what I can find on querying the data in ways that work with your dataset.

(For the first part, I think it's OK, but we should be careful when changing the RST file names - we should try to reduce to the minimum now I think to avoid breaking links)

**Comment by csadorf** [comment]
I'm in favor of moving "Adding support for custom data types" right below "Deleting data".

**Comment by ramirezfranciscof** [comment]
I can't find the sections described here, was this exclusively a problem with the old docs?

**Comment by ltalirz** [comment]
@ramirezfranciscof here you go: https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/data.html#adding-support-for-custom-data-types
