### ISSUE TITLE
Docs: Missing How to define exit codes

### ISSUE THREAD

**Issue by pzarabadip** [aiidateam/aiida-core#4283]
### Describe the current issue

When I was browsing the documentations, more specifically, in the following section:

https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/workflows/usage.html?highlight=exit%20codes#topics-workflows-usage-workchains-aborting-and-exit-codes

I realized that one of the links is broken. The broken link should refer to `how to define exit codes` but it does not work.

which is also broken in other versions such as `v1.1.1`, `v1.2.0`, and `v1.2.1`:

https://aiida.readthedocs.io/projects/aiida-core/en/v1.1.1/working/exit_codes
https://aiida.readthedocs.io/projects/aiida-core/en/v1.2.0/working/exit_codes
https://aiida.readthedocs.io/projects/aiida-core/en/v1.2.1/working/exit_codes

### Describe the solution you'd like

As it's the first time I tried to reach this part of documentations and considering that the hyperlink is broken in other versions of `AiiDA` too, I am not sure whether documentation was there berfore or just moved to other location and links are not corrected afterwards. 

EDIT:
I think the proper link should be the following where the definition and conventions are discussed:
https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html#exit-code-conventions

**Comment by mbercx** [comment]
Hi @pzarabadip, thanks for reporting! I opened a PR (#4284) to fix the broken link.
