### ISSUE TITLE
Orbital class with j, m_j quantum numbers

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#4285]
### Use case

Currently, the ``aiida-quantumespresso`` ``projwfc.x`` parser is limited to the collinear case. To extend it to the non-collinear case, it would need to handle outputs like the following, with quantum numbers ``j, m_j``:

```
     Atomic states used for projection
     (read from pseudopotential files):

     state #   1: atom   1 (In ), wfc  1 (l=0 j=0.5 m_j=-0.5)
     state #   2: atom   1 (In ), wfc  1 (l=0 j=0.5 m_j= 0.5)
     state #   3: atom   1 (In ), wfc  2 (l=1 j=0.5 m_j=-0.5)
     state #   4: atom   1 (In ), wfc  2 (l=1 j=0.5 m_j= 0.5)
     state #   5: atom   1 (In ), wfc  3 (l=1 j=1.5 m_j=-1.5)
     state #   6: atom   1 (In ), wfc  3 (l=1 j=1.5 m_j=-0.5)
    <...>
```

These need to be converted into an ``Orbital``. The current [RealhydrogenOrbital](https://github.com/aiidateam/aiida-core/blob/46af33022f49234307534c40089c0865103e4665/aiida/tools/data/orbital/realhydrogen.py#L248) implementation however does not (AFAICT) allow for ``j, m_j`` quantum numbers (only ``n, l, m``).

Related issues / discussion: https://github.com/aiidateam/aiida-wannier90-workflows/issues/9#issuecomment-666256943, https://github.com/aiidateam/aiida-quantumespresso/issues/542 

### Possible solutions

I am soliciting opinions / suggestions on how best to implement this. Possible options I can come up with:

1. Extend the `RealhydrogenOrbital` to allow either set of quantum numbers to be used. 
1. Add a separate `Orbital` subclass for the case of spin-orbit coupling

I'm also unsure if this should be added

1. Here in ``aiida-core``
1. Only in ``aiida-quantumespresso``
1. In a yet-to-be-created ``aiida-materials-science`` plugin (see context below).

### Additional context

The materials-science related parts are slanted for _eventual_ removal from `aiida-core`, see https://github.com/aiidateam/aiida-core/issues/2686

Tagging @qiaojunfeng, @giovannipizzi, @sphuber

**Comment by qiaojunfeng** [comment]
The `RealhydrogenOrbital` already completely represents the projections definitions of wannier90, and works well in aiida-wannier90 for generating the [inputs](https://github.com/aiidateam/aiida-wannier90/blob/ff00d26643152a0e0a56a287469887c85c15bc7b/aiida_wannier90/orbitals.py#L241). So I am thinking maybe it is better to keep it unchanged, and define a new e.g. `PseudoatomicOrbital` for representing pseudo atomic wavefunctions defined in pseudopotentials?

**Comment by giovannipizzi** [comment]
I would be tempted to keep the new implementation close to the new one, so people that find one will find also the other.
Moving one class more will not be the main problem when #2686 is implemented.

Regarding whether to extend or add a new class, I have no strong opinion. 
I think we should avoid the situation of the KpointsData class, where some methods stop working depending on what is stored.
So (to be investigated) if all methods work the same, maybe it's easier to extend the class, and add a flag that says if it's using spin-orbit or not. In methods start to diverge (or we need to represent more information, e.g. also the radial component over a grid etc., better to define a second class.

If anyone wants to start a draft implementation I'm happy to review.

**Comment by sphuber** [comment]
I am not intimately familiar with the `RealhydrogenOrbital` data type nor but it seems that since you are just looking for an extension, wouldn't it make sense to make this `PseudoAtomicOrbital` a sub-class of the `RealHydrogenOrbital` and just make that a new plugin type. I notice now that the latter is not even registered as a plugin. Is that intentional? Are `Orbital` instances stored as nodes, and then loaded as `RealHydrogenOrbital` some how?

Actually, there is the data type `aiida.orm.nodes.data.orbital.OrbitalData` and the `aiida.tools.data.orbital.orbital.Orbital`. Why are there two separate classes?

Again, I am not sure about the internal hierarchy and relationships between the concepts being described, but wouldn't the following make sense:

```
"aiida.data": [
      "orbital = aiida.orm.nodes.data.orbital:OrbitalData",
      "orbital.real_hydrogen = aiida.orm.nodes.data.orbital:RealHydrogenData",
      "orbital.pseudo_atomic = aiida.orm.nodes.data.orbital:PseudoAtomicData",
],
```
and for the classes:

```
class OrbitalData(Data):
    pass

class RealHydrogenData(OrbitalData):
    pass

class PseudoAtomicData(OrbitalData):
    pass
```

**Comment by greschd** [comment]
FYI, I think there is an implementation of this at https://github.com/aiidateam/aiida-quantumespresso/pull/546, but I haven't gotten around to looking at it yet.

**Comment by lbotsch** [comment]
FYI the Orbital subclasses (like [RealhydrogenOrbital](https://github.com/aiidateam/aiida-core/blob/46af33022f49234307534c40089c0865103e4665/aiida/tools/data/orbital/realhydrogen.py#L248))  in `aiida.tools.data.orbital` implement a convenient interface for orbitals. The actual orbital data (like quantum numbers, names, etc) is saved in the [OrbitalData](https://github.com/aiidateam/aiida-core/blob/46af33022f49234307534c40089c0865103e4665/aiida/orm/nodes/data/orbital.py#L20) node as a dict (in the `orbital_dicts` list) together with the Orbital convenience class name (`_orbital_type`):
https://github.com/aiidateam/aiida-core/blob/46af33022f49234307534c40089c0865103e4665/aiida/orm/nodes/data/orbital.py#L63

Therefore, adding new orbital convenience classes won't clutter the database structure.

In https://github.com/aiidateam/aiida-quantumespresso/pull/546 I implemented two such convenience classes for spin-orbit and non-collinear projection.

**Comment by greschd** [comment]
I think we can close this since https://github.com/aiidateam/aiida-quantumespresso/pull/546 covers at least the initial use case. Feel free to re-open if so desired.
