### ISSUE TITLE
pip's 2020-10 resolver

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#4286]
### Is your feature request related to a problem? Please describe

The `pip` installer is updating their resolver for version `20.3` in October 2020 (see [this](https://pip.pypa.io/en/stable/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020) for more information).

Since `aiida-core` is fixed to some old versions for various larger python packages (like `tornado`, `numpy`, ...) this will make it difficult to depend on `aiida-core` for a novel package.

Furthermore, it may even mess with `aiida-core`'s `pip install`. This can be tested by using the `--use-feature=2020-resolver` option from `pip` version `20.2`.

### Describe the solution you'd like

Update `aiida-core` and it's main dependency packages (like `plumpy`, `circus`, ...) to support newest versions of other or related dependencies.

### Describe alternatives you've considered

Support newest versions of the most major dependencies, like `numpy`.

**Comment by chrisjsewell** [comment]
Thanks for the update @CasperWA, its definitely good to hear pip are improving their dependency management, which has always been the source of annoyance. Though it's a shame that the behaviour is still "pip only considers the packages you are installing in that command, and may break already-installed packages." (this is one reason I prefer Conda).

However, this issue feels a bit open-ended, i.e. under what conditions can we considered it closed?
Also for reference:

- numpy version pinning will likely soon be governed by https://github.com/aiidateam/AEP/tree/master/003_adopt_nep_29
- the tornado dependency should maybe be able to be dropped once we move to asyncio in https://github.com/aiidateam/plumpy/pull/150 and https://github.com/aiidateam/aiida-core/pull/4218

**Comment by csadorf** [comment]
> However, this issue feels a bit open-ended, i.e. under what conditions can we consider it closed?

I would say the issue can be closed when our CI workflows do not fail with the feature flag enabled.

> * dependency as a whole will likely soon be governed by https://github.com/aiidateam/AEP/tree/master/002_dependency_management
> 

To clarify, AEP 002 is already implemented.

**Comment by csadorf** [comment]
@CasperWA It appears that all tests pass with the feature flag enabled: https://github.com/aiidateam/aiida-core/pull/4320

Do you think this is sufficient to close the issue?

**Comment by CasperWA** [comment]
> It appears that all tests pass with the feature flag enabled: #4320

Great to see!

> Do you think this is sufficient to close the issue?

Partly. I think we should add this flag permanently to the CI tests to make sure we're future proof in this regard. I don't know if it's then also necessary to run some tests without the flag, but I wouldn't think so, since if it works with the more strict version-reasoning, it should work with the currently "normal" pip install reasoner.

**Comment by csadorf** [comment]
> Partly. I think we should add this flag permanently to the CI tests to make sure we're future proof in this regard. I don't know if it's then also necessary to run some tests without the flag, but I wouldn't think so, since if it works with the more strict version-reasoning, it should work with the currently "normal" pip install reasoner.

In this case I propose that we run the `continuous-integration` workflow with the feature flag enabled and the `test-install` workflow with and without it. This ensures that AiiDA can be installed in the way a user would install it (that's the motivation for `test-install`), and that we are also future-proof for newer versions of pip. Good?
