### ISSUE TITLE
slurm v2.6.9: Unable to parse time string %V

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#4287]
- [X] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [X] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug

I have `slurm 2.6.9` in remote computer, when running jobs over slurm I got `[WARNING] Error parsing submission_time for job id 38011` . The debug message shows that it caused from parsing `%V` time string incorrectly. `[DEBUG] Unable to parse time string %V, the message was time data '%V' does not match format '%Y-%m-%dT%H:%M:%S'`. 

This definitely because of the incompatible slurm version, my question is how can I check the if slurm version of remote computer compatible with the scheduler plugin? Can we add a detail information about scheduler version in documentation. Or more better, check the remote scheduler version over `verdi computer test` and report the subtle problems?  

mention @espenfl for inputs.

### Your environment

- Operating system [e.g. Linux]:
- Python version [e.g. 3.7.1]:
- aiida-core version [e.g. 1.3.0]:

Other relevant software versions, e.g. Postres & RabbitMQ

**Comment by sphuber** [comment]
SLURM v2.6.9 dates back to 2014 and so can be considered really old. Just wanted to mention this in case finding a fix that is backwards compatible turns out to be difficult, it might not be worth the cost to try and address it.

**Comment by unkcpz** [comment]
Thanks a lot @sphuber . It's true the slurm version is outdated, and since this issue does not affect normal use, I will close this issue report.
