### ISSUE TITLE
An excessive number of ssh requests to a cluster frontend.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#4288]
### Describe the bug

We experienced this issue on AiiDA lab. An AiiDA lab user has submitted a work chain through AiiDA when his machine was overloaded. For (yet) an unknown reason, AiiDA started to initiate plenty of SSH connections to the frontend of the supercomputer. I didn't see it myself. The cluster admins have reported an excessive number of connections:

> We have noticed that from July the 26th the user _X_  made 13671 connections to the front-end Fidis.

### Steps to reproduce

Steps to reproduce the behaviour:

1. Submit a work chain
2. Overload your machine

### Expected behaviour

AiiDA should not open an excessive number of SSH connections.

### Your environment

- Operating system: Ubuntu 18.04.1
- Python version: 3.7.4
- aiida-core version: 1.2.1
- PostgreSQL: 10.12
- RabbitMQ: 3.6.10-1

**Comment by yakutovicha** [comment]
I am not totally sure how to reproduce the problem, that is why my instructions are so unprecise. This happened once and not even to me. So I decided to report what I know, instead of not reporting it.

**Comment by sphuber** [comment]
Is there a possibility to get more info from whoever reported it to you? If not, I will close this because there is nothing I can do here

**Comment by yakutovicha** [comment]
> Is there a possibility to get more info from whoever reported it to you?

I believe not.

>  If not, I will close this because there is nothing I can do here

Ok, if I manage to reproduce the problem - I will reopen the issue.
