### ISSUE TITLE
memory available in computer nodes

### ISSUE THREAD

**Issue by cpignedoli** [aiidateam/aiida-core#4297]
in apps/workchains where teh number of computer nodes to be used for a calculation
is determined automatically, it could be useful to know the memory available per node

add memory per node or memory per core in the definition of a new computer

**Comment by greschd** [comment]
One complication here are heterogeneous clusters: memory per node is not always a constant across a single computer.

**Comment by cpignedoli** [comment]
Dear Dominik
you are right. Despite in many cases
nodes  belong to different “queues” according to the characteristics of the node, this cannot be assumed as general case.
The only workaround I see to this problem that I did not have in mind
is then to define, for a computer, max and min possible memory per node.

Cheers

Carlo

**Comment by greschd** [comment]
Yeah, there might absolutely be value in allowing for this even if we don't have a complete solution for the heterogeneous case. For "num_mpiprocs_per_machine" we can also currently only set one default.

I think there are two separate but related issues here: 
- How to specify resources for the heterogeneous case. It probably makes sense to solve this is a consistent way for memory + CPU. The queue seems like the most straightforward way to distinguish them, but I don't know if there might be cases where even a single queue can have different nodes.
- Adding memory per node: While the previous point is unresolved, a single value per computer still seems valuable. We should just make sure we don't make it harder than necessary to later extend the functionality.
