### ISSUE TITLE
Add `metadata` column to the `Group` database class

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4303]
For certain use cases, it would be very useful to be able to store "metadata" on a `Group` instance. Especially now that `Groups` are pluginnable, a lot of power can be given to the user through this simple addition. One example use case, is the creation of a pseudo potential family, by subclassing `Group` as `PseudoFamily`. This group would store pseudo potential data nodes, one for each element. Often these pseudo potentials come with recommended metadata, such as wave function cutoffs in the case of `UpfData` nodes. These are family dependent and so should not be stored on the data node but belong to the "family". It would be perfect to be able to store this in the metadata. Now we are forced to come up with more complex solutions, such as using a `Dict` node that also contains a back reference to the `Group` to which it belongs.

As of yet, I do not really see any disadvantages of this feature, except that maybe it could encourage users to store too much information in the group metadata and "abuse" it in ways that end up losing provenance. However, with proper documentation and example use cases, this should be ok. @giovannipizzi @ltalirz @greschd comments?

**Comment by ltalirz** [comment]
I agree that storing extra information on the group level makes sense.

Since AiiDA users will already be familiar with `attributes` and `extras` from nodes, perhaps we should name it the same way here?

> it could encourage users to store too much information in the group metadata and "abuse" it in ways that end up losing provenance

One decision to make here is whether this information should be mutable or not (or whether we allow both).

**Comment by sphuber** [comment]
> Since AiiDA users will already be familiar with `attributes` and `extras` from nodes, perhaps we should name it the same way here?

Fair point. I'm not sure what which would be more intuitive though. First reaction was to suggest `attributes`. However, as you will see below, I think the `Group` attributes should be mutable, whereas those of a `Node` are not. This may be confusing, and so maybe using `extras` in this regard may be more consistent.

> > it could encourage users to store too much information in the group metadata and "abuse" it in ways that end up losing provenance
> 
> One decision to make here is whether this information should be mutable or not (or whether we allow both).

Since `Group` instances are mutable already, in terms of the nodes they contain, I would not see why their attributes should be immutable.

**Comment by mbercx** [comment]
I'd also be in favor of using a name that users are familiar with, and since the information will be mutable, `extras` seems like the better choice. So unless there are any objections, I'd go with that.

**Comment by sphuber** [comment]
I have added the 1.4 milestone because ideally we have this a.s.a.p. such that `aiida-pseudo` can use this immediately to store recommended cutoffs and not have to rely on a weird construct with a connected `Dict` node.
