### ISSUE TITLE
Coordinate text between code and computer

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#4313]
### Is your feature request related to a problem? Please describe

Right now, for a `computer` you use `rename`, while for a `code` you use `relabel`. Not sure of this is intentional or not.

### Describe the solution you'd like

`rename` or `relabel` for both.

**Comment by greschd** [comment]
I believe this is adressed in https://github.com/aiidateam/aiida-core/pull/4309

**Comment by espenfl** [comment]
Sounds great.
