### ISSUE TITLE
Allow the return of the valence band maximum

### ISSUE THREAD

**Issue by espenfl** [aiidateam/aiida-core#4315]
### Is your feature request related to a problem? Please describe

AiiDA already has a function that estimates the band gap when you have the occupancies, `find_bandgap`. But sometimes we also want to observe the valence band maximum as a function of something (for instance in convergence tests). As such it would be nice if the function could also return this quantity, maybe as an additional value to unpack after the gap. An alternative is to make a new driver function and two wrappers (find_bandgap as is and find_vbm) that simply loads the values. Then we would not have unpacking issues etc. We should avoid doing this calculation twice.

**Comment by sphuber** [comment]
Think this is a duplicate of #3560

**Comment by espenfl** [comment]
Indeed, closing this and adding discussion in #3560.
