### ISSUE TITLE
Calling `verdi export migrate` on an up-to-date file should return exit code 0

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4322]
Currently, when trying to migrate an export file that is already at the latest version, you get a critical error:
```bash
$ verdi export migrate old.aiida new.aiida
Critical: Your export file is already at the version 0.9
```

This makes it unnecessarily difficult to migrate a bunch of archives to the latest version (e.g. needed on Materials Cloud) - currently, you need to first check what version an archive has, and only if it is not already at the latest version, perform the migration.

The much simpler solution is to make the migration of an archive that is already at the latest version a no-op and return exit code 0.

**Comment by CasperWA** [comment]
It would be nice to inform the user about the export archive already being at the latest version as well, instead of just writing "Success" or nothing at all?

**Comment by ltalirz** [comment]
Currently it says
```
Success: migrated the archive from version 0.9 to 0.9
```
which is also not too bad.

Anyhow, I've adapted it a bit here https://github.com/aiidateam/aiida-core/pull/4220/commits/268f84ee812674962554a9ddb6bd3477299e3430
