### ISSUE TITLE
Replace 'tempfile.mkdtemp' with 'tempfile.TemporaryDirectory'.

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#4336]
The `tempfile.mkdtemp()` is used in many places in the code to create a temporary directory, that is later cleaned up manually (e.g. with `shutil.rmtree`). The drawback of this is that the cleanup will not happen if execution is somehow interruped.

By using `tempfile.TemporaryDirectory()` instead (even when a context manager cannot be used), cleanup will happen when the garbage collector picks up the object. The "manual" cleanup should still be kept, as calling the `.cleanup()` method - because the garbage collector doesn't run at predictable intervals.

See comment by @ltalirz in https://github.com/aiidateam/aiida-core/pull/4220#discussion_r479111846_

**Comment by sphuber** [comment]
Note that when this concerns tests, written for pytest, they should even probably use the `tmpdir` or `tmp_path` [builtin fixtures](https://docs.pytest.org/en/stable/builtin.html)
