### ISSUE TITLE
Newest `aiidateam/aiida-core:stable` docker image contains broken `pymatgen` dependency

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#4339]
### Short description

The [newest `aiidateam/aiida-core:stable` docker image](https://hub.docker.com/layers/aiidateam/aiida-core/stable/images/sha256-74a6e6e0fa060d04dbd72c1409f2d1fc2207bd5a40406ade7bb4f11bbfbd0214?context=explore) contains `pymatgen`, but that is missing its dependency `ruamel.yaml`.

**Update:** The `1.3.0.1` image is also broken, while `1.3.0` works. I suspect it's something about these being built more recently - the latest `pymatgen` release is from 2020-08-13.

### Steps to reproduce

- `docker pull aiidateam/aiida-core:stable`
- `docker run aiidateam/aiida-core:stable`
- `docker exec --tty $DOCKERID wait-for-services`
- `docker exec -it $DOCKERID bash`
- `su aiida`
- `verdi shell`
- `import pymatgen`

Result:
```python
(base) aiida@3e0b99c6409f:~$ verdi shell
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pymatgen
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-a3a39e60e980> in <module>
----> 1 import pymatgen

/opt/conda/lib/python3.7/site-packages/pymatgen/__init__.py in <module>
     12 from fnmatch import fnmatch
     13 
---> 14 import ruamel.yaml as yaml
     15 
     16 from monty.json import MontyEncoder, MontyDecoder, MSONable

ModuleNotFoundError: No module named 'ruamel'
```

### Expected behavior

The last command should import `pymatgen`.

### Your environment

- Docker version 19.03.12, build 48a66213fe
- aiida-core version: 1.3.1
- Python version: 3.7.4

Tagging @csadorf @yakutovicha

**Comment by csadorf** [comment]
@greschd Thank you for reporting!
@yakutovicha Could you investigate, please?

**Comment by yakutovicha** [comment]
Thanks @greschd. I will have a look!

**Comment by yakutovicha** [comment]
I am investigating this issue, and what I can tell already - when downgrading the pymatgen version the problem remains.

**Comment by yakutovicha** [comment]
The content of `/opt/conda/lib/python3.7/site-packages` in the broken image:
```shell
ruamel_yaml/                   ruamel_yaml-0.15.80.dist-info/
```

Of the working image:
```
ruamel/   ruamel_yaml/  ruamel_yaml-0.15.80.dist-info/  ruamel.yaml-0.16.10.dist-info/  ruamel.yaml-0.16.10-py3.8-nspkg.pth  ruamel.yaml.clib-0.2.0.dist-info/
```

**Comment by yakutovicha** [comment]
To temporarily fix the problem it is enough to do:

```
pip install --upgrade ruamel.yaml
```

**Comment by greschd** [comment]
Yeah, it's weird that it needs to be `pip` installed though, right? AFAICT, the docker image uses `conda` in general, right?

**Comment by yakutovicha** [comment]
> Yeah, it's weird that it needs to be `pip` installed though. AFAICT, the docker image uses `conda` in general, right?

We use it mostly for the environment, for the moment. Many plugins are not available through `conda`

**Comment by greschd** [comment]
Ah, maybe that's the source of the problem? If either `pymatgen` or `ruamel.yaml` are installed differently, maybe that could cause issues.

**Comment by yakutovicha** [comment]
So for some reason, in old image build the log looked as follows:
```
Collecting ruamel.yaml>=0.15.6
Downloading ruamel.yaml-0.16.10-py2.py3-none-any.whl (111 kB)
```

Recently, it has been changed:
```
Requirement already satisfied: ruamel.yaml>=0.15.6 in /opt/conda/lib/python3.7/site-packages (from pymatgen>=2019.7.2; extra == "atomic_tools"->aiida-core==1.3.1) (0.15.80)
```

**Comment by greschd** [comment]
Maybe some other dependency started requiring `ruamel.yaml`? I think that one is `conda` - installed, which may be incompatible with a `pip` - installed `pymatgen` for some reason?

**Comment by greschd** [comment]
I did try installing `pymatgen` onto a clean conda env (via conda), and that worked fine.

**Comment by greschd** [comment]
I'm really not a `conda` expert, but this link seems relevant: https://www.anaconda.com/blog/using-pip-in-a-conda-environment

**Comment by yakutovicha** [comment]
> I did try installing `pymatgen` onto a clean conda env (via conda), and that worked fine.

yes, I've tried that as well.

**Comment by yakutovicha** [comment]
ah, I might have a clue. The base image (`aiidateam/aiida-prerequisites:0.2.0`) has `ruamel` pre-installed

**Comment by greschd** [comment]
Alright, here's a minimal repro (in a clean `conda` env):

- `conda install ruamel_yaml`
- `pip install pymatgen`
- `python` -> `import pymatgen`

It seems indeed the `conda` and `pip` installs are incompatible in this case.

**Comment by yakutovicha** [comment]
Hmmmm, the old image did also have `ruamel` pre-installed as the dependency of miniconda:

```
The following packages will be downloaded:
package | build
---------------------------|-----------------
_libgcc_mutex-0.1 | conda_forge 3 KB conda-forge
_openmp_mutex-4.5 | 0_gnu 435 KB conda-forge
cffi-1.13.2 | py37h8022711_0 220 KB conda-forge
chardet-3.0.4 | py37_1003 167 KB conda-forge
conda-package-handling-1.6.0| py37h516909a_1 942 KB conda-forge
cryptography-2.8 | py37h72c5cf5_1 625 KB conda-forge
idna-2.9 | py_1 52 KB conda-forge
libffi-3.2.1 | he1b5a44_1006 46 KB conda-forge
libgcc-ng-9.2.0 | h24d8f2e_2 8.2 MB conda-forge
libgomp-9.2.0 | h24d8f2e_2 816 KB conda-forge
libstdcxx-ng-9.2.0 | hdf63c60_2 4.5 MB conda-forge
ncurses-6.1 | hf484d3e_1002 1.3 MB conda-forge
pycosat-0.6.3 |py37h516909a_1002 105 KB conda-forge
pycparser-2.19 | py_2 88 KB conda-forge
pyopenssl-19.1.0 | py_1 47 KB conda-forge
pysocks-1.7.1 | py37_0 27 KB conda-forge
readline-7.0 | hf8c457e_1001 391 KB conda-forge
requests-2.23.0 | py37_0 85 KB conda-forge
ruamel_yaml-0.15.80 |py37h516909a_1000 268 KB conda-forge
setuptools-45.2.0 | py37_0 654 KB conda-forge
six-1.14.0 | py37_0 23 KB conda-forge
sqlite-3.31.1 | h7b6447c_0 1.1 MB defaults
tk-8.6.10 | hed695b0_0 3.2 MB conda-forge
tqdm-4.43.0 | py_0 47 KB conda-forge
urllib3-1.25.7 | py37_0 159 KB conda-forge
wheel-0.34.2 | py_1 24 KB conda-forge
xz-5.2.4 | h14c3975_1001 366 KB conda-forge
yaml-0.2.2 | h516909a_1 82 KB conda-forge
zlib-1.2.11 | h516909a_1006 105 KB conda-forge
```

**Comment by greschd** [comment]
Maybe related, even though it's old: https://github.com/materialsproject/pymatgen/issues/758

**Comment by yakutovicha** [comment]
My second guess is: we have different pip versions, and new pip might handle dependencies differently

**Comment by yakutovicha** [comment]
> Maybe related, even though it's old: [materialsproject/pymatgen#758](https://github.com/materialsproject/pymatgen/issues/758)

I think this is not a problem. Ruaml has been put as a dependency quite some time ago, and we have images build with it.

**Comment by greschd** [comment]
> 
> 
> Alright, here's a minimal repro (in a clean `conda` env, `conda 4.8.4` on Ubuntu 18.04):
> 
>     * `conda install ruamel_yaml`
> 
>     * `pip install pymatgen`
> 
>     * `python` -> `import pymatgen`
> 
> 
> It seems indeed the `conda` and `pip` installs are incompatible in this case.

Does this work on the old `aiida-prerequisites` container?

**Comment by greschd** [comment]
So.. conda has packages `ruamel`, `ruamel_yaml` and `ruamel.yaml`. Installing only `ruamel_yaml` does not work, but installing `ruamel.yaml` does.

**Comment by greschd** [comment]
When installing `ruamel_yaml`, ... `import ruamel_yaml` works, but not `import ruamel.yaml`.

**Comment by yakutovicha** [comment]
so looks like we should install `ruamel.yaml==0.16.10` in the `aiida-prerequisites` image, what do you think?

**Comment by greschd** [comment]
Yeah, I think that makes sense. TBH, I have no idea at all why there are two different conda-force sources for that.

**Comment by yakutovicha** [comment]
I can now confirm that this is the pip problem. I downgraded pip and rebuild the image. It worked: `ruamel.yaml` got installed.

**Comment by greschd** [comment]
Even without the `pip` problem though, `conda install ruamel_yaml` doesn't work as advertised.

**Comment by yakutovicha** [comment]
> Even without the `pip` problem though, `conda install ruamel_yaml` doesn't work as advertised. I think pip installing a newer version on top is just masking the problem.

I agree.

**Comment by greschd** [comment]
So, the two are actually different packages (ever so slightly): https://github.com/conda-forge/ruamel.yaml-feedstock/issues/7#issuecomment-230599730

Not sure who exactly is responsible for the fact that `pip` doesn't realize that, though..

**Comment by yakutovicha** [comment]
> So, the two are actually different packages (ever so slightly): [conda-forge/ruamel.yaml-feedstock#7 (comment)](https://github.com/conda-forge/ruamel.yaml-feedstock/issues/7#issuecomment-230599730)
> 
> Not sure who exactly is responsible for the fact that `pip` doesn't realize that, though..

ah, my understanding was that it is the same package that just changed its name. But if those two packages are the different ones, we come back to the pip problem.

**Comment by greschd** [comment]
Yeah, so newer `pip` considers all of `ruamel_yaml`, `ruamel-yaml` and `ruamel.yaml` to be the same package..

The first two are fine (this is normal canonicalization), not sure what the standards say about the latter.

**Comment by yakutovicha** [comment]
should we report this to pip?

**Comment by greschd** [comment]
Might be https://github.com/pypa/pip/pull/8659

**Comment by greschd** [comment]
It seems to be on purpose: https://github.com/pypa/pip/issues/8645#issuecomment-665571641

**Comment by greschd** [comment]
According to [this page](https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py), package names aren't even supposed to contain dots 🙈

**Comment by greschd** [comment]
That's only semi-official though.. it's the packaging guide, not the official Python doc.

**Comment by greschd** [comment]
Yeah, so that's definitely intentional on the side of `pip` and PyPI. When you upload a package with any of `-`, `_`, `.`, it ends up in the same page. The displayed name is actually chosen by whichever it was uploaded as last 😄

Obviously, conda appears to have a different policy here. But it might be worthwhile to check with them if that is intentional.

**Comment by greschd** [comment]
Ah, it was actually changed just recently: https://github.com/conda-forge/ruamel_yaml-feedstock/pull/68
