### ISSUE TITLE
Fix workaround for setuptools version limitation

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4349]
In PR #4342 we merged a workaround for a bug in the python package ecosystem, involving `pip` and `setuptools`. Currently by not installing `setuptools==0.50.0` fixes the failing builds on Jenkins, but we need to fix this at some point. People have suggested that the actual bug is due to `pip` messing up with its isolated build environment when installing in a virtual env with `--system-site-packages`. Apparently in this case there is cross talk between setuptools installed by `pip` and a version that exists on the system. We don't use virtual envs on the Jenkins machine, but we do install in user space with `pip` using `--user`. The same problem might be at play here. Since on GHA we did not experience problems, where we do in fully isolated virtual envs, simply installing in a virtualenv on Jenkins may fix the problem.

**Comment by csadorf** [comment]
@sphuber Any objection to placing this issue on the next minor release milestone? I believe that this is a strong enough constraint that we should resolve it rather sooner than later.

**Comment by csadorf** [comment]
@chrisjsewell Any update on this?

**Comment by chrisjsewell** [comment]
indeed, as of 30 minutes ago, Jenkins now uses the `aiidateam/aiida-prerequisites` Docker image, and so this should no longer be relevant. So lets give it a go without the restriction then

**Comment by csadorf** [comment]
> indeed, as of 30 minutes ago, Jenkins now uses the `aiidateam/aiida-prerequisites` Docker image, and so this should no longer be relevant. So lets give it a go without the restriction then

@chrisjsewell Since you're still assigned to this issue, do you want to push the updated constraint or do you want me to do that?
