### ISSUE TITLE
Pytest infrastructure seems to be broken

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#4359]
### Describe the bug

Recently, the tests that are run on top of the `aiida-core:latest` image started to fail with the following error:

```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

../conda/lib/python3.7/site-packages/aiida/engine/launch.py:77: in run_get_pk

    runner = manager.get_manager().get_runner()

../conda/lib/python3.7/site-packages/aiida/manage/manager.py:251: in get_runner

    self._runner = self.create_runner()

../conda/lib/python3.7/site-packages/aiida/manage/manager.py:285: in create_runner

    settings['communicator'] = self.get_communicator()

../conda/lib/python3.7/site-packages/aiida/manage/manager.py:163: in get_communicator

    self._communicator = self.create_communicator()

../conda/lib/python3.7/site-packages/aiida/manage/manager.py:185: in create_communicator

    url = profile.get_rmq_url()

../conda/lib/python3.7/site-packages/aiida/manage/configuration/profile.py:344: in get_rmq_url

    protocol=self.broker_protocol,

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <aiida.manage.configuration.profile.Profile object at 0x7fbfaa172150>

    @property

    def broker_protocol(self):

>       return self._attributes[self.KEY_BROKER_PROTOCOL]

E       KeyError: 'broker_protocol'
```

### Steps to reproduce

1. Install latest aiida-core
2. Run test calculation that rely on aiida-pytest infrastructure.

### Examples of errors.

aiida-cp2k: https://travis-ci.org/github/aiidateam/aiida-cp2k/builds/725311241
aiida-raspa: https://travis-ci.org/github/yakutovicha/aiida-raspa

**Comment by greschd** [comment]
I think for some reason the test profile doesn't have the new attributes introduced in https://github.com/aiidateam/aiida-core/pull/4341.

**Comment by sphuber** [comment]
The problem is indeed that somehow the profile that is being used does not have the new broker parameters. I don't understand why though, because:

 1) Newly generated profiles get the defaults set
 2) I wrote migrations for existing profiles.

Additionally, the testing of `aiida-core` itself works without a problem. How is it possible anyway that you are testing against a version of `aiida-core` that hasn't been released yet? Is this because you are using a docker image? How does that docker image setup the profile? Would it be possible to have the build echo the content of the `.aiida/config.json` file to see if it was properly created? I don't think your build method uses an existing profile between builds, does it? I.e. it should not rely on the config migrations, should it?

**Comment by sphuber** [comment]
I think I see the problem now. The code that provides the fixtures does not reuse the same code as the main code for generating profiles and apparently that code path does not guarantee the new broker parameters. We could add a quick fix, but really this is a bigger problem and the fixtures should not use their own separate code for generating profiles.

**Comment by yakutovicha** [comment]
> How is it possible anyway that you are testing against a version of `aiida-core` that hasn't been released yet? Is this because you are using a docker image?

I use `aiida-core:latest` docker image for the tests. It points to the docker container build against the `develop` branch. Do you think I should better switch it to `aiida-core:stable` which points to `master`?

> Would it be possible to have the build echo the content of the .aiida/config.json file to see if it was properly created?

The problem is really for the tests run by `pytest`. If I go to the container and manually run the tests, everything works fine.

> I don't think your build method uses an existing profile between builds, does it? I.e. it should not rely on the config migrations, should it?

you are right, it doesn't. Pytest creates a temporary profile for the tests.

**Comment by greschd** [comment]
> Do you think I should better switch it to `aiida-core:stable` which points to `master`?

Well, for `aiida-core` it's nice that you test against `latest` - if anything slips through our tests, we have quicker feedback on that.

If you don't want to live on the bleeding edge though, maybe `stable` (or actually `1.3.1.1`, since `stable` still has that `ruamel.yaml` issue) is nicer.
