### ISSUE TITLE
Refactor the `aiida.manage.tests` fixture manager code

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4365]
See PR #4360 for the reason why. Because the fixture manager code rolls its own code to create configs and profiles, and the code is not tested, it is too easy for changes in the main code to break the fixtures. The fixture manager should reuse the same code to create profile as `verdi setup`.

**Comment by greschd** [comment]
Tagging @ltalirz

**Comment by ltalirz** [comment]
certainly agree this would be nice to have :-)
the fixture manager needs a bit of cleverness for temporary profiles etc. but I'm sure it could reuse more code

**Comment by ltalirz** [comment]
@sphuber maybe worth checking to which degree this still applies.

Code is in https://github.com/aiidateam/aiida-core/blob/d0ff88986391691a0307d0cafb300dbf48e303b3/aiida/manage/tests/main.py#L70
