### ISSUE TITLE
drop python 3.5 support

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4367]
Following the [AiiDA compatibility timeline](http://www.aiida.net/download/), we will drop python 3.5 support from September 13th 2020 onwards, i.e. with the upcoming 1.4.0 release.

This means python3.6+ only features are now fair game and we can stop testing on python 3.5 on CI
@chrisjsewell @greschd @dev-zero @sphuber @csadorf

**Comment by greschd** [comment]
Woowee, f-strings here we come 🚀 And we can drop the casts to `str` from `pathlib.Path`.

**Comment by sphuber** [comment]
The plan was to actually keep python 3.5 support for 1.4 and that mark the last release to support it. That would put this issue in the 1.5 milestone. Since we have develop compatible now and are close to the release don't see the reason to r move compatibility at the last moment.

**Comment by greschd** [comment]
Well, it does save us from having to test and keep up support anywhere between 1.4.0 and 1.5.0 - since presumably, we don't want to drop it on a patch release. But yeah, it's not _that_ strong of an argument. 

Then again, right before a minor release is probably the only time when you can reasonably drop it, right?

**Comment by sphuber** [comment]
The way I see it, we release 1.4 with 3.5 support but straight after it we drop it in develop so we can start merging code with 3.6 features. This way people have a final minor release with 3.5 support just before it's EOL. We could even say to still provide patch releases on 1.4.* for a moment that are 3.5 compatible but really don't think that will be necessary

**Comment by sphuber** [comment]
By the way, final thing. I already have a commit on my branch for the new repo that drops 3.5 support that is ready to go. I did this because I knew this would only be merged after the last release with 3.5 support and this way I could already use 3.6 code in the new repo code. Once I have released 1.4 I will make a pr with just this commit and merge it to develop

**Comment by greschd** [comment]
Hm, if you think there won't be patch releases for 1.4 then I guess it makes sense. Otherwise, dropping it now would potentially save some headaches in preparing / back-porting these patches.
Btw, is the current plan to go 1.4, 1.5, 2.0, or just 1.4, 2.0?

**Comment by ltalirz** [comment]
Unless there are important python-3.6-only features ready to go (do you have any @greschd ?), I'm fine with holding off any breaking changes until after the 1.4 release.

This post was meant more as a heads up; we can drop CI tests on python 3.5 together with release 1.4.

As for the timeline, it's not set in stone but 2.0 might still be some way off, i.e. a 1.5 seems likely.

**Comment by greschd** [comment]
Ok, I just wanted to make the point that we shouldn't drop 3.5 in-between 1.4.0 and 1.4.1. If there's no 1.4.1, then it doesn't matter. I don't have any important 3.6-only things ready.

**Comment by sphuber** [comment]
Yes, I think a 1.5 will most likely be released before the end of the year maybe, followed by 2.0 early next year.

**Comment by csadorf** [comment]
> Following the [AiiDA compatibility timeline](http://www.aiida.net/download/), we will drop python 3.5 support from September 13th 2020 onwards, i.e. with the upcoming 1.4.0 release.
> 
> This means python3.6+ only features are now fair game and we can stop testing on python 3.5 on CI
> @chrisjsewell @greschd @dev-zero @sphuber @csadorf

@ltalirz Could you update the timeline to reflect [AEP 003](https://github.com/aiidateam/AEP/tree/master/003_adopt_nep_29)?

**Comment by ltalirz** [comment]
Done!
