### ISSUE TITLE
Changes in features for new export format

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4382]
I think in the new implementation of the export format, I would like to see the following changes:
- [x] only `sealed` ProcessNodes can be exported
- [x] Logs are *always* imported and exported along with the node as they also constitute the "content" of the node (unless we agree that we don't want to consider them as content)
- [x] (SPH) `checkpoint` attributes should _not_ be exported. They can be used as an attack vector through arbitrary code execution.

[Feel free to add more requirements to this issue]

**Comment by greschd** [comment]
>     * (SPH) `checkpoint` attributes should _not_ be exported. They can be used as an attack vector through arbitrary code execution.

On this point, it's _importing_ of checkpoints that really needs disabling. The potential attacker controls what goes into the export file, but the user has control over the code that does the importing.

**Comment by giovannipizzi** [comment]
Indeed - I would put this as a safety check, but more than checkpoints I would again make sure that anything we import is sealed as a security measure (and anyway disable exporting unsealed nodes, I think)

**Comment by chrisjsewell** [comment]
Linking this to https://github.com/aiidateam/AEP/pull/21/files
