### ISSUE TITLE
New efficient import format (and import/export functionality) for AiiDA 2.x

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4384]
In AiiDA 2.x there is the plan to switch to the aiida-objecstore as a file repository backend.
This solves a number of efficiency issues when storing files.

Therefore, this calls for an improvement (or, rather, a complete redesign) of the export/import functionality, to leverage on the new performance benefits of the new implementation, and at the same time to solve a number of outstanding issues of the current export logic (very large memory consumption, a number of possible inconsistencies like the possibility to export unsealed nodes, ...).

This issue only acts as a placeholder for the long-term project (and so belongs to the `Long term projects` GitHub project); the actual issues can be found in [this project](https://github.com/aiidateam/aiida-core/projects/5) (that I think we can reuse fo this purpose)

A collection of the user stories that we are discussing in the team can be found in this [working Google Docs](https://docs.google.com/document/d/1weUB8cHJuvKUqH8TEL-hMj40jkqDJQM7ljlKxEKs63s/edit#) (and should be converted soon into an AEP by @chrisjsewell)

**Comment by ltalirz** [comment]
He already did ;-) https://github.com/aiidateam/AEP/pull/21
