### ISSUE TITLE
Duplicate SQLAlchemy migrations

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4389]
For some reason, we didn't realise that the same migration ID (at least for SQLA) has been committed twice:

`0edcdd5a30f0_add_extras_to_group.py`
and
`0edcdd5a30f0_dbgroup_extras.py`

I don't know about Django, neither if this messes up with the migrations.
Anyway, now at every verdi operation I get the warning
```
//Users/pizzi/.virtualenvs/aiida-dev/lib/python3.8/site-packages/alembic/script/revision.py:126: UserWarning: Revision 0edcdd5a30f0 is present more than once
  util.warn(
```

@sphuber @mbercx are both correct migrations, the UUID needs to be changed, or one is committed by mistake?

**Comment by sphuber** [comment]
Good catch, there should be just one. The second one `0edcdd5a30f0_add_extras_to_group.py` was committed by mistake. I will create a PR now to remove it.

**Comment by sphuber** [comment]
How did you manage to catch this? Was there a problem with the migration?

**Comment by giovannipizzi** [comment]
Because of the annoying warning after having migrated a SQLA profile ;-)
