### ISSUE TITLE
WarnWhenNotEntered wrapper breaks __iter__

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#4397]
### Describe the bug

The `WarnWhenNotEntered` wrapper breaks some behavior of `Node.open()`: The object can not be iterated, maybe also other things.

### Steps to reproduce

```python
In [1]: import io

In [2]: from aiida import orm

In [3]: sf = orm.SinglefileData(io.BytesIO(b"1.2"))

In [4]: iter(sf)
```

### Expected behavior

Should return an iterator over the lines of the file.

### Your environment

- aiida-core version: 1.4.0

### Additional context

See discussion in https://github.com/aiidateam/aiida-quantumespresso/pull/560

**Comment by sphuber** [comment]
Already opened #4396 so closing this as duplicate

**Comment by greschd** [comment]
Yup, just saw it 👍
