### ISSUE TITLE
Should we support hard links in the remote_copy_list?

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#4417]
Currently there is a remote_copy_list and a remote_symlink_list.
The former must be used if the next calculation might change the files, to avoid interacting with previous calculations.
However, there are many cases in which this is very expensive and can take minutes, beside filling quickly the scratch folders.

One interesting option would be (if the remote file system supports it) to do hard links instead of symlinks.
These should be created quickly.

The only thing to check (e.g. by running a QE restart) is the behaviour of C/Fortran codes on hard links: do they just modify them, so modifying also the original copy (and then it doesn't make sense to implement this, it would behave like a symlink) or it does a copy-on-write and creates a duplicate only of the files that are modified, only when they are modified? If this is the case, a remote_hardlink_list might be very useful.

**Comment by greschd** [comment]
With "copy on write", do you mean that the program creates a new inode and then renames it to the original name? If so, wouldn't the behavior be the same for soft- and hard-links (in both cases, the original inode is not changed)?

To be more clear what I mean, neither of the below operations (with soft and hard links) changes `orig`:
```bash
$ echo foo > orig
$ ln -s orig soft_link
$ ln orig hard_link
$ echo bar > tmp
$ mv tmp soft_link
$ echo bar > tmp
$ mv tmp hard_link
$ cat orig
foo
```

**Comment by ramirezfranciscof** [comment]
> The only thing to check (e.g. by running a QE restart) is the behaviour of C/Fortran codes on hard links: do they just modify them, so modifying also the original copy (and then it doesn't make sense to implement this, it would behave like a symlink) or it does a copy-on-write and creates a duplicate only of the files that are modified, only when they are modified? If this is the case, a remote_hardlink_list might be very useful.

Also, separate from what @greschd mentions: if we want AiiDA to be able to wrap CalcJobs around any kind of external code shouldn't we be considering all the posibilities, regardless of what QE/C-codes/Fortran-codes do in particular? I.E. that this lists will be used for both programs that do copy-on-write or that do edits in place.

**Comment by giovannipizzi** [comment]
@greschd you are right; also, both hard and soft links work the same instead with appending or overwrite with `>` or `>>`. So maybe adding hard links is maybe not really needed.
On the other hand, it would be good for the different codes to understand how their codes behave.
E.g. for aiida-quantumespresso we could check if we could always use symlinks for restarts also for pw.x and this is always safe to do. 

@greschd unless you are aware of some case where the two behave differently from a practical point of view, we can close this issue.

@ramirezfranciscof I agree on your comment - my point is that if there is at least one application where hard links provide the hoped behaviour and soft links do not, it's worth adding this feature to AiiDA. Then of course it's up to the plugin developers to implement it, but at least the feature is available.
Let's see if this issue can be safely closed and symlinks are enough.

**Comment by ramirezfranciscof** [comment]
> One interesting option would be (if the remote file system supports it) to do hard links instead of symlinks.

Ahhh I see. Sorry, I understood from the quoted line that the idea was to relpace the symlinks.

**Comment by greschd** [comment]
> @greschd unless you are aware of some case where the two behave differently from a practical point of view, we can close this issue.

I can't think of any practical difference, except that the hard link would mean the old directory can be removed without the new calculation crashing. That's more a matter of scratch cleaning policy on the compute cluster however.

I'll close the issue, if we find a particular use case where hard links are needed we can always reconsider.
