### ISSUE TITLE
`CalcJob`: allow to specify additional files to be retrieved through `metadata.options`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4423]
The files that are to be retrieved after a `CalcJob` has finished are specified in the `retrieve_list` which is defined by the `CalcJob.prepare_for_submission` and set on the `CalcInfo` object that it returns. People have realized that sometimes a user of a `CalcJob` wants to retrieve additional files on a per-calcjob basis. The solution was implemented by adding the special `settings` input node that contained a key `additional_retrieve_list`. This has to be implemented separately by each `CalcJob` that wants to add this functionality though, even though it could be implemented in `aiida-core` by adding the `retrieve_list` option.

**Comment by ramirezfranciscof** [comment]
As a note that might be relevant: we are not considering the same exposition for the other lists (`local_copy_list`, `remote_copy_list` and `symlink_copy_list`) because the files present in the folder when the calculation is ran may affect the behaviour of the code and thus is better to keep these under the control of the plugin developer.

**Comment by giovannipizzi** [comment]
Also, @ramirezfranciscof if this gets implemented before your TransferCalcJob PR #4194 is implemented, you could just leverage this flag rather than having custom input flags to decide what to retrieve in the `instructions`? Maybe you could even try to implement this first?

**Comment by ramirezfranciscof** [comment]
I mean, the problem with that is that the user would need to first set up the regular lists and then set up this `additional_retrieve_list` manually themselves vs just setting a keyword that will automatically copy all of the other list's files. I mean, it might be useful in a strange "hybrid" case where the user wants to upload to the remote folder and bring back some files simultaneously, but I think the "switch" keyword is still the best way to go for normal usage.
