### ISSUE TITLE
Add `verdi group move-nodes` command

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#4426]
When moving nodes from one group to another, the user now has to execute two commands, e.g.:
```
verdi group remove-nodes -G source_group <node_pks>
verdi group add-nodes -G target_group <node_pks>
```
Instead, it might be useful to have a `verdi group move-nodes` command, which executes both steps in one command:
```
verdi group move-nodes -s source_group -t target_group <node_pks>
```

**Comment by giovannipizzi** [comment]
Fully in support of this! :-)

**Comment by mbercx** [comment]
> Fully in support of this! :-) (I guess this should however warn you or even fail if the node does not exist in the source group)

Thanks for your support! ^^ I agree with your comment, but perhaps we should also apply this remark to the `Group.remove_nodes()`/`verdi group remove-nodes` commands? See #4438.
