### ISSUE TITLE
aiida-core source distributions missing on pypi.org for versions 1.4.1 and v1.4.2

### ISSUE THREAD

**Issue by astamminger** [aiidateam/aiida-core#4447]
### Describe the bug

Starting with aiida-core version 1.4.1 only ``wheel`` files are available on [pypi](https://pypi.org/project/aiida-core/1.4.1/#files) but it seems like no source tarball is distributed since that version. This breaks the AiiDA recipe on ``conda-forge``: https://github.com/conda-forge/aiida-core-feedstock/pull/39

### Steps to reproduce

Check-out the listed files for [aiida-core v1.4.1](https://pypi.org/project/aiida-core/1.4.1/#files) /   [aiida-core v1.4.2](https://pypi.org/project/aiida-core/1.4.2/#files) and start to wonder

### Expected behavior

A source distribution should be available from pypi

**Comment by sphuber** [comment]
Thanks for the report @astamminger . I am not sure what happened this time. I built the distribution and uploaded it exactly as normal, at least I don't recall making an explicit change in the procedure. Anyway, I rebuilt the versions 1.4.1 and 1.4.2 and pushed it again. They now contain the source tarball on PyPI. It also uploaded another a wheel, this time only for Python 3, whereas the original one is marked as both Python 2 and 3. Hope that won't cause problems elsewhere. Could you please try to see if this has addressed the problem for conda?

**Comment by astamminger** [comment]
Hi @sphuber and thanks for the quick fix. Yes, I was also wondering because I checked and did not find any relevant changes that would affect this, super strange. I will check if the conda builds are passing now and report back here! Thanks again!

**Comment by astamminger** [comment]
@sphuber looks good :) conda builds for ``1.4.1`` and ``1.4.2`` have both passed! Closing this issue and thanks again 👍
