### ISSUE TITLE
Docs: move 'datatypes' content to new topic section

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4449]
This is a structure that was left over from the old documentation and needs to be removed, but first we need to check if all the content has been re-assigned in the new documentation. The files considered are:

- [ ] [bands.rst](https://aiida-core.readthedocs.io/en/v1.1.0/datatypes/bands.html)
- [ ] [functionality.rst](https://aiida-core.readthedocs.io/en/v1.1.0/datatypes/functionality.html)
- [ ] [index.rst](https://aiida-core.readthedocs.io/en/v1.1.0/datatypes/index.html)
- [ ] [kpoints.rst](https://aiida-core.readthedocs.io/en/v1.1.0/datatypes/kpoints.html)

### Proposition:

It is not clear to me what to do with this, maybe we should create a "Topics/data" section for this?

**Comment by mbercx** [comment]
> It is not clear to me what to do with this, maybe we should create a "Topics/data" section for this?

👍 I'd be in favour of having a "Topics/Data Types" section, which explains the purpose/content of each data type and maybe some basic usage. Let's see if the others agree, if so I'm happy to work on this.

**Comment by sphuber** [comment]
Let's create a new topic called `Data types` and move the existing content there. Propose to start with the data types that are generic and will stay in `aiida-core`, followed by a section for the materials science specific ones that will be moved out of the package at some point. This will make the move easier as well.

**Comment by ramirezfranciscof** [comment]
To whoever takes this: please delete the old files in the PR with the new section.

**Comment by mbercx** [comment]
While working on this, I noticed that the [`functionality.rst`](https://aiida-core.readthedocs.io/en/v1.1.0/datatypes/functionality.html) file contains mainly information on how to export the data types. Some of this information is data type specific, so perhaps this can be put as usage examples in the topics section, but it starts with some more general content on exporting data that may be more at home in the "How to - share data" section (see #3998).

I'll move it into the "Topics - Data Types" section for now as I rework it, but if we don't move it we should at least link to it from the "How to - share data" section.
