### ISSUE TITLE
Docs: remove old content from 'get_started/' and 'restapi/'

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4453]
This are two structures that were left over from the old documentation and need to be removed, but first we need to check if all the content has been re-assigned in the new documentation. The files considered are:

- [x] [get_started/index.rst](https://aiida-core.readthedocs.io/en/v1.1.0/get_started/index.html) - install plugin  #4468 
- [x] [get_started/index.rst](https://aiida-core.readthedocs.io/en/v1.1.0/get_started/index.html) - develop plugin #4468 
- [x] restapi/index.rst (unlinked in the old docs) - Move "Running the REST API" to "How to share data => AiiDA REST API"
- [x] restapi/index.rst (unlinked in the old docs) - "Serving your data to others" ("Running REST API in production mode" subsection in "Serving data over REST API")
- [x] restapi/index.rst (unlinked in the old docs) - Move "General form of URLs" to REST API Reference section

### Proposition:

~~The first one (`get_started/index.rst`) actually mostly contains infor on installing existing plugins, and could maybe go in a "plugin" section of ["howto: manage your installation"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/installation.html). The second one contains some information on the internals of the RestAPI and should probably be considered for the [corresponding section](https://github.com/aiidateam/aiida-core/issues/4043).~~

See comments

**Comment by mbercx** [comment]
> The first one (`get_started/index.rst`) actually mostly contains infor on installing existing plugins, and could maybe go in a "plugin" section of ["howto: manage your installation"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/installation.html). 

Isn't this also partly discussed in ["How to run external codes"](https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_codes.html)? I suppose adding a short piece on how to find/install plugins to the "How to manage your installation" section.

I would definitely be in favour of adding more reminders about `reentry scan/verdi daemon restart`though, can't have enough of those! 😄 

> The second one contains some information on the internals of the RestAPI and should probably be considered for the [corresponding section](https://github.com/aiidateam/aiida-core/issues/4043).

👍

**Comment by sphuber** [comment]
There should be a dedicated section that explains how to install plugins. Should go a bit like:
* Link to registry explaining how plugins can be found
* explain installation: `pip install` and `reentry scan`
* explain `verdi plugin list`.
* Say very important, after you install new plugin -> `verdi daemon restart --reset`.

This section could either be in a "Installing plugins" subsection of the "How to manage installation" section, or it could even become its own toplevel How-to "How to install plugins". This is very important information and should maybe not be buried in some other section. Once we have this easy to find section, other locations that explain this process in any amount of detail can simply be updated to link to this new section instead, reducing duplication.

The more detailed information about what `pip install -e` actually does, should not go in this section. If we want to keep it, we should move it probably to the "How to develop a plugin" section for plugin developers.


The `restapi` content should be merged with the REST API Reference section. All the endpoints seem to already be there, but information about offsets, pagination etc. not yet.

**Comment by sphuber** [comment]
@ltalirz the old content of `restapi/index.rst` should be partially moved to the reference and the intro part will go to the new "How to share data"

**Comment by ltalirz** [comment]
Thanks for the ping! I've updated the issue description to reflect the status quo.
I can take care of `Move "Running the REST API" to "How to share data => AiiDA REST API"`

Is someone else already working on `Move "General form of URLs" to REST API Reference section` ?
