### ISSUE TITLE
`verdi data` tab completition is broken

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida-core#4455]
### Describe the bug

`verdi data` tab completion is broken.

The error produced is:
```
  File "/home/max/tut/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/max/tut/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/max/tut/lib/python3.6/site-packages/click/core.py", line 777, in main
    _bashcomplete(self, prog_name, complete_var)
  File "/home/max/tut/lib/python3.6/site-packages/click_completion/patch.py", line 133, in _shellcomplete
    do_bash_complete(cli, prog_name)
  File "/home/max/tut/lib/python3.6/site-packages/click_completion/core.py", line 170, in do_bash_complete
    echo('\t'.join(re.sub(r"""([\s\\"'()])""", r'\\\1', opt) for opt, _ in choices), nl=False)
  File "/home/max/tut/lib/python3.6/site-packages/click_completion/core.py", line 170, in <genexpr>
    echo('\t'.join(re.sub(r"""([\s\\"'()])""", r'\\\1', opt) for opt, _ in choices), nl=False)
  File "/home/max/tut/lib/python3.6/site-packages/click_completion/core.py", line 131, in get_choices
    choices.append((name, ctx.command.get_command_short_help(ctx, name)))
  File "/home/max/tut/lib/python3.6/site-packages/click_completion/patch.py", line 78, in multicommand_get_command_short_help
    return self.get_command(ctx, cmd_name).get_short_help_str()
AttributeError: 'NoneType' object has no attribute 'get_short_help_str'

```

### Steps to reproduce

from command line type `verdi data` and `Tab`

### Your environment

- Operating system [e.g. Linux]: Quantum mobile 20.06.1 (Ubuntu  18.04.4)
- Python version [e.g. 3.7.1]: 3.6.9
- aiida-core version [e.g. 1.2.1]: 1.4.2

**Comment by sphuber** [comment]
This might be a problem of a plugin having installed entry points in the `aiida.cmdline.data`. Can you run `verdi plugin list aiida.cmdline.data` to see which you have installed. For me the tab completion is working just fine on `aiida-core==1.4.2`

**Comment by bosonie** [comment]
Thanks Sebastiaan. I verified and the problem is actually that I simply didn't do `reentry scan` after installing a plugin that contains  `aiida.cmdline.data` entry point.
Do you think I should open a more informative issue? I guess it won't be easy though to add a more informative error message.

**Comment by sphuber** [comment]
> Do you think I should open a more informative issue?

No, we can keep this issue. I will update the issue title to include the additional information.

> I guess it won't be easy though to add a more informative error message.

Indeed it won't. As you can see from the stacktrace, it does not involve any calls in code of AiiDA. The completion is taken care fully by the `click-completion` plugin for `click`. I am not sure how we would hook into to this to either capture the exception, or even hook into it before. Even if we could, it wouldn't be necessarily easy to fix, because somehow we would have to detect an outdated entry point cache, but for that we would have to refresh the cache, which is exactly what we do not want to do for every `verdi ` call as it would slow things down way too much.

**Comment by chrisjsewell** [comment]
`reentry scan` is no longer required (https://github.com/aiidateam/aiida-core/commit/3ad071244332cc78e4be597a05ad5703d17787bd) so I guess we can close this?
