### ISSUE TITLE
Go to RemoteData directory

### ISSUE THREAD

**Issue by pfebrer96** [aiidateam/aiida-core#4456]
### Is your feature request related to a problem? Please describe

Everytime I need to go check a file of a simulation I need to `verdi node show` the calculation node, then look for the pk of the `RemoteData` node, then `verdi node attributes <pk>`, manually copy the path, and then finally `cd <path>` (previously ssh-ing if it's not a local folder.)

### Describe the solution you'd like

Is there a better way to go to the remote folder of a calculation in aiida that I've not noticed? 

I would like to, at least, be able to do `verdi data remote cd <pk>` (or something similar).

It would be incredibly awesome if I could just `verdi node cd <pk>`. Here, I guess that each node would need to have their own implementation of `cd`, but it would allow me to go to the directory just using the pk of the calculation :)

Thanks in advance!

**Comment by greschd** [comment]
You can use `verdi calcjob gotocomputer <calculation_pk>`.

**Comment by pfebrer96** [comment]
Ok, great, thank you very much!
