### ISSUE TITLE
Docs: Move "modifying the schema" to the wiki

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4471]
Content can be found on `core/modifying_the_schema.rst` (see [old documentation](https://aiida-core.readthedocs.io/en/v1.1.0/developer_guide/core/modifying_the_schema.html))

**Comment by CasperWA** [comment]
The ["Modifying the database schema"](https://github.com/aiidateam/aiida-core/wiki/Modifying-the-database-schema) wiki page has just been created and the content has been updated to fit the new format.
Some minor fixes to the text has also been added.

Keeping this issue open to close by a PR that removes the `modifying_the_schema.rst` file.

**Comment by CasperWA** [comment]
Note, this is part of #4451, but the reference was, for one reason or another, not added to this issue.
