### ISSUE TITLE
Docs: Move docs on caching

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4472]
From #4451 

Move the content of "Controlling hashing" and "Design guidelines" inside of `core/caching.rst` to `topics/provenance/caching` (see the [old documentation](https://aiida-core.readthedocs.io/en/v1.1.0/developer_guide/core/caching.html)).

**Comment by sphuber** [comment]
Will be done in conjunction with #2549

**Comment by ramirezfranciscof** [comment]
This was already done in #4228

**Comment by ltalirz** [comment]
@ramirezfranciscof Have you check

> This was already done in #4228

Have you checked the PR?

I think this is not true - there is both a user-facing documentation (which was handled in the PR) and a developer-facing one

**Comment by ramirezfranciscof** [comment]
This issue was about the user-facing documentation. The developer-facing one was mentioned in (this issue)[https://github.com/aiidateam/aiida-core/issues/4038] which is being handled by @chrisjsewell .

**Comment by ltalirz** [comment]
> This issue was about the user-facing documentation.

I don't think so; see the link to the [old documentation](https://aiida-core.readthedocs.io/en/v1.1.0/developer_guide/core/caching.html) at the top as well as the matching description in the issue

> Move the content of "Controlling hashing" and "Design guidelines" 

In any case, it's fine if it is handled somewhere else.

**Comment by ramirezfranciscof** [comment]
I'm not sure I understand what you mean. From the [originating issue](https://github.com/aiidateam/aiida-core/issues/4451) the instructions on what to do with this section was:

> * core/caching.rst: The first section is "Controlling hashing" needs to go to topics/provenance/caching since this is user facing information, not for core developers. The "Design guidelines" should be merged into this new section.
> * core/caching.rst: The "Controlling caching" section should go to a section in the internals/engine.rst

I opened this with the instructions from the first item (which I understand is the user-facing part), and copied the second in the `internals` issue I mentioned before (developer-facing). Am I missing anything?

**Comment by ltalirz** [comment]
Thanks for the clarification, I indeed missed that you guys decided to consider part of the sections in the [old documentation](https://aiida-core.readthedocs.io/en/v1.1.0/developer_guide/core/caching.html) to be user-facing (while, originally, all of this was considered to be too detailed for the user).

At the same time, I believe you may have overlooked that there were *two* pages on caching in the old documentation - a [user-facing one](https://aiida-core.readthedocs.io/en/v1.1.0/working_with_aiida/index.html#caching) and a [developer-facing one](https://aiida-core.readthedocs.io/en/v1.1.0/developer_guide/core/caching.html) (the one linked above).

PR #4228 only took care of moving the user-facing one to the new docs.

In particular, you won't find the sections "Controlling hashing" and "design guidelines" anywhere in 
 https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/provenance/caching.html

**Comment by ramirezfranciscof** [comment]
Oh wow, you are completely right. I thought the content looked differently because it was re-worked but now I see this is a different content. Nice catch @ltalirz, thanks!
