### ISSUE TITLE
Docs: move the public API list from `working_with_aiida`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4483]

**Comment by ramirezfranciscof** [comment]
This is regarding the content of working_with_aiida/python_api.rst (see old documentation) in #4452

> this is actually user facing documentation. It tells users which resources are intended to be used by clients and therefore come with stability guarantees. Ideally then, it should be close to the actual API reference. However, this one is automatically generated, so we should see how to best integrate it.

I will add the "requires discussion" tag because I understood the situation was (according to quoted text) that we still didn't know where or how this needed to be incorporated.
