### ISSUE TITLE
Docs: use `verdi process status` in tutorial

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4505]
### Describe the current issue
The `verdi process status` command is very useful to debug runs of WorkChains, since it helps pinpointing where the original exception occurred - e.g.

```
$ verdi process status 596175
ZeoppMultistageDdecWorkChain<596175> Excepted [2:run_zeopp_after]
    ├── NetworkCalculation<596176> Finished [0]
    ├── get_structure_from_cif<596184> Finished [0]
    └── Cp2kMultistageDdecWorkChain<596186> Excepted [1:run_cp2kddec]
        └── Cp2kMultistageWorkChain<596187> Excepted [None]
            └── check_resize_unit_cell_legacy<596188> Finished [0]
```
This command is currently mentioned only once in the documentation (in [topics/processes/usage](https://aiida-core.readthedocs.io/en/latest/topics/processes/usage.html#verdi-process-status) ).

One reason why this currently isn't mentioned in the tutorial may be because the tutorial relies on `verdi graph generate` and `verdi process status` is relevant mainly for debugging.
I'm not saying that we need to introduce a bug in the example workchain that they need to fix (that would make things too long), but in my experience, debugging workchain runs is one of the most likely things new users need to do and we should  make sure that they know the `verdi process status` command.

### Describe the solution you'd like

I propose to add this command to the tutorial at the end of https://aiida-core.readthedocs.io/en/latest/intro/tutorial.html#workflows as another quick way to look at the tree of a workchain for debugging purposes.

Thoughts @mbercx @csadorf ?

**Comment by mbercx** [comment]
👍 I agree that it would be good if users are made aware of this command straight away in the basic tutorial. I use this command a lot more in practise compared to e.g. generating the provenance graph. And I wasn't aware of it before you mentioned it! 😅  (I think in the context of the Virtual tutorial)

I would maybe add it right before the user generates the final provenance graph, i.e. before "We can now generate the full provenance graph <...>".

**Comment by sphuber** [comment]
>  is relevant mainly for debugging.

Don't really agree with this. Although it is useful for debugging, it is also useful (and designed mostly for) when running bigger workchains with lots of steps and variable pathways. It gives the best overview of the steps a workchain took, very useful also when everything ran as expected without anything to debug

**Comment by csadorf** [comment]
I'm in favor of adding it to the tutorial and fairly impartial about where.

**Comment by ltalirz** [comment]
Great, thanks @mbercx for volunteering to fix this!
