### ISSUE TITLE
Docs: update cheatsheet and link to it

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4506]
### Describe the current issue

This is a feedback received from new user @mpougin - she found the [cheatsheet](https://aiida-tutorials.readthedocs.io/en/latest/_downloads/5f69c3f9ce1f31f1f959b3da46fdc99d/cheatsheet.pdf) very helpful, especially the first page.

For the second page, she suggest to add hyperlinks to the documentation (i.e. just making e.g. the words clickable), which I think makes sense given that many people are using the materials in a digital form nowadays.

### Describe the solution you'd like

I suggest to consider:
 * updating the cheatsheet
 * making it a little more general so that it can become part of the official documentation (rather than being specific to a tutorial)
 * adding hyperlinks for users who use it in digital format

**Comment by sphuber** [comment]
Cheatsheet was integrated in #6332
