### ISSUE TITLE
local mypy failure

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4507]
### Describe the bug

When running mypy locally, on the current `develop` I get

```
$ pre-commit run mypy --file aiida/tools/importexport/dbexport/__init__.py
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

aiida/tools/importexport/dbexport/__init__.py:1221: error: Incompatible return value type (got "Tuple[float, Optional[float], Any, Any]", expected "Tuple[float, float, float, float]")
Found 1 error in 1 file (checked 1 source file)
```
while on CI the test passes.

It seems that my mypy is not recognizing the `# type: ignore` statement
https://github.com/aiidateam/aiida-core/blob/23757ab84df41dc7f9a311803b6fdb0c7338570e/aiida/tools/importexport/dbexport/__init__.py#L1219-L1223

This is weird, because mypy is installed inside its own virtual "hook" environment, i.e. it should really be quite locked down.
Just mentioning this here in case anyone else happens to run into this.

### Your environment

- Operating system: MacOS
- Python version: 3.7.1
- aiida-core version: `develop`

**Comment by chrisjsewell** [comment]
Yeh that is weird. Did you try with python 3.8 (e.g. I use `tox -e py38-pre-commit`), because that's the only difference I can think of?

**Comment by chrisjsewell** [comment]
FYI this is because it is reporting the error on a different line to which the `# type: ignore` is on. I have also encountered this in a different bit of code. The "brute force" way to fix is to include the ignore comment on both lines.
Perhaps there was a change in mypy or it really is intermittent

**Comment by ltalirz** [comment]
I no longer encounter this issue
```
$ pre-commit run mypy --file aiida/tools/importexport/dbexport/__init__.py
mypy.....................................................................Passed
```

For future reference, these are my mypy versions
```
$ pip list | grep mypy
mypy                     0.790
mypy-extensions          0.4.3
```
