### ISSUE TITLE
ZeroDivisionError: percent_load = (active_slots / available_slots)

### ISSUE THREAD

**Issue by blokhin** [aiidateam/aiida-core#4512]
NB for a severely overloaded environment (_e.g._ all the Postgres `max_connections` are busy) this place produces an error:

https://github.com/aiidateam/aiida-core/blob/33c9f41d029a22640646be295b9316c533685b19/aiida/cmdline/utils/common.py#L509

**Comment by chrisjsewell** [comment]
cheers will fix in #4513
