### ISSUE TITLE
Finishing the last stretch of the doc-days

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#4524]
During the dedicated doc days we managed to get done almost all of the most pressing outstanding issues regarding the [documentation revamp](https://github.com/aiidateam/aiida-core/projects/18), great job everyone!

However, even though there have been just a couple of issues that remain to be done, things have naturally become slower now. To help with that so that we can fully close this workbatch, I'm opening this issue to gather here all tasks that remain to be done and ping the people in charge to check the status of each.

1. [Flow of introduction](https://github.com/aiidateam/aiida-core/issues/4254) (PR #4496): Work in progress by @csadorf, will be reviewed by me. Do you have an estimate on when this could be ready?
2. [Topics - Scheduler Plugin](https://github.com/aiidateam/aiida-core/issues/3989) (PR #4476): Work done by @yakutovicha , pending review by @sphuber, do you think you can take a look at this today?
3. [Topics - Datatypes](https://github.com/aiidateam/aiida-core/issues/4449) (PR #4469): Work done by @mbercx , pending review/feedback by @giovannipizzi . Not sure if maybe you had any discussion in person/zoom, but in the PR it seems @mbercx is waiting for @giovannipizzi to reply to some questions.
4. [How to Extend Workflows](https://github.com/aiidateam/aiida-core/issues/3993) (PR pending): This should also incorporate whatever suggestion remains relevant from [this older issue](https://github.com/aiidateam/aiida-core/issues/1927). This is in charge of @mbercx and I will be reviewing it; are you currently working in this? do you have an estimate of when you could make a PR?
5. [Topics - Caching](https://github.com/aiidateam/aiida-core/issues/4472) (PR pending): This should also incorporate the documentation related suggestions from [this other issue](https://github.com/aiidateam/aiida-core/issues/2549). This is in charge of @ltalirz , were you able to take a look at this and decide what can be incorporated now and what should be left for the future?

Please, if you were tagged above, check the item and reply here to any question addressed to you so that we can assess the status of this. Thanks!

**Comment by ltalirz** [comment]
> Topics - Caching (PR pending): This should also incorporate the documentation related suggestions from this other issue. This is in charge of @ltalirz , were you able to take a look at this and decide what can be incorporated now and what should be left for the future?

This is not really urgent and I don't have time for it right now. We can take care of it during the next coding days; feel free to unassign me.

**Comment by sphuber** [comment]
I will look at #4476 now

**Comment by ramirezfranciscof** [comment]
> I will look at #4476 now

@sphuber thanks!

> This is not really urgent and I don't have time for it right now. We can take care of it during the next coding days; feel free to unassign me.

Mmm, ok; although the topic may not be super urgent, this involves re-incorporating some of the old content into the new docs which was one of the "objectives" of this days, so at least that part we should finish. If you are busy then I can take care of doing [that re-incorporation](https://github.com/aiidateam/aiida-core/issues/4472) and then we can leave for later [your compiled improvements](https://github.com/aiidateam/aiida-core/issues/2549).

**Comment by csadorf** [comment]
> [Flow of introduction](https://github.com/aiidateam/aiida-core/issues/4254) (PR #4496): Work in progress by @csadorf, will be reviewed by me. Do you have an estimate on when this could be ready?

I think that should be ready by early next week.

**Comment by mbercx** [comment]
> 3. [Topics - Datatypes](https://github.com/aiidateam/aiida-core/issues/4449) (PR #4469): Work done by @mbercx , pending review/feedback by @giovannipizzi . Not sure if maybe you had any discussion in person/zoom, but in the PR it seems @mbercx is waiting for @giovannipizzi to reply to some questions.

The PR is waiting for @giovannipizzi's review indeed, but I think Gio mentioned that it's ok to merge for now. I'll definitely be opening another issue to add the final data types, so I can go over the whole section again at that time. 

> 4. [How to Extend Workflows](https://github.com/aiidateam/aiida-core/issues/3993) (PR pending): This should also incorporate whatever suggestion remains relevant from [this older issue](https://github.com/aiidateam/aiida-core/issues/1927). This is in charge of @mbercx and I will be reviewing it; are you currently working in this? do you have an 
estimate of when you could make a PR?

I've already done some work on this, but it's not quite finished. I'll prioritise this so I can have a first draft today/tomorrow.

**Comment by ramirezfranciscof** [comment]
> I've already done some work on this, but it's not quite finished. I'll prioritise this so I can have a first draft today/tomorrow.

I see, no hurry. Probably I won't have time to review this tomorrow so I will anyways do it on friday.

> The PR is waiting for @giovannipizzi's review indeed, but I think Gio mentioned that it's ok to merge for now. I'll definitely be opening another issue to add the final data types, so I can go over the whole section again at that time.

Ok, then could you rebase it and change the draft status so then @giovannipizzi can leave an aproving review? I can merge it afterwards. Also, best if you can open the issue now so that we don't forget. Thanks!

**Comment by yakutovicha** [comment]
#4476 is done, btw.

**Comment by chrisjsewell** [comment]
Closing this, since all the referenced PRs have been merged
