### ISSUE TITLE
Scheduler plugins: virtual and physical memory mix-up

### ISSUE THREAD

**Issue by eimrek** [aiidateam/aiida-core#4526]
Hi AiiDA developers,

In most schedulers the `metadata.options.max_memory_kb` input to a `CalcJob` specifies the physical or "real" memory limit. For example in the Slurm plugin:

https://github.com/aiidateam/aiida-core/blob/55f8706e8ecfb37745efe6bc838719b8dceed1fa/aiida/schedulers/plugins/slurm.py#L382-L395

The `#SBATCH --mem=` directive is used, which set the real (physical) memory limit (https://slurm.schedmd.com/sbatch.html). To set the virtual memory limit, one would use the `VSizeFactor` parameter in `slurm.conf` (https://slurm.schedmd.com/slurm.conf.html). The Slurm plugin implementation is fine, except for the `virtual_memory_kb` variable name.

In the Direct scheduler, however, the virtual memory limit is set with the `ulimit -v` directive:

https://github.com/aiidateam/aiida-core/blob/55f8706e8ecfb37745efe6bc838719b8dceed1fa/aiida/schedulers/plugins/direct.py#L144-L155

In addition to being inequivalent to other schedulers, setting the virtual memory limit is less convenient, as the virtual memory usage is usually much higher than physical memory usage and in the end, much of the used virtual memory might never end up in physical memory (e.g. if the program loads a large library but only uses a small part of it).

A specific example how this problem manifested is in this PR: https://github.com/aiidateam/aiida-common-workflows/pull/57 (i.e. i have to ask a high virtual memory limit for a gaussian calculation, even when the real physical memory usage will be quite low).

**Comment by chrisjsewell** [comment]
thanks @eimrek, do you have any suggestions of what you'd like to see the fix be 😬

**Comment by eimrek** [comment]
hey @chrisjsewell, one option would be to just ignore the `max_memory_kb` for the direct scheduler (or make it unsupported). Another option is to implement something that is proposed e.g. [here](https://unix.stackexchange.com/questions/134414/how-to-limit-the-total-resources-memory-of-a-process-and-its-children/174894). For example the `cgroups`  solution, but that might require installing additional packages and would be quite complex in the end, I think.
