### ISSUE TITLE
Verdi export unflexible: due to not toggleable GraphTraversalRules

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida-core#4537]
In my view the export command needs to be more flexible and should support/expose the creation of any export the user wishes and can basicly do.
Currently, it enforces traverser rules which are not toggleable and can therefore not be overridden in the verdi command.
The default setting is sensible of course.

### Is your feature request related to a problem? Please describe
Thus for example creating an export of just a set of single (result) nodes (Dicts, structures, whatever) WITHOUT large parts of the provenance (because I do not want to export it) is not allowed through the verdi export command.

The default GraphTraversalRules Export rules are:
```
{'input_calc_forward': GraphTraversalRule(link_type=<LinkType.INPUT_CALC: 'input_calc'>, direction='forward', toggleable=True, default=False),
 'input_calc_backward': GraphTraversalRule(link_type=<LinkType.INPUT_CALC: 'input_calc'>, direction='backward', toggleable=False, default=True),
 'create_forward': GraphTraversalRule(link_type=<LinkType.CREATE: 'create'>, direction='forward', toggleable=False, default=True),
 'create_backward': GraphTraversalRule(link_type=<LinkType.CREATE: 'create'>, direction='backward', toggleable=True, default=True),
 'return_forward': GraphTraversalRule(link_type=<LinkType.RETURN: 'return'>, direction='forward', toggleable=False, default=True),
 'return_backward': GraphTraversalRule(link_type=<LinkType.RETURN: 'return'>, direction='backward', toggleable=True, default=False),
 'input_work_forward': GraphTraversalRule(link_type=<LinkType.INPUT_WORK: 'input_work'>, direction='forward', toggleable=True, default=False),
 'input_work_backward': GraphTraversalRule(link_type=<LinkType.INPUT_WORK: 'input_work'>, direction='backward', toggleable=False, default=True),
 'call_calc_forward': GraphTraversalRule(link_type=<LinkType.CALL_CALC: 'call_calc'>, direction='forward', toggleable=False, default=True),
 'call_calc_backward': GraphTraversalRule(link_type=<LinkType.CALL_CALC: 'call_calc'>, direction='backward', toggleable=True, default=True),
 'call_work_forward': GraphTraversalRule(link_type=<LinkType.CALL_WORK: 'call_work'>, direction='forward', toggleable=False, default=True),
 'call_work_backward': GraphTraversalRule(link_type=<LinkType.CALL_WORK: 'call_work'>, direction='backward', toggleable=True, default=True)}
```

### Other solutions

Of course I can call ```export``` in python myself with any GraphTraversalRule set I like, so in principle these types of exports are allowed and should be, but they are not supported through the verdi command line.

### Describe the solution you'd like
Make all GraphTraversalRule toggleable, but keep the sensible default of course .
(could be that something similar applies to other GraphTraversalRules sets)

**Comment by ramirezfranciscof** [comment]
> Thus for example creating an export of just a set of single (result) nodes (Dicts, structures, whatever) WITHOUT large parts of the provenance (because I do not want to export it) is not allowed through the verdi export command.

Hi @broeder-j ; this example you are describing should be allowed by running `verdi export create --no-create-backward <nodeid>`. At least it seems to be working for me, are you having any issues with it?

For reference, you can see other ways of customizing the traversal rules of the `verdi export` command by running `verdi export create -h`.

Let me know if this is enough to cover all the cases you were considering or not; we tried to think these options so that it will allow any sensible request (your example of a single data node without its creating provenance makes sense because you always "start from a data node" anyway, but we do not allow exporting a single calc node without its inputs and outputs, for example, as this does not make sense in isolation).

**Comment by broeder-j** [comment]
@ramirezfranciscof 
I tried the export with everything switched off which is not per default False, i.e ``` verdi export create --no-create-backward --no-call-calc-backward --no-call-work-backward -G 39 41 ...`` 
And I still got large parts of the provenance (i.e >100K nodes instead of 4 K). These two groups containing only Dicts as far as I know. But I will check this. We have data that is connected via `RETURN` and also `INPUT_WORK` links for. So my first attempt was to switch of  just `create-backward` since `return_backward` and `input_work_forward`  is per default False.
In the end I switched all off all rules by modifying aiida-core and then I could export the single nodes. I have not checked in detail which rule I needed. But I will investigate this.

However, it could be and I have not thought about it when I opened the issue, that since my database is old (over time migrated from aiida-core v0.12 to aiida-core v.1.4) there could be some specialties. Through I think all old create links and so on from workchains have been removed in the migrations and on the graphs parts that I looked at the linkage seems ok. (Of course it may be that not all links are shown to me on an exported graph). Overall some classes which have historically been `WorkFunctions` and could create Data should now be `Calcfunctions` and the aiida migration just deleted the create links and the data is connected via return links and pops out of nowhere. In principle this should not cause an issue.

**Comment by ramirezfranciscof** [comment]
> These two groups containing only Dicts as far as I know. But I will check this.

Please do so and report back. I suspect that there might be process nodes in those groups, because toggling `--no-create-backward` should be enough to isolate any data node when creating the export. If this is not the case, there might be a bug in the code rather than a feature request.

> However, it could be and I have not thought about it when I opened the issue, that since my database is old (over time migrated from aiida-core v0.12 to aiida-core v.1.4) there could be some specialties. Through I think all old create links and so on from workchains have been removed in the migrations and on the graphs parts that I looked at the linkage seems ok. (Of course it may be that not all links are shown to me on an exported graph). Overall some classes which have historically been WorkFunctions and could create Data should now be Calcfunctions and the aiida migration just deleted the create links and the data is connected via return links and pops out of nowhere. In principle this should not cause an issue.

Mmm I would think this shouldn't be the case since I expected links to be automatically translated during the migrations. We can check it out if you confirm there are only data nodes in your group.

**Comment by broeder-j** [comment]
@ramirezfranciscof: you are right. Thanks!
One group contained also some workchain nodes, I exported the wrong group.

**Comment by ramirezfranciscof** [comment]
Haha, ok, that is a relief on our end because it would have been hard to debug. Thanks!
