### ISSUE TITLE
`verdi --version` can report incorrect version if package is installed in editable mode

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4556]
To reproduce:

1) Install `aiida-core==1.4.2` in editable mode
2) `verdi --version` prints `1.4.2`
3) Switch to `aiida-core==1.4.3`
4) `verdi --version` still prints `1.4.2`

This is a problem of the `@click.version_option` decorator which does not dynamically inspect the linked library version but the version that was copied when it was installed.

**Comment by greschd** [comment]
(Copied from https://github.com/aiidateam/aiida-core/issues/4551#issuecomment-725510905)

Guess that's a limitation of importlib.metadata.version, in the master branch they added some more documentation for that: https://click.palletsprojects.com/en/master/api/#click.version_option

We should be able to get around that by simply passing version=aiida.__version__. That might be a few milliseconds slower, but at least it'll be correct.
