### ISSUE TITLE
v0.9 archives with group extras not importable on aiida v1.4.2

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4560]
### Describe the bug

`subset.aiida` is an export file created with the current `develop` branch (and includes group extras).
```
$ verdi import subset.aiida
Info: importing archive subset.aiida

IMPORT
--------  ------------
Archive   subset.aiida

Parameters
--------------------------  ------
Comment rules               newest
New Node Extras rules       import
Existing Node Extras rules  kcl
Error: an exception occurred while importing the archive subset.aiida
TypeError: string indices must be integers
```

### Steps to reproduce
 1. Install `aiida-core` 1.4.2
 1. wget `https://www.dropbox.com/s/0hm1y89d9go3533/subset_1.aiida?dl=1 -O subset.aiida`
 1. `verdi import subset.aiida`

Note: The export file was created with a group containing extras.
I've created [another export file](https://www.dropbox.com/s/pum3vfwxgtpvqef/subset_1_nogroup.aiida?dl=0) that contains all the nodes of the group but not the group itself.
This export file imports fine on aiida 1.4.2.

**Comment by ltalirz** [comment]
As discussed with @chrisjsewell , this will be fixed by bumping the export file format to v0.10 (with a migration that does nothing).

**Comment by ltalirz** [comment]
Just as a final clarification: 

As long as the groups exported do not contain extras, import on aiida v1.4.2 works fine.
The following change in the `data.json` makes the import choke under v1.4.2:
```diff
7c7,9
<             "extras" : {},
---
>             "extras" : {
>                "t" : 0
>             },
```

**Comment by chrisjsewell** [comment]
To clarify even further, it is due to the lack of these lines in 1.4.2:

https://github.com/aiidateam/aiida-core/blob/def9a0300b92ea8a844ab4b11523e3721269aac4/aiida/tools/importexport/dbimport/utils.py#L192-L194

**Comment by sphuber** [comment]
Just for my understanding, the export file *is* importable on `develop`, i.e. what will become 1.5? And if so, are you suggesting that you want to create `v1.4.4` with a patch fix?

**Comment by ltalirz** [comment]
> Just for my understanding, the export file _is_ importable on `develop`, i.e. what will become 1.5?

yes.



> And if so, are you suggesting that you want to create `v1.4.4` with a patch fix?

No. We will bump the export file format instead, i.e. export files with groups that contained extras, created from the `develop` branch between Oct 28th 2020 and today will not be importable with aiida < 1.5
I think that is acceptable.
