### ISSUE TITLE
Add `verdi archive` that replaces `verdi export` and `verdi import`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4599]
The commands `verdi export` and `verdi import` are to be deprecated and will be joined into `verdi archive`.

**Comment by chrisjsewell** [comment]
On it 👍

**Comment by sphuber** [comment]
@chrisjsewell just a quick reminder that since this is slated for v1.6.0, this should be ready by next week for review. Can you let me know if you think you will manage, otherwise we can ask someone else. Thanks
