### ISSUE TITLE
Implement a new more efficient format for export archives

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4601]
The new format is described by [AEP #005](https://github.com/aiidateam/AEP/pull/21)

**Comment by sphuber** [comment]
@chrisjsewell I tried to see if this issue already existed, but couldn't find one. Feel free to close it an link the duplicate if that exists.

**Comment by giovannipizzi** [comment]
A comment - a user reported privately that to import the AiiDA file from [this Materials Cloud Archive entry]( https://archive.materialscloud.org/record/2020.60), in Quantum Mobile 20.06.1, the logic volume (hard drive) has to be at least 300GB (as the data is uncompressed), for importing automatic_wannier_provenance.aiida. 

The archive itself is smaller. Therefore, this could be a good dataset to benchmark the requirement in the AEP:
> Exporting/importing an archive should not at any point require more free disk space than 2x the size of the uncompressed AiiDA data

**Comment by chrisjsewell** [comment]
cheers yep now we can finally merge the new repository, I can get back to finishing this

**Comment by ramirezfranciscof** [comment]
Duplicate of #4384 , we can continue the discussion there since these are interlinked topics.
