### ISSUE TITLE
Files in retrieve_list are staged out with incorrect folder hierarchy

### ISSUE THREAD

**Issue by timostrunk** [aiidateam/aiida-core#4609]
### Describe the bug

The documentation states on https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/calculations/usage.html :
``` 
calc_info.retrieve_list = ['output1.out', ''output_folder/output2.out']
The retrieved files will be copied over keeping the exact names and hierarchy. If you require more control over the hierarchy and nesting, you can use tuples of length three instead, with the following items: (...)
```

ExecManager however removes the folder hierarchy of retrieve_list files, when copying from the Sandbox folder. The reason is: 

https://github.com/aiidateam/aiida-core/blob/e303cc450d3dd1e949de39785cbc141aa340ac70/aiida/engine/daemon/execmanager.py#L506

Here AiiDA splits everything except for the actual filename away
In the example this would mean that
sandbox_folder/'output_folder/output2.out' is copied into repository_folder/output2.out

### Steps to reproduce
Use a trivial CalcJob and add the file 'Analysis/core/partial_charges.yml' to the retrieve list. Execute the CalcJob.
Monitor repo folder and sandbox folder, while doing this.

### Expected behavior
The file should end up at repository_folder/Analysis/core/partial_charges.yml but instead it ends up at repository_folder/partial_charges.yml

### Your environment

- Operating system:  Linux 5.9.11
- Python version: 3.8.6 / conda-forge
- aiida-core version: 1.4.3
- rabbitmqctl version 3.8.9
- pg_ctl (PostgreSQL) 12.5

### Additional context
A fix would be in aiida/engine/daemon/execmanager.py: (starting from line 500)

```
        else:  # it is a string
            if transport.has_magic(item):
                remote_names = transport.glob(item)
                local_names = remote_names # Changed line here, default to source hierarchy, this branch is not tested.
            else:
                remote_names = [item]
                local_names = remote_names # Changed line here, default to source hierarchy

        for rem, loc in zip(remote_names, local_names):
            target = os.path.join(folder, loc) 
            target_folder = os.path.split(target)[0] # Get target folder abspath
            os.makedirs(target_folder, exist_ok=True) # subfolder might not exist. Create it here
            transport.logger.debug(
                f"[retrieval of calc {calculation.pk}] Trying to retrieve remote item '{rem}' into {target}"
            ) # Logging message changed to show target.
            transport.get(rem, target, ignore_nonexisting=True)
```

I can send a pull request for this. If requested I can also cut down my calcjob and send it for reproduction.

**Comment by sphuber** [comment]
Thanks @timostrunk , this looks indeed a bug as you describe. A PR is very much welcome, but we should definitely include a test for it. I can help you with that if you are not familiar with it yet.

**Comment by sphuber** [comment]
Thinking about it, just fixing this may introduce more problems. Depending on how long this behavior has been in place plugins may have come to rely on it, even though it doesn't match the documentation. If we were to change it, these plugins may start to fail all of a sudden. @chrisjsewell and @ramirezfranciscof it would be important to try and figure out when this behavior was first introduced to see how long it has been there. I would be willing to wager it has been there for all of `v1.0`. If that is the case, we might actually want to consider the opposite action of updating the docs, provided that there is a way to keep the hierarchy of retrieved files because I can imagine this is a valid use case.

**Comment by timostrunk** [comment]
I also had this thought, i.e. fixing this inconsistency might break existing plugins. I still think it should be fixed, as otherwise lots of unexpected breakage can occur.
One example:
You want to stage out

* folder1/energies
* folder2/eneriges

Now you end up with one energies file in the root and you won't know, which one.

**Comment by sphuber** [comment]
Looking into a bit more detail, I think this may simply be an error in the documentation that you linked. If we look at the documentation in the code of `aiida.common.datastructures.CalcInfo` on the `retrieve_list` attribute it says the following:
```

    * retrieve_list: a list of strings or tuples that indicate files that are to be retrieved from the remote
        after the calculation has finished and stored in the repository in a FolderData.
        If the entry in the list is just a string, it is assumed to be the filepath on the remote and it will
        be copied to '.' of the repository with name os.path.split(item)[1]
        If the entry is a tuple it is expected to have the following format

            ('remotepath', 'localpath', depth)

        If the 'remotepath' is a file or folder, it will be copied in the repository to 'localpath'.
        However, if the 'remotepath' contains file patterns with wildcards, the 'localpath' should be set to '.'
        and the depth parameter should be an integer that decides the localname. The 'remotepath' will be split on
        file separators and the local filename will be determined by joining the N last elements, where N is
        given by the depth variable.

        Example: ('some/remote/path/files/pattern*[0-9].xml', '.', 2)

        Will result in all files that match the pattern to be copied to the local repository with path

            'files/pattern*[0-9].xml'
```
If an element of `retrieve_list` is just a string, i.e. `output/sub/file.txt` it will be  retrieved as `file.txt` i.e. stripping the folders. I am looking now what exactly one should specify (if it is even possible) to retrieve an entire folder.

I am working on a PR that adds significant more testing to try and sort this out, because honestly this syntax of the `retrieve_list` is not intuitive, badly tested and badly documented.

**Comment by timostrunk** [comment]
I agree with you that the documentation in the actual class is correct and reflects current behaviour.

In this case "my" usecase should be explicitly mentioned in the documentation as

    filename = "Analysis/core/partial_charges.yml"
    retrieve_list = [ (filename, filename, 0) ]

This is, what I tried, when the above did not work and it also does not work. It breaks at a different, point, which is:
https://github.com/aiidateam/aiida-core/blob/e57d18df4cb264404770fbc4aa106fa608ccea67/aiida/transports/plugins/local.py#L491
The reason is that the relative folderstructure of filename is not generated prior to copying.

A fix for this would be:

        mylocpath = os.path.split(localpath)[0]
        os.makedirs(mylocpath, exist_ok=True)
        shutil.copyfile(the_source, localpath)



I can open a second bugreport for this, if required.

**Comment by sphuber** [comment]
I think for your use case, you should use the following:
```
filename = "Analysis/core/partial_charges.yml"
retrieve_list = [ (filename, '.', 3) ]
```
and that should work.

**Comment by timostrunk** [comment]
This works, thank you.

I will look at the testing and the docs, once you finish. This bug report can be closed.
