### ISSUE TITLE
CI breaking because `pymatgen` is installing release candidate of `numpy`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4614]
It is that time of the year again and our [CI builds on Python 3.6 are failing](https://github.com/aiidateam/aiida-core/pull/4613/checks?check_run_id=1495195639) because `numpy` released a new candidate version that will remove Python 3.6 support. Since `pymatgen` still hasn't addressed their build problem, it will install the latest release candidate and so we are fucked....

**Comment by chrisjsewell** [comment]
Pymatgen is the worst 😒

**Comment by sphuber** [comment]
Fixed in PR #4615

**Comment by mkhorton** [comment]
👋 hi from the pymatgen side

As we're tracking in https://github.com/materialsproject/pymatgen/issues/2010, we can't identify why this is happening -- our `setup.py` simply requires `numpy>=1.14.3` (as does our conda-feedstock), and if you're installing directly from our `requirements.txt` that's pinned to `numpy==1.19.2`. All our test suites still run and pass in Python 3.6 in CI too.

If you manage to identify the issue though, let us know and I'd be happy to fix.
