### ISSUE TITLE
`BaseRestartWorkChain` does not return `output_namespaces` of `_process_class`

### ISSUE THREAD

**Issue by bosonie** [aiidateam/aiida-core#4623]
I'm not sure whether to consider this as a bug or a feature request.

The `BaseRestartWorkChain`  contains a step `results` that is meant to return the outputs specified in the output specification using the outputs the of last completed process.
The line that does the job is:
https://github.com/aiidateam/aiida-core/blob/e073972ba6b0b83d7d7964750a762da26603fa74/aiida/engine/processes/workchains/restart.py#L277-L280
This mechanism works well for normal outputs, but it ignores `output_namespaces`. In fact the line above checks that the "name" of the output port is equal to any of the return outputs of the last completed process. Supposing the name of the output namespaces is "name", the return outputs of the last completed process will be "name__key" and therefore not detected.

**Comment by JPchico** [comment]
@bosonie do you have a small code where one can reproduce this error?

I have an idea on how to fix it but would be nice to have a small example on this as I do not currently have any `BaseRestartWorkChain` to test this.

**Comment by bosonie** [comment]
No I don't. I can try to build it later. I'll update you tonight

**Comment by bosonie** [comment]
```
from aiida.engine import BaseRestartWorkChain
from aiida.engine import while_, run
from aiida.workflows.arithmetic.multiply_add import MultiplyAddWorkChain

class MyMul(MultiplyAddWorkChain): 
    @classmethod 
    def define(cls, spec): 
             super().define(spec) 
             spec.output_namespace('inpp', valid_type=Int, dynamic=True, required=False) 
         def result(self): 
             inpp={} 
             inpp["test"] = self.ctx.addition.outputs.sum 
             self.out('inpp', inpp) 
             self.out('result', self.ctx.addition.outputs.sum)

class Test(BaseRestartWorkChain): 

         _process_class = MyMul 
         _proc_exit_cod = _process_class.exit_codes 
         
         @classmethod 
         def define(cls, spec): 
             super().define(spec) 
             spec.expose_inputs(MyMul) 
             spec.outline( 
                 cls.setup, 
                 cls.prepare_inputs, 
                 while_(cls.should_run_process)( 
                     cls.run_process, 
                     cls.inspect_process, 
                 ), 
                 cls.results 
             ) 
             spec.expose_outputs(MyMul) 
              
         def prepare_inputs(self): 
             self.ctx.inputs = {"code":self.inputs.code,"x":self.inputs.x,"y":self.inputs.y,"z":self.inputs.z}
```
To run, first set up an add code:
```
verdi code setup -L add --on-computer --computer=localhost -P arithmetic.add --remote-abs-path=/bin/bash -n
```
Then in the shell:
```
a=Test.get_builder()
a.x = Int(1)
a.y = Int(3)
a.z = Int(2)
a.code = load_code(<PKcode>)
run(a)
```
You will see that the `inpp` output is not returned.

**Comment by JPchico** [comment]
@bosonie I see. 

Looking at this if one loop over `self.spec().outputs.items()` one does not have the information needed to pass the `link_label_filter`  as the `port` does not have the information that one needs. 

One can add 
```python
link_types = (LinkType.CREATE, LinkType.RETURN)
process_outputs_dict = node.get_outgoing(link_type=link_types).nested()

for name, port in self.spec().outputs.items():
    output = process_outputs_dict[name]
```
Of that way one can get even the nested namespaces. The only issue then is that one needs to then check if one can loop over that output itself. Then one could construct the `name` of the link that can be passed to `link_label_filter` to determine if the node is required or not. 

It is not the prettiest solution but it is a solution.

**Comment by JPchico** [comment]
@bosonie 

This is a very ugly solution, but it illustrates how one could solve the problem.

In `aiida-core/aiida/engine/processes/workchains/restart.py` one can change the `results` function by something like this.

```python
    def results(self) -> Optional['ExitCode']:
        """Attach the outputs specified in the output specification from the last completed process."""
        node = self.ctx.children[self.ctx.iteration - 1]

        # We check the `is_finished` attribute of the work chain and not the successfulness of the last process
        # because the error handlers in the last iteration can have qualified a "failed" process as satisfactory
        # for the outcome of the work chain and so have marked it as `is_finished=True`.
        max_iterations = self.inputs.max_iterations.value  # type: ignore[union-attr]
        if not self.ctx.is_finished and self.ctx.iteration >= max_iterations:
            self.report(
                f'reached the maximum number of iterations {max_iterations}: '
                f'last ran {self.ctx.process_name}<{node.pk}>'
            )
            return self.exit_codes.ERROR_MAXIMUM_ITERATIONS_EXCEEDED  # pylint: disable=no-member

        self.report(f'work chain completed after {self.ctx.iteration} iterations')

        link_types = (LinkType.CREATE, LinkType.RETURN)
        process_outputs_dict = node.get_outgoing(link_type=link_types).nested()

        for name, port in self.spec().outputs.items():
            try:

                for _key in process_outputs_dict[name].keys():
                    _name = name + '__' + _key
                    self.report(f'name {_name}')
                    try:
                        output = node.get_outgoing(link_label_filter=_name).one().node
                        self.report(f'output: {output}')
                    except ValueError:
                        if port.required:
                            self.report(f"required output '{_name}' was not an output of {self.ctx.process_name}<{node.pk}>")
                    else:
                        self.out(name+'.'+_key, output)
            except AttributeError:

                try:
                    output = node.get_outgoing(link_label_filter=name).one().node
                except ValueError:
                    if port.required:
                        self.report(f"required output '{name}' was not an output of {self.ctx.process_name}<{node.pk}>")
                else:
                    self.out(name, output)

        return None
```
It would be good of course to have a more elegant solution, without having to have so many `try` instances and/or without having to recreate the link name. But I'm a bit unsure of what kind of method one could use.

**Comment by unkcpz** [comment]
I agree this should be regarded as a `bug`, since the baseworkchain is thought to be almost the same as its wrapped process.
Well, I believe this is the case where `out_many` take effect, correct? 

why not simply doing this?
```
    def results(self) -> Optional['ExitCode']:
        """Attach the outputs specified in the output specification from the last completed process."""
        node = self.ctx.children[self.ctx.iteration - 1]

        # We check the `is_finished` attribute of the work chain and not the successfulness of the last process
        # because the error handlers in the last iteration can have qualified a "failed" process as satisfactory
        # for the outcome of the work chain and so have marked it as `is_finished=True`.
        max_iterations = self.inputs.max_iterations.value  # type: ignore[union-attr]
        if not self.ctx.is_finished and self.ctx.iteration >= max_iterations:
            self.report(
                f'reached the maximum number of iterations {max_iterations}: '
                f'last ran {self.ctx.process_name}<{node.pk}>'
            )
            return self.exit_codes.ERROR_MAXIMUM_ITERATIONS_EXCEEDED  # pylint: disable=no-member

        self.report(f'work chain completed after {self.ctx.iteration} iterations')

        # for name, port in self.spec().outputs.items():

        self.out_many(
            self.exposed_outputs(
                node,
                self._process_class,
            )
        )

        return None
```

I test this implementation with test case of @bosonie and it output the `inpp.test`
```
Outputs    PK    Type
---------  ----  ------
inpp
    test   40    Int
result     40    Int
```

**Comment by unkcpz** [comment]
@JPchico you can have a look at the method `exposed_outputs`, it is similar to your implementation above  ;-) https://github.com/aiidateam/aiida-core/blob/2f1c1f82c5085bd311303dfc82c0a3bf67629377/aiida/engine/processes/process.py#L863

**Comment by bosonie** [comment]
Thanks @JPchico and @unkcpz.
The only downside of @unkcpz implementation is that it does not warn (self.report) outputs that were requested but not returned. For me this is not an important feature since a  workchain shouldn't finish with exit code 0 while missing requested outputs. In conclusion, @unkcpz implementation is fine by me.
In any case I do not have expertise nor power here to decide. I believe you can make a PR and ask @ramirezfranciscof review.

**Comment by unkcpz** [comment]
@bosonie thanks for the inputs, I just make a PR at https://github.com/aiidateam/aiida-core/pull/4961 . You may want have a look, where it remains the original exit code check and report.
