### ISSUE TITLE
`ProcessBuilder` looses `AttributeDict` properties of nested namespaces when `_update` is used with nested dictionary

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4630]
When a process builder is updated with a nested dictionary using the `_update` method, the nested namespaces are overwritten by plain dictionaries instead of `ProcessBuilderNamespace` instances, causing the nested namespaces to loose their functionality, such as validation and tab-completion. The solution is to properly recursively apply values of the dictionary in `_update` just setting the values in the namespace instead of overwriting it completely.

**Comment by greschd** [comment]
Probably worth looking at #4420 at the same time, as it touches the same code.

**Comment by sphuber** [comment]
So I am pretty sure that I encountered this bug at some point but didn't create the issue at the time. When I created this issue I didn't try to reproduce and now I actually can't :confused: So until I can, I am going to close this

**Comment by giovannipizzi** [comment]
I managed to reproduce this (for better or for worse :-) ) in the context of the common workflows.

Here a snippet of code (where I want to set the `settings` input to the QE calculation):
```python
from aiida.plugins import DataFactory, WorkflowFactory
from aiida import orm
from aiida.engine import submit

from aiida_common_workflows.common import ElectronicType, RelaxType, SpinType
from aiida_common_workflows.plugins import get_entry_point_name_from_class
from aiida_common_workflows.plugins import load_workflow_entry_point

CODE_LABEL = 'qe-6.7-pw@daint-mc'

Structure = DataFactory('structure')

sub_process_cls = load_workflow_entry_point('relax', 'quantum_espresso')
sub_process_cls_name = get_entry_point_name_from_class(sub_process_cls).name
generator = sub_process_cls.get_input_generator()

engine_types = generator.get_engine_types()
engines = {}
# There should be only one
for engine in engine_types:
    engines[engine] = {
        'code': CODE_LABEL,
         'options': {
            'resources': {
                'num_machines': 1
            },
            'account': 'mr0',
            'max_wallclock_seconds': 3600
        }
    }

structure = orm.load_node(428)
builder = generator.get_builder(structure, engines)
```
(you'll need to replace the PK of th structure, and the name of the code, of course).

Now, my `builder['base']` looks like this:
```
{'metadata': {}, 'pw': {'metadata': {'options': {'resources': {'num_machines': 1}, 'max_wallclock_seconds': 3600, 'withmpi': True, 'account': 'mr0'}}, 'pseudos': {'Ag': <UpfData: uuid: 412a56f8-70fc-46ba-8683-975331b8ccb7 (pk: 111)>, 'O': <UpfData: uuid: 5ddd8424-f424-4fd2-b028-edddf5f3bf30 (pk: 112)>}, 'code': <Code: Remote code 'qe-6.7-pw' on daint-mc, pk: 1, uuid: ffbe4685-9182-4787-a653-32dbc09ae42c>, 'parameters': <Dict: uuid: 24d575ab-1513-415e-9222-91e6ee6b725b (unstored)>}, 'kpoints_distance': <Float: uuid: b17ed4e9-10fd-47a6-b497-28d89076ad0e (unstored) value: 0.15>, 'kpoints_force_parity': <Bool: uuid: abf7dd95-b3fe-44f5-925c-4969089b0159 (unstored) value: False>}
```

If I run `builder._update({'base': {'pw': {'settings': 'new'}}})` (of course I wouldn't have `new` as a value, but this is just to show the behaviour), I get for `builder['base']`:
```
{'metadata': {}, 'pw': {'settings': 'new'}, 'kpoints_distance': <Float: uuid: b17ed4e9-10fd-47a6-b497-28d89076ad0e (unstored) value: 0.15>, 'kpoints_force_parity': <Bool: uuid: abf7dd95-b3fe-44f5-925c-4969089b0159 (unstored) value: False>}
```
where everything disappeared inside the nested `pw` namespace.

This monkey patched code (using recursion, but I don't think we'll hit the recursion limit soon) seems to do the job instead:
```python
import collections

def _dynamically_update(dictionary, key, value):
    if isinstance(value, collections.abc.Mapping):
        for inner_key, inner_value in value.items():
            _dynamically_update(dictionary[key], inner_key, inner_value)
    else:
        #print('_here', dictionary, key, value)
        dictionary[key] = value

def _update(self, *args, **kwds):
    if len(args) > 1:
        raise TypeError(f'update expected at most 1 arguments, got {int(len(args))}')

    if args:
        for key, value in args[0].items():
            _dynamically_update(self, key, value)

    for key, value in kwds.items():
        _dynamically_update(self, key, value)

# Monkeypatching
import functools
builder = generator.get_builder(structure, engines)
builder._update = functools.partial(_update, builder)
```
where now running `builder._update({'base': {'pw': {'settings': 'new'}}})` returns this for `builder['base']['pw']`:
```
{'metadata': {'options': {'resources': {'num_machines': 1}, 'max_wallclock_seconds': 3600, 'withmpi': True, 'account': 'mr0'}}, 'pseudos': {'Ag': <UpfData: uuid: 412a56f8-70fc-46ba-8683-975331b8ccb7 (pk: 111)>, 'O': <UpfData: uuid: 5ddd8424-f424-4fd2-b028-edddf5f3bf30 (pk: 112)>}, 'code': <Code: Remote code 'qe-6.7-pw' on daint-mc, pk: 1, uuid: ffbe4685-9182-4787-a653-32dbc09ae42c>, 'parameters': <Dict: uuid: feec64b3-ab98-41b4-bd65-99615cbdff63 (unstored)>, 'settings': 'new'}
```
i.e., the expected behaviour.

Is the suggested new code OK or do you see a problem with it?
Also, I now do `dictionary[key] = value` inside `_dynamically_update`.
In the current code, there is a call to `__setattr__` instead (lines 140 and 146), on self (a builder):
https://github.com/aiidateam/aiida-core/blob/5ab86cca5fc2070937cfa90b1a479d06878e68dd/aiida/engine/processes/builder.py#L122-L146

 (but this now fails as internally, when iterating, we just get dictionaries). Was there a reason to use `__setattr__` over `__setitem__`?

**Comment by sphuber** [comment]
> In the current code, there is a call to __setattr__ instead (lines 140 and 146), on self (a builder):

The `self` is not actually a `ProcessBuilder` instance but a `ProcessBuilderNamespace`. Now granted, the `ProcessBuilder` is a direct subclass of `ProcessBuilderNamespace` but the point is that `self` here is just a mapping. The bug you describe is different from the OP in this issue but they are related. It is important that all nested dictionaries in the builder are `ProcessBuilderNamespace`s themselves. In the constructor we do this properly recursively, but the `__setattr__` will simply assign the dictionary, overriding everything that was there. This is the original bug that I described. This is why your fix breaks when using `__setattr__` because the `ProcessBuilderNamespace` is replaced by a normal dict which doesn't have a set attribute method. I am looking into it now to fix this and then I can probably add your fix to fix the problem.

The reason we need `__setattr__` is because it is overridden to perform validate the value according to the spec of the corresponding port. This ensure that the port is validated as soon as you assign a value to it, for example:
```
builder.pw.code = Int(5)
```
will raise because the `__setattr__` will validate the value against the port and raise since 'code' needs a `Code` of course.
The `__setitem__` just forwards to `__setattr__` though, so either way the value should get validated.
