### ISSUE TITLE
event loop not nested in Jupyter notebook

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#4635]
Run process in Jupyter notebook cause following exception, since notebook has its own loop and it is not wrap with `nest_asyncio`. 

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-be59121f5c68> in <module>
----> 1 res = dummy(x, y)
~/pyProject/aiida_core/aiida/engine/processes/functions.py in decorated_function(*args, **kwargs)
    173         def decorated_function(*args, **kwargs):
    174             """This wrapper function is the actual function that is called."""
--> 175             result, _ = run_get_node(*args, **kwargs)
    176             return result
    177 
~/pyProject/aiida_core/aiida/engine/processes/functions.py in run_get_node(*args, **kwargs)
    146 
    147             try:
--> 148                 result = process.execute()
    149             finally:
    150                 # If the `original_handler` is set, that means the `kill_process` was bound, which needs to be reset
~/pyProject/aiida_core/aiida/engine/processes/functions.py in execute(self)
    355     def execute(self):
    356         """Execute the process."""
--> 357         result = super().execute()
    358 
    359         # FunctionProcesses can return a single value as output, and not a dictionary, so we should also return that
/data/CONDA_ENV/aiida-testing38/lib/python3.8/site-packages/plumpy/processes.py in func_wrapper(self, *args, **kwargs)
     72         if self._closed:
     73             raise exceptions.ClosedError('Process is closed')
---> 74         return func(self, *args, **kwargs)
     75 
     76     return func_wrapper
/data/CONDA_ENV/aiida-testing38/lib/python3.8/site-packages/plumpy/processes.py in execute(self)
   1055         """
   1056         if not self.has_terminated():
-> 1057             self.loop.run_until_complete(self.step_until_terminated())
   1058 
   1059         return self.future().result()
/data/CONDA_ENV/aiida-testing38/lib/python3.8/asyncio/base_events.py in run_until_complete(self, future)
    590         """
    591         self._check_closed()
--> 592         self._check_running()
    593 
    594         new_task = not futures.isfuture(future)
/data/CONDA_ENV/aiida-testing38/lib/python3.8/asyncio/base_events.py in _check_running(self)
    550     def _check_running(self):
    551         if self.is_running():
--> 552             raise RuntimeError('This event loop is already running')
    553         if events._get_running_loop() is not None:
    554             raise RuntimeError(
RuntimeError: This event loop is already running
```

**Comment by unkcpz** [comment]
I think the crux is that `asyncio.get_event_loop()` will [default return the running loop](https://stackoverflow.com/questions/44000136/using-alternative-event-loop-without-setting-global-policy) if there is one. So a possible restorative procedure can be replace `asyncio.get_event_loop()` with `asyncio.get_event_loop_policy().get_event_loop()` to explicitly calling the expected loop generator(I find this has been in [some other code](https://www.programcreek.com/python/example/82370/asyncio.get_event_loop_policy) and might be the better way to use event loop policy?).

However, the attendant problems, do we then replace all `asyncio.get_event_loop` in code base or which of them should be replace? 
Pining @muhrin who may know a better way to fix this.

**Comment by sphuber** [comment]
I can confirm that the patch is not actually being applied even though we set the event loop policy that should do it.
The following example works:
```
from aiida import load_profile
load_profile()

from aiida import engine
from aiida import orm

@engine.calcfunction
def test(a, b):
    return a + b

import nest_asyncio
import asyncio
loop = asyncio.get_event_loop()
print(loop)
nest_asyncio.apply(loop)
print(loop)

test(orm.Int(1), orm.Int(2))
```
So we just need to figure out why the `get_event_loop` of the `PlumpyEventPolicy` isn't being called and so the patch is not being applied.

**Comment by sphuber** [comment]
Think I found the problem but not sure what the cause of it is. Essentially, in Jupyter, even when we successfully set the event loop policy, calling `asyncio.get_event_loop` still calls the original method and not the one of `PlumpyEventLoopPolicy`. This can be shown by running the following in a notebook:
```
import asyncio
from plumpy import set_event_loop_policy, PlumpyEventLoopPolicy
set_event_loop_policy()
assert isinstance(asyncio.get_event_loop_policy(), PlumpyEventLoopPolicy)
assert hasattr(asyncio.get_event_loop(), '_nest_patched')
```
which will fail at the second assert. The event loop policy was successfully set but the returned loop somehow still is not a patched one. Surprisingly, as soon as I get the loop through the event loop policy once, by calling asyncio.get_event_loop_policy().get_event_loop()` then the loop is patched and even `asyncio.get_event_loop` at that point will return the patched loop.

With this information in hand, I patched the `plumpy.set_event_loop_policy` to actually call this:
```

def set_event_loop_policy():
    """Enable plumpy's event loop policy that will make event loop's reentrant."""
    asyncio.set_event_loop_policy(PlumpyEventLoopPolicy())
    asyncio.get_event_loop_policy().get_event_loop()
```

With this change, it is now possible to run a process function in Jupyter again.

The question is why we have to call `get_event_loop_policy` once manually for `asyncio.get_event_loop` to start returning the patched loop. Is this the expected behavior or is there another problem in our setup?

The weird thing is that we have a test for all of this in `test/test_event.py:test_get_event_loop` which passes. There we don't actually have to call `get_event_loop_policy().get_event_loop()` at all for `asyncio.get_event_loop` to start returning the patched loop. Is the difference because Jupyter maybe also already changed the event loop policy?

**Comment by unkcpz** [comment]
I think the code https://github.com/python/cpython/blob/ba760f3710eccdfae2b680a5f94fe0160ddb1536/Lib/asyncio/events.py#L752-L765 explain what happened in this case. `set_event_loop_policy` only point the `get_event_loop` of the policy to the new one but not really run it. Directly calling the `asyncio.get_event_loop()` in a running loop will skip calling the long in new policy but just retire the running one.

**Comment by unkcpz** [comment]
What you implement now is a choice @sphuber. I think another choice is to reimplement the behaviour of `get_event_loop`(might lower the performance?).

**Comment by sphuber** [comment]
> What you implement now is a choice @sphuber. I think another choice is to reimplement the behaviour of `get_event_loop`(might lower the performance?).

behavior of which `get_event_loop`? The one of `asyncio` or of `PlumpyEventLoopPolicy`? And how would you change it?

**Comment by unkcpz** [comment]
> behavior of which get_event_loop?

I mean the one of `asyncio`, manually patch the loop when it is a running loop. I guess the original behaviour is design to prevent the running loop(already exist one) from overwriting.

**Comment by unkcpz** [comment]
Never mind I think the current workaround is good to go.
