### ISSUE TITLE
yaml failed in constructing numpy object from checkpoint

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#4639]
I get the following exception after restarting the daemon:
```
....
               File "/data/CONDA_ENV/aiida-production/lib/python3.7/site-packages/yaml/constructor.py", line 570, in make_python_instance
                 node.start_mark)                                                      
             yaml.constructor.ConstructorError: while constructing a Python instance                                                                                          
             expected a class, but found <class 'builtin_function_or_method'>
               in "<unicode string>", line 10, column 30:
                   lowest_highest_eigenvalue: !!python/object/apply:numpy.core ...
```

In my workchain I set the `self.ctx.lowest_highest_eigenvalue=np.amin(bands[:, -1])` and yaml refuse to load a function specified in the YAML(https://github.com/yaml/pyyaml/issues/286). I guess this be also related to the switch to safe YAML loading(https://github.com/aiidateam/aiida-core/issues/3709)? @sphuber @greschd 

My point is whether this can be fixed by in the workchain instead of registering `ctx.lowest_highest_eigenvalue` as a numpy function, get the value first and set it in the `ctx`, like:
```
v = np.amin(bands[:, -1])
self.ctx.lowest_highest_eigenvalue = v
```

**Comment by greschd** [comment]
This feels like a duplicate of #3709. Can you try applying the [unsafe workaround](https://github.com/aiidateam/aiida-core/issues/3709#issuecomment-727990256) mentioned there to confirm that it has the same root cause?

Given that it's now come up a few times, maybe we should increase the priority of that issue.

**Comment by unkcpz** [comment]
> This feels like a duplicate of #3709. Can you try applying the unsafe workaround mentioned there to confirm that it has the same root cause?

Yes, that's the same issue. I'd better close this issue at the moment.
