### ISSUE TITLE
'Unexpected end of file' and daemon keeps restart

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#4661]
- [X] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [X] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug
- Operating system [In my local aiidalab-20.12.0]:
- Python version [e.g. 3.7.4]:
- aiida-core version [e.g. 1.4.3]:
- 
I submit a process to daemon and then the daemon keeps doing restarts and my CPU is fully loaded. The process is stay in the running state. What's happening here? what's the meaning of 'Unexpected end of file'.
```
01/14/2021 08:55:10 AM <2933> aiida.engine.daemon.runner: [INFO] Starting a daemon runner
01/14/2021 08:55:10 AM <2933> aiida.orm.nodes.process.workflow.workchain.WorkChainNode: [INFO] Loaded process<31> from saved state
Unexpected end of file
```

Is this the problem of aiidalab @yakutovicha ? OR anyone else see this problem before?
Other relevant software versions, e.g. Postres & RabbitMQ

**Comment by sphuber** [comment]
Have you encountered this problem since @unkcpz ? Or can we close it?

**Comment by unkcpz** [comment]
No, never see this again. I close it.
