### ISSUE TITLE
Computer setup: proposed configure command does not include profile

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4679]
### Is your feature request related to a problem? Please describe

When configuring a new computer, the command proposes to configure the computer next

```
(aiida) ubuntu@qmobile:~$ verdi -p failed-mofs-2021-01-14 computer setup --config aiida-code-registry/daint.cscs.ch/multicore/computer-setup.yaml
Success: Computer<4> daint-mc created
Info: Note: before the computer can be used, it has to be configured with the command:
Info:   verdi computer configure ssh daint-mc
```

However, this command is only correct, if the computer is to be configured on the default AiiDA profile.

### Describe the solution you'd like

In order to be able to just copy-paste this command, there should be a check on whether the `setup` command is being run on the default AiiDA profile, and the proposed command should provide the AiiDA profile parameter (if needed).

**Comment by kenkirito** [comment]
can i work on this

**Comment by lkbhitesh07** [comment]
Hello @ltalirz , I would like to work, but while setting up the environment I'm getting this error, will you please help me out.
Thanks
```
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/ht/opensource/aiida-core
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/ht/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp3op_m41n
       cwd: /home/ht/opensource/aiida-core
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/ht/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/ht/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ht/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/ht/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
WARNING: Discarding file:///home/ht/opensource/aiida-core. Command errored out with exit status 1: /usr/bin/python3 /home/ht/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp3op_m41n Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/ht/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp3op_m41n Check the logs for full command output.
```

**Comment by ltalirz** [comment]
Hey @lkbhitesh07 
hm ... I think you've hit https://github.com/pypa/setuptools/issues/1694#issuecomment-466010982

Maybe try https://github.com/pypa/setuptools/issues/1694#issuecomment-466023567

I haven't heard of this in a while but we might want to have a look back at changing the pyproject.toml setup.

Also, for next time please consider opening a new issue in case you encounter problems like this (since it is not related to this particular thread).

Cheers!

**Comment by lkbhitesh07** [comment]
Hello @ltalirz, As far as I understand that we need to check the setup command, is it running on the default aiida profile or another profile but I'm confused on how to approach this particular issue, where should we look at to filter if we need default aiida profile or other.
Thanks

**Comment by ltalirz** [comment]
hey @lkbhitesh07 , I believe this is available from the "context", see e.g. 
https://github.com/aiidateam/aiida-core/blob/b5a35a683f3b323e787c96d4e1776d6cce0d59e0/aiida/cmdline/params/options/commands/setup.py#L97

**Comment by lkbhitesh07** [comment]
I'm trying to figure it out for past one hour that what's happening and how to fix it but unfortunately I'm not being able to do it, sorry for that. Incase @ltalirz you get some time will you please explain me what should I do as this codebase is totally new.
Thanks
