### ISSUE TITLE
Docs: readthedocs build frequently failing due to timeouts

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4687]
### Describe the current issue

Over the last weeks I've received a couple of notifications on readthedocs builds failing due to exceeding the 400s build timeouts - e.g. https://readthedocs.org/projects/aiida-core/builds/12867886/

### Describe the solution you'd like

First of all, I think someone else from the team should subscribe to these notifications on https://readthedocs.org/dashboard/aiida-core/notifications/ as well - any volunteers?

![image](https://user-images.githubusercontent.com/1053245/105987584-c1f39f00-609e-11eb-8499-fd18ab5b961e.png)

Second, we may either need to look into ways of speeding up the build or ask rtd for an extension

**Comment by ltalirz** [comment]
Looking into it in more detail, it seems like it's actually not the build time, it's .... pymatgen!

Last working build https://readthedocs.org/projects/aiida-core/builds/12478281/
First failing build (all afterwards faild) https://readthedocs.org/projects/aiida-core/builds/12491656/

I think it's likely that the reason is pymatgen still using the [discouraged](https://setuptools.readthedocs.io/en/latest/references/keywords.html?highlight=setup_requires#keywords) `setup_requires` keyword.
I'll prepare a pymatgen PR to finally fix this.

**Comment by chrisjsewell** [comment]
@ltalirz this appears to be fixed in the last build?

I was going to suggest, we could try using in `.readthedocs.yml`:

```yaml
python:
    version: 3.8
    install:
        - requirements: requirements/requirements-py-3.8.txt
        - method: pip
          path: .
```

to ensure exact dependency versions are installed.
Although actually RTD uses eager upgrades for pip, so these version might be "overriden": `/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/develop/bin/python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .[docs,tests]`

**Comment by ltalirz** [comment]
Thanks, indeed seems fixed, not quite sure why?
Anyhow, pymatgen finally adopted the `pyproject.toml` as well (not yet released). Hopefully that will reduce issues going forward.
