### ISSUE TITLE
Docs: Add section(s) on handling failure modes (BaseRestartWorkChain)

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#4706]
@sphuber's [advanced workflows tutorial](https://aiida-tutorials.readthedocs.io/en/tutorial-2020-intro-week/source/sections/workflows_adv.html) has a lot of information regarding error handling that has not been integrated into the documentation. It would be good to e.g. add another section that explains how to use the `BaseRestartWorkChain` based on part of this content. Here's how I suggest the content is divided:

  * **7.1. Exit Codes**: There is already a [section on exit codes](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/functions.html?highlight=exit#exit-codes) in the "Topics - Processes" part of the documentation, but I think it would be good to take some of the arithmetic examples @sphuber explains and add them to a `BaseRestartWorkChain` section.
  * **7.2.1. The problem**: This seems like a section that belongs in the "Topics - Workflows" section.
  * **7.2.2. Writing a base restart work chain**: This would go into the section on the `BaseRestartWorkChain`.
  * **7.2.3. Exposing inputs and outputs**: This info has been added to the "How to extend workflows" section in #4562.
  * **7.2.4. Error handling** and **7.2.5. Multiple process handlers**: Both of these can go into the section on the `BaseRestartWorkChain`.

So, my suggestion is to create a new how-to section on error handling that describes how to write a `BaseRestartWorkChain`, and move the more conceptual section 7.2.1 into the "Topics - Workflows" section.

**Comment by chrisjsewell** [comment]
Note that when this is closed, https://github.com/aiidateam/aiida-quantumespresso/issues/645 can then be addressed
