### ISSUE TITLE
Pytest fixture to allow capturing AiiDA logs

### ISSUE THREAD

**Issue by greschd** [aiidateam/aiida-core#4708]
In https://github.com/aiidateam/aiida-core/pull/4707, I created a test with `pytest`'s `caplog`. It took me a while to figure out that the `AIIDA_LOGGER` has `propagate=False` set, and this interferes with `caplog`.

Maybe we should create a fixture that temporarily sets `propagate` to `True`? Ideally we could `autouse` it so that developers don't need to know about its existence, but I'm not sure there's a good way to do that.

Can someone with more knowledge of our logging system comment on why we need to turn off `propagate`, and whether it might be ok to set `True` while testing?

**Comment by chrisjsewell** [comment]
not sure about the implications of the `autouse` 😬, but in #4778 I have added an `aiida_caplog` which just temporarily turns on propagation.
