### ISSUE TITLE
Remove deprecated import from 'collections' instead of 'collections.abc' module

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#4723]
I found at least two more issues with py 3.9 compatibility.

First, I created this: DropD/reentry#57 that needs to be fixed first.

Second: I have (from `pip freeze`): `SQLAlchemy-Utils==0.34.2` that matches our requirements in the setup.json (`sqlalchemy-utils~=0.34.2`). 
However, with this requirement I get:
```
tests/transports/test_all_plugins.py::TestBasicFunctionality::test_is_open
  /Users/pizzi/.virtualenvs/aiida-dev/lib/python3.8/site-packages/sqlalchemy_utils/observer.py:176: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    from collections import defaultdict, Iterable, namedtuple
```
I think this has been fixed in [this PR of them](https://github.com/kvesteri/sqlalchemy-utils/pull/397) and, looking [at the corresponding commit](https://github.com/kvesteri/sqlalchemy-utils/commit/45f4e4a3d83f7e45cdf449c7c2c4bfab659d47a7), this should have been released from 0.35.0 (see list of tags in the blue bar at the top of the page from GitHub). So we should update the dependency?

Probably this second issues is not caught in new venvs since the most recent version is installed, but I had an older venv.
[EDIT]: I tested and indeed 0.35.0 does not raise that warning anymore. However, I don't know if the version has been pinned to < 0.35 on purpose or not.

@csadorf I'm reopening this issue, but of course feel free to open another one instead moving my comments there.

_Originally posted by @giovannipizzi in https://github.com/aiidateam/aiida-core/issues/4302#issuecomment-775020859_

**Comment by csadorf** [comment]
Related problem is the deprecated use of `frozendict` in `plumpy`, see: https://github.com/aiidateam/aiida-core/issues/4302#issuecomment-775031129

**Comment by csadorf** [comment]
References:
 - https://docs.python.org/3.9/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code
 - https://lwn.net/Articles/811369/

**Comment by ltalirz** [comment]
reentry 1.3.2 has been released. updating the dependency in the CI requirements files should fix that warning
