### ISSUE TITLE
CI: Non-deterministic timeouts in `test-install` workflow

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#4731]
The `test-install` GitHub actions workflow is sometimes canceled (due to timeout).
The timeouts appear to occur randomly, however they are clustered around two steps:

<details><summary>Canceled on line 29 (<code>
verdi -p test_${AIIDA_TEST_BACKEND} run .ci/test_daemon.py
</code>)</summary>
<ul>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1775661886?check_suite_focus=true">run 1775661886</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1776053647?check_suite_focus=true">run 1776053647</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1787650572?check_suite_focus=true">run 1787650572</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1790065232?check_suite_focus=true">run 1790065232</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1808225938?check_suite_focus=true">run 1808225938</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1808280405?check_suite_focus=true">run 1808280405</a></li>
</ul>
</details>

<details>
<summary>Canceled at <code>tests/cmdline/commands/test_plugin.py ......                             [ 28%]</code></summary>
<ul>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1776556930?check_suite_focus=true">run 1776556930</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1776838336?check_suite_focus=true">run 1776838336</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1799687152?check_suite_focus=true">run 1799687152</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1803637702?check_suite_focus=true">run 1803637702</a></li>
<li><a href="https://github.com/aiidateam/aiida-core/runs/1856166142?check_suite_focus=true">run 1856166142</a></li>
</ul>
</details>

Facts:
- For cancellations on line 29, usually all tests fail regardless of tested combination (Python version, backend) except for run 1808225938 and 1808280405.
- For cancellations at `test_plugin.py` there appears to be no correlation with the tested combination, but it is completely random.

Next steps
- [x] Increase test verbosity to identify at what exact step the tests are timing out or canceled.

**Comment by csadorf** [comment]
Created draft PR to increase the pytest verbosity: #4740

**Comment by csadorf** [comment]
Non-ironically the `test-install` workflow hung for two jobs for #4740: [`tests (3.7, django)`](https://github.com/aiidateam/aiida-core/pull/4740/checks?check_run_id=1878054034) and [`tests (3.8, sqlalchemy)`](https://github.com/aiidateam/aiida-core/pull/4740/checks?check_run_id=1878054124). In both cases jobs were canceled after test step `aiida.workflows:arithmetic.add_multiply` passed.

**Comment by csadorf** [comment]
Most likely culprit is: `tests/cmdline/commands/test_process.py::TestVerdiProcessDaemon::test_pause_play_kill`.

**Comment by ramirezfranciscof** [comment]
I was actually also working with this test in PR #4671, trying to migrate it to pytest and add related functionality, but was having a couple of issues which I haven't had time to review yet. This might be relevant so I'm just posting to connect the issues.

**Comment by csadorf** [comment]
This should be resolved with merge of #4747 .
