### ISSUE TITLE
load_node(1) != load_node(1)   ... The node should be equal to itself.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#4736]
### Describe the bug

```python
In [1]: load_node(1) == load_node(1)
Out[1]: False
```

### Expected behaviour

```python
In [1]: load_node(1) == load_node(1)
Out[1]: True
```

**Comment by greschd** [comment]
I think this is a duplicate of #1917.

**Comment by yakutovicha** [comment]
heh, sorry, I was searching for some words like 'equal', but didn't find the issue. Thanks @greschd

**Comment by greschd** [comment]
Yeah no problem, it's good that we good a ping about fixing that issue.

Since we were looking for broader feedback (see [this comment](https://github.com/aiidateam/aiida-core/issues/1917#issuecomment-692778969)), would be great to also hear your opinion on that.

**Comment by yakutovicha** [comment]
> Yeah no problem, it's good that we good a ping about fixing that issue.
> 
> Since we were looking for broader feedback (see [this comment](https://github.com/aiidateam/aiida-core/issues/1917#issuecomment-692778969)), would be great to also hear your opinion on that.

going through, I feel exactly as @giovannipizzi wrote (c):

> I have to admit that while reading it, at every comment I thought "ok we should do this" and at the following "ah right, wait!"...
