### ISSUE TITLE
`verdi quicksetup` does not work on WSL

### ISSUE THREAD

**Issue by zhubonan** [aiidateam/aiida-core#4748]
- [x] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [x] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug

`verdi quicksetup` does not work on WSL due to `DEAFULT_TRY_SUDO` being `False` by default. 
It might be difficult to detect WSL as the `platform.versions` function does not return a string containing `Ubuntu`, which
is used as an option to try the `sudo` commands. 

It would be useful to have an option in `verdi quicksetup` to manually let the program to try `sudo` regardless.

### Steps to reproduce

1. setup a WSL1/WSL2 environment
2. run `verdi quicksetup`

### Expected behavior

Quick profile setup can be performed

### Your environment

- Operating system: Ubuntu 18.04 on WSL1
- Python version [e.g. 3.7.1]: 3.7
- aiida-core version [e.g. 1.2.1]: 1.5.2

Other relevant software versions, e.g. Postgres & RabbitMQ

Postgres10

**Comment by ltalirz** [comment]
This was fixed in https://github.com/aiidateam/pgsu/pull/25 and is released as part of pgsu v0.2.0
