### ISSUE TITLE
On behaviour of get_detailed_job_info

### ISSUE THREAD

**Issue by atztogo** [aiidateam/aiida-core#4752]
- [x] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [x] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug?

I'm not sure if this is a bug or not because my usage is possibly what is not considered in aiida-core.

In an instance of SGE scheduler, when `get_detailed_job_info(self, job_id):` is called with `job_id is None`, the aiida daemon gets stuck at `Waiting for transport task: retrieve`. 

This happened when I used the aiida-vasp plugin and `VaspImmigrant`. After [a discussion](https://github.com/aiida-vasp/aiida-vasp/issues/443) the reason that gets stuck is that `qacct -j` (without arguments) is called on the remote server and this returns a very long text output when `job_id is None` at the following lines:

https://github.com/aiidateam/aiida-core/blob/dca50f47a340ffa14302d7bd0714ba86227b4b57/aiida/schedulers/plugins/sge.py#L135-L137

### Steps to reproduce

Setting up aiida-vasp (0224e9b53) with SGE scheduler and running the script pasted [here](https://github.com/aiida-vasp/aiida-vasp/issues/443#issuecomment-778720609).

### Expected behavior

Setting `command` blank (`""`) in the line below when `job_id is None`. But I'm not very sure if this can be a general solution or not.

https://github.com/aiidateam/aiida-core/blob/dca50f47a340ffa14302d7bd0714ba86227b4b57/aiida/schedulers/scheduler.py#L281

### Your environment

- Operating system [e.g. Linux]: Ubuntu server 18.04
- Python version [e.g. 3.7.1]: 3.8.5
- aiida-core version [e.g. 1.2.1]: v1.5.2

**Comment by ltalirz** [comment]
thanks @atztogo for the report and sorry for the super slow reply - not sure whether nobody picked this up?

@chrisjsewell @giovannipizzi Perhaps one could generally catch cases where `job_id` is `None` and return an empty dictionary here?
https://github.com/aiidateam/aiida-core/blob/02248cf3686a0ab89faf1625e0da24d9e33d8cde/aiida/schedulers/scheduler.py#L272-L291

Are there cases where this is not the expected behavior?

**Comment by giovannipizzi** [comment]
Hi, indeed this is a use case that probably wasn't expected - one option would be to raise when job_id is not valid, but indeed @ltalirz suggestion is good - I would catch this directly in `get_detailed_job_info` (but I suggest to return `None` rather than `{}` in that case, and let the caller deal with it - so this might need some additional code change).
For the internal function `_get_detailed_job_info_command`, maybe adding a `raise` if the value is None is a good idea (since we don't want to pass the string `None` to the scheduler, I think)

**Comment by chrisjsewell** [comment]
> one could generally catch cases where job_id is None and return an empty dictionary here?

the best protection against catching functions that can return `None` is to add type declarations+checking 😉 

(I actually had to add a catch for `job_id` is `None` not long ago: https://github.com/aiidateam/aiida-core/commit/8c079175bbb32a6dc3b4ae663c586c7099cbb9a6)

**Comment by atztogo** [comment]
I am lost. Should I close this issue if this is not the issue?

**Comment by giovannipizzi** [comment]
@atztogo no, don't worry, it's good to keep this issue open.

@atztogo If we change the function to this:
```python
 def _get_detailed_job_info_command(self, job_id): 
     if job_id is None:
         raise ValueError("job_id cannot be None")
     command = f'qacct -j {escape_for_bash(job_id)}' 
     return command 
```
and then, here:
https://github.com/aiidateam/aiida-core/blob/5ab86cca5fc2070937cfa90b1a479d06878e68dd/aiida/schedulers/scheduler.py#L272-L291

we start with an additional
```python
    if job_id is None:
        return {
            'retval': None,
            'stdout': None,
            'stderr': None,
        }
```
what is going to happen? Is this going to fix the problem, or shift the problem somewhere else?

In this case we don't even need to change the typing, probably. Even if we need to, of course I agree with @chrisjsewell that adding typing would help, but if we don't have the time to do it consistently through that part of code, I would still try to fix the issue in the meantime

**Comment by atztogo** [comment]
@giovannipizzi, thanks for your help. I tested with aiida-core release `v1.6.3` (c0fec533).

Your modification (i.e., below) of `get_detailed_job_info` in `aiida-core/aiida/schedulers/scheduler.py` solved the issue!

```python
    if job_id is None:
        return {
            'retval': None,
            'stdout': None,
            'stderr': None,
        }
```

Either with or without your modification (i.e. below) of `_get_detailed_job_info_command` in `aiida-core/aiida/schedulers/plugins/sge.py`, it works.

```python
 def _get_detailed_job_info_command(self, job_id): 
     if job_id is None:
         raise ValueError("job_id cannot be None")
     command = f'qacct -j {escape_for_bash(job_id)}' 
     return command 
```

**Comment by giovannipizzi** [comment]
Thanks Togo!
@ramirezfranciscof could you take care of implementing this fix? Thanks!

**Comment by atztogo** [comment]
From the comment by @sphuber of PR #4967, this is not an issue. I will close this. Thanks for your discussion.
