### ISSUE TITLE
Delete unused `ProcessFuture`

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4758]
The `ProcessFuture` was intended for a use case that never came to fruition (maybe @muhrin can add 1-2 sentences on that).

`ProcessFuture`s are currently not used in the AiiDA codebase and, when I tested them for investigating the memory leak, they seemed to be broken.
We agreed together with @muhrin to remove them from the code.

**Comment by chrisjsewell** [comment]
yep delete away

**Comment by ltalirz** [comment]
Turns out that `runner.get_process_future()` was used in some *tests* in order to wait until a process completes.
In that case it must (?) work at least to some degree, so let's keep it for the moment.
