### ISSUE TITLE
Pymatgen release 2022.0.3 is incompatible

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#4797]
As of pymatgen version [2022.0.2](https://pypi.org/project/pymatgen/2022.0.2/) (released on March 06 202**1**) , tests executed as part of the `test-install` workflow are failing. That specific version was actually yanked, but version 2022.0.3 also appears to be incompatible.

### Additional context

* [Ex. of workflow succeeding for version 2021.3.3](https://github.com/aiidateam/aiida-core/runs/2036569656?check_suite_focus=true)
* [Ex. of workflow failing of version 2022.02](https://github.com/aiidateam/aiida-core/runs/2044525080?check_suite_focus=true)
* [Ex. of workflow failing of version 2022.03](https://github.com/aiidateam/aiida-core/runs/2062382834?check_suite_focus=true)

### Recommended steps:

- Add upper bound on supported pymatgen version (2021.3.3).
- Permanently maintain upper bound of supported pymatgen versions and increase bound explicitly in new releases.

**Comment by chrisjsewell** [comment]
Just to note this has already been fixed: https://github.com/aiidateam/aiida-core/commit/4b7febe8264da5c49ec0125c31f7ca8dd0713b2c

but yeh an upper bound makes sense, the upshot of https://github.com/materialsproject/pymatgen/issues/2083 is that they are not using semantic versioning, but they are using semantic versioning 🤷 

> Finally, the 2022 versions are in fact a compromise towards temporary semantic version for the remainder of this year.

**Comment by chrisjsewell** [comment]
Also, on my request, 2022.0.01 and 2022.0.02 have been "yanked" from pypi

**Comment by csadorf** [comment]
@chrisjsewell @ltalirz I would appreciate if you could more consistently ping me on dependency-related issues. In this particular case I would not have needed to waste time on compiling this issue. Please understand that I do not perform daily aiida-core dev work so I am not always fully aware of all the PRs that are being opened and closed on a daily basis. If somebody else (e.g. one of you) would prefer to start taking take care of the dependency management that is fine with me as well.

**Comment by ltalirz** [comment]
thanks for the reminder @csadorf and sorry for this oversight - it was originally something we were planning to fix "right there and then" but of course it still make sense to ping @aiidateam/dependency-manager 

will do!

**Comment by csadorf** [comment]
> thanks for the reminder @csadorf and sorry for this oversight - it was originally something we were planning to fix "right there and then" but of course it still make sense to ping @aiidateam/dependency-manager
> 
> will do!

Appreciated. Even if you are able to "fix it right there and then", the ping is still important so that I can maintain an overview in this context. As I said, is not possible for me to follow every commit and conversation, so I do rely on your help with this.

**Comment by csadorf** [comment]
I've ran a test on all pymatgen versions that are currently considered compatible and identified the following versions as incompatible:

- 2022.0.1
- 2022.0.2
- 2019.9.7

Except for the last one I believe this meets our expectations.
I therefore propose the following revised pymatgen dependency specification:
`pymatgen>=2019.7.2,!=2019.9.7,<2022.02.1,==2022.02.03`

The test command was `pytest -v -k pymatgen` executed with Python 3.6 and Python 3.7. The source code to the test project is [here](https://github.com/aiidateam/pymatgen-compatible-version-check).

**Comment by csadorf** [comment]
Closed by #4805
