### ISSUE TITLE
SQLAlchemy v1.4 is breaking `verdi setup`

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#4808]
### Describe the bug

It seems the just released v1.4.0 of SQLAlchemy is breaking `verdi setup`.

The error seems to not be able to import `_literal_as_text` from `sqlalchemy.sql.expression`:
https://github.com/Materials-Consortia/optimade-python-tools/pull/740/checks?check_run_id=2115274484#step:10:51

[Here](https://github.com/Materials-Consortia/optimade-python-tools/pull/740/checks?check_run_id=2115274484#step:9:251) is the proof of which `sqlalchemy` version is being installed (1.4.0).

### Steps to reproduce

Try to setup an AiiDA profile using `verdi setup` with a YAML config file.
It might also be reproducible without using a config file.

### Your environment

- Operating system: GH Actions `ubuntu-latest`
- Python versions: 3.6 - 3.9 (the latest of these on GH Actions).
- aiida-core version: v1.5.2

Note, I'm expecting this to fail for `aiida-core`'s own CI as well.

**Comment by greschd** [comment]
Ping @aiidateam/dependency-manager
