### ISSUE TITLE
No root_dir in ProfileManager

### ISSUE THREAD

**Issue by JPchico** [aiidateam/aiida-core#4837]
- [x] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [x] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug

When trying to perform tests using the pytest fixtures from aiida-core in combination with the fixtures from aiida-vasp results in failure. 

```python
aiida_profile = <aiida.manage.tests.TestManager object at 0x7f83d5d19eb0>
    @pytest.fixture()
    def fresh_aiida_env(aiida_profile):
        """Reset the database before and after the test function."""
>       print('The root directory of the fixture manager is: {}'.format(aiida_profile._manager.root_dir))  # pylint: disable=protected-access
E       AttributeError: 'ProfileManager' object has no attribute 'root_dir'
```

The `ProfileManager` seems to not have the `root_dir` property, while the `ProfileTestManager` does seem to have it. Is this intended behavior? Or is the feature missing from the class?

### Steps to reproduce

1. Expose the `aiida-core` pytest fixtures and the `aiida-vasp` fixtures in `conftest.py`
2. Create a test profile via `verdi setup --config tests/config/test_config.yml`
3. Run a test via `AIIDA_TEST_PROFILE=test_relax LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' pytest -q tests/relaxation/test_relaxation_vasp.py`

### Expected behavior

The test is supposed to run, with the fixture cleaning the database if needed. 

### Your environment

- Operating system [e.g. Linux]: Ubuntu 20.04
- Python version [e.g. 3.7.1]: 3.8.5
- aiida-core version [e.g. 1.2.1]: 1.6.0 (develop branch hash a8ee41deb)

### Additional context

The code uses aiida-vasp fixtures (aiida-vasp version 2.1.0 develop branch hash d08feba). The issue has been discussed in the [aiida-usergroups](https://groups.google.com/g/aiidausers/c/cIByOcETjJc).

**Comment by chrisjsewell** [comment]
I'm going to close this here for now, but feel free to re-open if you or the aiida-vasp developers still think there is something that needs to be changed in aiida-core

**Comment by espenfl** [comment]
@chrisjsewell Thanks. How would you eject the `root_dir` of the tests when using the current AiiDA test profile framework. Would like to fix this. Informing @zhubonan as well. I use this sometimes when creating new tests. One could maybe argue that such checks would only take place when developing the tests, not when running them in production and then accessing `_manager` etc. might be okey. Still, it is a bit dirty.

**Comment by greschd** [comment]
Since the `root_dir` is only used for informational purposes, one possible approach would be to keep the access to `._manager`, but make it fail gracefully (i.e., the test still succeeds) when there is an exception.

Another option would be to add something to the built-in aiida fixtures - either an (optional) printing, or some "officially sanctioned" way of accessing the profile info.
