### ISSUE TITLE
Incorrect check in `aiida.cmdline.utils.decorators.load_backend_if_not_loaded` causes backend to sometimes not be loaded

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4877]
It uses the `PROFILE` global to determine whether a database backend has been loaded, but this global can be set without having loaded the corresponding database backend.

**Comment by chrisjsewell** [comment]
To add some extra detail, this regression occurs only in 1.6.2 (from #4865) and manifests in e.g. `verdi archive import` (https://github.com/marvel-nccr/ansible-role-aiida/pull/72/checks?check_run_id=2457849742)
