### ISSUE TITLE
PluginTestCase removed without deprecation warning

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#4887]
### Is your feature request related to a problem? Please describe

https://github.com/aiidateam/aiida-core/commit/287d1385884c1c77a942d4945506c406ee98acde removed the `PluginTestCase`.

I vaguely remember that we were planning to remove it at some point, but [it is still used by many plugins](https://github.com/search?p=1&q=aiida+plugintestcase&type=Code), including [the plugin cutter](https://github.com/aiidateam/aiida-plugin-cutter/blob/master/%7B%7Bcookiecutter.plugin_name%7D%7D/tests/test_cli.py#L11),  and there was no deprecation warning for those who do (e.g. see [logs](https://github.com/ltalirz/aiida-zeopp/runs/2464961968#step:10:22) from aiida-zeopp against the previous state of aiida-core develop).

### Describe the solution you'd like

I think the hard removal of the `PluginTestCase` causes unnecessary extra work for plugin developers on short notice.
Since no deprecation warning was raised, I suggest we put it back with a clear deprecation warning (that includes a pointer on how to fix it) and remove it in aiida-core v3.

mentioning @sphuber for comment

**Comment by sphuber** [comment]
The reason I removed it is because we decided after v1.0 to remove `unittest` support for `v2.0` and there was a deprecation warning here:

https://github.com/aiidateam/aiida-core/blob/c0fec5337a30f006d6917c8e369d78e297b9ccd3/aiida/manage/tests/unittest_classes.py#L85

in the `TestRunner.run` method. Since the `PluginTestCase` docstring also explicitly states:

https://github.com/aiidateam/aiida-core/blob/c0fec5337a30f006d6917c8e369d78e297b9ccd3/aiida/manage/tests/unittest_classes.py#L26

I thought it was ok to remove. Is the docstring incorrect then and are you running the `PluginTestCase` differently in your plugin?

**Comment by ltalirz** [comment]
I agree that we planned to remove it with 2.0 (so no blame for removing it in the commit!) but we overlooked that the deprecation warning would not be raised when the test classes deriving from `PluginTestCase` are run through `pytest`.

This is still the case in the plugin cutter, and therefore in many plugins that used it.
I would therefore not feel comfortable removing it now.

Depending on how long it takes until the v2.0 release (e.g. say if it's still >6 months) it could perhaps still go there but I think we will need to give people time to adjust.

**Comment by sphuber** [comment]
So you propose to reinstate those files and add a deprecation warning with it being removed when?

**Comment by chrisjsewell** [comment]
Ha, I literally though about cc'ing you @ltalirz https://github.com/aiidateam/aiida-core/pull/4881#discussion_r622835601, but then got caught up doing other stuff 🤦

**Comment by ltalirz** [comment]
> So you propose to reinstate those files and add a deprecation warning with it being removed when? Since this is testing infrastructure, maybe this wouldn't require a new major release to be removed and so we just give a rough date/version? Somewhere in `v2.x`?

You can still say that it will be removed in 2.x (it's good to push people to make the change - as long as we don't break their code) - once it's time for the release we can still decide to keep it around for a bit longer.

This deprecation warning should also be backported into the next 1.6.x patch release. What matters to me is that there is enough time between having the warning released in 1.6.x and the time of a release that has the feature removed.
