### ISSUE TITLE
Object store migration: Node folders `raw_input` vs. `path`

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#4910]
### Describe the bug

There is a known edge case that can happen during the migration to the object store repository, where a `Node` can have both a `path` and a `raw_input` folder in the current repository.
If this is encountered, the migration will fail with a `CRITICAL` and report the `Node` in question, describe the issue and instruct the user to delete one or the other folder.

At the AiiDA team developers meeting (on 05.05.2021) @giovannipizzi mentioned [his comment](https://github.com/aiidateam/aiida-core/pull/4345#issuecomment-749699623) regarding this issue.
His suggested solution is to: "ignore if both are there AND `path` is empty (then just pick `raw_input`)".

### Expected behavior

It would be nice if there is a solvable solution, where the migration doesn't fail, but simply reasons slightly, choosing the correct folder (if possible) and then continues. If this is not possible, then the migration should still fail with a `CRITICAL`, of course.

**Comment by giovannipizzi** [comment]
Indeed - maybe, I would extend my suggestion as:
"ignore if both are there AND path is empty AND it's a process node [node_type starts with `process.`]: then just pick raw_input"

@sphuber do you agree?

I think this will happen for repositories created with old versions 0.x of AiiDA that went through migration - for some reason there but be some path we didn't consider where `path` is not removed. I don't think we'll see from new repositories even when importing old archives.

**Comment by sphuber** [comment]
I am wondering if we cannot add even more logic. If there are two folders, but either both or at least one is empty, we can simply take the one that is not empty? Or could there be situations where the node shouldn't have any files, but it still (erroneously) has another subfolder with some content? If that is not possible, then we can simplify it to just only raise if both subfolders have content. And in that case, we could than even still add more heuristics to pick on or the other based on the `node_type`, but I am not sure if that is 100% guaranteed to do the right thing.

**Comment by giovannipizzi** [comment]
I don't know - I wouldn't make additional heuristics if we're not sure either of why that situation could have happened, or if we have an example.
So far I think the only case is process nodes with both, and `path` is empty, so I would personally vote to just support that case and stop with a message as now for the others (and maybe point users to this issue if they get an error in a different scenario). We can always keep improving the migration if more edge cases pop up, no?

**Comment by sphuber** [comment]
@CasperWA can you confirm that for the node that raised the error that it  actually corresponds to a `ProcessNode` and it had an empty `path` folder?

If Casper confirms and this is the same problem that you had Gio, then it is fine to just treat this edge case for now. We can indeed keep updating the migration if we find other edge cases.

**Comment by sphuber** [comment]
Uhm, I am confused now: the fix you propose is already in
https://github.com/aiidateam/aiida-core/blob/dc686c5aaede1944bc40a06becbef34cde3ed282/aiida/backends/general/migrations/utils.py#L273

So now I think we should definitely first confirm what exactly happened in @CasperWA 's case, because I doubt it is the one you had @giovannipizzi , which we apparently already addressed when the original PR was still open.

**Comment by CasperWA** [comment]
> @CasperWA can you confirm that for the node that raised the error that it actually corresponds to a `ProcessNode` and it had an empty `path` folder?
> 
> If Casper confirms and this is the same problem that you had Gio, then it is fine to just treat this edge case for now. We can indeed keep updating the migration if we find other edge cases.

It's a `node_type="process.calculation.calcjob.CalcJobNode."` and `process_type=" aiida.calculations:quantumespresso.pw"`.

**Comment by giovannipizzi** [comment]
@sphuber indeed I was surprised the fix wasn't already there since we had discussed it.

@CasperWA it's the .gitignore! How did it end up in there? Which repository is it?

**Comment by CasperWA** [comment]
> @sphuber indeed I was surprised the fix wasn't already there since we had discussed it.
> 
> @CasperWA it's the .gitignore! How did it end up in there? Which repository is it?

Which repository? It's a random one of mine which I have as default and used as a development/miscellaneous profile. I have no idea how the `.gitignore` got in there, honestly.

**Comment by sphuber** [comment]
Ok, then I think we can safely attribute this to an exceptional manual manipulation and close this issue, right? I doubt this was done through any sort of normal usage of AiiDA.

**Comment by giovannipizzi** [comment]
There was a time where .gitignore were added for testing plugins, but this was loooong ago before Casper joined - so if this is a repository that you Casper created from scratch (and not "inherited" from a early AiiDA user) indeed I don't think that file was added by AiiDA.

**Comment by giovannipizzi** [comment]
My guess: @CasperWA you have been running tests on that profile?

I found this in v1.6.3:
https://github.com/aiidateam/aiida-core/blob/c0fec5337a30f006d6917c8e369d78e297b9ccd3/tests/tools/importexport/test_reader.py#L70

This line has been already removed by @sphuber from the code:
https://github.com/aiidateam/aiida-core/commit/f30f000f985d0acf63c00b7f0d63ea6660feb9f6#diff-f82c7abe3bdd76fb85eb238e00c2abcc3d1731b1adec7a596f80dff3a8f2bcf3L69

but maybe that file comes from one of the reference import archives? If that is the case, it would be good to ensure that the `path` folder with the .gitignore is not there (or, if it's there to test some migration, to ensure that the migration removes it?)

**Comment by ltalirz** [comment]
Just to report that I ran into the same issue, and also in my case the `path` folder was empty except for a `.gitignore`.

zipped node folder is attached
[node.zip](https://github.com/aiidateam/aiida-core/files/6503242/node.zip)

**Comment by ltalirz** [comment]
It's definitely present in the export file https://github.com/aiidateam/aiida-core/tree/develop/tests/fixtures/export/migrate

@CasperWA Would you be ok to take care of fixing this one?

**Comment by ltalirz** [comment]
Apart from this, however, I think we should still make sure that the migration doesn't fail in this particular case (when people have run tests on the profile).
I don't care much how specific the check is as long as it solves this issue

**Comment by CasperWA** [comment]
> It's definitely present in the export file https://github.com/aiidateam/aiida-core/tree/develop/tests/fixtures/export/migrate
> 
> @CasperWA Would you be ok to take care of fixing the export archive?

Sure. As mentioned in today's developer's meeting, I'll implement the logic that if one folder contains *only* `.gitignore`, the migration will auto-remove it. If anything else is there and it's non-empty, this will still except (as it should).
