### ISSUE TITLE
Migration for `Computer` column `name` rename to `label` is broken for SqlAlchemy

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#4925]
it should use `alter_column` in order to prevent violations of the non-nullable new column. Rookie mistake and even worse that it was not caught because yours truly thought this was such a simple migration it didn't need one.

![](https://media.giphy.com/media/Ob7p7lDT99cd2/source.gif)

**Comment by sphuber** [comment]
@CasperWA I am ashamed to inform you that we have found the culprit of your mystery migration error :grimacing:

**Comment by CasperWA** [comment]
> @CasperWA I am ashamed to inform you that we have found the culprit of your mystery migration error 😬

Well done in finding it! :)
