### ISSUE TITLE
export archive format forces reading of data.json file to memory

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida-core#493]
It seems to me that when doing a verdi import, such as

```bash
verdi import <export_file>.aiida
```
the content of ``<export_file>.aiida`` is first cached in the RAM, if not entirely, at least for what concerns the database. As a consequence, this actually sets the largest size of a file that can be imported to the instantaneous amount of free RAM.

**Comment by ltalirz** [comment]
On aiida-core `develop` (47cfe3400a7f5ef863e2a10b88afa6187459bb96, django backend), this problem still exists.

In particular, while trying to import an export file of 7GB in size, the export manages to go through everything until
```
...
STORING NEW NODE EXTRAS...
UPDATING EXISTING NODE EXTRAS (mode: kcl)
```
At this point, I get the out of memory error:

```
Error: an exception occurred while importing the archive export_hcofs_co2.aiida
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/envs/discover-hcofs/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.ProgramLimitExceeded: out of memory
DETAIL:  Cannot enlarge string buffer containing 0 bytes by 1257443654 more bytes.
```
 1257443654 being ~1.2 GBytes.

I.e. it seems to me we are creating a query string that exceeds the [max alloc size](https://github.com/postgres/postgres/blob/master/src/include/utils/memutils.h#L40) of postgresql, which defaults to 1GB.

While the export file is not terribly large, it *does* have a rather large `data.json` file, namely ~2GB:
```
$ unzip -l export_hcofs_co2.aiida data.json metadata.json
Archive:  export_hcofs_co2.aiida
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [export_hcofs_co2.aiida]:  2718573025 extra bytes at beginning or within zipfile
  (attempting to process anyway)
  Length      Date    Time    Name
---------  ---------- -----   ----
2086189646  12-13-2019 08:56   data.json
 16216422  12-13-2019 08:57   metadata.json
---------                     -------
2102406068                     2 files
```

**Comment by ltalirz** [comment]
Support has been added in https://github.com/ICRAR/ijson/commit/d4cca873471c914aa7c8a89e266ce7918c7f93ff , i.e. one can now do

```python
import ijson
f = open('data.json', 'r')
for k,v in ijson.kvitems(f, 'node_attributes'):
    print(k, v)
```

In my [test](https://github.com/ICRAR/ijson/issues/18#issuecomment-576184311), the python implementation takes about 0.2ms per key-value pair (=per node).
However, the wheel of the package comes with a pre-built C extension for many platforms that takes about 0.01ms per key-value pair, putting it within less than a factor of 2 of calling `json.load` in terms of time per k/v pair - pretty fast!

There's one more issue - the [layout of AiiDA's `data.json` file](https://aiida.readthedocs.io/projects/aiida-core/en/latest/import_export/main.html#data-json) splits node columns, attributes and extras into three separate lists.
That makes it quite difficult to get a "batch of nodes" - you need at least three iterators and it is not even clear whether all three lists always have the same length & order.

There are several possible ways forward:

A) We stick with the current format and try to implement a (suboptimal and slightly complex) batch parser with three iterators going at once.

B) We change the layout of `data.json` to something that can be sensibly parsed as a stream - e.g. simply move `node_extras` and `node_attributes` inside the `Node` dict.

C) We switch to a new file format that is made for "seeking" and "slicing" (like HDF5)

Mentioning @giovannipizzi @sphuber for comment

**Comment by giovannipizzi** [comment]
I would definitely go for B, but possibly taking into account also other requirements rather than just this one in the redesign of th export format (that could possibly end up in solutions like C). If however implementing this is fast and (probably) C it's going to take longer, ok to start working on it.

**Comment by ltalirz** [comment]
Just as a comment: There is a new format called [JSON Lines](http://jsonlines.org/) (or "newline-delimited JSON) which is essentially one JSON per line and suitable for storing large numbers of nested data structures in one file (Google adopted it for BigQuery).
It might be worth considering this format when going with option B) 

See also discussion on "[Loading Data Efficiently](https://www.oreilly.com/library/view/google-bigquery-the/9781492044451/ch04.html#loading_data_efficiently)" for option C)
