### ISSUE TITLE
Add `entry_point` attribute to `Node` and `Group` classes.

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#4939]
### Is your feature request related to a problem? Please describe

When I first wanted to obtain the entry point from a `Group` instance, I intuitively looked for the `entry_point` attribute. However, it seems that the entry point of a `Group` type can be obtained with the `type_string` attribute instead. Is there a difference between the `type_string` and the entry point? If not, perhaps we can add an alias for this attribute called `entry_point`?

For `Node` instances, I don't seem to find an attribute or method that directly returns the entry point. There is `node_type` and `class_node_type`, but they return something along the lines of `'<entry point group>.<entry point>.<class name>'` e.g. `'data.structure.StructureData.'`. So, the user would have to understand this structure and adapt the output accordingly.

### Describe your desired solution

I think it would be useful for users and developers if we can obtain the entry point for any object that has one with an `entry_point` attribute. Since users learn about entry points early on, it seems more intuitive to obtain a `Node` or `Group`'s entry point via an attribute with the same name.

**Comment by chrisjsewell** [comment]
I agree 👍
