### ISSUE TITLE
Docs: API docs cumbersome to browse

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida-core#4946]
### Describe the current issue

Starting from the `aiida package` docs: https://aiida.readthedocs.io/projects/aiida-core/en/latest/reference/apidoc/aiida.html when one selects a subtopic https://aiida.readthedocs.io/projects/aiida-core/en/latest/reference/apidoc/aiida.orm.html nothing changes in the index to the left or the outline to the right, reflecting that the user is now actually on a different page.
Also, there is no backlink "up", making it difficult for the user to orient themselves, especially on browsers where the URL bar is hidden.

### Describe the solution you'd like

The index on the left seems to the right place to replicate the information about the top sub-packages when being on the `aiida package` site, while giving the user a sense on how deep in the tree they are and allowing for quick access to go to level up.

**Comment by chrisjsewell** [comment]
This should basically just be improved when we update the version of pydata-sphinx-theme, to incorporate: https://github.com/pydata/pydata-sphinx-theme/pull/349

See for example, the API documentation on one of my other packages (this uses the sphinx-book-theme, which I'm a maintainer of and derives from pydata-sphinx-theme): https://markdown-it-py.readthedocs.io/en/latest/api/markdown_it.rules_core.replacements.html
