### ISSUE TITLE
`verdi daemon restart` ignores change of daemon.default_workers (and possibly other values)

### ISSUE THREAD

**Issue by dev-zero** [aiidateam/aiida-core#4948]
### Describe the bug

```console
$ verdi daemon status
Profile: default
Daemon is running as PID 214995 since 2021-05-18 08:35:19
Active workers [1]:
   PID    MEM %    CPU %  started
------  -------  -------  -------------------
214999    1.835        0  2021-05-18 08:35:20
Use verdi daemon [incr | decr] [num] to increase / decrease the amount of workers
$ verdi config set daemon.default_workers 4
Success: 'daemon.default_workers' set to 4 for 'default' profile
$ verdi daemon restart
Restarting the daemon... OK
$ verdi daemon status
Profile: default
Daemon is running as PID 214995 since 2021-05-18 08:35:19
Active workers [1]:
   PID    MEM %    CPU %  started
------  -------  -------  -------------------
215162    1.104        0  2021-05-18 08:36:46
Use verdi daemon [incr | decr] [num] to increase / decrease the amount of workers
```

### Expected behavior

After the restart the new number of workers should be used

### Your environment

- Operating system [e.g. Linux]: Linux
- Python version [e.g. 3.7.1]: 3.9.5
- aiida-core version [e.g. 1.2.1]: 1.6.2 and 773e94441382c9133441b936f1f81bfee291acdd

**Comment by ltalirz** [comment]
This is indeed unexpected - @sphuber do you agree?

**Comment by ltalirz** [comment]
@dev-zero what happens when you stop and start again?

**Comment by dev-zero** [comment]
it comes up with the correct number of workers

**Comment by sphuber** [comment]
> This is indeed unexpected - @sphuber do you agree?

Not necessarily. `verdi daemon restart` is a soft restart and only restarts the workers, not the circus daemonizer. That means all settings remain unchanged. For that you need a full restart through `verdi daemon restart --reset` which is equivalent to `verdi daemon stop && verdi daemon start`.

If this is unclear, what we could do is making `verdi daemon restart` do the full reset and then replace `--reset` flag with something else (say `--workers` or `--soft`) and have that just restart the workers. Reason I did it the current way is that often one wants to just restart the workers and that is a lot faster than fully restarting the entire daemon

**Comment by dev-zero** [comment]
from Linux world (systemd and what not) I am used to `restart` being equivalent to a `stop` and `start`

**Comment by ltalirz** [comment]
The time difference is indeed significant, so I understand @sphuber 's original rationale.
```
$ time (verdi daemon stop && verdi daemon start)
Profile: nanoporous_pipeline
Waiting for the daemon to shut down... OK
Starting the daemon... RUNNING

real	0m5.027s
user	0m3.386s
sys	0m2.615s
```

```
$ time (verdi daemon restart)
Restarting the daemon... OK

real	0m1.572s
user	0m1.224s
sys	0m0.838s
```

At the same time, in typical operation restarting the daemon is a rare event, i.e. 4 seconds more or less does not make a world of difference and I would prefer simplicity of use over "performance" in the default setting here.

> If this is unclear, what we could do is making `verdi daemon restart` do the full reset and then replace `--reset` flag with something else (say `--workers` or `--soft`) and have that just restart the workers.

I would vote for this solution.

**Comment by giovannipizzi** [comment]
Since we often anyway recommend `verdi daemon restart --reset`, shall we implement this change (and go with a full restart by default, and `--soft` as an option)? @sphuber @khsrali @GeigerJ2 - if we agree, it's an easy change

**Comment by khsrali** [comment]
yes, I agree it makes sense. It should be an easy change.
I'll do it, it's a good exercise.

**Comment by danielhollas** [comment]
> The time difference is indeed significant, so I understand @sphuber 's original rationale.

FWIW I re-did a quick n dirty timing on my machine on current main, and the soft reset now takes about 1s, while the hard reset about 1.8s so the difference seems to be much less significant. :+1:
