### ISSUE TITLE
What about indexing ctime and mtime in dbnode model?

### ISSUE THREAD

**Issue by fernandogargiulo1986** [aiidateam/aiida-core#496]
this is relevant for typical restapi calls of the aiida web interface (AWI). In fact, one commonly used feature is to sort nodes by date in the views listing any kind of nodes ,e.g. calculations, data, etc... And this takes considerably longer time than sorting by labels, id, state etc...

I checked in my fork that indexing ctime and mtime ameliorates performances a lot without increasing sensibly the size of the database.

**Comment by chrisjsewell** [comment]
both ctime and mtime are indexed in the latest ORM
