### ISSUE TITLE
Reading in UpfData as a filelike object has inconsistencies in md5 hashing and upf parsing

### ISSUE THREAD

**Issue by QwertycowMoo** [aiidateam/aiida-core#4987]
### Describe the bug

When reading in a filelike-object for UpfData, the type of filelike-object is inconsistent for parsing the upf and creating an md5 hash.

### Steps to reproduce

1. Read in a UpfData file into a filelike object (`with open() as f`, `io.BytesIO`, `io.StringIO`, `django.InMemoryUploadedFile, urllib.urlopen()`)
2. Try to save file into the object either by constructor or by set_file()
``` 
with open("C.upf", "rb") as f:
     pseudo = UpfData()
     pseudo.set_file(f)
     # or more simply, pseudo = UpfData(f)
```

However, based on the type, it throws an error either during the Upf parsing phase or the md5 hashing phase.

To parse the upf, it needs to read in the file as either a file with a .read() function [Line 197](https://github.com/aiidateam/aiida-core/blob/3f7ee1be22b698458d776fc1499a2cc972585a5a/aiida/orm/nodes/data/upf.py#L197) or read in by filepath [Line 200](https://github.com/aiidateam/aiida-core/blob/3f7ee1be22b698458d776fc1499a2cc972585a5a/aiida/orm/nodes/data/upf.py#L200). This bug happens when you try to read in the file as a filelike. The filelike is also required to have a `.name` but I see that in the develop branch that this is removed.

Once it reads in the file, the return type from the filelike's .read() function must be a string because it applies regex functions onto it. [Line 203](https://github.com/aiidateam/aiida-core/blob/master/aiida/orm/nodes/data/upf.py#L203)

After parsing the upf, it also creates an md5 hash of the file using [aiida.common.files](https://github.com/aiidateam/aiida-core/blob/master/aiida/common/files.py) in [Line 352-355](https://github.com/aiidateam/aiida-core/blob/master/aiida/orm/nodes/data/upf.py#L352) depending on whether it is a filelike object or a filepath. Again, we will be focusing on the filelike because it is where the bug happens.

The way that it processes the file in when using a filelike object is using a .read() function, chunking it and stopping at a sentinel value of a byte empty string `b''` in [Line 26-27](https://github.com/aiidateam/aiida-core/blob/master/aiida/common/files.py#L26). If the filelike's `.read()` function returns a string, the sentinel value is never reached because is a byte representation of an empty string rather than the string representation. 

With byte objects encoded in UTF-8, the md5 has a type error trying to hash the string.

With `with open("C.upf", "r") as f`: Throws a `TypeError: Unicode-objects must be encoded before hashing`

With `io.StringIO` object that has a .name: Throws a `TypeError: Unicode-objects must be encoded before hashing`

With `io.BytesIO` object that has a .name: Throws a `TypeError: cannot use a string pattern on a bytes-like object`

### Expected behavior

I expected that when a filelike object is given to the UpfData constructor, that it would properly process it.

### Your environment

- Operating system [Debian]:
- Docker Image from [python:3.8]
- Python version [3.8.10]:
- aiida-core version [1.3.6]:

### Additional context

I prefer that I do not save the file into disk and then read from disk as that can be very intensive.

If [lines 23-27](https://github.com/aiidateam/aiida-core/blob/master/aiida/common/files.py#L23) are changed to 
```
for chunk in iter(lambda: fileIOWrapper.read(128 * md5.block_size), ''):
      chunk = chunk.encode("UTF-8")
      md5.update(chunk)
```
Where fileIOWrapper is a filelike object that has a .read() return a string object rather than a byte object, this correctly creates an md5 hash for the file.

**Comment by sphuber** [comment]
It seems indeed impossible to construct a `UpfData` from a filelike object since the `parse_upf` function that is called will try to read the name, which is usually not available for those types, resulting in the exception:
```python
ValueError: cannot use filelike objects when `check_filename=True`, use a filepath instead.
```
This behavior can be disable by passing `check_filename=False` to `parse_upf`, but this function is called by the `UpfData` constructor and hard-codes the argument, so it cannot be changed by the caller.

This `UpfData` is a legacy code, however, and I am not sure we should touch it now. The new de-facto standard for pseudo-potentials with AiiDA is the `aiida-pseudo` plugin package: https://github.com/aiidateam/aiida-pseudo/  This comes with its own `UpfData` implementation that does allow constructing from filelike objects without problems. I would suggest using that plugin instead as the `UpfData` implementation of `aiida-core` will be decommissioned soon.
