### ISSUE TITLE
Module load exception whereas module containing workchain class is in path

### ISSUE THREAD

**Issue by sylviancadars** [aiidateam/aiida-core#4988]
Hi,

I am trying to reproduce the simple MultiplyAddWorkChain described in AiiDA documentation but face an ImportError even though the module containing the  MultiplyAddWorkChain is in a subdirectory of one defined in the PYTHONPATH.

I created a module file testModule.py containing the class definition : 
**************************
testModule.py
**************************
```python
"""Implementation of the MultiplyAddWorkChain for testing and demonstration purposes."""
from aiida.orm import Code, Int
from aiida.engine import calcfunction, WorkChain, ToContext
from aiida.plugins.factories import CalculationFactory

ArithmeticAddCalculation = CalculationFactory('arithmetic.add')


@calcfunction
def multiply(x, y):
    return x * y


class MultiplyAddWorkChain(WorkChain):
    """WorkChain to multiply two numbers and add a third, for testing and demonstration purposes."""

    @classmethod
    def define(cls, spec):
        """Specify inputs and outputs."""
        super().define(spec)
        spec.input('x', valid_type=Int)
        spec.input('y', valid_type=Int)
        spec.input('z', valid_type=Int)
        spec.input('code', valid_type=Code)
        spec.outline(
            cls.multiply,
            cls.add,
            cls.validate_result,
            cls.result,
        )
        spec.output('result', valid_type=Int)
        spec.exit_code(400, 'ERROR_NEGATIVE_NUMBER', message='The result is a negative number.')

    def multiply(self):
        """Multiply two integers."""
        self.ctx.product = multiply(self.inputs.x, self.inputs.y)

    def add(self):
        """Add two numbers using the `ArithmeticAddCalculation` calculation job plugin."""
        inputs = {'x': self.ctx.product, 'y': self.inputs.z, 'code': self.inputs.code}
        future = self.submit(ArithmeticAddCalculation, **inputs)

        return ToContext(addition=future)

    def validate_result(self):
        """Make sure the result is not negative."""
        result = self.ctx.addition.outputs.sum

        if result.value < 0:
            return self.exit_codes.ERROR_NEGATIVE_NUMBER

    def result(self):
        """Add the result to the outputs."""
        self.out('result', self.ctx.addition.outputs.sum)
```
**************************

The directory containing this file is a subfolder of a folder defined in my python path. When I try to import the class from a verdi shell : 
from testModule import MultiplyAddWorkChain
it works fine.

I then created the following run_test.py script : 

**************************
run_test.py
**************************
```python
from testModule import MultiplyAddWorkChain
from aiida.engine import submit

add_code = load_code(label='add@tutor')
inputs = {
    'x': Int(1),
    'y': Int(2),
    'z': Int(3),
    'code': add_code
}
workchain_node = submit(MultiplyAddWorkChain, **inputs)
```
**************************

When I try to run this with 'verdi run run_test.py' the corresponding process is Excepted and the process report reads : 

**************************

```
 File "/usr/local/miniconda/envs/aiida/lib/python3.8/site-packages/aiida/engine/persistence.py", line 48, in load_object
    module = importlib.import_module(module_name)
  File "/usr/local/miniconda/envs/aiida/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'testModule'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/envs/aiida/lib/python3.8/site-packages/aiida/manage/external/rmq.py", line 208, in _continue
    result = await super()._continue(communicator, pid, nowait, tag)
  File "/usr/local/miniconda/envs/aiida/lib/python3.8/site-packages/plumpy/process_comms.py", line 607, in _continue
    proc = cast('Process', saved_state.unbundle(self._load_context))
  File "/usr/local/miniconda/envs/aiida/lib/python3.8/site-packages/plumpy/persistence.py", line 60, in unbundle
    return Savable.load(self, load_context)
  File "/usr/local/miniconda/envs/aiida/lib/python3.8/site-packages/plumpy/persistence.py", line 448, in load
    load_cls = load_context.loader.load_object(class_name)
  File "/usr/local/miniconda/envs/aiida/lib/python3.8/site-packages/aiida/engine/persistence.py", line 50, in load_object
    raise ImportError(f"module '{module_name}' from identifier '{identifier}' could not be loaded")
ImportError: module 'testModule' from identifier 'testModule:MultiplyAddWorkChain' could not be loaded
```

**************************

I suppose I missed something but I cannot figure out what it is.
Thanks for your help.
Best wishes.

Sylvian.

**Comment by unkcpz** [comment]
Hi @sylviancadars, I think you did it correctly. Since you *submit* the calculation to the daemon by `submit` you need to `verdi daemon restart --reset` after you set your `PYTHONPATH` to let the daemon load your new env setting.

**Comment by sylviancadars** [comment]
Dear unkcpz,

Thank you for your answer. I ran the `verdi daemon restart --reset` command (I did restart the daemon before but omitted the --reset option) and then changed `submit()` to `run()`, which worked fine.

However, when I then tried to change back to `submit()` and ran the process with verdi run run_test.py I obtained the same exception related to module loading as above. It looks like it is the dameon that cannot load my modules. Does it have access to the PYTHONPATH ?

Thanks.
All the best.

Sylvian

**Comment by sphuber** [comment]
If you want to submit the workchain, you need to indeed make sure that the module is in the `PYTHONPATH` otherwise the daemon won't be able to import it. The reason that it works when you run it in a local script is because in that case the script is running in the same working directory as where the module is located and the working directory is always automatically included in the `PYTHONPATH`.

**Comment by mbercx** [comment]
@sphuber but if I understand correctly, the _daemon_ `PYTHONPATH` is constructed from the `activate` script of the virtual environment, so in order to set the correct `PYTHONPATH`, you have to do something along the lines of what we do [at the end of the `EquationOfState` example of last year's tutorial](https://aiida-tutorials.readthedocs.io/en/tutorial-2020-intro-week/source/sections/workflows_basic.html#submitting-the-workflow-workchains):

```
echo "export PYTHONPATH=\$PYTHONPATH:$PWD" >> /home/max/.virtualenvs/aiida/bin/activate
```
i.e. just adding the directory with the module to the `PYTHONPATH` and restarting the daemon doesn't work, since the daemon doesn't read the `PYTHONPATH` from the current environment?

**Comment by sphuber** [comment]
@mbercx exactly. As [described here in the documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html#process-launch) (see the warning box) the process class needs to be importable by the daemon, which means either giving it an entry point or by putting the module in the `PYTHONPATH`. As you say, the addition of the module to the `PYTHONPATH` should be added to the activation script to make sure that the change is automatic and permanent the next time the daemon is loaded.

**Comment by sylviancadars** [comment]
Thank you @sphuber and @mbercx for your messages.

The thought I had everything set correctly as you suggested but then realized that my modules had to be contained in a folder contained in the PYTHONPATH and not in a subfolder thereof (which if I remember well works with the Spyder IDE, for example).

When I include specifically the folder containing the module .py file via the activation script of my aiida environment as suggested by @mbercx, I can import it within a verdi shell launched from any location.

After this I has to re-run the `verdi daemon restart --reset` command, and then the submit() command finally worked.

Would there be a way to recursively search modules within the PYTHONPATH folders ?

Thanks.
Best wishes.

Sylvian

**Comment by mbercx** [comment]
> Would there be a way to recursively search modules within the PYTHONPATH folders ?

Not that I'm aware of. 🤔 But maybe @sphuber knows of some Python magic to do this? However, when you get to the point that you have several workchains organised in a directory with subdirectories, perhaps it would be better to move them into a package (or plugin) that you can install in your environment and add entry points for.

**Comment by sphuber** [comment]
Any folder that is in the `PYTHONPATH` will be considered as the root of Python module's or packages. Since packages are nested modules, Python will find those nested modules automatically. If we take `aiida` as example. Let's assume your `PYTHONPATH` contains `/home/user/packages` and in that folder there is the `aiida` package. This will allow you to import `aiida` or any subpackage such as `aiida.orm`. However, if the `aiida` package were to be in `/home/user/packages/some/sub/folder/` then I don't think that having just `/home/user/packages` in your `PYTHONPATH` will find it. This is nothing specific to AiiDA though but default Python behavior

**Comment by sylviancadars** [comment]
Thanks again for your messages and clarifications. This is very helpful.
Best regards.
Sylvian.
