### ISSUE TITLE
Install via pip/conda broken

### ISSUE THREAD

**Issue by mjclarke94** [aiidateam/aiida-core#4993]
The issue referenced in #4989 does more than just break the testing; it prevents the creation of profiles from a clean install. 

A hotfix to update the dependencies may be needed in the short term as right now installations via pip and conda are broken.

**Comment by bosonie** [comment]
@chrisjsewell, @ramirezfranciscof @mbercx. I believe it is critical to have a release as soon as possible. We will soon have an aiida school and people might try out in advance. In here we will also run a siesta school next week and want to present aiida as well. Thank you!

**Comment by mjclarke94** [comment]
@bosonie This doesn't help for people trying it out on their own unless they happen to find this issue, but for the in person stuff manually downgrading `psycopg2` fixes the problem:
```
pip install psycopg2==2.8.3
```

The conda installation is a bit more complicated (either due to it being harder or due to me not being all that familiar with anaconda...one of the two). I found just installing the services, then doing everything else via pip worked:

```
conda create -n aiida -c conda-forge aiida-core.services pip
conda activate aiida
pip install aiida-core psycopg2==2.8.3
```

**Comment by bosonie** [comment]
Thanks @mjclarke94, I'm aware of the fix (and not an expert of conda either) and it is good to have it here for reference.
My concern was more about having a hotfix as you have mentioned already. I would like to advertise a product that works and not fails in the setting up. 
Also for @chrisjsewell, please be aware that this problem also leads to a fail in the construction of the Quantum Mobile. I had to fix it in the aiida role[1], but having it in aiida directly would be better:
[1] https://github.com/siesta-project/ansible-role-aiida/blob/569f09ab5677d1ef7a17d65a0de06cde4c0a9ae7/defaults/main.yml#L24

**Comment by mjclarke94** [comment]
@bosonie I figured you might! You just highlighted to me that I complained about a problem and neglected to mention the actual solution!

**Comment by ramirezfranciscof** [comment]
Hey @mjclarke94 @bosonie thanks for the heads up on this! Indeed from what you are saying this sounds problematic, sorry we didn't notice this (the problem and/or this issue) before.

If I understand correctly the merged PR referenced in this OP (#4989) solves the problem, we just need to hot fix this into a released version?

**Comment by bosonie** [comment]
I don't know much about `==`, `~=` and so on but yes.

**Comment by mjclarke94** [comment]
Yeah, I think so. My only question would be about pinning to `psycopg2-binary~=2.8.3`. Given the issues seem to have emerged with the release of `2.9.x`, is there any reason the version restriction couldn't be:
```
psycopg2-binary~=2.8.6,<2.9
``` 
on the off chance that some bug in`2.8.3-2.8.5` will pop up.

**Comment by bosonie** [comment]
Agree with @mjclarke94 !

**Comment by ramirezfranciscof** [comment]
I'm also not an expert on the requirements syntax, but from what I could understand from [the PEP](https://www.python.org/dev/peps/pep-0440/#compatible-release) that the pip installer is following, `psycopg2-binary~=2.8.3` only sets `2.8.3` as the minimum but then will add any other fix `2.8.x` on that minor version. I will confirm but this is what you want and what you understand from that source too?

**Comment by bosonie** [comment]
Ah ok. Then it is exactly what we need! Therefore a release will be enough!

**Comment by chrisjsewell** [comment]
Guys, don’t worry I’m going to make a release now

**Comment by mjclarke94** [comment]
@ramirezfranciscof Ah, right you are.
