### ISSUE TITLE
Docs /latest point to wrong version

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#5013]
If I go here: https://aiida.readthedocs.io/projects/aiida-core/en/latest/index.html I see "aiida-core version: 1.6.2".
However the most recent version of AiiDA is 1.6.4.

Note that that version of the docs exists: https://aiida.readthedocs.io/projects/aiida-core/en/v1.6.4/index.html
So it seems it's only an issue of where latest is pointing to.
Any idea why? @chrisjsewell

**Comment by giovannipizzi** [comment]
@chrisjsewell I realised this is because on `develop` the version is still 1.6.2.
Can we rename to 2.0.0a1 maybe, to avoid confusion?
@sphuber @mbercx @csadorf @ramirezfranciscof

**Comment by csadorf** [comment]
This appears to be resolved.
