### ISSUE TITLE
Docs: Known RabbitMQ issue in WSL2

### ISSUE THREAD

**Issue by CasperWA** [aiidateam/aiida-core#5016]
### Describe the current issue

As found out during the 2021 Virtual Tutorial, there can be issues with IPv4 versus IPv6 for the RabbitMQ service.

### Describe the solution you'd like

A note of this known issue, and how to solve it, should be added to the installation instructions.
To solve it see [this](https://stackoverflow.com/questions/54322974/wsl-error-mainprocess-consumer-cannot-connect-to-amqp-guest127-0-0-156) StackOverflow accepted answer, where the RabbitMQ configuration file is changed.

**Comment by sphuber** [comment]
Since we have had no recent reports I am closing this
