### ISSUE TITLE
Allow `WorkChains` to accept inputs that are not nodes

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#5022]
Is there a way to already do this? As far as I could tell there is none. Minimal example of what I mean: I tried adding `spec.input("y", valid_type=int)` to the [tutorial example](https://aiida-tutorials.readthedocs.io/en/tutorial-2021-intro/sections/writing_workflows/workchain.html#adding-the-steps-in-the-outline) and it crashed:

```python
(lot of error text)

TypeError: source should be a `Node` but got: <class 'int'>
```

Calcjobs can have non-node inputs, is there any specific reason why we are not allowing it for workchains?

**Comment by chrisjsewell** [comment]
Yes, with `non_db` inputs; this is what calcjobs use (for metadata) and there is no difference for workchains.
For further information, I would look at: https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html?highlight=non_db#non-storable-inputs

**Comment by ramirezfranciscof** [comment]
Cool, thanks! But a little follow up question: where does that information get stored? I didn't find it in the `attributes` of the finished `Workchain` node, nor can I access it through the `node.inputs.` construct.

**Comment by chrisjsewell** [comment]
Well it’s not stored in the database. If you want it stored in the database you can have look at the next section: https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/processes/usage.html?highlight=non_db#automatic-input-serialization

**Comment by chrisjsewell** [comment]
The main point here, I would say, is that workchain nodes are not part of the data provenance and so they should not be used to store data. You should be using data nodes for this
