### ISSUE TITLE
mypy keeps complaining error: unused "type: ignore" comment in pre-commit

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5026]
The pre-commit failed with mypy `error: unused "type: ignore" comment`. Have no idea how to fix this, and it prevents me from running pre-commit check locally.  

After checkout to https://github.com/aiidateam/aiida-core/pull/4996 this 'unused' error disappear. 

The python version of my environment is `3.8.10`.

**Comment by chrisjsewell** [comment]
See https://github.com/aiidateam/aiida-core/pull/4970#issuecomment-897006010; I managed to do this with zero issues: #5066, just make sure your environment is up-to-date, and I highly recommend the use of tox

**Comment by chrisjsewell** [comment]
Note, if you really can't fix it, then you can always locally comment out `warn_unused_ignores = true` in the pyproject.toml
