### ISSUE TITLE
Support django 3.x

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#5040]
The django dependency is currently constrained to `~=2.2`, but the latest release is version 3.2.6.

**Comment by csadorf** [comment]
Relevant issue: #4985

**Comment by csadorf** [comment]
This is issue is also blocking the installation of AiiDA with conda and Python 3.9: https://github.com/conda-forge/aiida-core-feedstock/issues/56

**Comment by chrisjsewell** [comment]
django no longer a dependency #5330
