### ISSUE TITLE
REST API: make the target profile a query parameter

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5052]
Currently, the profile on which the REST API operates is fixed at runtime of the REST API and cannot be changed or configured per request. For a machine serving multiple profiles, this necessitates running a separate REST API instance per profile, which is not very performant. It would be great if the profile can be specified per request and the instance switches the loaded profile if needed. Some of the code necessary for this is already present, but it has not been marked as safe for use in production. Issue #2759 is tracking robustifying this and making switching profiles within a Python interpreter safe.

**Comment by ltalirz** [comment]
related: https://github.com/aiidateam/aiida-core/issues/4494#issue-725965690
