### ISSUE TITLE
Add batch operations to new `repository`

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#5053]
Currently a lot of the methods of the [new abstract repository](https://github.com/aiidateam/aiida-core/blob/develop/aiida/repository/backend/abstract.py) class deal with single object operations. I've been thinking on including methods for enabling batch operations. For example:

``` python
    @abc.abstractmethod
    def has_object(self, key: str) -> bool:
        """Return whether the repository has an object with the given key.
        :param key: fully qualified identifier for the object within the repository.
        :return: True if the object exists, False otherwise.
        """

    @abc.abstractmethod
    def has_objects(self, keys: List[str]) -> List[bool]:
        """Return whether the repository has a list of objects with the given keys.
        :param keys: list of fully qualified identifiers for the objects within the repository.
        :return: list with each position having True if the corresponding object exists, False otherwise.
        """
```

I think this could improve performance, particularly in situations of intensive multiple accesses (e.x. when doing backups, exports, maintenance, etc). Moreover, I would expect this to become crucial if we intent to enable the use of cloud based services as remote repositories via this interface.

For the following methods, I think it is quite straightforward how to do the adaptation:

- `put_object_from_filelike` (and `_put_object_from_filelike`)
- `put_object_from_file`
- `has_object`
- `delete_object`

The one that might be more tricky is `open` (and therefore `get_object_content` and `get_object_hash`) since it is a context manager. In principle I guess one could do `yield list_of_objects` and then `with open_many(list_of_keys) as list_of_objects:`, but I guess this is then limiting to handling all the objects under the same context (which would be ok for the cases mentioned above, but maybe not for other user specific cases). Would it be convenient to design a way of requesting the construction of objects that then could be used as separate context managers? Is anybody aware of any pre-existing way of dealing with this problem?

Anyways, besides that last consideration with contexts I just wanted to check with you before I started to implement this, in case you had any reason why you would discourage this. Moreover, what would you consider the best option among the following? (I would be initially inclined for option 2)

1. Have both kinds of methods (`has_object` and `has_objects`) [_increases code complexity affecting maintainability_]
2. Have only batch operations that can take both kinds of inputs (`def has_objects(self, keys: Union[ List[str], str ] )  -> Union[ List[bool], bool ]:`) [_increases code complexity affecting efficiency_]
3. Have only batch operations that act on batch inputs (so the only way of doing a single operations would be `if has_objects([single_key])[0]:`) [_increases complexity on usage for the user and/or serviced codes_]

**Comment by ramirezfranciscof** [comment]
Please let me know if you have any feedback on this @giovannipizzi @sphuber @chrisjsewell , I will probably mention it on the group meeting on Wednesday but unless I get any objections by the end of that day, I'll start working on this then.

**Comment by giovannipizzi** [comment]
My feedback would be: let's only implement batch operations for those methods for which we already know at least one place where we would be using the batch function, and not yet for those cases where we don't plan to use it immediately.

More in detail:
- let's identify the few methods where doing bulk access makes sense (and ideally also limiting to those for which the current implementation can provide significant performance boost). We can always add more later on, when the need arises. I think `has_objects` and `delete_objects` might good candidates to include now (but what would the interface be? e.g. `has_objects` returns a list of bools? also, for `delete_objects`, good to think at how to behave in case of errors and how to communicate back what was deleted and what wasn't. ~Note however that with the current implementation (JSON in the PSQL DB) I'm not 100% sure some of these are efficient?~ EDIT: thinking better to it: if this acts on the objects *of a given node*, this will be typically always fast (you have in memory the full JSON). If it's about "give me any node that has this object", this is quite trickier (probably not fast right now, but if this is used only in maintenance operations, probably OK not to be super performant).
- I wouldn't make bulk operations for `open` - it's tricky to do it right (and indeed as you mention you will hit a number of limitations like the max # of open file handles). Also, I'm not sure it's really useful - you open a file when you have to do something with it, so you'll end up doing the work serially. I wouldn't spend time on this until we have a use case for its needs
- I don't like having has_objects understand if you're being passed a string or a list (option 2). I prefer option 1: code complexity is really minimal, you just implement has_object along these lines:
   ```python
   def has_object(key):
       return has_objects([key])[0]
   ```
   so the code complexity increase is really almost zero.

**Comment by ramirezfranciscof** [comment]
> My feedback would be: let's only implement batch operations for those methods for which we already know at least one place where we would be using the batch function, and not yet for those cases where we don't plan to use it immediately.
> 
> More in detail:
> 
> * let's identify the few methods where doing bulk access makes sense (and ideally also limiting to those for which the current implementation can provide significant performance boost). We can always add more later on, when the need arises. I think `has_objects` and `delete_objects` might good candidates to include now (but what would the interface be? e.g. `has_objects` returns a list of bools? also, for `delete_objects`, good to think at how to behave in case of errors and how to communicate back what was deleted and what wasn't. ~Note however that with the current implementation (JSON in the PSQL DB) I'm not 100% sure some of these are efficient?~ EDIT: thinking better to it: if this acts on the objects _of a given node_, this will be typically always fast (you have in memory the full JSON). If it's about "give me any node that has this object", this is quite trickier (probably not fast right now, but if this is used only in maintenance operations, probably OK not to be super performant).
>
> * I wouldn't make bulk operations for `open` - it's tricky to do it right (and indeed as you mention you will hit a number of limitations like the max # of open file handles). Also, I'm not sure it's really useful - you open a file when you have to do something with it, so you'll end up doing the work serially. I wouldn't spend time on this until we have a use case for its needs

Indeed, for the maintenance commands I already need to use the `delete_objects` so that would be immediately convenient (I haven't actually checked if there is a performance impact directly from the multiple calls because I need an implementation of the bulk process to actually do it, but from the other tests I kind of suspect it might be relevant).

I feel like the `open` / `put_object` might already be quite critical for export/import, considering the repository contains a lot of really small files (inputs for example). But yeah, in principle I don't think I need them for the maintenance tool so I'm ok with skipping for now unless there is the specific need.

> * I don't like having has_objects understand if you're being passed a string or a list (option 2). I prefer option 1: code complexity is really minimal, you just implement has_object along these lines:
>
>       ```python
>       def has_object(key):
>           return has_objects([key])[0]
>       ```
>  
>   so the code complexity increase is really almost zero.

Yeah, good point. I've seen this in the other interfaces, I don't know why I didn't propose it here (it is very similar to 2 in that it takes a small hit in performance compared to 1, but probably this way ensures that the hit and complexity is minimal). I can do it this way.

**Comment by giovannipizzi** [comment]
As a follow-up comment on "open / put_object": very often for import export you don't really need to open the files. You just need to tell "copy the objects with IDs in this list from HERE to THERE". The disk objectstore has optimised routines to do that in bulk. I think this is anyway already implemented in the code. I think as you suggest that it's safe not to implement them yet and we'll see when the need arises.

**Comment by sphuber** [comment]
This was added in v2.0 so closing
