### ISSUE TITLE
update ipykernel once v6.1 is released

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5071]
ipykernel 6.0.3 required importlib-metadata<4 for python 3,7, which caused @chrisjsewell to use ipykernel 5 (which does not have this restriction) for python3.7 in the test requirements [1], see https://github.com/aiidateam/aiida-core/pull/5058/files#diff-5096c356dcee4904c32d307b2394b651880eca46af0b1255d3bada8a8cc302fd

My PR to relax this requirement in ipykernel has been merged https://github.com/ipython/ipykernel/pull/738#event-5148667693 and should be released with ipykernel 6.1

@aiidateam/dependency-manager Please update the ipykernel dependency in the python3.7 requirements after ipykernel 6.1 is released 

[1] While this makes the tests pass, not sure whether that solves the problem for users installing aiida under python3.7

**Comment by ltalirz** [comment]
ah - now I realize that ipykernel was released immediately in the process.

Let me try to fix it myself then

**Comment by csadorf** [comment]
@ltalirz Please assign this issue to me if you want me to take action after all.
