### ISSUE TITLE
Per-calculation cache control

### ISSUE THREAD

**Issue by jbweston** [aiidateam/aiida-core#5102]
### Is your feature request related to a problem? Please describe

Sometimes I want to have a single calculation instance (or many calculations in a workflow) run by the daemon, but for Aiida _not_ to use the cache. Currently the only way I am aware of to achieve this is to disable caching globally, however this is not ideal if I have several workflows of the same type running concurrently, but I only want to disable caching for a single one.

### Describe the solution you'd like

A potential solution would be to have an extra piece of metadata passed as input to a calculation (e.g. `disable_cache`) that would  disable caching for that calculation instance only.

### Describe alternatives you've considered
Globally disabling the cache. As I mentioned above, this is not ideal, as then any other calculations of the same type running concurrently would have caching disabled also.

**Comment by sphuber** [comment]
In the current `develop` branch, which will be released as `v2.0.0b1` in a few days at most, there is a new feature that allows a node to be marked as an invalid source node for caching. Essentially doing:
```python
node.is_valid_cache = False
```
See the details [on the documentation](https://aiida.readthedocs.io/projects/aiida-core/en/develop/topics/provenance/caching.html?highlight=caching#sources). I think this would satisfy your use case requirements, would it not?

**Comment by ltalirz** [comment]
Hi @jbweston , just came across this issue.

Process-level control on caching has actually been available in AiiDA since quite a while, see [the docs](https://aiida.readthedocs.io/projects/aiida-core/en/develop/howto/run_codes.html#instance-level).

It would be great to know whether this addresses your use case and, if yes, what could be done to make it more obvious in the documentation.

**Comment by sphuber** [comment]
I now read the original description again and misunderstood the problem, and so my response was incorrect. @ltalirz I don't think that what @jbweston requires is currently supported, at least not in a way that is compatible with submitting through the daemon. The caching config is only on the level of process *classes* but this will affect *all* instances of that class. The contextmanager `aiida.manage.caching.disable_caching` *does* allow finer-grained control, however, this will only work for the current interpreter and so won't work when submitting to the daemon. I think @jbweston is right and the only solution is to add another input to the `metadata` namespace of the `Process` class that disables the caching for that instance and that instance only. @jbweston is this still a required use-case? If so, I could look at whipping up an implementation
