### ISSUE TITLE
The localhost computer is hard-coded to have only one MPI core

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#5117]
https://github.com/aiidateam/aiida-core/blob/75e7024ecbbb24b2d4b04d744989057d0b925930/.docker/opt/configure-aiida.sh#L45

This line leads any hosts that runs this container to assume that it has only one MPI proc available which is not necessarily true. I recently had to monkey-patch the localhost computer metadata to work-around that constraint in the context of running AiiDAlab with multiple cores.

Is there a specific reason that this parameter is set like this? Pinging @yakutovicha and @sphuber for input.

**Comment by sphuber** [comment]
This merely sets the _default_ value to be used when a `CalcJob` is run. It can be overwritten on a per-run basis using the `metadata.options.resources.num_mpiprocs_per_machine` input

**Comment by yakutovicha** [comment]
Just a couple of points to consider:
- When submitting a calculation, one could always modify this parameter. It just provides the default value, nothing more than this.
- 1 CPU seems to be a safe choice for me, as this always leads to a working setup.

At the same time, I believe setting the value to the actual number of CPUs is also fine, because:
- One could assume (as @csadorf  did) that `mpiprocs-per-machine` refers to the number of the **available** CPUs on the machine.
- If the issue https://github.com/aiidateam/aiida-core/issues/3236 going to be fixed, and `withmpi` becomes a code attribute, then we can switch MPI on and off per each code individually.

Thinking about the two options, I would go with the second one, provided that we can correctly identify the number of the available cores on a machine.

**Comment by csadorf** [comment]
> This merely sets the _default_ value to be used when a `CalcJob` is run. It can be overwritten on a per-run basis using the `metadata.options.resources.num_mpiprocs_per_machine` input

In this particular case we actually try to do a basic resource estimate where this _default_ value poses part of the basis for the calculation. We try to provide the user with some feedback whether a given structure can be run on localhost or rather not.

In essence, we need to be able to trust that this value is somewhat reasonable for the localhost computer. Do you have a suggestion how we should deal with this problem? Would it be reasonable to make this value configurable e.g. via an environment variable or have it be based on the equivalent of `os.cpu_count`?

**Comment by csadorf** [comment]
> Thinking about the two options, I would go with the second one, provided that we can correctly identify the number of the available cores on a machine.

I believe that the equivalent of `os.cpu_count()` would be a reasonable assumptions in the vast majority of cases.

**Comment by yakutovicha** [comment]
> > Thinking about the two options, I would go with the second one, provided that we can correctly identify the number of the available cores on a machine.
> 
> I believe that the equivalent of `os.cpu_count()` would be a reasonable assumption in the vast majority of cases.

How does it work with hyper-threading? I believe that for our purpose, we need to count the physical core and not the virtual ones.

**Comment by csadorf** [comment]
> > > Thinking about the two options, I would go with the second one, provided that we can correctly identify the number of the available cores on a machine.
> > 
> > 
> > I believe that the equivalent of `os.cpu_count()` would be a reasonable assumption in the vast majority of cases.
> 
> How does it work with hyper-threading? I believe that for our purpose, we need to count the physical cores and not the virtual ones.

We should probably use [`psutil.cpu_count(logical=False)`](https://psutil.readthedocs.io/en/latest/index.html?highlight=cpu_count#psutil.cpu_count) to be safe.

**Comment by csadorf** [comment]
@sphuber I should base a fix on the [support/1.6.x branch](https://github.com/aiidateam/aiida-core/tree/support/1.6.x), correct?

**Comment by sphuber** [comment]
> @sphuber I should base a fix on the [support/1.6.x branch](https://github.com/aiidateam/aiida-core/tree/support/1.6.x), correct?

That depends on when it needs to be released. If this needs to be released before v2.0, then it should be released with v1.6.6. But even for this, you can still just base it on `develop` and merge it in there. Then we just cherry-pick that commit onto the support branch. That is what I have been doing for the past support patch releases and works well.

**Comment by yakutovicha** [comment]
FYI, I've just submitted a PR that should fix #3236.

**Comment by yakutovicha** [comment]
> @sphuber I should base a fix on the [support/1.6.x branch](https://github.com/aiidateam/aiida-core/tree/support/1.6.x), correct?

I think it would be preferable to keep it in the develop. As far as I understand, the `withmpi` option for the codes will only be released in AiiDA 2.0.

**Comment by sphuber** [comment]
> I think it would be preferable to keep it in the develop. As far as I understand, the `withmpi` option for the codes will only be released in AiiDA 2.0.

What do you mean with the `withmpi` option? Do you mean the `metadata.options.withmpi` of `CalcJobs`? Because that has been there for a long time.

**Comment by yakutovicha** [comment]
> What do you mean with the `withmpi` option? Do you mean the `metadata.options.withmpi` of `CalcJobs`? Because that has been there for a long time.

I meant the code attribute which I added in #5152.
