### ISSUE TITLE
aiida-core docker image outdated

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5132]
```
$ docker pull aiidateam/aiida-core:1.6.5
Error response from daemon: manifest for aiidateam/aiida-core:1.6.5 not found: manifest unknown: manifest unknown
```
In particular, this means the commands from the [docs](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/run_docker.html) is currently do not work.

This is a result of docker silently [discontinuing autobuilds for free accounts](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/run_docker.html).

It seems, however that as an open-source project one can [apply for open source status](https://www.docker.com/blog/expanded-support-for-open-source-software-projects/) and still get this feature.

I will take care of the application, could someone else please upload the latest docker container (perhaps @yakutovicha or @mbercx ?)

**Comment by ltalirz** [comment]
form for open source status submitted

**Comment by yakutovicha** [comment]
Weird, the image should be built and pushed to Docker Hub on every tag created in the repo: https://github.com/aiidateam/aiida-core/blob/develop/.github/workflows/push_image_to_dockerhub.yml

**Comment by ltalirz** [comment]
Thanks for the hint - I was looking for a workflow like this but somehow I overlooked it.

The problem is here:
https://github.com/aiidateam/aiida-core/blob/22d4e2ecc256e8dc840bd0e76e5f4421ddbe0f6a/.github/workflows/push_image_to_dockerhub.yml#L8-L10

I will modify it to include the support branches

**Comment by ltalirz** [comment]
@yakutovicha In the meantime, would you be ok to push the 1.6.5 docker image to dockerhub?

**Comment by yakutovicha** [comment]
> @yakutovicha In the meantime, would you be ok to push the 1.6.5 docker image to dockerhub?

sure, I can do that.

**Comment by ltalirz** [comment]
let's wait until the new prerequisites are released

**Comment by sphuber** [comment]
Pinging @ltalirz and @yakutovicha . What is the status of this?

**Comment by ltalirz** [comment]
By the way, they are all shown as pushed by @yakutovicha 

<img width="187" alt="image" src="https://user-images.githubusercontent.com/1053245/165838136-320c6ef6-8f22-4436-8322-29e2dd6aaa07.png">

I guess that is by design; just making sure this is intended

**Comment by yakutovicha** [comment]
> By the way, they are all shown as pushed by @yakutovicha
> 
> <img alt="image" width="187" src="https://user-images.githubusercontent.com/1053245/165838136-320c6ef6-8f22-4436-8322-29e2dd6aaa07.png">
> 
> I guess that is by design; just making sure this is intended

Yeah, one needs to provide somebody's credentials to push the image to Dockerhub. There is no way, at least to my knowledge, to push it as an "aiidateam" organisation. Feel free to put somebody's else credentials.

**Comment by sphuber** [comment]
Well it seems it is just pushed with two repository secrets `DOCKER_TOKEN` and `DOCKER_USERNAME`. I take it we could just create a shared account on Docker hub for `aiidateam` and use that instead. Would that be better @yakutovicha ?

**Comment by yakutovicha** [comment]
> Well it seems it is just pushed with two repository secrets `DOCKER_TOKEN` and `DOCKER_USERNAME`. I take it we could just create a shared account on Docker hub for `aiidateam` and use that instead. Would that be better @yakutovicha ?

I think so.

**Comment by sphuber** [comment]
I have just updated the tokens to that of aiidateambot. Let me know if it still doesn't work.

**Comment by yakutovicha** [comment]
> I have just updated the tokens to that of aiidateambot. Let me know if it still doesn't work.

thanks!
