### ISSUE TITLE
Exit code that reflects that executable path could not be found

### ISSUE THREAD

**Issue by louisponet** [aiidateam/aiida-core#5179]
### Is your feature request related to a problem? Please describe
For example PWCalcjob fails with exit code 305 that no output could be parsed, indicating a problem with the i/o, whereas the problem is that the configured executable does not exist.

### Describe the solution you'd like
Either automatic checking of executable paths on setup (preferred), or a default exit code that reflects the actual error.

**Comment by sphuber** [comment]
> Either automatic checking of executable paths on setup (preferred)

This has been discussed before and rejected as an idea as it requires that an SSH connection is available to the computer on which the code is being configured, which is not always the case.

It would be nice to have a check and specific exit code for this though, I agree. Question is where to put it. Ideally this is done before the calculation is even submitted, which is possible, but again requires to potentially open up an SSH connection, which can be a performance bottle-neck when submitting in high-throughput. Alternative is to have the check be done by the engine in the `UPLOAD` step when it anyway has to open up a connection and that one is properly pooled. I think this is the best option, but downside is of course that the calculation will still be created in the database and has to wait for it to launch for the problem to be detected. Then there is the fact that the code of course cannot be simply updated, but has to be duplicated and the path fixed.

Maybe, in addition to the check by the engine and the dedicated exit code, we should also add `verdi code test` just like `verdi computer test` that performs this check. This way one can check before running any calculations, but the question is how many users will find and use this, even if we put it in the docs and tutorials.

**Comment by louisponet** [comment]
Again, these are hypotheticals, have they ever actually happened to the point that it warrants the code to be designed around this case?

Sure, it's perfectly possible to it with which and ls. I'm also doing that in combination with ldd to be sure that if someone submits a calculation it will actually run. 

If that's possible to do also in AiiDA then that would be fantastic!

**Comment by sphuber** [comment]
> Again, these are hypotheticals

Not true, we have plenty of environments that are being automatically setup that shouldn't fail if a remote is temporarily not available, for example CI testing, Docker containers, AiiDAlab servers etc. Not everything is a single user manually configuring a code to directly launch a calculation. I understand that is what your use case is and what you seem to perceive as being the only or main use case, but I think this is simply not true.

**Comment by louisponet** [comment]
If the main use case of aiida is not people using it, then why are we even
discussing this... Why is there an interactive way to set things up in the
first place.

Anyway it's clear that solving this is very difficult so let's just leave
it as it is.
