### ISSUE TITLE
Replace `verdi database` commands with more general `verdi storage`

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#5226]
In order to hide unnecessary complexity from the end user, the current `verdi database` commands will be adapted into a `verdi storage` group. This will in turn also allow to include in the same group commands to deal with the repository, as many of these features typically affect both aspects of the backend simultaneously.

There are 4 specific commands that need to be dealt with in the following way:

- `integrity`: the checks that were performed here are no longer relevant. There will be a new `verdi storage integrity` that will perform more general checks (once the features of the repository are implemented here).
- `migrate`: the exact same procedure will be now performed by `verdi storage migrate`
- `summary`: the information returned by this will be now accessible through the `verdi storage info` options.
- `version`: the information returned by this should be automatically provided by just calling `verdi status`

**Comment by ramirezfranciscof** [comment]
> `version`: the information returned by this should be automatically provided by just calling `verdi status`

I opened this issue in case we needed to discuss any aspects of this and I think I already found something worth noting. The `verdi database version` didn't  just got the schema and revision, but did so in a way that skipped the validation of the schema:

``` python
@verdi_database.command('version')
def database_version():
    """Show the version of the database.

    The database version is defined by the tuple of the schema generation and schema revision.
    """
    from aiida.manage.manager import get_manager

    manager = get_manager()
    manager._load_backend(schema_check=False)  # pylint: disable=protected-access
    backend_manager = manager.get_backend_manager()

    echo.echo('Generation: ', bold=True, nl=False)
    echo.echo(backend_manager.get_schema_generation_database())
    echo.echo('Revision:   ', bold=True, nl=False)
    echo.echo(backend_manager.get_schema_version_database())
```

This was in order to get the information even if there was some error in the schema validation that is performed every time the profile is loaded by default (for identifying possible problems with a setup I seem to remember).

I have two options for dealing with this:

1. I can have the `verdi status` work normally and print the extra information, and then have the `schema_check=False` test be used in the `verdi storage integrity` command.
2. I can add a `try ...(schema_check=False)... except...(schema_check=False)...` clause in the `verdi status` if there is no problem with doing the rest of the status tests with a broken schema (i.e. does it need to read the DB for the checks on the daemon, rabbitmq, etc?).

@sphuber I remember seeing/discussing this from when you included the schema tracking into the DB. I'll try to track down the path that it goes with the `schema_check=False`, but let me know if you already think we should prefer one over the other or how to best "generate/simulate" a broken DB to test this.

**Comment by sphuber** [comment]
> The verdi database version didn't just got the schema and revision, but did so in a way that skipped the validation of the schema

The reason for skipping the schema check is that the command should work even if the database schema is outdated with respect to the code. Otherwise the command would be pointless. So it _has_ to load the database environment without the schema check. What is the problem of running `verdi status` without checking the schema to get the database schema information?

**Comment by ramirezfranciscof** [comment]
> The reason for skipping the schema check is that the command should work even if the database schema is outdated with respect to the code. Otherwise the command would be pointless. So it _has_ to load the database environment without the schema check. What is the problem of running `verdi status` without checking the schema to get the database schema information?

I guess nothing, this was my option 2, I just wanted to check that an outdated schema would also not be a problem for the rest of the subsequent method calls inside the `verdi status`.
