### ISSUE TITLE
After Crash -- Daemon won't start, doesn't provide debugging info

### ISSUE THREAD

**Issue by Zausinator** [aiidateam/aiida-core#5234]
After a weeklong absence due to hardware failures, I am having trouble starting my daemon:
```
~$ verdi daemon start --foreground
Starting the daemon... FAILED
Try to run 'verdi daemon start --foreground' to potentially see the exception
~$
```
The daemon log also does not provide any additional information, the last update being from a week ago. 
Everything else seems to be working fine, I can create new nodes etc..
I am running aiida-core 1.4.3 on an Ubuntu 18.04. Python version is 3.8.3.

If you have any idea what I could still try/read that would be much appreciated. Thanks!

**Comment by dev-zero** [comment]
In my case running the following command manually showed me the traceback (note: my profile is named `default`, change this accordingly):

```
verdi -p default daemon start-circus --foreground
```

**Comment by Zausinator** [comment]
Awesome!!!! Thank you so much, through this I was able to spot that the error was in my version of pyzmq. The version was at 19.0.2, which apparently doesn't have the proper required properties. By reverting it back to 19.0.1 I was able to solve my issue.
Shoutout to you!

**Comment by ltalirz** [comment]
I guess we should include `verdi daemon start-circus --foreground` in the error message as well (?)

**Comment by sphuber** [comment]
The command `verdi daemon start --foreground` (which is already mentioned in the error message) should show exactly the same information.

**Comment by Zausinator** [comment]
Exactly, 
```
verdi daemon start --foreground
```
didn't show any error messages. Only 
```
verdi daemon start-circus --foreground
```
did.

**Comment by sphuber** [comment]
Thanks for confirming @Zausinator . I will update the error message then.
