### ISSUE TITLE
`SshTransport.listdir` pattern handling is wrong

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#5244]
Pretty sure this is erroneous:

https://github.com/aiidateam/aiida-core/blob/08ac107a0776be160f8b60983ce3df071adc75fd/aiida/transports/plugins/ssh.py#L1277-L1280

since `glob` acts on local paths. It looks like it was just copied from `_local_listdir`.
I imagine the tests pass, on GH actions because the SSH is just set up to connect to the localhost

unless I'm missing something @giovannipizzi @sphuber?

**Comment by sphuber** [comment]
Never touched that part of the code, but I would agree that that seems incorrect.

**Comment by giovannipizzi** [comment]
Thanks, you're right! I opened a PR to fix the bug.
As I mentioned in the commit, maybe in the future we should run the tests for the transport against a docker container - this however requires (a bit of) work to rewrite the way SSH tests are run probably...
