### ISSUE TITLE
`verdi`: add `backup` sub-command to the `storage` group

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#5273]
One separate and possibly major outstanding addition of the `verdi storage` command (discussed in #4321 , implemented in #5228 and #4965) is to add the possibility of using a `backup` command that would allow users to very easily create backups for their AiiDA profiles.

**Comment by chrisjsewell** [comment]
Agreed, although I don't think we should being telling "general" users to do it how we do now (see https://aiida.readthedocs.io/projects/aiida-core/en/develop/howto/installation.html#backing-up-your-installation), it should be a backend agnostic mechanism.

I'd note you can run `verdi archive create --all  --include-authinfos`, then that effectively backs up the entire profile, with the current drawbacks:

1. It doesn't backup profile level options that can be set in the config.json, this might be nice to optionally save in an archive
2. Its not ideal to be creating a new archive every time (particularly for large profiles). Here updatable archives would be nice, which is entirely possible with the new infrastructure and export/import code (also the push/pull mechanism we have started to discuss may be relevant here)

**Comment by giovannipizzi** [comment]
@eimrek @sphuber this can be closed now?

**Comment by sphuber** [comment]
Implemented in #6069
