### ISSUE TITLE
Test v2.0 before release with high verbosity and remove warnings that can be removed

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#5282]
I think it would be double check that there are no warnings that go unnoticed (either because some parts of the code still use deprecated features, or because new features issue warnings). We can use this issue to track warning that occur while testing 2.0.

(I will also create another issue to discuss syncing other dependencies during the phase between the 2.0RC and the 2.0 release).

**Comment by giovannipizzi** [comment]
Is this something that should be improved?
```
$ verdi process list
/Users/pizzi/git/aiida-core/aiida/orm/implementation/sqlalchemy/querybuilder/main.py:223: SAWarning: Class jsonb_typeof will not make use of SQL compilation caching as it does not set the 'inherit_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make use of the cache key generated by the superclass.  Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
  for row in self.get_session().execute(stmt):
   PK  Created    Process label    Process State    Process status
-----  ---------  ---------------  ---------------  ----------------
51640  17h ago    PwCalculation    ⏹ Created

Total results: 1

Report: last time an entry changed state: 17h ago (at 20:57:57 on 2021-12-16)
Report: Using 0% of the available daemon worker slots.
```

**Comment by ltalirz** [comment]
Also ran into this warning, now in `/home/aiida/aiida-core/aiida/storage/psql_dos/orm/querybuilder/main.py:223`
https://github.com/aiidateam/aiida-core/blob/d0ff88986391691a0307d0cafb300dbf48e303b3/aiida/storage/psql_dos/orm/querybuilder/main.py#L223


This is about caching the mapping between ORM and the corresponding SQL query string.

Maybe we should just try adding `inherit_cache = True` here
https://github.com/aiidateam/aiida-core/blob/d0ff88986391691a0307d0cafb300dbf48e303b3/aiida/storage/psql_dos/orm/querybuilder/main.py#L66-L67

and start by checking whether any tests break?

**Comment by chrisjsewell** [comment]
Yeh cheers, I already mentioned internally that I was aware of this, and planning to fix. But happy for you to give it a go cheers 😄

**Comment by ltalirz** [comment]
Just mentioning that the specific issue raised by Giovanni has been resolved.
If others encounter warnings during testing, feel free to add - otherwise I suggest to close this after the 2.0 release.
