### ISSUE TITLE
Make sure key external packages/plugins are updated to 2.0

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#5284]
A number of key external packages and plugins should be updated to make sure they work with 2.0.

I suggest to do the work as soon as the RC is out (mid Jan?), to make sure that key packages are updated before the actual release (1 month should be enough?)
Linking to #5282 as this is also related to checking warnings (but due to external packages issuing warnings, or even crashing, rather than aiida-core itself).

I add here a few things to check, feel free to add comments or edit this description to add more, and we can track progress here.

- [ ] encourage all plugins to support 2.0, and to replace their dependencies from `<2.0` to `<3.0` (now installing any plugin like this will actually revert AiiDA's version to 1.6.5 which is pretty annoying if people don't realise they are installing an older version). Actually if anybody has some clever idea on how to avoid that people have to keep reverting downgrades would be great as I see this as a common problem for a few months - but I don't know if `pip` allows to do this in simple way?
- [ ] at least we should upgrade the following packages and release a new version:
   - `aiida-quantemespresso` (@mbercx)
   - `aiida-pseudo` (I noticed for instance that the CLI uses some classes that have been probably moved) (@sphuber)
   - strongly encourage all aiida-common-workflows plugins to upgrade, as well as the `aiida-common-workflows` package itself (@sphuber  or @bosonie, and ping the various plugin developers)
   - `aiida-submission-controller` (@giovannipizzi)
   - `aiida-wannier90` (@qiaojunfeng) and possibly related packages (like the aiida-wannier90-theosworkflows)

**Comment by giovannipizzi** [comment]
Also, as soon as the RC of 2.0 is released, we should actively reach out to developers of plugins in various possible channels (GitHub discussion channel, AiiDA mailing list, issues in the respective repos, possibly direct contact where we know them) to ask them to actively address 2.0 compatibility (fully reading the 2.0 wiki page), ideally during the month from the RC to the release.

**Comment by sphuber** [comment]
Closing this as most if not all plugins have been updated.
