### ISSUE TITLE
CI failing because of compilation issue of `pymatgen`

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5293]
Recently, CI builds started failing as soon as the tests start:
```
==================================== ERRORS ====================================
__________________ ERROR collecting tests/test_dataclasses.py __________________
tests/test_dataclasses.py:62: in <module>
    ???
aiida/orm/nodes/data/structure.py:107: in has_pymatgen
    import pymatgen  # pylint: disable=unused-import
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymatgen/__init__.py:20: in <module>
    from .core.composition import Composition  # noqa
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymatgen/core/__init__.py:11: in <module>
    from .lattice import Lattice  # noqa
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymatgen/core/lattice.py:23: in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymatgen/util/coord.py:17: in <module>
    from . import coord_cython as cuc
pymatgen/util/coord_cython.pyx:1: in init pymatgen.util.coord_cython
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
____________ ERROR collecting tests/orm/nodes/data/test_jsonable.py ____________
tests/orm/nodes/data/test_jsonable.py:6: in <module>
    from pymatgen.core import Molecule
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymatgen/__init__.py:21: in <module>
    from .core.lattice import Lattice  # noqa
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymatgen/core/__init__.py:11: in <module>
    from .lattice import Lattice  # noqa
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymatgen/core/lattice.py:23: in <module>
    from pymatgen.util.coord import pbc_shortest_vectors
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pymatgen/util/coord.py:17: in <module>
    from . import coord_cython as cuc
pymatgen/util/coord_cython.pyx:1: in init pymatgen.util.coord_cython
    ???
E   ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
=============================== warnings summary ===============================
```
We have seen this problem before where there is a mismatch between the versions of `numpy` with which `pymatgen` is built and the version of `numpy` that ends up being installed. This may have to do with the fact that `numpy==1.22.0` was released recently.

Since the build process of `pymatgen` uses a different system than we use to install our package, our dependency requirements are not respected by `pymatgen`'s build process. Since they only require a lower limit, it is possible that during the build process `numpy==1.22.0` is installed. However, when `aiida-core` is installed, another (incompatible) version of `numpy` is installed.

In the past, as a workaround, we used to install an older version of `numpy` explicitly, _before_ installing `aiida-core`, which would prevent the building of `pymatgen` to install the latest version of `numpy`. However, this approach no longer seems to work and we still run in the problem reported above.

**Comment by csadorf** [comment]
It seems that the user installation is so far not affected: https://github.com/aiidateam/aiida-core/actions/runs/1665900358

**Comment by sphuber** [comment]
I opened two separate issues with `pymatgen` because I suspect a solution might have to be implemented there, although not sure:

* [Builds failing on Python 3.8](https://github.com/materialsproject/pymatgen/issues/2333)
* [Building will fail on Python 3.10](https://github.com/materialsproject/pymatgen/issues/2332)

The origins for these two are different. Especially the first one is problematic for us, but the second may be in the future if 3.10 becomes more widespread.

Not sure yet if there is a workaround we can implement on our side for the time being.

**Comment by ramirezfranciscof** [comment]
I think the fixes they did for those issues are not enough? I tried updating the version of `pymatgen` to their latest release [here](https://github.com/aiidateam/aiida-core/pull/5296/files), but I am still getting the [same errors](https://github.com/aiidateam/aiida-core/runs/4773584845?check_suite_focus=true). Did I do something wrong?

**Comment by sphuber** [comment]
The problem can be reproduced locally by running the following:
```
mkvirtualenv test_pymatgen
pip install pymatgen  # Will install latest version, that is built with latest version of `numpy`, currently `v1.22.0`
pip install numpy==1.21.4  # Now install an older `numpy` version
python -c 'from pymatgen.util.coord import pbc_shortest_vectors'
```
The last command will incur the exception:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/sph/.virtualenvs/test_pymatgen/lib/python3.8/site-packages/pymatgen/util/coord.py", line 17, in <module>
    from . import coord_cython as cuc
  File "pymatgen/util/coord_cython.pyx", line 1, in init pymatgen.util.coord_cython
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```
