### ISSUE TITLE
Docs: Clarify where calculation goes in CalcJob

### ISSUE THREAD

**Issue by Drvanon** [aiidateam/aiida-core#5304]
### Describe the current issue

Right now when I go into the documentation for [CalcJobs ](https://aiida.readthedocs.io/projects/aiida-core/en/latest/topics/calculations/usage.html#calculation-jobs), I first am introduced to the calcfunction, in which we learn to write an addition function. Then we learn how to write a CalcJob that should do the same thing. However in the example provided, we are never shown where the actual addition should go. 

### Describe the solution you'd like

It would be very nice if you would complete the CalcJob so that it is clear where the python code (as opposed to the commandline code) would go.

### Note
Please note that I am very new to AiiDA and that this question may come from me not understanding AiiDA sufficiently well. In that case, please label this issue with help, because it remains unclear to me how to write proper CalcJobs, because of the aforementioned issue.

**Comment by sphuber** [comment]
The idea of the `CalcJob` is that you don't do the addition (or whatever computation it may be, the addition is just a simple example) yourself in the implementation, but that you _wrap_ some external executable that does the work for you. In the example, we use the `bash` shell to perform the addition, so the `CalcJob` writes a bash script based on the inputs and tells AiiDA how to run it. The example that is shown in the documentation is complete, and would be able to run. If you have more user questions, the best place to ask them is [the mailing list](https://www.aiida.net/mailing-list/).
