### ISSUE TITLE
Write plugin migration script for AiiDA v2.0

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#5335]
Some of the changes that plugin developers need to make in order to migrate their plugin can be automated. It would be great if we could create a script that automatically makes as many of the required changes as possible.

In this issue we can keep track of a list of changes which we want to automate:

- [ ] Adding the `core.` prefix to the entry points of the `aiida-core` classes.
- [ ] Removing the now unnecessary `dict=` and `list=` keyword arguments from `Dict` and `List` node initializations.
- [ ] Substituting `echo_highlight` for `echo`, see [this comment](https://github.com/aiidateam/aiida-core/issues/5335#issuecomment-1047801004).

We could also look in the plugin for code that might break because of backwards incompatible changes and warn the developer. For example:

- [ ] Look for equality comparisons of `Dict` nodes, and warn that these now compare the _content_ of the node.

**Comment by chrisjsewell** [comment]
Thanks @mbercx, yeh as mentioned in the aiida meeting, I was interested in having a look if the code in something like https://github.com/asottile/pyupgrade could be adapted to do achieve this,
i.e. read in a python file, make some changes, re-write the python file

**Comment by mbercx** [comment]
`echo_highlight` was also removed from `aiida.cmdline.utils` in 2eba6aba5fe7ab1993672203c317b8058710aa67. Had to do the following changes for `aiida-pseudo`:

```diff
-        echo.echo_highlight(' [FAILED]', color='error', bold=True)
+        echo.echo(' [FAILED]', fg=echo.COLORS['error'], bold=True)
```

```diff
-        echo.echo_highlight(' [OK]', color='success', bold=True)
+        echo.echo(' [OK]', fg=echo.COLORS['success'], bold=True)
```

Should be easy enough to look for these and replace, although I'm not sure if many plugins use the CLI utils.

**Comment by chrisjsewell** [comment]
Lets play around with this over in https://github.com/aiidateam/aiida-upgrade/discussions/1 😄

**Comment by sphuber** [comment]
I will close this as `v0.1.0` of `aiida-upgrade` has been released and can be used. We can track improvements there.
