### ISSUE TITLE
code setup unit test failed when running in local machine 

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5346]
When run:

```
pytest tests/cmdline/commands/test_code.py::test_noninteractive_remote
```

I got the following error:

```
        runner = click.testing.CliRunner()
        result = runner.invoke(command, options, input=user_input, obj=obj, **kwargs)
    
        if raises:
            assert result.exception is not None, result.output
            assert result.exit_code != 0
        elif catch_exceptions:
>           assert result.exception is None, ''.join(traceback.format_exception(*result.exc_info))
E           AssertionError: Traceback (most recent call last):
E               File "/home/jyu/Projects/WP-aiida/aiida_core/aiida/cmdline/params/types/plugin.py", line 249, in convert
E                 entry_point = self.get_entry_point_from_string(value)
E               File "/home/jyu/Projects/WP-aiida/aiida_core/aiida/cmdline/params/types/plugin.py", line 202, in get_entry_point_from_string
E                 raise ValueError(
E             ValueError: entry point 'core.arithmetic.add' matches more than one valid entry point group [aiida.calculations aiida.calculations], please specify an explicit group prefix
```

Any idea how to fix this? What is the current strategy of doing reentry, I guess that is related?
I am in the latest develop branch.

**Comment by sphuber** [comment]
This is a problem with the entry points. Try running `pip install -e .` again and see if that fixes it.

**Comment by unkcpz** [comment]
Sadly no. I also tried uninstalling and install again but not help.

**Comment by sphuber** [comment]
how did you uninstall? If you have mixed normal with editable installs, that can also sometimes give problems. Make sure you remove all aiida_core packages from the virtual environment, something like `rm -rf /path/to/venv/lib/python3.9/site-packages/aiida_core*` and then also remove `aiida_core.egg-info/` in your local repository

**Comment by sphuber** [comment]
By the way, what do you get when you run `verdi plugin list aiida.calculation` do you see an error or duplicate plugins there as well?

**Comment by unkcpz** [comment]
> By the way, what do you get when you run verdi plugin list aiida.calculation do you see an error or duplicate plugins there as well?

It is all fine with this entry point group. Only pytest failed.

**Comment by unkcpz** [comment]
> then also remove aiida_core.egg-info/ in your local repository. 

This solve the issue. Thanks a lot! @sphuber
