### ISSUE TITLE
Editable install of aiida 1.6.x fails in system conda environment

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5363]
This is an issue I encountered installing

 - aiida-core 1.6.5 from GitHub
 - with pip 22.0.3 (latest)
 - in editable mode
 - in a conda environment managed by `root` (like on the AiiDA lab)

Here, pip needs to figure out that it should do a `--user` install - and it does for the most part but at some point along the line it fails:

```
$ pip install -e .
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/aiida/aiida-core
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
...
        ipython -> {'pygments.lexers': {'ipython': 'ipython = IPython.lib.lexers:IPythonLexer', 'ipython3': 'ipython3 = IPython.lib.lexers:IPython3Lexer', 'ipythonconsole': 'ipythonconsole = IPython.lib.lexers:IPythonConsoleLexer'}}running develop
    
    /tmp/pip-build-env-5nyjyazk/overlay/lib/python3.7/site-packages/setuptools/command/easy_install.py:163: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      EasyInstallDeprecationWarning,
    WARNING: The user site-packages directory is disabled.
    /tmp/pip-build-env-5nyjyazk/overlay/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    error: can't create or remove files in install directory
    
    The following error occurred while trying to add or remove files in the
    installation directory:
    
        [Errno 13] Permission denied: '/opt/conda/lib/python3.7/site-packages/test-easy-install-894427.write-test'
    
    The installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        /opt/conda/lib/python3.7/site-packages/
    
    Perhaps your account does not have write access to this directory?  If the
    installation directory is a system-owned directory, you may need to sign in
    as the administrator or "root" account.  If you do not have administrative
    access to this machine, you may wish to choose a different installation
    directory, preferably one that is listed in your PYTHONPATH environment
    variable.
    
    For information on other options, you may wish to consult the
    documentation at:
    
      https://setuptools.pypa.io/en/latest/deprecated/easy_install.html
    
    Please make the appropriate changes for your system and try again.
    
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
``` 

I'm not necessarily suggesting that this needs to be fixed; I'm just reporting this here since there is a simple workaround: delete the `pyproject.toml` file and try again.

**Comment by sphuber** [comment]
Do you know why removing `pyproject.toml` makes it possible to install? It would be interesting to see if current develop can be installed in editable mode, because there we use `flit` as the backend and we no longer rely on `setup.py` and the custom `setup.json` but purely `pyproject.toml`. If that works, we can backport those changes to `support/1.6.x` and make a release together with the other fix you cherry-picked.

**Comment by ltalirz** [comment]
Thanks a lot for looking into this @sphuber !

> Do you know why removing `pyproject.toml` makes it possible to install?

I don't, sorry.


> It would be interesting to see if current develop can be installed in editable mode

That's a good point.

I tried, but it turns out this fails when trying to uninstall aiida 1.6.5 ("permission denied '/opt/conda/bin/runaiida'").

This sounds like the correct behavior to me in this case, which makes me realize that the case I mentioned above may be a bit special: 1.6.5 already installed on system level; me re-installing it at the `--user` level.

It's still worth mentioning, since this is how the AiiDAlab environment is set up, and users may need to apply fixes to their aiida-core installation from time to time.

Since this is potentially so specific to the AiiDAlab setup, I'm not sure whether this warrants removing the `pyproject.toml` (or at least its `build-system` section) on `support/1.6.x` .

I'm going to close this issue; if others encounter the same problem, please comment here and we can reevaluate.

**Comment by ltalirz** [comment]
P.S. There is a workaround for this as well: combining the `-I/--ignore-installed` option (possibly combined with `--no-deps`).
