### ISSUE TITLE
readthedocs build failing

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5367]
See https://readthedocs.org/projects/aiida-core/builds/16126865/

ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/docs/checkouts/readthedocs.org/user_builds/aiida-core/envs/stable/lib/python3.8/site-packages/markupsafe/__init__.py)

tagging @chrisjsewell @sphuber

**Comment by sphuber** [comment]
The culprit is [`markupsafe==2.1.0` that was release 6 hours ago](https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0).

**Comment by sphuber** [comment]
Issue on `jinja2` for fixing it is here: https://github.com/pallets/jinja/issues/1587

**Comment by chrisjsewell** [comment]
> Additionally, please read [hynek.me/articles/semver-will-not-save-you](https://hynek.me/articles/semver-will-not-save-you/)

Thanks, but I'm well aware of these blog posts, so let's not get into the whole upper pinning discussion here 😅 

You've provided me an interesting example for my discussion though: https://github.com/executablebooks/meta/issues/648#issuecomment-1044669191

**Comment by CasperWA** [comment]
Will this be implemented as part of a patch update to the latest public release of AiiDA in the near future?

**Comment by sphuber** [comment]
We are close to releasing `2.0.0b1` early next week. This should include this fix.

**Comment by CasperWA** [comment]
> We are close to releasing `2.0.0b1` early next week. This should include this fix.

But no backport/hotfix for v1.x?

**Comment by sphuber** [comment]
No probably will do that as well. The support branch already has another cherry-picked fix that would merit a release

**Comment by CasperWA** [comment]
Much appreciated. I'm seeing this error when simply installing AiiDA on a fresh environment and trying to import a DB... So I'd consider it critical :)

**Comment by CasperWA** [comment]
[It seems](https://github.com/aiidateam/aiida-optimade/runs/5449062470?check_suite_focus=true) this did not fix the issue at hand. Since the `markupsafe` restriction is in the `docs` extra it isn't respected when installing AiiDA straight up.
When installing AiiDA straight up, `markupsafe` is still a dependency, and then `verdi import` fails. I.e., AiiDA v1.6.6 can be considered broken.

**Comment by sphuber** [comment]
Round number two: https://pypi.org/project/aiida-core/1.6.7/ :pray:
