### ISSUE TITLE
CI: Test-install workflow timing out more often

### ISSUE THREAD

**Issue by csadorf** [aiidateam/aiida-core#5370]
@chrisjsewell It looks like the test-install CI workflow jobs are [reaching the time limit significantly more often](https://github.com/aiidateam/aiida-core/actions/workflows/test-install.yml?query=event%3Aschedule) rendering them flaky. I had created a PR last week to address that (#5351), however you suggested an alternative. I still think that we either have to increase the test efficiency or increase the time limit to address this.

**Comment by chrisjsewell** [comment]
Heya, this was already fixed in #5354
