### ISSUE TITLE
Replace use of `simplejson` with built-in `json` module

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5374]
`aiida-core` ships with the `aiida.common.json` module which provides the `dump`, `dumps`, `load` and `loads` functions that have the same interface as the `json` module of the standard library. These custom wrappers are used internally by AiiDA to serialize and deserialize JSON before it is written to files in the repository or in the database. For the implementation it uses [`simplejson`](https://simplejson.readthedocs.io/en/latest/) which is the externally maintained version of `json` to provide backwards compatibility of old Python versions. Since we no longer support those Python versions, it would be good to investigate if we can remove these custom wrappers and libraries and simply rely on the standard library.

**Comment by soma2000-lang** [comment]
@sphuber  can i work on this
