### ISSUE TITLE
Migration message

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#5399]
Currently, the migration message already says `Migrating your storage might take a while and is not reversible.`

In principle this is already enough, but we know people just press ENTER without reading all of it...
Also, "a while" could mean minutes, and then after 24h the user might be bewildered (it's true that there's a progress bar, but e.g. the previous migration can also take >20 minutes for DBs with millions of nodes). 

I'm wondering if we can make more explicit that:
- if you have few nodes this can jus take minutes, but if you have millions of nodes, this will probably take multiple hours and up to few days (see also stats in the discussion thread #5379)
- "is not reversible" is not equivalent to "it's better not to interrupt it" (even if in principle it should not be too bad, there are transactions etc., but we didn't really stress-test that part). I would suggest to tell explicitly not to interrupt it, and even suggest to run in a `screen` if they are connected remotely (or it's too much)?

@sphuber @chrisjsewell @ramirezfranciscof what do you think? I don't want to make big changes, probably just understanding if/how we can make the message more explicit without making it too long. Suggestions welcome.

**Comment by giovannipizzi** [comment]
Also (seen the experience with Quantum Mobile, where most of the problems come from low disk space): should we warn users that they will need a lot of disk space since all the repo will be duplicated (can be manually freed later, but during the process you need the disk space)?

**Comment by sphuber** [comment]
Given that we have released v2.0, I think we can close this for now. If we get messages from users that they think things seem stuck, we can reopen and implement a verbose messaging.
