### ISSUE TITLE
verdi code setup input plugin prompt does not show the list of calculations for choosing

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5406]
Configuring code in aiida-core v2.0.0 when asked for the Default calculation input plugin the help message does not give the list of entry points anymore but only show:

```
...
Default calculation input plugin: ?
Entry point name of the default calculation plugin (as listed in 'verdi plugin list aiida.calculations').
```

which is not very convenient to stop and check the plugins.

**Comment by mbercx** [comment]
I've also noticed that when setting up a code from a config file, the instructions for the prompts still appear even when the file has all the required information:

```console
$ verdi code setup --config qe-6.8-matdyn@localhost.yaml 
Report: enter ? for help.
Report: enter ! to ignore the default and set no value.
Success: Code<236443> qe-6.8-matdyn@localhost created
```

**Comment by sphuber** [comment]
Opened #5432 to fix the issue of the OP. Issue mentioned by @mbercx has a different source, so will split it off in a separate issue.
