### ISSUE TITLE
verdi load time check failing on `develop`

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5459]
On the most recent commit 2982e404bcceb1e979f4097541544fa7584c1ebe I'm [seeing](https://github.com/aiidateam/aiida-core/runs/5635468174?check_suite_focus=true)

``` 
Run verdi devel check-load-time
/home/runner/work/aiida-core/aiida-core/aiida/manage/configuration/settings.py:61: UserWarning: Creating AiiDA configuration folder `/home/runner/.aiida`.
  warnings.warn(f'Creating AiiDA configuration folder `{path}`.')
Success: no issues detected
WARNING: loading time 0.42 at iteration 1 above 0.4
WARNING: loading time 0.40 at iteration 2 above 0.4
WARNING: loading time 0.40 at iteration 3 above 0.4
WARNING: loading time 0.41 at iteration 4 above 0.4
WARNING: loading time 0.43 at iteration 5 above 0.4
ERROR: loading time exceeded the load limit 5 consecutive times.
ERROR: please check that 'aiida.cmdline' does not import 'aiida.orm' at module level, even indirectly
ERROR: also, the database backend environment should not be loaded.
Error: Process completed with exit code 2.
``` 

I recall that I saw the same in a PR of mine I worked on March 20th, i.e. I suspect that the performance issue was introduced before that (or the github action runners are getting slower/less reliable ...)

Any ideas what might be causing this?

**Comment by chrisjsewell** [comment]
> Any ideas what might be causing this?

No not really, I even removed `aiida.backend` (now `aiida.storage`) from the "allowed" loaded modules.

unless there's a quick solution here, let's increase the time limit to ~0.42, so we don't have to mess around re-running tests for this known issue

**Comment by chrisjsewell** [comment]
(and also it's normally only the older python 3.8 that it fails on)

**Comment by sphuber** [comment]
It's been doing this for a while, slowly crept up. The margin on the GHA runners was always minimal. If we cannot find a clear offender, we might just need to up the threshold to 0.45

**Comment by sphuber** [comment]
I have profiled it a bit and see nothing out of the ordinary or anything that could/should be removed. So if it keeps failing, just up it to .45

**Comment by sphuber** [comment]
This hasn't been failing for a while now so I will temporarily close this. We'll reopen and increase the timeout if it starts failing again
