### ISSUE TITLE
Shell completion broken for click > 8.1.0

### ISSUE THREAD

**Issue by chrisjsewell** [aiidateam/aiida-core#5502]
Due to this https://github.com/pallets/click/commit/f2e579ab187ca8fdfbe6ce86de08f0e9f62fe4ae

which doesn't match the override here: https://github.com/aiidateam/aiida-core/blob/b404a2aaa25baed7c3d3315ae269859bb5952c97/aiida/cmdline/commands/cmd_verdi.py#L37

@sphuber, given this issue was fixed in https://github.com/pallets/click/pull/2041, do we actually need this override anymore?

**Comment by sphuber** [comment]
> do we actually need this override anymore?

That depends. Does it now auto-complete option values starting with `~` for example? I added tests I believe so the CI should catch it if it doesn't when you remove the patch.

**Comment by chrisjsewell** [comment]
> Does it now auto-complete option values starting with ~ for example?

No idea, but patching private methods is shaky ground 😅 so if it doesn't, I would just suggest making a PR to click

**Comment by sphuber** [comment]
> I would just suggest making a PR to click

We did originally and they refused it. Bit surprised they accepted it in the end. Anyway, we needed this hacky fix for the time being.

But looking at the code, it seems indeed that they fixed it and we can now remove the work around.
