### ISSUE TITLE
write info of caching source to extra attributes of process when it is created from caching

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5524]
When a process is run and created from a caching node, it has no information record that it is run by caching. 
I think this information is useful to show in `verdi process status` for debugging caching behaviors when writing workflows and also useful in querying to filter out the cached node.

**Comment by sphuber** [comment]
Are you sure? The source should be added to the extras with the key `_aiida_cached_from`. You can get it from the node through `node.base.caching.get_cache_source()`.

**Comment by unkcpz** [comment]
Okay, I didn't know that. Thanks!
