### ISSUE TITLE
Raise when detecting multiple matching entry points

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5530]
### Describe the bug
Due to a slight misunderstanding of the new `importlib.metadata` API, AiiDA did no longer raise when detecting multiple entries for a given entry point (pair of group + name), and instead simply loaded the first one.

Will open PR to fix

**Comment by ltalirz** [comment]
While our code clearly intends to do this check (and was doing it), I now notice that reintroducing it creates problems e.g. in the AiiDAlab environment, where users may want to e.g. install a newer AiiDA version over the one that is shipped with the image (and which they can't remove).

E.g. after installing a separate AiiDA version in the user's local environment, opening the `verdi shell` gives me
```
ValueError: aiida.groups:core is not a valid entry point string: Multiple entry points 'core' found in group 'aiida.groups': [EntryPoint(name='core', value='aiida.orm.groups:Group', group='aiida.groups'), EntryPoint(name='core', value='aiida.orm.groups:Group', group='aiida.groups')]
```

I'm a little surprised that this did not surface before... it's true that we started using entry points more in aiida-core, but we were using them also before.

In my view it needs to be possible to install AiiDA over an existing installation.

One thing we could do is: if multiple entries are discovered, check whether their values (target strings) are the same.
If they are, then it does not matter which one we load and we can proceed.
If their values differ, we don't know what to do and raise.

I will add this to the PR now.

@csadorf @sphuber thoughts welcome

**Comment by chrisjsewell** [comment]
Are you sure you are not misunderstanding the difference between importlib.metadata and importlib_metadata, the latter of which implements the new python 3.10 API

**Comment by ltalirz** [comment]
> Are you sure you are not misunderstanding the difference between importlib.metadata and importlib_metadata, the latter of which implements the new python 3.10 API

What would make you think that?
