### ISSUE TITLE
Exception in verdi archive create with FolderData nodes on a packed storage

### ISSUE THREAD

**Issue by Crivella** [aiidateam/aiida-core#5564]
### Describe the bug

An exception is raised when running the command `verdi archive create` on a CifData Node:
```
verdi archive create -f -N 45747 -- test.aiida
Report: 
Archive Parameters
--------------------  ----------
Path                  test.aiida
Version               main_0001
Compression           6

Inclusion rules
----------------------------  --------
Computers/Nodes/Groups/Users  Selected
Computer Authinfos            False
Node Comments                 True
Node Logs                     True

Traversal rules
---------------------------------  -----
Follow links input calc forwards   False
Follow links input calc backwards  True
Follow links create forwards       True
Follow links create backwards      True
Follow links return forwards       True
Follow links return backwards      False
Follow links input work forwards   False
Follow links input work backwards  True
Follow links call calc forwards    True
Follow links call calc backwards   True
Follow links call work forwards    True
Follow links call work backwards   True

Report: Validating Nodes                                                                                                                                                                                    
Report: Creating archive with:
-----  -
users  1
nodes  1
-----  -
Traceback (most recent call last):                                                                                                                                                                          
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/bin/verdi", line 8, in <module>
    sys.exit(verdi())
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/aiida/cmdline/utils/decorators.py", line 73, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/aiida/cmdline/commands/cmd_archive.py", line 197, in create
    create_archive(entities, filename=output_file, archive_format=archive_format, **kwargs)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/aiida/tools/archive/create.py", line 341, in create_archive
    _stream_repo_files(archive_format.key_format, writer, entity_ids[EntityTypes.NODE], backend, batch_size)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/aiida/tools/archive/create.py", line 585, in _stream_repo_files
    writer.put_object(stream, key=key)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/aiida/tools/archive/implementations/sqlite_zip/writer.py", line 186, in put_object
    self._stream_binary(f'{utils.REPO_FOLDER}/{key}', stream, buffer_size=buffer_size)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/aiida/tools/archive/implementations/sqlite_zip/writer.py", line 171, in _stream_binary
    handle.seek(0, os.SEEK_END)
  File "/home/aiida/.virtualenvs/aiida-mat2D_2/lib/python3.8/site-packages/disk_objectstore/utils.py", line 421, in seek
    raise NotImplementedError(
NotImplementedError: Invalid value for `whence`: only 0 and 1 are currently implemented.
```

In my particular use case, this was happening when trying to export a StructureData of the newly migrated MC2D database. I was able to single out the CifData as the offender by checking the topmost nodes in the provenance tree 1 by 1.
### Steps to reproduce

I was not able to reproduce this in a new environment.
At least exporting the CIF file of the tested node, and creating a new CifData in a new virtual environment using
```
from aiida import orm
c = orm.CifData(file='/PATH_TO_FILE/test.cif')
c.store()
```
does not reproduce the error

### Your environment

- Operating system [e.g. Linux]: Ubuntu 20.04.1 LTS
- Python version [e.g. 3.7.1]: 3.8.10
- aiida-core version [e.g. 1.2.1]: 2.0.1

@chrisjsewell @giovannipizzi

**Comment by Crivella** [comment]
After more investigation i was able to find a way to reproduce the bug:

- Create a new virtual environment
- `pip install aiida-core[atomic_tools]==1.6.5]`
- setup the profile on a new DB/archive
- `verdi shell`
- $ `from aiida import orm`
- $ `c = orm.CifData(file='/PATH_TO_FILE/test.cif')
- `pip install --upgrade aiida-core` (upgrade aida to 2.0.1
- verdi archive migrate -N 1 -- test.aiida

It seems that the bug is indeed related to migrated CifData nodes from aiida 1.6.5 to 2.0

**Comment by Crivella** [comment]
Another test.
The problem is not related to the migration itself, but to the packed archive.

I checked the `packs.idx` files in the storage of the 2 venv i used for the test and the one where the archive creation was successful did not have any entry. I assume this mean that all the archive was still loose and not packed.
If i run `verdi storage mantain` than i get the same exception when trying to create the export file.

Also this is not limited to CifData but to FolderData node in general

**Comment by Crivella** [comment]
Thanks @chrisjsewell  for the fast reply.

I guess idea (c) is the best for an hotfix by changing lines 171-172 to
```
        try:
            handle.seek(0, os.SEEK_END)
        except NotImplementedError:
            file_size = 1
        else:
            file_size = handle.tell()
```

While for long term the best solution would be (a)  or (b).
I think this code suggestion would work well because once the `NotImplementedError` is removed from `disk_objectstore` no code changes will be needed to aiida-core, and if idea (b) needs to be implemented it can be added under the `except` clause instead of the `file_size = 1` line

**Comment by giovannipizzi** [comment]
I think allowing to use this method on a zipped object will always require to decompress the whole stream, which is inefficient for large repositories with many compressed files.
So even if we implement SEEK_END (a), I would avoid using it for this purpose.

(b) could work: @chrisjsewell do we need to be very generic in this specific file about *any* bytes stream, or we can assume it's a disk-objectstore one? E.g. the caller could just ask the metadata to the disk-objectstore (with `get_objects_stream_and_meta`), and then pass it an optional size hint, default = None meaning please compute it yourself (or, better, just use Zip64? See below).

(c) I think this might indeed be the easiest. I think @Crivella solution is *almost* OK, but specifying a size of 1 will not enable Zip64. I think in the past we didn't see major slowdowns of using Zip64, so we can just use that by default (if we don't have size hints, see point (b) above). Therefore in the except clause, one would put `file_size = VERY_LARGE_SIZE_TO_ENFORCE_ZIP64`?
