### ISSUE TITLE
Allow user to restrict caching to successfully finished calculations

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5572]
### Is your feature request related to a problem? Please describe

By default, AiiDA caches all calculations where the node `.is_finished`.
This includes calculations that finish with non-zero exit codes.

I'm not necessarily suggesting changing the default setting, but I have encountered multiple scenarios where the user expects all calculations to finish with exit code 0.
When a calculation fails, it is perhaps because of some temporary hardware/network issue, or there might be some hidden parameters that AiiDA does not track - in short, one would not like to cache the result.

As far as I am aware (haven't yet looked into the code, just at the docs), there is no straightforward way to tell AiiDA "only cache calculations with exit code 0" (`.is_finished_ok`).

### Describe the solution you'd like

There should be a simple way for an AiiDA user to tell AiiDA to only cache calculations that are finished ok - e.g. via a `verdi config` setting.

**Comment by ltalirz** [comment]
Relevant part of the code
https://github.com/aiidateam/aiida-core/blob/2c183fc4486e00f3348a1b66cdcd6d9fbfd563f0/aiida/orm/nodes/process/process.py#L43

**Comment by ltalirz** [comment]
Just came across another instance of this, where a user was surprised about this behavior. @sphuber what do you think of this?

Seems to me it would be quite straightforward to implement

**Comment by sphuber** [comment]
Can I ask a bit more about the specific case? There are tools for plugins to mark certain exit codes as invalid for the cache. For example:
```python
class SomeCalcJob(CalcJob):

    @classmethod
    def define(cls, spec):
        super().define(spec)
        spec.exit_code('SERIOUS_ERROR', 300, invalidates_cache=True)
```
Any calculation that has this error code will not be cached from.

We use this functionality in `aiida-quantumespresso`, for example, where we maintain a convention that all exit codes below `400` are irrecoverable errors and a base `CalcJob` is used to automatically set `invalidates_cache=True` for all those exit codes: https://github.com/aiidateam/aiida-quantumespresso/blob/main/src/aiida_quantumespresso/calculations/base.py

The reason I am saying this is that I am not sure that a _blanket_ disabling of all non-zero exit statuses for caching is a solution either. Typically there are some exit statuses that can be cached from and certain not.

Still, if the use-case you found clearly does make this simple binary switch, then I can look into adding such a configuration switch.

**Comment by ltalirz** [comment]
Thanks for the detailed follow-up @sphuber !

One use case is instabilities in AiiDA (was the case here, see https://github.com/aiidateam/aiida-core/issues/3867#issuecomment-1286750836); another use case is anything outside the control of AiiDA (node failure / ...) that can lead to a calculation intermittently failing, when it should succeed in a "mathematical sense".

**Comment by sphuber** [comment]
> One use case is instabilities in AiiDA (was the case here, see https://github.com/aiidateam/aiida-core/issues/3867#issuecomment-1286750836); another use case is anything outside the control of AiiDA (node failure / ...) that can lead to a calculation intermittently failing, when it should succeed in a "mathematical sense".

Can you give a concrete example of a calculation plugin and the relevant exit code?

Let's say that we provide this option and a user enables it as they use a calculation plugin that has an exit code that corresponds to a calculation that should not be cached from. That fixes _that_ particular problem, but the direct consequence is that any other non-zero exit status will also be affected. If they run `aiida-quantumespresso` for example, caching will effectively be useless. `PwCalculation` has many non-zero exit status that are perfectly fine to serve as a cache and actually *should*! So I still have the feeling that the correct solution, most likely, is going to be to update the `CalcJob` plugin in question.

**Comment by ltalirz** [comment]
Sorry, what I meant is to only cache calculations for which `.is_finished_ok` is true.
I understand now that plugins can override AiiDA's default behavior of what this means.

**Comment by ltalirz** [comment]
After discussing, we came to the following conclusion:

 1. Parsers should set `.is_valid_cache=False` on "broken" calculations that are not useful for follow-up calculations. When users encounter a plugin that does not do this, they should open an issue on the plugin's issue tracker.
 2. To resolve the problem at hand (e.g. for exit code `300`), users can mark the corresponding nodes as invalid cache:
```python
from aiida.orm import QueryBuilder, CalcJobNode

nodes=QueryBuilder().append(CalcJobNode, filters={'attributes.exit_status':300}).all(flat=True)
for node in nodes:
  node.base.caching.is_valid_cache = False
```

To improve the user experience, it may still make sense to expose the ability to set the `invalid_cache` property on calcjobs via the command line interface, e.g. under `verdi process` or `verdi devel`.
This would then allow to do something like
```bash
verdi process list -a -E 300 -r -P pk | verdi process invalidate-cache
```

**Comment by ltalirz** [comment]
Thanks for the clarification; I should have read your earlier code example ;-)
