### ISSUE TITLE
UnicodeDecodeError for CifData with \xb7 characters

### ISSUE THREAD

**Issue by eimrek** [aiidateam/aiida-core#5581]
### Describe the bug / steps to reproduce

I have a CifData node that contains a "·" ("\cdot") character with (i believe) an ANSI encoding, which makes decoding via utf-8 except.

Here's the file: 
[27906.cif.txt](https://github.com/aiidateam/aiida-core/files/8943298/27906.cif.txt)

Here's the exception:
![image](https://user-images.githubusercontent.com/8721264/174669704-6aaac66f-fff4-45ab-aebc-7d20f55d5ced.png)

### Expected behavior

Unrecognized characters could be ignored or perhaps replaced by something like �

### Your environment

- Operating system: Ubuntu
- Python version: 3.9.13
- aiida-core version: 2.0.1

**Comment by ltalirz** [comment]
I guess with "ANSI" you mean Windows-1252?

I wonder whether silently replacing unrecognized characters is really better than alerting the user to their presence.

Perhaps the "fix" to this bug should simply be that AiiDA expects text files to be encoded in UTF-8 (and writes text files in this format)?

**Comment by ltalirz** [comment]
I see... yes, AiiDA did not enforce the utf8 encoding for a while, which meant that text files in your repository could be encoded with the default encoding of the machine where it was created (information which is not stored in an AiiDA archive).

I understand there needs to be a workaround for use cases like yours.
Could you perhaps experiment a bit, e.g. by passing `errors='ignore' to `decode` in the last line, and make the error go away?

If it's straightforward, one could even think about a verdi config setting to enable this behavior (but that would need to be discussed with @sphuber as well).

**Comment by eimrek** [comment]
Ok, I was wrong. Exactly the same problem exists with aiida 1.6.5 (also when trying to create the node from the file). So probably the node originated from a much older version.

Ok, in principle, we can consider this issue "solved" for the current aiida version as these types of files are not supported any more and new nodes (since a long while, i guess) don't have this issue.

For these rare cases where the database still contains files like I found, perhaps there could be just a hacky script that converts all of these non-utf-8 symbols. Would it be easy to make a script like this?

**Comment by ltalirz** [comment]
Yes, the archive is likely from an older version. Of course, AiiDA should be able to handle it nevertheless.

> For these rare cases where the database still contains files like I found, perhaps there could be just a hacky script that converts all of these non-utf-8 symbols. Would it be easy to make a script like this?

I guess it's not difficult.

At the same time, if someone else runs into this, they may want to try replacing
https://github.com/aiidateam/aiida-core/blob/25265ef655d0b0e928767bd4e01de6161d3dceca/aiida/orm/nodes/repository.py#L185
with
```
yield io.StringIO(handle.read().decode('utf-8', errors='ignore'))
```
and move on from there
