### ISSUE TITLE
backport rabbitmq warning to 1.6.x

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5588]
### Is your feature request related to a problem? Please describe
https://github.com/aiidateam/aiida-core/issues/5105 affects all versions of AiiDA.

We should backport it at least to 1.6.x

**Comment by sphuber** [comment]
That was added in `v1.6.8`, see the commits: https://github.com/aiidateam/aiida-core/commits/support/1.6.x
This is the backported commit: https://github.com/aiidateam/aiida-core/commit/ccbcf74d45363fae08b5a47c128076dd88e267fd
Or is this not what you meant?

**Comment by ltalirz** [comment]
Sorry, I had to make a note of this very quickly and didn't have time to check whether we actually backported it already (was going to check today). You are completely correct.
