### ISSUE TITLE
Testing framework for workflows

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#5590]
## Description

For plugins that consist of many new workflows and work chains, it is hard to create unit tests during development but have to create profiles and actually run the workflows. 
The GitHub CI test has to be configured to run the daemon in the background and run the workflow as a whole to check the outputs. 
There are efforts to tackle this with caching and pre-installed/config code, e.g [aiida-testing](https://github.com/aiidateam/aiida-testing). But it is not easy to use and still test workflow in a whole test case.  
The idea is to have a test framework based on `pytest` that can easily create mock tests for specific steps of a workflow.

As mentioned in the offline meeting, this can all be tackled by using the new portable profile. The use cases from @unkcpz side are:
-  At the moment, in the GitHub CI test action of aiida-sssp-workflow, I have to create test similar to [nightly test](https://github.com/aiidateam/aiida-core/blob/main/.github/workflows/nightly.yml) of aiida-core which install aiida-core with rabbitmq and PostgreSQL properly configured and computer/code nodes setup. Moreover, after running the workflow, it is not clear how to write unit test for things needs to check, have to check the whole workflow output in an `assert` statement. What I want is to have a way to write tests for steps of the workflow, so I know which specific step went wrong and need to check in detail.
- Not only I want to run the CI test on GitHub action, during workflow development, I want to run some test workflow quickly without the necessity to create a profile and computer/codes every time and create new nodes in the database. 

## Next action

Maybe, the requirement is already can be solved by using the portable profile (already implemented by  Chris) to quickly set up and run the test for workflows. But the documentation needs to add.

**Comment by sphuber** [comment]
Just to mention that I have been working on the daemon part of this recently for `aiida-shell`. I came up with a working solution that allows you to submit a process to the daemon and easily check the result in a simple unit test.

It essentially looks like this:
```python
def test_daemon(generate_code, submit_and_wait):
    """Test submitting a ``ShellJob`` to the daemon."""
    code = generate_code('echo')
    node = submit_and_wait(ShellJob, code=code, arguments=['testing'])
    assert node.outputs.stdout.get_content().strip() == 'testing'
```
So you just add the `submit_and_wait` fixture and use that instead of `submit` itself. It will automatically check and wait for the process to complete. It also makes sure the daemon is started if it hasn't already. The fixture is session scoped and will automatically shut down the daemon at the end of the session.

I haven't merged it yet, but you can check the implementation of the fixtures in this branch: https://github.com/sphuber/aiida-shell/tree/fix/daemon-tests

**Comment by unkcpz** [comment]
@sphuber thanks a lot! That is what I am looking for, I can try to use it to replace the tests for `aiida-sssp-workflow`. I assume this fixture will finally also merge to `aiida-core` correct?

**Comment by sphuber** [comment]
> I assume this fixture will finally also merge to aiida-core correct?

I mean if it works properly and is useful to other packages, sure, would make sense to then add it to `aiida-core`.

**Comment by unkcpz** [comment]
The pytest fixtures are now able to be use in aiida-core, introduced by PR https://github.com/aiidateam/aiida-core/pull/5701
The documentation can be found at: https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/plugins_develop.html?highlight=pytest%20fixture#aiida-s-fixtures
