### ISSUE TITLE
Uploading POTCAR FILE

### ISSUE THREAD

**Issue by Feugmo** [aiidateam/aiida-core#5595]
- [x] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [x] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug

aiida ais not uploading the potcar file so I am not able to run any calculation 

2022-07-08 17:04:40 [255 | REPORT]: [1708|VerifyWorkChain|verify_next_workchain]: The called WorkChainNode<1709> returned a non-zero exit status. The exit status ExitCode(status=702, message='No POTCAR found for full name Si in family pbe', invalidates_cache=False) is inherited

### Steps to reproduce

1)  go the potential folder 
2)  verdi data vasp-potcar uploadfamily -n "PBE_54" -D "PBE potentials for version 5.4.4" -v debug
### Expected behavior
POTCAR files found: 327. New files uploaded: 327, Added to Family: 327
## What happened instead
.
.
.
Debug: PotcarData node 56e9ee75-25ad-4682-aab8-438e4d877b1b used instead of uploading file S_h/POTCAR to family PBE_54

POTCAR files found: 327. New files uploaded: 0, Added to Family: 327
### Your environment

verdi  data vasp-potcar listfamilies
## What happened instead
No POTCAR family available.
- Operating system [e.g. Linux]: Ubuntu 20.4 lts
- Python version [e.g. 3.7.1]: 3.python 3.9.7
- aiida-core version [e.g. 1.2.1]: v2.0.1

Other relevant software versions, e.g. Postres & RabbitMQ

 Postres 12.11
RabbitMQ v3.8.2

**Comment by sphuber** [comment]
This is a problem specific to the `aiida-vasp` plugin and so should probably be moved there. @espenfl @zhubonan this was also already reported on the mailing list. Seems to appear after an upgrade to `aiida-core` 2.0. Have you seen this before and an idea what it might relate too? Could it have to do with the changed entry points, having the `core.` prefix in 2.0 and the code still uses the old ones so seems to not find the families or pseudos?

**Comment by zhubonan** [comment]
> This is a problem specific to the `aiida-vasp` plugin and so should probably be moved there. @espenfl @zhubonan this was also already reported on the mailing list. Seems to appear after an upgrade to `aiida-core` 2.0. Have you seen this before and an idea what it might relate too? Could it have to do with the changed entry points, having the `core.` prefix in 2.0 and the code still uses the old ones so seems to not find the families or pseudos?

It has been resolved. I think the problem was likely that the plugin was not reinstalled properly after upgrading the aiida-core installation (may be just updating the plugin repository previously install with pip -e), which resulting in missing entrypoints etc. Although I am not 100% sure.
