### ISSUE TITLE
Control the number of jobs in a workchain

### ISSUE THREAD

**Issue by proexcuse** [aiidateam/aiida-core#5596]
Hi,
I'm a beginner of aiida, and want to know if you can control the number of jobs (or cores) submitted by one workchain. I use PBS scheduler. 

In writing my own aiida plugin, I have a step in workchain outline where multiple jobs are submitted in parallel by using for-loop and to_context. The total number of jobs can amount to ~1000, and I want to set the maximum number of jobs executed at the same time to be 100 or fewer. 

Is there a way to realize this? If not, I request this feature of workchain to control the number of submitted jobs.

**Comment by danielhollas** [comment]
If you're using a scheduler, why would you need to limit the nber of submitted jobs? 1000 is a bit large but maybe still manageable?

To answer you question, I don't know of a way to do this, perhaps a more knowledgeable person can chime in. But you should be able to rewrite your workflow in a way that it submits only 100 jobs, e.g. using a `while_` loop.

**Comment by proexcuse** [comment]
I see. Thanks.
