### ISSUE TITLE
Stashing does not accept wildcards.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-core#5600]
- [x] [AiiDA Troubleshooting Documentation](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html)
- [x] [AiiDA Users Forum](https://groups.google.com/forum/#!forum/aiidausers)

### Describe the bug

As an AiiDA plugin user, I would like to have the flexibility to provide wildcards for stashing. However, currently it is not possible.

This is the error I've got after the job was terminated:

```python
07/14/2022 03:12:25 PM <27885> aiida.execmanager: [WARNING] failed to stash /scratch/snx3000/yaa/aiida/42/f2/047b-69a6-42f3-96d2-5a6f2717807f/grid_time_*.nc to /users/yaa/aiida_stash/42/f2/047b-69a6-42f3-96d2-5a6f2717807f/grid_time_*.nc: Pathname patterns are not allowed in the destination
``` 

### Steps to reproduce

Add a similar section to the submission script:
```python
    builder.metadata.options.stash = {
        'source_list': ['aiida.out', '_scheduler-stderr.txt', 'grid_time_*.nc',  '_scheduler-stdout.txt'],
        'target_base': '/users/yaa/aiida_stash',
        'stash_mode': StashMode.COPY.value,
    }
```

### Expected behaviour

Wildcards should be acceptable in the` source_list`.

### Your environment

- Operating system [e.g. Linux]: Ubuntu 18.04
- Python version [e.g. 3.7.1]: 3.7.9
- aiida-core version [e.g. 1.2.1]: 1.6.5

**Comment by sphuber** [comment]
Are you sure that your "steps to reproduce" example is accurate, because it doesn't include any strings with wildcards. Looking through the code though I think you may be right that it currently doesn't support it. Will have a look at implementing it.

**Comment by yakutovicha** [comment]
> Are you sure that your "steps to reproduce" example is accurate, because it doesn't include any strings with wildcards.

Yep, the example didn't contain wildcards. I just updated it. Thanks!
