### ISSUE TITLE
Support for storing metadata about units in ArrayData

### ISSUE THREAD

**Issue by ahkole** [aiidateam/aiida-core#5622]
### Is your feature request related to a problem? Please describe

After returning to a project that has been on hold for a while, I have sometimes forgotten what the units for a particular quantity stored in an array are. It can take up a lot of unnecessary time searching through simulation code documentation figuring out what the units were.

### Describe the solution you'd like

It would be very useful for me to be able to store metadata about the units of the quantity in an array in an `ArrayData` node. This is already possible with an `XyData` node, but these nodes expect a relationship between the arrays stored in it, which is not always the case. On top of that, an `XyData` node can only store arrays that have the exact same shape.

### Describe alternatives you've considered

Abusing the `XyData` node by storing each array in its separate node. This is clearly suboptimal because it creates a lot of unnecessary nodes and prevents you from neatly organising arrays that belong together (but are not necessarily related through an x-y relationship) in a single Data node.

**Comment by chrisjsewell** [comment]
Heya, at present I guess you could always store these in the node's extras yourself.

On a longer term note, storing units will actually be available directly in numpy at some point: https://numpy.org/neps/nep-0042-new-dtypes.html

**Comment by ahkole** [comment]
Hi, thanks for your quick reply!

> On a longer term note, storing units will actually be available directly in numpy at some point: https://numpy.org/neps/nep-0042-new-dtypes.html

Ah okay, I didn't know that. Good to know! I guess that would make this feature obsolete.

> Heya, at present I guess you could always store these in the node's extras yourself.

This sounds like a satisfactory solution for now. Could I also ask what the current appropriate interface is for interacting with a node's extras? In the documentation (https://aiida.readthedocs.io/projects/aiida-core/en/latest/reference/apidoc/aiida.orm.nodes.html#aiida.orm.nodes.node.Node._deprecated_extra_methods) I see that a lot of the extras functions are marked as deprecated but I cannot find any replacement functions. I did find this https://aiida.readthedocs.io/projects/aiida-core/en/latest/reference/apidoc/aiida.orm.nodes.html#aiida.orm.nodes.node.NodeBase.extras but accessing that property for a (stored) output node seems to return a regular Python dict, not an `EntityExtras` (unless you access it through `node.base.extras`).

**Comment by sphuber** [comment]
Indeed, wherever you used to do `Node.get_extra` or `Node.set_extra`, those should now be `Node.base.extras.get` and `Node.base.extras.set` etc.

**Comment by ahkole** [comment]
Okay thanks! Then as far as I'm concerned this issue is resolved.
