### ISSUE TITLE
Some deprecation warnings are difficult to locate

### ISSUE THREAD

**Issue by ramirezfranciscof** [aiidateam/aiida-core#5633]
When updating the `aiida-quantumespresso` package ([reference](https://github.com/aiidateam/aiida-quantumespresso/pull/836)) I came across a couple of warnings that were not showing the call to the deprecated method in the stack trace. Instead, they pointed to the place were the warning was being raised inside of the aiida-core code. I didn't go much into the detail of each problem (in some of them, like case 1, I was hard to even figure out how the test where the warning was detected was calling the fixture in which the offending method was being invoked), but I think it would be good at some point to figure out why this was the behavior and if it is possible to correct it.

## Case 1

``` console
  /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/aiida/manage/tests/main.py:125: AiidaDeprecationWarning: reset_db() is deprecated, use clear_profile() instead (this will be removed in v3)
    warn_deprecation('reset_db() is deprecated, use clear_profile() instead', version=3)
```

This was being triggered in a test that had no calls to `reset_db` whatsoever (`tests/calculations/test_autoinvalidate_cache.py::test_exit_code_invalidates_cache[quantumespresso.cp]`). The actual problem was in one fixture in `tests/conftest.py` that was also not directly used in that test (it must have been loaded in some call of a call or something like that).

## Case 2

``` console
  /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/aiida/plugins/entry_point.py:307: AiidaDeprecationWarning: The entry point `array.kpoints` is deprecated. Please replace it with `core.array.kpoints`. (this will be removed in v3)
    warn_deprecation(
```

For this one, a possible reason it might not have triggered correctly is that the execution of `KpointsData = DataFactory('array.kpoints')` was set as a global variable instead of being called inside a method, so I guess it runs on import of the module. Still, I'm not sure why this would imply that the stack trace can't show the location.

## Case 3

``` console
  /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/aiida/orm/entities.py:174: AiidaDeprecationWarning: This property is deprecated, use `.collection` instead. (this will be removed in v3)
    warn_deprecation('This property is deprecated, use `.collection` instead.', version=3, stacklevel=2)
```

This problem was all over. I think at least in this case the tests that were listed before the error message were the actual places where the deprecated calls were located, but still it didn't explicitly show the lines. Moreover, perhaps it would be nice to improve this error message to explicitly mention the name of the method that is producing the problem (`The 'objects' property is deprecated' instead of `This property is deprecated`).

## Case 4

``` console
  /opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/aiida/orm/utils/managers.py:101: AiidaDeprecationWarning: dereferencing nodes with links containing double underscores is deprecated, simply replace the double underscores with a single dot instead. For example: 
  `self.inputs.some__label` can be written as `self.inputs.some.label` instead.
   (this will be removed in v3)
    warn_deprecation(
```

Again, no idea why this one is not showing up (the offending command `pw_input_dict = self.node.inputs.pw__parameters.get_dict()` was inside a method of the parser). One thing that could improve the error message here is also including the offending label in it.

**Comment by sphuber** [comment]
The first one is pretty much impossible to solve thanks to how `pytest` works and how it magically loads fixtures. I don't think there is much we can do here.

Case 2 is also problematic. The function that emits the warning can be called from different places. Not just the `*Factory` classes but also directlky through `get_entry_point`. As a result, we cannot know in advance what the "right" stack level is going to be. We could set it to match the factory, betting that those cases are going to be the majority case, however, if a user then calls `get_entry_point` directly, they will get a very cryptic message most likely, since it went too far up the stack. So I think this one also cannot be fixed.

I have added fix for case 4 to the PR #5774 which already contained a fix for case 3 and will be closing this issue with that PR.
