### ISSUE TITLE
Tests randomly fail due to `sqlalchemy` raising an `OperationalError` claiming too many clients being active

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5640]
This has been going on for a while and I have seen multiple occurrences, even in changesets that do not touch any code having to do with the ORM or the database whatsoever.

Example run here: https://github.com/aiidateam/aiida-core/actions/runs/3044999156/jobs/4907218906
The relevant exception is
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: FATAL:  sorry, too many clients already
```
Essentially, when trying to connect to the database somewhere during the test suite, it is refused by `sqlalchemy` claiming that too many clients are already open. Not sure what constitutes a client, whether this is a "connection" to the database, or something else, but there might be a leak somewhere and something is not properly cleaned up.

**Comment by sphuber** [comment]
@chrisjsewell any ideas?

**Comment by sphuber** [comment]
Is each individual test that uses the `aiida_profile` function opening and closing a connection? If so, should it? As long as the next use of `aiida_profile` uses the same backend, why should it have to reopen the connection, can't it reuse the one if it was already opened?

**Comment by chrisjsewell** [comment]
Note that each psql_dos storage instance is responsible for a single `sqlalchemy.Session`.
Sqlalchemy keeps a weak references of all sessions in `sqlalchemy.orm.session._sessions`, which you could use to check what sessions are open: https://github.com/sqlalchemy/sqlalchemy/blob/ac9a74ac0d60f5e95d9dbbce7f804f532bef2bea/lib/sqlalchemy/orm/session.py#L54

**Comment by chrisjsewell** [comment]
> Is each individual test that uses the aiida_profile function opening and closing a connection?

well its every time you call `aiida_profile.clear_profile()`, which in-turn calls `reset_profile` : https://github.com/aiidateam/aiida-core/blob/a8b3da36a0c3d7007519bb563774d38f2ce6b2e2/aiida/manage/tests/main.py#L165

You are welcome to try changing it 😅
