### ISSUE TITLE
`verdi setup`: add option to set the profile UUID

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5670]
Each profile has a UUID which is automatically generated that is used to create unique channels and queues on RabbitMQ. This way there is no cross-talk between multiple active profiles. However, in certain use cases one may actually want to configure a profile to access a certain queue on RabbitMQ. For example when configuring multiple AiiDA instances that each talk to the same resources (storage and message broker). In this case it is necessary to set the profile UUID to the same value but currently there is no API for this.

It would be good if this value can be set through `verdi setup`. The option should not prompt but only be settable through the a yaml config file in combination with the `--config` option, or through a non-interactive option. Most normal users using the interactive mode do not care about the profile UUID and so it should not even prompt.

**Comment by ltalirz** [comment]
>  For example when configuring multiple AiiDA instances that each talk to the same resources (storage and message broker). In this case it is necessary to set the profile UUID to the same value but currently there is no API for this.

I agree it is semantically correct to give those profiles the same UUID (fully support the feature); just wondering: what makes it _necessary_ here?

**Comment by sphuber** [comment]
The necessity is that the profile UUID is used to create the various queues and channels with RabbitMQ, so in order to connect to the same queues, profiles need to have the same UUIDs. In hindsight, it might be better to maybe have a separate UUID for the broker that can be configured separately. But for now I don't really see a disadvantage to this approach since the UUID is not used for anything else and will still be unique per AiiDA instance, since in this use-case, the duplicate profiles will always be in separate AiiDA instances.

**Comment by ltalirz** [comment]
Thanks for the clarification.

> In hindsight, it might be better to maybe have a separate UUID for the broker that can be configured separately.

We can cross that bridge when we come to it
