### ISSUE TITLE
add_multiply and multiply_add workflows

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#5684]
We still have both in the code, they are slightly different (one uses calcfunctions, the other a workflow with calcjobs and calcfunctions inside). Is this the main difference between the two? Where are these used (tutorials, test, ...)? Maybe it's a bit confusing to have very similar ones with different implementation, just swapping the names... We should probably replace one of the two with a slightly different task to avoid confusion?

@mbercx @sphuber @chrisjsewell @ramirezfranciscof

**Comment by sphuber** [comment]
These are used in the documentation to explain how to run workflows (https://aiida.readthedocs.io/projects/aiida-core/en/latest/howto/run_workflows.html). We registered them with entry points so they can be properly tested. I think the naming is not a problem if you follow the docs, which is where you would read about them anyway.

I assume you saw them listed in the output of `verdi plugin list aiida.workflows`? We could think of removing them if you think it is confusing, but we would have to add them dynamically for the tests and maybe even the docs (if parts are actually evaluated in the tests). I don't think this is worth the hassle. We have other plugins that are essentially for testing/demonstration purposes such as the `aiida.calculations:core.arithmetic.add` one.

If you disagree, feel free to reopen and suggest what you think should be fixed.
