### ISSUE TITLE
Allow to change the filename for `verdi node graph generate`

### ISSUE THREAD

**Issue by giovannipizzi** [aiidateam/aiida-core#5692]
Currently, `verdi graph node generate` will select the filename based on the node PK. This is hardcoded and cannot be changed:

https://github.com/aiidateam/aiida-core/blob/1c5dfef09d18895ce327b4b145466373f9f05118/aiida/cmdline/commands/cmd_node.py#L461

During the tutorial, the use case emerged to allow this to be changed. I suggest to add another command line option, optional - keeping the current behaviour if not specified - that however allows to change the base name of the file if the user wants.

**Comment by hemantsoni42** [comment]
@giovannipizzi if this issue is still open can you please assign this to me.
I have an idea about implementation of this by adding a new command line option.

**Comment by jeromtom** [comment]
> Currently, `verdi graph node generate` will select the filename based on the node PK. This is hardcoded and cannot be changed:

@giovannipizzi Hope you meant `verdi node graph generate`. I have understood the need for the feature and am working on it.

**Comment by jeromtom** [comment]
Will changing the above line (461) to the snippet below work? Do you have any corrections/suggestions?
```python

echo.echo_info('Output filename is by default based on the node PK. Would you like to change it?(Y/N)')
    if input()== 'Y':
        echo.echo_info('Enter the desired filename')
        filename=input()
        output_file_name = graph.graphviz.render(
        filename, format=output_format, view=show, cleanup=True
    )
    elif input()== 'N':
        output_file_name = graph.graphviz.render(
        filename=f'{root_node.pk}.{engine}', format=output_format, view=show, cleanup=True
    )

    echo.echo_success(f'Output file: {output_file_name}')

```

**Comment by AhmedBasem20** [comment]
Hi @giovannipizzi, I reached a solution to this issue as follows:
- adding click option basename with default value None
- passing this basename to the `graph_generate` function
- inside that function, setting the basename to node PK if it is None

I'm also working on testing those changes.
I think this line should be replaced with the new basename variable.
https://github.com/aiidateam/aiida-core/blob/43261d11e148a6e95a657232b737cff0f5c5262a/tests/cmdline/commands/test_node.py#L286


What do you think? Am I on the right track? I'm waiting for your feedback.
