### ISSUE TITLE
verdi setup and database migration failure

### ISSUE THREAD

**Issue by vdemestral** [aiidateam/aiida-core#5755]
### Describe the bug

I intentionally installed a previous version of AiiDA (v1.6.5) and have postgreSQL and Rabbitmq already installed on a Centos machine. I created a database and am now trying to setup a profile. I get 2 contradictory messages:
1. Success: created new profile 'name'
2. Critical: database migration failed, probably because connection details are incorrect:
    syntax error at or near "WITH ORDINALITY"
    LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
    

As a double-check, when I type `verdi status`, I get:
> (aiida) verdi status
    ✔ config dir:  /home/vdemestral/.aiida
    ⏺ profile:     no profile configured yet
   Info: Configure a profile by running `verdi quicksetup` or `verdi setup`.

Conclusion: no profile was created

### Steps to reproduce

1. $(aiida) verdi setup
2. fill in the profile name, email address, ...
3. error message obtained:
>Success: created new profile `vdemestral`.
Info: migrating the database.
Operations to perform:
  Apply all migrations: auth, contenttypes, db
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying db.0001_initial... OK
  Applying db.0002_db_state_change... OK
Critical: database migration failed, probably because connection details are incorrect:
syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
                                                  ^
Applying db.0003_add_link_type...(aiida) 

### Expected behavior

Setup an AiiDA configuration profile

### Your environment

- Operating system [e.g. Linux]: CentOS Linux 7
- Python version [e.g. 3.7.1]: 3.9.13
- aiida-core version [e.g. 1.2.1]: 1.6.5

Other relevant software versions, e.g. Postres: 9.2.24 & RabbitMQ

### Additional context

It seems that the problem is inherent to the verdi running procedure, and is associated to the CRITICAL step in the running migration protocol. Does anyone know what this syntax error at or near "WITH ORDINALITY" could come from?

Many thanks

**Comment by sphuber** [comment]
Thanks for the report @vdemestral . This error comes from Postgres. You have a very old version 9.2.24 installed that is not supported. It has been [end-of-life since 2018](https://www.postgresql.org/support/versioning/). Please use Postgres 11 or newer.

**Comment by vdemestral** [comment]
Thank you for having spotted that so quickly!
