### ISSUE TITLE
verdi code test failing

### ISSUE THREAD

**Issue by degennar** [aiidateam/aiida-core#5795]
I just setup a remote machine (called `marvel`), which passes all the tests without errors:
```
(aiida) degennar@theospc39:~/.aiida$ verdi computer test marvel
Report: Testing computer<marvel> for user<riccardo.degennaro@epfl.ch>...
* Opening connection... [OK]
* Checking for spurious output... [OK]
* Getting number of jobs from scheduler... [OK]: 13 jobs found in the queue
* Determining remote user name... [OK]: degennar
* Creating and deleting temporary file... [OK]
Success: all 5 tests succeeded
```

On that computer I installed `pw`, which actually runs properly. However when I run the command `verdi code test pw@marvel`, I get the following error message:
```
Critical: validation failed: Could not connect to the configured computer to determine whether the specified executable exists.
```

I am using `Aiida 2.1.2`.

**Comment by ltalirz** [comment]
Thanks for the report - that is indeed unexpected.

This feature was added recently by @sphuber in https://github.com/aiidateam/aiida-core/pull/5184 - perhaps he has an idea?

**Comment by sphuber** [comment]
This is indeed a bug, for which I have already opened a PR #5787 . It first requires #5786 to be reviewed and merged first. They are simply waiting for a reviewer to have a look at them.
