### ISSUE TITLE
Process excepts when daemon is restarted in v2.1.2

### ISSUE THREAD

**Issue by PhilippRue** [aiidateam/aiida-core#5803]
### Describe the bug

A calculation that runs a remote code on a computer ends up in the `excepted` state if the daemon is restarted (`verdi daemon restart`)

```
$ verdi process list -a -p1
 194  1m ago     VoronoiCalculation  ⨯ Excepted       Transport task update was cancelled

$ verdi process report
*** 194: None
*** Scheduler output: N/A
*** Scheduler errors: N/A
*** 1 LOG MESSAGES:
+-> REPORT at 2022-11-28 16:06:45.288051+00:00
 | [194|VoronoiCalculation|on_except]: Traceback (most recent call last):
 |   File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/processes.py", line 1193, in step
 |     next_state = await self._run_task(self._state.execute)
 |   File "/opt/aiida-kernel/lib/python3.8/site-packages/plumpy/processes.py", line 559, in _run_task
 |     result = await coro(*args, **kwargs)
 |   File "/opt/aiida-core/aiida/engine/processes/calcjobs/tasks.py", line 482, in execute
 |     process_status = f'Waiting for transport task: {self._command}'
 | AttributeError: 'Waiting' object has no attribute '_command'
```

### Steps to reproduce

1. Submit a calculation (tried calculations from `aiida-kkr`)
```
from aiida_kkr.tools import kkrparams
from aiida_kkr.calculations import VoronoiCalculation

s = orm.StructureData(cell=[[1,0,0], [0,1,0], [0,0,1]])
s.append_atom(position=[0,0,0], symbols='X')

builder = VoronoiCalculation.get_builder()
builder.metadata.options = {
    'withmpi': False,
    'resources': {'num_machines': 1, 'tot_num_mpiprocs': 1},
    'max_wallclock_seconds': 60*10,
    'custom_scheduler_commands': f'sleep {60*10}', # here I just make sure I am waiting long enough to restart the daemon
    'queue_name': 'oscar'
}
builder.code = orm.Code.get_from_string('voronoi_3.5_intel@iffslurm')
builder.parameters = orm.Dict(kkrparams(LMAX=2, NSPIN=1, RCLUSTZ=2))
builder.structure = s

test = engine.submit(builder)
```
2. restart the daemon `verdi daemon restart`
3. then the `excepted` behaviour appears

### Expected behavior

The daemon should pick up the process where it left it and simply check if it is completed in the meantime.

### Your environment

- Operating system [e.g. Linux]: Ubuntu 20.04.4 LTS
- Python version [e.g. 3.7.1]: 3.8.10
- aiida-core version [e.g. 1.2.1]: 2.1.2

Other relevant software versions, e.g. Postres & RabbitMQ

```
$ verdi status
 ✔ version:     AiiDA v2.1.2
 ✔ config:      /home/ruess/.aiida
 ✔ profile:     default
 ✔ storage:     Storage for 'default' [open] @ postgresql://aiida_qs_ruess_bdfd5a648f2694cd94fe245ca0e1fdce:***@localhost:5432/default_ruess_bdfd5a648f2694cd94fe245ca0e1fdce / DiskObjectStoreRepository: 674e260c3db54a16a0e4ec1a2320e3ef | /Local/aiida_v2/aiida/repository/default/container
 ✔ rabbitmq:    Connected to RabbitMQ v3.8.2 as amqp://guest:guest@127.0.0.1:5672?heartbeat=600
 ✔ daemon:      Daemon is running as PID 19790 since 2022-11-28 16:03:48
```

### Additional context

Downgrading to `aiida-core v2.1.1` fixes the problem.

**Comment by sphuber** [comment]
Indeed, is it possible that you had a released version installed, launched the calculation, then (accidentally) installed AiiDA from the `main` branch and restarted the daemon. That would explain the bug because as @chrisjsewell says the code that refers to the exception you see is currently only in the `main` branch.

**Comment by PhilippRue** [comment]
Yes you are right, I have an editable installation and recently pulled the newest version. If I go to commit f9368db0d  for the release of `v2.1.2` the problem is not there.

**Comment by sphuber** [comment]
Ok, thanks for confirming. Then I will close this, since this considered switching to non-released development code
