### ISSUE TITLE
`delete_stale_pid_file` incorrectly assumes the daemon process died because the process name does not match

### ISSUE THREAD

**Issue by sphuber** [aiidateam/aiida-core#5825]
This was discovered on the machine of a user that installed AiiDA v2.0.4 using Conda on an Ubuntu machine. The daemon could be started with success, but as soon as `verdi daemon status` was run it would say that it detected a stale PID file and conclude the daemon was not running. However, in reality the daemon _was_ running. The problem is however that the circus daemon process was launched with the process name `circusd`, whereas the `aiida.cmdline.utils.delete_state_pid_file` utility uses `psutil` to check the name and expects `start-circus`. Since the process names do not match, it concludes that the original process must have died and the PID recycled by some other process.

It is unclear why the circus process on this machine gets the name `circusd` instead of `start-circus` and so why we get this false positive. The installed circus version was `0.17.2` which seems normal.

**Comment by ltalirz** [comment]
likely duplicate of https://github.com/aiidateam/aiida-core/issues/5336

**Comment by sphuber** [comment]
Yep, this is a duplicate, thanks
