### ISSUE TITLE
test-install workflow broken

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5857]
See e.g. https://github.com/aiidateam/aiida-core/actions/runs/3762763338/jobs/6395771660

Only two errors of the test suite fail
```
FAILED tests/orm/test_querybuilder.py::TestRepresentations::test_as_sql_literal_quote - sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "['Si']" with datatype JSONB
FAILED tests/orm/test_querybuilder.py::test_analyze_query - sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "['x', 1]" with datatype JSONB
```

Given that the only difference to the testing on `main` should be the dependencies that are installed, I suspect one of the packages is responsible - e.g. on python 3.8 this installs `SQLAlchemy-1.4.45-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl` while we're pinning at SQLAlchemy==1.4.27

I don't know what is causing this, though - if someone could have a look that would be great 

@sphuber @aiidateam/dependency-manager

**Comment by sphuber** [comment]
Looks likely indeed that that is the culprit. The [first failure](https://github.com/aiidateam/aiida-core/actions/runs/3667101809) ran on December 11th and [`sqlalchemy==1.4.45`](https://pypi.org/project/SQLAlchemy/1.4.45/) was released on December 10.

**Comment by ltalirz** [comment]
Looking a bit into it, the two values pointed out by sqla are indeed not valid json.

The question is: do they need to be valid JSON (and the test is wrong), or is the generated query wrongly assuming they need to be valid JSON?

Taking `tests/orm/test_querybuilder.py::TestRepresentations::test_as_sql_literal_quote`

Query generated with sqlalchemy 1.4.42
```
 p qb.as_sql(inline=True)
'SELECT db_dbnode_1.uuid 
FROM db_dbnode AS db_dbnode_1 
WHERE CAST(db_dbnode_1.node_type AS VARCHAR) LIKE \'data.core.structure.%%\' AND CAST((db_dbnode_1.extras #> \'{elements}\') AS JSONB) @> \'["Si"]\'
'
```
Instead, on sqlalchemy 1.4.46 I get
```
p qb.as_sql(inline=True)
*** sqlalchemy.exc.CompileError: No literal value renderer is available for literal value "['Si']" with datatype JSONB
```

Looking at [example uses of the `@>` containment operator from the postgres docs](https://www.postgresql.org/docs/15/datatype-json.html#JSON-CONTAINMENT), it appears that lists, strings, etc. are valid operands, but in the examples the literals all include an explicit `::jsonb` suffix, i.e. an explicit cast to the jsonb type.

In the SQL query above, the left operand `CAST((db_dbnode_1.extras #> \'{elements}\') AS JSONB)` has the cast as well but the right operand `\'["Si"]\'` is missing the cast.

This looks like an implementation error on our side.

**Comment by ltalirz** [comment]
Ok, turns out that sqlalchemy simply started throwing a different type of error in 1.4.45. Will fix
