### ISSUE TITLE
drop requirement for Code executable paths to be absolute

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5867]
### Is your feature request related to a problem? Please describe

At the moment, when setting up a `Code` in AiiDA, the user needs to provide the absolute path to the executable (rather than, say, just the name of the executable, assuming it is in the `PATH`). 

While recording the absolute path of the executable in the code _does_ provide additional provenance information, it has downsides in terms of usability.

In my use cases, this often leads to duplication of information, since in addition to a `module load quantum-espresso/...` in the `prepend_text`, I also need to provide the absolute path to the executable. This path can change, for example, depending on where the corresponding directory is mounted. 

Furthermore, requiring the absolute path makes it impossible to rely on auto-detection of, say, the microarchitecture at the `module load` level - e.g. by pointing the module path to different locations depending on the microarchitecture of the machine, so that `module load quantum-espresso/7.1` will  automatically load different modules on an AMD zen3 node than on an Intel skylake node.
In practice, this means not only the AiiDA administrator (who manages, say, the [code registry](https://github.com/aiidateam/aiida-code-registry)), but also the AiiDA user is forced to know about (& select) the right code depending on the machine architecture. If the requirement was dropped, it would be possible to use the same code definition across microarchitectures.

### Describe the solution you'd like

Users should be able to decide by themselves whether they want to provide an absolute or a relative path to the executable.

### Additional context

discussion in https://github.com/aiidateam/AEP/pull/37#discussion_r1083537062

@sphuber @chrisjsewell

**Comment by sphuber** [comment]
As already stated in the AEP discussion, I am in favor of implementing this request.
