### ISSUE TITLE
slurm plugin: transport task `submit` should fail when encountering slurm error

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5870]
### Describe the bug

I've specified an invalid partition for a job.

The job remains in 
```
$ verdi process list -a -p1
  PK  Created    Process label    Process State    Process status
----  ---------  ---------------  ---------------  ----------------------------------
2142  7m ago     PwCalculation    ⏵ Waiting        Waiting for transport task: submit

Total results: 1
```

Inspecting the report, however, shows that submission encountered an irrecoverable error:
```
verdi process report 1234
...
 |     return self._parse_submit_output(*result)
 |   File ".../aiida/schedulers/plugins/slurm.py", line 427, in _parse_submit_output
 |     raise SchedulerError(f'Error during submission, retval={retval}\nstdout={stdout}\nstderr={stderr}')
 | aiida.schedulers.scheduler.SchedulerError: Error during submission, retval=1
 | stdout=
 | stderr=sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified
 | 
```

### Steps to reproduce

Submit calcjob to compute resource with slurm scheduler, specifying a wrong partition

### Expected behavior

The calculation should exit with an exit code specified by the slurm scheduler that points out the incorrect partition.

### Your environment

- Operating system [e.g. Linux]:Centos 7
- Python version [e.g. 3.7.1]: 3.9
- aiida-core version [e.g. 1.2.1]: 2.1.2

**Comment by ltalirz** [comment]
mentioning @sphuber for info

**Comment by sphuber** [comment]
I think this should have already been fixed by https://github.com/aiidateam/aiida-core/pull/5850 which hasn't been released yet, but maybe you could try the `main` branch.

**Comment by ltalirz** [comment]
ah damn, I vaguely remembered about this, thanks for pointing it out ;-) 

In that case I'm sure it's fixed.
