### ISSUE TITLE
conda install workflow broken

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5872]
### Describe the bug

The conda-based install test from the nightly run is currently broken.
Problems already start when trying to install `mamba`

https://github.com/aiidateam/aiida-core/blob/main/.github/workflows/test-install.yml#L167

### Steps to reproduce

See https://github.com/aiidateam/aiida-core/actions/runs/4015254159/jobs/6896759488#step:6:1

**Comment by sphuber** [comment]
Fixed by #5873
