### ISSUE TITLE
Docs: 

### ISSUE THREAD

**Issue by ireaml** [aiidateam/aiida-core#5880]
### Describe the current issue

Hi! Just noticed that in the `Troubleshooting` docs page ([RabbitMQ incompatibility section](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/troubleshooting.html#rabbitmq-incompatibility)), the keyword `consumer_timeout` should be in capital letters in the `rabbitmq` configuration file (which may cause an issue when initialising `rabbitmq` if you're not paying attention when modifying the file).

### Describe the solution you'd like

Replace `consumer_timeout`  by `CONSUMER_TIMEOUT` in
```
consumer_timeout = 36000000000 # 10,000 hours in milliseconds
``` 

Thanks!

**Comment by ltalirz** [comment]
Hi @ireaml , thanks for pointing this out!

You are positive that `consumer_timeout` (lowercase) does not work for you? Which rabbitmq version are you running?

Also, just to be sure, you are saying that the official rabbitmq documentation is currently incorrect? https://www.rabbitmq.com/consumers.html#acknowledgement-timeout

**Comment by ireaml** [comment]
I just tested using `consumer_timeout` and seem to work fine now!
Guess I might have changed something else when I modified `consumer_timeout` (and incorrectly thought that was the issue)
Sorry about this!
