### ISSUE TITLE
python 3.11 tests flaky & slow

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#5881]
### Describe the bug

Looking at https://github.com/aiidateam/aiida-core/actions?query=workflow%3Atest-install the python 3.11 tests have failed to complete twice in the last week - once due to timeout and once due to an error.

I also notice a cancellation on a recent commit https://github.com/aiidateam/aiida-core/actions/runs/4072225558/jobs/7014766994

Also when the tests complete fine, as in https://github.com/aiidateam/aiida-core/actions/runs/4068984058/jobs/7008193822 or https://github.com/aiidateam/aiida-core/actions/runs/4056425552/jobs/6980910222, it appears they take consistently a couple of minutes longer than the tests on python 3.8.

Probably worth looking into

**Comment by ltalirz** [comment]
for some reason, the `test-install` workflow for installing with conda on py 311 failed yesterday
https://github.com/aiidateam/aiida-core/actions/runs/4120344080/jobs/7114980642#step:6:15
```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package aiida-core-0.[12](https://github.com/aiidateam/aiida-core/actions/runs/4120344080/jobs/7114980642#step:6:13).2-py27_0 requires python >=2.7,<2.8.0a0, but none of the providers can be installed


Error: Process completed with exit code 1.
```

this is weird, since the exact same workflow succeeded yesterday
https://github.com/aiidateam/aiida-core/actions/runs/4110028234/jobs/7092462000

**Comment by ltalirz** [comment]
Perhaps this was a false alarm. The entire `test-install` workflow run from yesterday is weird
https://github.com/aiidateam/aiida-core/actions/runs/4120344080

on the left, `install-with-conda (3.11, true)` is shown as succeeded, while under "annotations" it is shown as failed.

both link to the same run, though, and that run did indeed fail

**Comment by sphuber** [comment]
I am closing this for now. I haven't seen a failure of the tests on 3.11 on the `main` branch in the last few weeks. Also the timing seems to not be consistently worse compared to 3.8. There is quite a large spread, but for both versions.
