### ISSUE TITLE
Add the support of unary operators (+ and -) for orm.Int and orm.Float

### ISSUE THREAD

**Issue by hujay2019** [aiidateam/aiida-core#5911]
The binary operators between orm.Int, orm.Float, and Python builtin number types are supported, while the unary operators (+ and -) not.
After adding the support of unary operators (+ and -), the expression `-orm.Float(1.5).value` can be simplified to `-orm.Float(1.5)`.

**Comment by sphuber** [comment]
Feel free to open a PR @H9660
