### ISSUE TITLE
`flask.json.JSONEncoder` was removed in `flask==2.3.0`

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#5986]
`flask` removed the `JSONEncoder` class in v2.3.0:

https://flask.palletsprojects.com/en/2.3.x/changes/?highlight=jsondecoder#version-2-3-0

In favor of using `JSONProvider`, see

https://github.com/pallets/flask/pull/4692

An example of how `connexion` updated their code to deal with this deprecation:

https://github.com/spec-first/connexion/pull/1582/files

**Comment by sphuber** [comment]
Fixed in #6011
