### ISSUE TITLE
Docs: Node extras cannot be modified when iterating over QueryBuilder results with `.iterall()`

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-core#6009]
### Describe the current issue

Upon retrieving Nodes from the database with the QueryBuilder, iterating over them and changing the `extras` is not possible using `.iterall()`, but requires `.all()`.

This might lead to confusion, as the `.set_extra()` method seems to work as expected, and the applied changes are reflected in the `extras` property of the Node instance during the iteration, but they are not actually written to the database.

### Describe the solution you'd like

Considering that `.iterall()` returns a generator, this behavior is, of course, reasonable, so I don't think it warrants changes in the implementation. However, it might be helpful to add a note to the documentation (e.g. the "How to find and query for data" section) that no modifications to the Node `extras` can be made when using `.iterall()` or `.iterdict()`.

**Comment by mbercx** [comment]
ChatGPT has the answer. ^^

![Screenshot 2023-05-19 at 02 16 15](https://github.com/aiidateam/aiida-core/assets/25607960/46093569-a8d2-49fd-a7ea-318b6bf9a67a)

**Comment by sphuber** [comment]
See #6133 . Trying to submit a fix for this bug
