### ISSUE TITLE
❓Easier way to get `work_dir` of `CalcJob` process before execution?

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#6019]
### Is your feature request related to a problem? Please describe

AFAIK, it's currently somewhat tedious to get the working directory from a `CalcJob` process before it has been run. Maybe there is a better way, but this is what I came up with:

```python
computer = calcjob.computer
username = computer.get_configuration()['username']
work_dir = Path(computer.get_workdir().format(username=username)) 
work_dir /= Path(calcjob.uuid[:2], calcjob.uuid[2:4], calcjob.uuid[4:])
```

I had to redo the sharding manually because it actually happens right before the upload:

https://github.com/aiidateam/aiida-core/blob/60756fe30dfaff443ab434d92196249eea47f166/aiida/engine/daemon/execmanager.py#L136-L144

### Describe the solution you'd like

I'd have to look into it a bit more, but maybe we can have a `work_dir` property on the `CalcJob` class or something similar, and then consolidate the logic to create/get the working directory there? Also see https://github.com/aiidateam/aiida-core/issues/6018

**Comment by sphuber** [comment]
Is there a particular use-case for this? On first thought I would not favor exposing this on the public API as the user should not be messing with these implementation details. I would vote to close this as won't-implement.

**Comment by mbercx** [comment]
Thanks for following up on this, @sphuber. I'll admit I don't remember my exact use case. I believe I was trying to execute a Python script on the remote which requires the directory of the calculation job.

Happy to close this as not planned for now, will re-open if I come across the original use case I had in mind again!
