### ISSUE TITLE
`QueryBuilder.iterall()` out of memory when mutating nodes

### ISSUE THREAD

**Issue by eimrek** [aiidateam/aiida-core#6029]
### Describe the bug

Mutating nodes when iterating over the results of the QueryBuilder causes memory usage to keep growing. I can't do large queries & mutate the extras without running out of memory (have cases where this fills up to 32 GB). Currently running into this issue with the `aiida-optimade` plugin, which needs to modify a large amount of extras.

Possibly relevant PR: #5736

### Steps to reproduce

```python
import aiida
from aiida.orm import QueryBuilder, StructureData

aiida.load_profile("li-ion-conductors")

import os
import psutil

def print_memory_usage_psutil():
    # return the memory usage in percentage like top
    process = psutil.Process(os.getpid())
    mem = process.memory_percent()
    print(f"MEMORY: {mem:.2f} %")

query = QueryBuilder()
query.append(StructureData)

for i, (node,) in enumerate(query.iterall()):
    node.set_extra("test", "test")
    if i % 1000 == 0:
        print_memory_usage_psutil()
```

And the output will be

```
MEMORY: 0.48 %
MEMORY: 0.77 %
MEMORY: 1.02 %
MEMORY: 1.29 %
MEMORY: 1.47 %
MEMORY: 1.64 %
MEMORY: 1.88 %
MEMORY: 2.04 %
MEMORY: 2.20 %
MEMORY: 2.37 %
MEMORY: 2.54 %
MEMORY: 2.75 %
...
```

### Expected behavior

I think I could split the large query into multiple with `limit` and `offset` to bypass this problem, but I'm wondering if this could somehow be fixed more directly. For example, by closing and committing the SQL session with some interval.

### Your environment

- Operating system [e.g. Linux]: Ubuntu
- Python version [e.g. 3.7.1]: 3.9.13
- aiida-core version [e.g. 1.2.1]: 2.3.0

**Comment by mbercx** [comment]
Interesting, I thought the whole point of `iterall` is that is returns the query in batches of default size 100 to avoid high memory usage, see the `yield_per` method in `SQLAlchemy`:

https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.yield_per

You might also want to check out https://github.com/aiidateam/aiida-core/issues/6009. Apparently changes to the extras inside `iterall` don't get committed to the database. I'm starting to think we should give the `QueryBuilder` some love during the upcoming coding week. ^^

**Comment by eimrek** [comment]
Thanks for the reply @mbercx. You're right, I double-checked and after restarting the kernel, changes made to extras while using `iterall()` were not retained.

**Comment by mbercx** [comment]
As a side note: doing these kind of operations with extras on large groups is a common use case which takes _a lot_ of time and resources. We should come up with a better way to handle this, if there isn't one already.

**Comment by sphuber** [comment]
This most likely has nothing to do with the `QueryBuilder` but rather how sqlalchemy sessions are handled in the `PsqlDosStorageBackend`. We have been battling a number of issues that are related to this:

* https://github.com/aiidateam/aiida-core/issues/5672
* https://github.com/aiidateam/aiida-core/issues/5802

The common denominator in all these issues is that when using `iterall` (or `iterdict`) we handle an open _cursor_, but as soon as we mutate state of a database object (e.g., storing a node, or changing an extra an an already stored node) the session is committed, and this closes the cursor. So when the batch is done and the cursor is used to get the next batch, we get this exception that is reported.

I have tried to solve this, and at least managed to do so for allowing to set extras and attributes, but storing nodes is still broken. I _had_ found a fix, but that actually broke the CLI as none of the changes were persisted. This is similar to the behavior you report here. This "fix" was originally released with `v2.2.0` but quickly reverted with `v2.2.1`. 

I think that the increase in memory is probably a consequence of the other "fix" that _is_ still in the current code that actually allows setting extras in an `iterall` without excepting, but probably it retains references to the objects in memory, even after the batch is done.

Unfortunately, I have already spent quite some time trying to address these problems but haven't been able to find a solution so far. The handling of these sessions is quite complicated in AiiDA's model. Normally, an application in SqlAlchemy will "know" when to open and commit/revert/close sessions, but with AiiDA, this has to be done automatically as we don't want the user to do this. 

The biggest question I can see that is difficult to answer

> When do we commit changes?

So far, we have coded it such that each change is automatically committed as soon as it is made. This is necessary for changes to be persisted if the session is closed suddenly. For example, the CLI command terminates, a user closes the interactive shell, or a daemon worker stops or is killed.

But this has downsides as well. In the case of itering over batches, it both corrupts the cursor (which is something that we might work around), but committing at each individual change is also very inefficient.

Ultimately, I don't think we can automate both of these requirements. I think it is inevitable that if we want to provide a working API to _effeciently_ mutate a lot of state, it will _have_ to include the user manually indicating this. For example, they would have to manually open a transaction and commit it when they are ready.

**Comment by sphuber** [comment]
I just reran your example script @eimrek and I cannot reproduce it. For me it started on 1.70% and after 50k nodes it raised to 1.73%, basically being static at 1.73% after the first few iterations.

I wonder if there is a subtle difference in our environments, or whether the underlying problem has been addressed. There have been some fixes recently to transaction use in the `PsqlDosBackend`. Could you please repeat your test on the lastest `main` branch and see if the problem persists?

**Comment by eimrek** [comment]
Thanks @sphuber, reran this as well, and indeed the memory problem seems to be fixed!

I'm closing this issue.

However, basically what i'm doing in the script is still not working as the changes to the extras are not committed to the database (as @mbercx mentioned and also in https://github.com/aiidateam/aiida-core/issues/6009).

E.g if i do

```python
import aiida
from aiida.orm import QueryBuilder, StructureData

query = QueryBuilder()
query.append(StructureData, filters={"uuid": "5c8c29c7-2f5f-4f17-a8ee-36182ca47ea1"})

for i, (node,) in enumerate(query.iterall()):
    print(node.uuid)
    print(node.extras.keys())
    node.set_extra("test", "test")
    print(node.extras.keys())
    node.store()
```

I get 

```
5c8c29c7-2f5f-4f17-a8ee-36182ca47ea1
dict_keys(['optimade'])
dict_keys(['optimade', 'test'])
```

If i run it again in the same session of the jupyter kernel, the extra is still there

```
5c8c29c7-2f5f-4f17-a8ee-36182ca47ea1
dict_keys(['optimade', 'test'])
dict_keys(['optimade', 'test'])
```

However, when i restart the kernel, the extra is gone.

**Comment by sphuber** [comment]
> However, when i restart the kernel, the extra is gone.

Is that on latest `main`? Because that would be a big bug.

**Comment by eimrek** [comment]
@sphuber yes, latest main. should be easy to reproduce.

**Comment by sphuber** [comment]
Can confirm the problem. And it seems it has been there since at least v2.2.
See https://github.com/aiidateam/aiida-core/issues/6133
