### ISSUE TITLE
🐛 Dev warning is always shown in Jupyter notebook

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#6049]
### Describe the bug

When setting the `warnings.development_version` configuration to `False`, the warning regarding the development version will indeed disappear when using e.g. the `verdi` CLI:

```console
❯ verdi status
 ✔ version:     AiiDA v2.3.1.post0
 ✔ config:      /Users/mbercx/project/qe/.aiida
 ✔ profile:     dev
 ✔ storage:     Storage for 'dev' [open] @ postgresql://mbercx:***@localhost:5432/qe-dev / DiskObjectStoreRepository: 8500714aa0a841aa88831d0d0e1c548d | /Users/mbercx/project/qe/repository/dev/container
 ✔ rabbitmq:    Connected to RabbitMQ v3.11.15 as amqp://guest:guest@127.0.0.1:5672?heartbeat=600
 ⏺ daemon:      The daemon is not running.
```

However, when loading the profile in a Jupyter notebook, the warning is still shown:

![Screenshot 2023-06-04 at 19 54 58](https://github.com/aiidateam/aiida-core/assets/25607960/240bf48d-c2ec-492c-815e-abf16c7349d9)

### Expected behavior

It's only a minor annoyance, but it would be good if the configuration was also respected inside a Jupyter notebook.

**Comment by mbercx** [comment]
Hmm, this may be due to the fact that something funky is going on with the VSCode Jupyter server.

**Comment by sphuber** [comment]
> Hmm, this may be due to the fact that something funky is going on with the VSCode Jupyter server.

I think so. At least in the code in `aiida-core` there is no explicit distinction being made. One thing I can imagine is that when you load the `Config` in the interpreter (for example when you load the profile), and then change it in another interpreter (e.g. through `verdi` in another shell), then that change won't be visible in the running interpreter. So to make sure the new setting is respected, the kernel has to be fully restarted. Did you maybe not restart the Jupyter kernel in VSCode after having changed the setting?

**Comment by mbercx** [comment]
> Did you maybe not restart the Jupyter kernel in VSCode after having changed the setting?

Oh for sure, I even restarted VSCode. Seems it is _no longer_ picking up the `AIIDA_PATH` for this specific environment anymore for some reason. Other environments are still a-okay. 🤷 I'll just run my own Jupyter server again where I have the kernels properly configured.

Anyway, it's not an AiiDA-related issue, so I'll close.
