### ISSUE TITLE
support List.value and Dict.value

### ISSUE THREAD

**Issue by superstar54** [aiidateam/aiida-core#6057]
For Int, and Float data nodes, one read their value by `x.value`. For `List` and `Dict`, one uses `x.get_list()` and `x.get_dict()`. It would be convenient if `.value` is also supported by `List` and `Dict`.

**Comment by sphuber** [comment]
We have had this discussion before and decided explicity not to implement this, see https://github.com/aiidateam/aiida-core/issues/5313
So I will close this for now. If a majority of the team feels that the decision was incorrect, we can reopen this for discussion.
