### ISSUE TITLE
Computer.configure does not use the Computer instance backend (.collection issue?)

### ISSUE THREAD

**Issue by rikigigi** [aiidateam/aiida-core#6105]
Following yesterday discussion with @sphuber and @giovannipizzi 

I'm using aiida v2.4.0 on Python 3.11.5
Take the following code

```
import aiida
import aiida.orm
import aiida.storage.sqlite_temp.backend as sqtemp

#create an in-memory backend
profile = sqtemp.SqliteTempBackend.create_profile()
backend = sqtemp.SqliteTempBackend(profile)

# create a new computer

comp = aiida.orm.Computer(backend=backend, label='localhost', hostname='localhost', transport_type='core.local', scheduler_type='core.direct', workdir='/tmp/aiida')

#create a new user

user = aiida.orm.User(backend=backend, email='pippo@localhost')

user.store()

print(f'user stored {user}')

# configure the computer for the user

#remove comment to reproduce the error
#comp.configure(user=user)

authinfo = aiida.orm.AuthInfo(comp, user, backend=backend)
authinfo.store()

comp.store()
```
This works as expected. But if I use the `configure` method of the Computer class I get the following:
```
user stored pippo@localhost
Traceback (most recent call last):
  File "/home/bertossa/pippo/aiida_test.py", line 23, in <module>
    comp.configure(user=user)
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/orm/computers.py", line 681, in configure
    authinfo = self.get_authinfo(user)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/orm/computers.py", line 574, in get_authinfo
    authinfo = authinfos.AuthInfo.collection(self.backend).get(dbcomputer_id=self.pk, aiidauser_id=user.pk)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/common/lang.py", line 99, in __get__
    return self.getter(owner)
           ^^^^^^^^^^^^^^^^^^
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/orm/entities.py", line 184, in collection
    return cls._CLS_COLLECTION.get_cached(cls, get_manager().get_profile_storage())
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bertossa/pippo/venv/lib/python3.11/site-packages/aiida/manage/manager.py", line 242, in get_profile_storage
    raise ConfigurationError(
aiida.common.exceptions.ConfigurationError: Could not determine the current profile. Consider loading a profile using `aiida.load_profile()`.
```

An issue very similar to this one (code that is not using the profile stored in the orm class) is found in this function

https://github.com/aiidateam/aiida-core/blob/517ffcb1c5ce32f281589432cde1d58588fa83e0/aiida/orm/nodes/data/upf.py#L73

where again a call to .collection triggers the global profile loading

I think it is natural to expect that a method of an orm class uses the same backend that was used to instantiate the class, but I think this is not happening everywhere.

**Comment by sphuber** [comment]
Thanks for the extensive bug report @rikigigi . This is indeed a bug. We should check the entire `aiida.orm` module and see where the collections are used and make sure that it is instantiated with `.collection(self.backend)`.

**Comment by sphuber** [comment]
I spoke too fast. The problem here is with the `collection` property. This is a classproperty of the `Entity` base class, which all ORM classes inherit from. Even though it _looks_ like we are calling it with `self.backend` but really, since `collection` is a property which returns a `Collection`, we are _calling_ the `Collection` instance with `self.backend`. But we never get there, because the `collection` property is defined as:
```python
    @classproperty
    def collection(cls) -> CollectionType:  # pylint: disable=no-self-argument
        """Get a collection for objects of this type, with the default backend.

        :return: an object that can be used to access entities of this type
        """
        return cls._CLS_COLLECTION.get_cached(cls, get_manager().get_profile_storage())
```
and so it is trying to get the currently loaded backend. Since it is a property, we cannot pass it to it. We would have to make it a method, but this would be backwards incompatible. Currently it is possible to do `orm.User.collection` to get the collection, but if we turn it into a method, it will _have_ to become `orm.User.collection()`. But we really we should be turning it into a method so we can optionally pass a backend, e.g.:
```python
    @classmethod
    def collection(cls, backend: 'StorageBackend' | None) -> CollectionType:  # pylint: disable=no-self-argument
        """Get a collection for objects of this type.

        :param backend: An optional backend.
        :return: an object that can be used to access entities of this type
        """
        return cls._CLS_COLLECTION.get_cached(cls, backend or get_manager().get_profile_storage())
```

**Comment by rikigigi** [comment]
So `.collection` is something that should not be used by the library code but only by the library user, for convenience? Maybe we could add an other function that allows us to specify the backend explicitly and we can use that one inside aiida-core.

**Comment by sphuber** [comment]
@rikigigi see #6107 for a fix. May have to search a bit more in the codebase for instances of `.collection(backend)` that will have to be replaced with `.get_collection(backend)`.
