### ISSUE TITLE
Create archive the dst folder check need to happen before the dump and compress start

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#6167]
When dumping data to the archive with `verdi archive create`, it takes hours to create the `export.zip` but the command failed because of the dst folder does not exist. 
It'll be very helpful if the check can happen before or automatically create a folder with `mkdir -p`.

**Comment by prady0t** [comment]
Hey can I work on this?

**Comment by unkcpz** [comment]
Sure, please go ahead.

**Comment by AryanNanda17** [comment]
#!/bin/bash

# Specify source and destination folders
src_folder="/path/to/source/folder"
dst_folder="/path/to/destination/folder"

# Check if the destination folder exists
if [ ! -d "$dst_folder" ]; then
    # If it doesn't exist, create it
    mkdir -p "$dst_folder"
fi

# Perform the data export to export.zip
tar -czf "$dst_folder/export.zip" -C "$src_folder" .

# Check the exit status of the previous command
if [ $? -eq 0 ]; then
    echo "Data export successful."
else
    echo "Data export failed."
fi

**Comment by AryanNanda17** [comment]
```
#!/bin/bash

source_folder="/path/to/source_folder"
destination_folder="/path/to/destination_folder"
archive_name="export.zip"

if [ ! -d "$destination_folder" ]; then
    mkdir -p "$destination_folder"
fi

if [ -d "$destination_folder" ]; then
    your_custom_dump_command "$source_folder" "$destination_folder/$archive_name"
else
    echo "Failed to create destination folder or it does not exist. Exiting..."
    exit 1
fi

```

**Comment by AryanNanda17** [comment]
I think this will resolve the bug. I am not sure
-  where to make the file  data_dump_script.sh
- what is the destination path and the source folder. 
- what is the custom dump command.

**Comment by AryanNanda17** [comment]
@unkcpz 
Please help me with that.
