### ISSUE TITLE
The process status is None for a paused workchain.

### ISSUE THREAD

**Issue by superstar54** [aiidateam/aiida-core#6205]
### Describe the bug

The process status is None for a paused process. It should be a message similar to "Paused through verdi process pause"

### Steps to reproduce

Submit a `MultiplyAddWorkChain`, and pause the main process.
```console
10092  29s ago    MultiplyAddWorkChain           ⏸ Waiting        Paused through `verdi process pause`
10093  29s ago    multiply                       ⏹ Finished [0]
10095  29s ago    ArithmeticAddCalculation       ⏵ Waiting        Monitoring scheduler: job state RUNNING
```
After the sub-process `ArithmeticAddCalculation` is finished, the process status of the the WorkChain is `None`. Thus, it confuses for the user what the process is waiting.
```console
10092  35s ago    MultiplyAddWorkChain           ⏸ Waiting
10093  34s ago    multiply                       ⏹ Finished [0]
10095  34s ago    ArithmeticAddCalculation       ⏹ Finished [0]
```

**Comment by danielhollas** [comment]
> After the sub-process ArithmeticAddCalculation is finished, the process status of the the WorkChain is None. Thus, it confuses for the user what the process is waiting.

Oooh, I think this is what confused me in an issue that I described on Discourse: https://aiida.discourse.group/t/how-to-debug-a-workflow-stuck-in-waiting-state/220/26

@superstar54 thanks for fixing this!
