### ISSUE TITLE
🐛 `warnings.showdeprecations` config is not respected

### ISSUE THREAD

**Issue by mbercx** [aiidateam/aiida-core#6210]
### Describe the bug

Explanation from @sphuber [here](https://github.com/aiidateam/aiida-core/pull/6202#issuecomment-1846929989):

The problem is that in `v2.0.0` Chris add the `aiida.common.warnings.warn_deprecation` method that should be used to raise deprecation warnings. It only checks the `AIIDA_WARN_v{version}` environment variable to determine whether the warning should be emitted:
https://github.com/aiidateam/aiida-core/blob/184fcd16e9a88fbf9d4e754870416f4a56de55b5/aiida/common/warnings.py#L48

It completely ignores the `warnings.showdeprecations` config option though.

The argument for adding this environment variable and having it off by default was that we were introducing quite a number of deprecation warnings in v2.0. To make it less annoying to users, we would silence them by default and they would have to explicitly turn it on. I am not sure why he chose to use an env variable and not use the existing config option. Maybe to make it easier to turn on in CI of plugins perhaps? I know he modeled it after how sqlalchemy did deprecations for their v2  and he is a big fan of that library and its developer.

### Expected behavior

Also from @sphuber (so it doesn't look like I'm talking with myself here 😅):

Anyway, I think we should consider a few things here:

* We should probably at the very least make `warnings.showdeprecations` be respected again.
* Maybe we should get rid of `AIIDA_WARN_v3`. Only use is that it might be easier to temporarily enable it, without having to switch it through `verdi config set`. I can see how this might still be useful though. If we keep it, we have to think about the precedence rules though. What if `AIIDA_WARN_v3` are in conflict? The `warnings.showdeprecation` is `True` by default, but the env variable is off by default.
* Currently deprecation warnings are _not_ shown by default, only if `AIIDA_WARN_v3` is switched on. I think we should change this. The idea was that plugin developers could easily enable it in their CI to address all warnings, but normal users are also affected by deprecation warnings. I don't think it is realistic that they will switch the warnings on at some point.

**Comment by mbercx** [comment]
> We should probably at the very least make warnings.showdeprecations be respected again.

Fully agree. :)

> Maybe we should get rid of AIIDA_WARN_v3. Only use is that it might be easier to temporarily enable it, without having to switch it through verdi config set. I can see how this might still be useful though. If we keep it, we have to think about the precedence rules though. What if AIIDA_WARN_v3 are in conflict? The warnings.showdeprecation is True by default, but the env variable is off by default.

I think typically an environment variable overrides the configuration. This would also allow your use case, i.e. if you want to run some code with deprecation warnings without changing the config and back, you simply set the environment variable temporarily. Then we'd have to make the `warnings.showdeprecation` config `False` by default though.

> Currently deprecation warnings are not shown by default, only if AIIDA_WARN_v3 is switched on. I think we should change this. The idea was that plugin developers could easily enable it in their CI to address all warnings, but normal users are also affected by deprecation warnings. I don't think it is realistic that they will switch the warnings on at some point.

I would be inclined to agree. AiiDA v2.X has been out for a while, and probably users are not adapting their scripts unless they see the deprecation warning. If we leave the `warnings.showdeprecation` to `True` by default and respect it, then do we still need `AIIDA_WARN_v3` then?

**Comment by sphuber** [comment]
> If we leave the `warnings.showdeprecation` to `True` by default and respect it, then do we still need `AIIDA_WARN_v3` then?

I think we leave it for now. 1) We would have to deprecate the deprecation flag 😅 which is bound to be a mess. And 2) it still has some function. If a user wants warnings off by default and so sets `warnings.showdeprecations` to `False`, it can still be useful to quickly invoke a command with `AIIDA_WARN_v3` to have the warnings enabled just for that command.

In the end, I think it might be useful to allow _any_ config option to be overwritten to environment variables in this way. i.e. that `warnings.showdeprecations` can be overridden with `AIIDA_CONFIG_WARNINGs_SHOWDEPRECATIONS=1`. This could become a generic approach. But that would be a separate feature request for another time

**Comment by mbercx** [comment]
> In the end, I think it might be useful to allow any config option to be overwritten to environment variables in this way. i.e. that warnings.showdeprecations can be overridden with AIIDA_CONFIG_WARNINGs_SHOWDEPRECATIONS=1. This could become a generic approach. But that would be a separate feature request for another time

Fully agree. As discussed privately, I would love to just set an environment variable in my `.bashrc` to let _all_ AiiDA instances know I reconfigured my `brew`-installed RabbitMQ properly. e.g.

```
export AIIDA_WARNINGS_RABBITMQ_VERSION=False
```
