### ISSUE TITLE
Bug: Outdated Twitter Logo 

### ISSUE THREAD

**Issue by AquibKhann** [aiidateam/aiida-core#6244]
The Aiida website currently displays an outdated version of the Twitter logo. The logo being used is not in sync with the latest branding guidelines.

Steps to Reproduce:

Visit the Aiida website
Navigate to the section displaying social media links.
Observe the Twitter logo and compare it with the latest Twitter branding guidelines.
Expected Result:
The Twitter logo should adhere to the most recent branding guidelines provided by Twitter.

Actual Result:
The current Twitter logo appears to be outdated and may not align with the latest branding standards.

https://github.com/aiidateam/aiida-core/assets/120818337/9051c230-adda-4dbd-982b-1b12aa6e13ad

**Comment by sphuber** [comment]
You already reported this and I moved it here: https://github.com/aiidateam/aiida-website/issues/57
