### ISSUE TITLE
Docs: unifying or merging tutorials, documentation, and qe-demo into one

### ISSUE THREAD

**Issue by khsrali** [aiidateam/aiida-core#6287]
### The current issue

For new users, like myself, it was difficult to find out there are more advanced tutorials available online than the basic one in [Documentation](https://aiida.readthedocs.io/). Specifically these two: [tutorials](https://aiida-tutorials.readthedocs.io/en/latest/) and [qe-demo](https://aiida-qe-demo.readthedocs.io/en/latest/).
There might even be more of these available online, that I'm not aware of. In that case please let me know.  

### Possible solutions

The bare minimum is to add a section just below the [*basic tutorial*](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/index.html) with the title "Advanced tutorial" that links to formally known [tutorials]([tutorials](https://aiida-tutorials.readthedocs.io/en/latest/)). In addition and a better suggestion would be to merge [aiida-tutorials](https://github.com/aiidateam/aiida-tutorials) repository into the documentation of [aiida-core](https://github.com/aiidateam/aiida-core) in GitHub, making it easier to maintain, and keeping it updated with the current version of AiiDA.

Regarding [qe-demo](https://aiida-qe-demo.readthedocs.io/en/latest/), perhaps we can combine it with [aiida-tutorials](https://github.com/aiidateam/aiida-tutorials); otherwise, new users may be unsure which way to go.

Finally, as a side note, I guess the [aiidalab documentation](https://aiidalab.readthedocs.io/) is not referenced or linked in the [aiida documentation](https://aiida.readthedocs.io/). 
This is critical for new users to understand their options, which ones to use, and where to find their documentation. So, perhaps there should be a brief explanation of aiidalab in the main aiida documentation with proper links.

**Comment by khsrali** [comment]
If you give me your thoughts @edan-bainglass, @sphuber, and @giovannipizzi, I can go ahead and start making pull requests for any of these.
Thanks! 

P.S. Sorry, I'm not sure if you notice when a new issue is created, or if I need to pin it. --please let me know.

**Comment by mbercx** [comment]
Thanks @khsrali! At first glance I'm also in favour of integrating the tutorials a proper part of our documentation. One bottleneck I mention in [this comment](https://github.com/aiidateam/aiida-core/pull/6286#issuecomment-1941154909) is that the `aiida-core` documentation is still written in RestructuredText, whereas the `aiida-tutorials` repo uses MyST Markdown. I think you can mix the two, but we should probably start using MyST anyways. We'll probably also have to update [the `docs` dependencies](https://github.com/aiidateam/aiida-core/blob/487c6bf047030ee19deed49d5fbf9a093253538e/pyproject.toml#L193-L203) etc, and I hope we don't run into trouble there.

Regarding the QE demo, we've already considered just adding a "demos" page in the past, where we link to various examples of AiiDA being used in practise. The difference between a demo and tutorial would be that the former is more of an advertisement to get people to start using AiiDA and the latter tries to teach users AiiDA and its concepts. But happy to discuss.

> The bare minimum is to add a section just below the [basic tutorial](https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/index.html) with the title "Advanced tutorial" that links to formally known tutorials.

Indeed, this is low-hanging fruit that we should start with.

> P.S. Sorry, I'm not sure if you notice when a new issue is created, or if I need to pin it. --please let me know.

Anyone watching `aiida-core` will get a notification, but pinging someone is def a good way to get someones attention. I for example don't always look at every notification I get, but if I'm mentioned I'm much more likely to. ^^

**Comment by GeigerJ2** [comment]
Hi @khsrali, thanks for creating the issue! :rocket: I also think that merging [`aiida-tutorials`](https://github.com/aiidateam/aiida-tutorials) into the main documentation and having it as another section would be nice to have. For each actual AiiDA virtual/in-person tutorial, we could then freeze a version at the respective state, while keeping it updated together with `aiida-core` overall.

Another point that also recently came up on [discourse](https://aiida.discourse.group/t/aiida-cli-cheatsheet/262) is the [AiiDA cheat sheet](https://github.com/aiidateam/aiida-tutorials/blob/main/docs/cheatsheet/cheatsheet.pdf). We should update that (see `aiidateam/aiida-tutorials#345`), as well, and add a pointer to it, possibly also on the main readthedocs page. Further, we could also extend it, e.g. with useful `cli` commands, that might otherwise be overlooked (thanks to @bastonero for the suggestion).

**Comment by sphuber** [comment]
One argument for keeping the other tutorials separate, was that they could be very domain specific, such as the `aiida-quantumespresso` tutorial, whereas AiiDA is in principle domain agnostic. We have to be wary that where most of the developers come from may be familiar with DFT codes and QE in particular, this may not be the case for all potential users of AiiDA. So I think there should always be good generic tutorials, and then domain specific examples should be clearly marked as such.

Finally, I am not sure that merging the `aiida-tutorials` into `aiida-core` is the required solution. If the main problem is discoverability, that can be easily resolved by including links in the appropriate places of the `aiida-core` docs, right? If it were merely a few tutorials in the style of the basic tutorial that is already in `aiida-core`'s docs, I probably wouldn't object to this. However, the `aiida-tutorials` repo is quite bulky and was actually used for _actual_ in person tutorials, so it contains a lot of additional info like program schedules, presentations, practical info etc.

Unless it really provides additional benefits, I would prefer we keep all that content in `aiida-tutorials` and just link to it from `aiida-core`, or move/copy the relevant tutorials into `aiida-core` matching the style and form of the basic tutorial that we already have there.

**Comment by khsrali** [comment]
Thanks everyone for your useful comments. 

@sphuber 
> Finally, I am not sure that merging the `aiida-tutorials` into `aiida-core` is the required solution. If the main problem is discoverability, that can be easily resolved by including links in the appropriate places of the `aiida-core` docs, right?

Yes, I think the main issue is discoverability. But apart from that, also a bit of confusion or uncertainty if one needs to stick with the detailed `aiida-tutorials` or to jump back and forth between that and `aiida-core` with the hope of grasping something not that thorough and not this short, again, a new user experience. 
So I vote for adding links in the `aiida-core` docs for `aiida-tutorials` as well as other available domains, in addition maybe a "maneuverability" guide right in the homepage, where to look for anything you need, sort of thing. For example:
if you are a QE user,  and would like to quickly setup aiida please refer to this demo
if you are a QE user, and would like to be thorough, you may skip this documentation and directly refer to this tutorials..
if you are a VASP user, please direct to that link of demo...
if you are a generic user, please follow things in this documentation and... here is a quick example to setup aiida for your own mypython-script.py


@GeigerJ2 
> Another point that also recently came up on [discourse](https://aiida.discourse.group/t/aiida-cli-cheatsheet/262) is the [AiiDA cheat sheet](https://github.com/aiidateam/aiida-tutorials/blob/main/docs/cheatsheet/cheatsheet.pdf). We should update that (see [here](https://github.com/aiidateam/aiida-tutorials/issues/345) and [here](https://github.com/aiidateam/aiida-core/issues/4506)) as well, and add a pointer to it, possibly also on the main readthedocs page. Further, we could also extend it, e.g. with useful `cli` commands, that might otherwise be overlooked (thanks to @bastonero for the suggestion).

This is a good idea as well; I support adding a direct link to those cheat sheets so that new users can see a wide range of options right away. In fact, I created a cheat sheet for myself because I thought it would help me memorize how to.


@mbercx 
> Regarding the QE demo, we've already considered just adding a "demos" page in the past, where we link to various examples of AiiDA being used in practise. The difference between a demo and tutorial would be that the former is more of an advertisement to get people to start using AiiDA and the latter tries to teach users AiiDA and its concepts. But happy to discuss.

Indeed, in my honest opinion, everything should be addressed in a main documentation of aiida, which I believe is the `aiida-core` docs. Otherwise, a naive fresh user like me, all of the sudden discover himself immersed in tons of pages of docs, and not even sure if that's all. 
Just a side note for future, we could also classify some docs for user and some for developers.

**Comment by mbercx** [comment]
@sphuber 

> But then I would really advocate for simply taking the best content from aiida-tutorials and add it as additional/advanced tutorials to the aiida-core docs, making sure they match the style of the already existing basic tutorial.

Agreed. I would say we can add another section in the top bar called "Tutorials":

![Screenshot 2024-02-13 at 15 56 11](https://github.com/aiidateam/aiida-core/assets/25607960/8f089986-0274-40b4-a41b-2c1b40148f70)

The current version of the tutorials already divides the content in "Units" ("Running processes", "Managing Data", ...) and "modules", without using the top bar:

![Screenshot 2024-02-13 at 15 58 10](https://github.com/aiidateam/aiida-core/assets/25607960/b15f2410-cb5d-400b-aac4-e8d6aaf7e975)

> I don't see a need to keep all historic versions of the in-person tutorials as is done on aiida-tutorials

Fully agree on that one. :)

**Comment by GeigerJ2** [comment]
> That is fair enough. But then I would really advocate for simply taking the best content from aiida-tutorials and add it as additional/advanced tutorials to the aiida-core docs, making sure they match the style of the already existing basic tutorial. I don't see a need to keep all historic versions of the in-person tutorials as is done on aiida-tutorials

Also strongly agreeing here!

> The current version of the tutorials already divides the content in "Units" ("Running processes", "Managing Data", ...) and "modules", without using the top bar:

In addition, what do you guys think about adding two more panels to the readthedocs landing page, one for "Advanced Tutorial" and another for "Cheatsheet". Like this, all the different channels of information would be directly visible at a glance? E.g.:
|                 |                       |
| --------------- | --------------------- |
| Getting Started | Cheat Sheet           |
| Basic Tutorial  | Advanced Tutorial     |
| How-To Guides   | Topics                |
| API Reference   | Internal Architecture |
