### ISSUE TITLE
📝 DOCS: Better/quicker highlighting of useful resources

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-core#6290]
### Describe the current issue

Alright, so this might be one of the last issues @khsrali and I will raise here regarding the documentation for now 😅 
One thing that was recently brought up by @bastonero on [Discourse](https://aiida.discourse.group/t/aiida-cli-cheatsheet/262) is that it would be nice to have some kind of CLI cheat sheet. The reason being that there are quite some useful commands that one might not be aware of when starting out. While the documentation is extensive and basically everything can be found there, it might be, for that very reason, a bit overwhelming for a beginner, leading to some useful tools being overlooked, thus complicating the adaptation. The issue is also not limited to the CLI, but other resources, as well - to give some examples:
- `verdi calcjob gotocomputer/inputcat/outputcat`
- `verdi devel rabbitmq tasks analyze --fix`
- A pointer to the location of the config file (e.g. to debug possible `postgres` issues)
- The fact that caching exists (at least when I started, I wasn't aware that it was a thing, though, now it should be more obvious, with it being mentioned in the `verdi process` outputs)
- The possibility to use YAML files to define protocols and set configurations
- [The AiiDA resource registry](https://github.com/aiidateam/aiida-resource-registry)
- [The AiiDA plugin cookie cutter](https://github.com/aiidateam/aiida-plugin-cutter)
- [AiiDA-project](https://github.com/aiidateam/aiida-project)

### Describe the solution you'd like

Now, of course, these points depend on the trajectory each person had when learning AiiDA, and the way they use it now, but we could compile some kind of "wish I'd known that sooner" list - possibly open it as a discussion on Discourse to ask users for input?

Personally, I am a big fan of the [AiiDA cheat sheet](https://aiida-tutorials.readthedocs.io/en/legacy/_downloads/5f69c3f9ce1f31f1f959b3da46fdc99d/cheatsheet.pdf), and feel like it could be a nice place to compile such information. There already are open PRs ([here](https://github.com/aiidateam/aiida-tutorials/issues/345) and [here](https://github.com/aiidateam/aiida-core/issues/4506)) to update the cheat sheet, make it more general, and integrate it into the main documentation, so we could combine the tasks. The idea was also brought up to convert it into an interactive webpage, though, even providing clickable links in the `svg`/`pdf` file where applicable could be a quick solution. Lastly, I think it would be nice to have a panel for the cheat sheet (and/or other resources, such as [demos](https://github.com/aiidateam/aiida-core/issues/6287)) on the `readthedocs` landing page, so that they are directly visible at a glance. Curious to hear your thoughts on this!

**Comment by agoscinski** [comment]
Some of the information in the cheat sheet I like a lot. What I don't like is that this is a pdf which is not great for version control, and that it will need frequent updates. I think the main purpose of a cheat sheet is to quickly get an overview of all important aspects of aiida. Then why can't it be just a compressed getting started page [similar as the one in aiida-workgraph](https://aiida-workgraph.readthedocs.io/en/latest/autogen/quick_start.html). [aiida-core's introduction page](https://aiida.readthedocs.io/projects/aiida-core/en/v2.6.2/intro/index.html) is at the moment too high-level to be a getting started page for users. I can see that a pdf can be more compressed in space than a doc page, but I think the additional maintenance will result in it never being up to date. So would not a compressed getting started page with all the information in the cheat sheet, do also the job?

Also I wonder, regarding the nested trees that the cheatsheet shows, can't we make this information automatically accessible in the CLI with an additional command? Then it is autogenerated and is always up to date (and hopefully needs less maintenance)
```
verdi help nodetree
verdi help verditree
verdi help node <DATA_TYPE> # e.g. core.strucure
verdi help cheatsheet # an CLI cheat sheet to highlight very useful commands
```
I am using the help command which can be accessed anyway with `verdi --help`. The design of the CLI command would be a different discussion.
