### ISSUE TITLE
Handling `jinja`-style fields in `yaml` files when using `--config`

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-core#6294]
For easy setting up of computers and codes, there currently exist `aiida-code-registry` and `aiida-resource-registry`. In the former repo, configuration files are explicit/specific, with most values already set (apart from things like `username`). While in the latter repo, fields are often kept more general, and instead `jinja` variables are used, e.g. for Quantum Espresso:
```yaml
label: '{{ code_binary_name }}-{{ version }}'
```
This is done to keep these fields dynamic, so they can then be filled in manually/graphically in `aiidalab` (if I understand correctly, the main focus of the repo so far).

Now, as we are planning to replace `aiida-code-registry`, and make `aiida-resource-registry` the main hub for computer and code configuration files, they should also be compatible with `aiida-core`. Currently, with the provided files, `verdi` fails due to the `metadata` section, and sets the `jinja` variable expressions as the literal fields, e.g. labelling the computer `{{ label }}` (ofc, to resolve the latter, one could just do a simple search-and-replace).

Now, to make `aiida-resource-registry` easier compatible with `aiida-core` we could differentiate inside the repo between files intended to be used in `aiidalab` and `aiida-core`, and just update and move the files from `aiida-code-registry` there (will create issues/PRs in the respective places, as well).

Or, additionally, which might be a neat feature, add in `aiida-core` the functionality that when `jinja` variables are found, the user is prompted for input only on these items. Like this, fully specified files are still read in automatically by `verdi`, while one is only prompted for fields such as `label` that cannot be generalized (or could they? :3) - that is, without each person having to manually search-and-replace them in the `yaml` files. Also, forgetting to replace fields wouldn't lead to things like codes labelled `{{ label }}` in the database.

In the short term, this seems like a small issue, but in the long term we could almost fully automate the setup of computers/codes by using the registry, such that new users basically don't have to take care of anything during their setup and configuration, as long as the files already exist in the registry (see also [this PR](https://github.com/aiidateam/aiida-project/issues/1)), possibly removing another entry hurdle.

Pinging @mbercx and @unkcpz here to add their thoughts, as I brought it up to both of you.

**Comment by sphuber** [comment]
Related (and possible duplicate) issues:

https://github.com/aiidateam/aiida-core/issues/5949
https://github.com/aiidateam/aiida-core/issues/4680

**Comment by GeigerJ2** [comment]
Ah, good catch! I'll close this issue in favor of #4680.

**Comment by unkcpz** [comment]
Also this one in team-compass https://github.com/aiidateam/team-compass/issues/4
