### ISSUE TITLE
Inconsistent PK order of uploaded archive

### ISSUE THREAD

**Issue by edan-bainglass** [aiidateam/aiida-core#6302]
I noticed in a recent import including a computer, several codes, a workflow, and 4 of its called descendants, that the order of PKs assigned to the loaded nodes is inconsistent

WorkChain (17)
Child 1 (3)
Child 2 (30)
Child 3 (23)
Child 4 (4)

Children 1 and 2 are submitted in the first step, then child 3, then 4. Not so clear after the upload.

Seems like a bug.

**Comment by sphuber** [comment]
The pks are not required to be sorted in chronological order. When you are running normally, that is a side effect that newer nodes have greater pks, but there is no reason why this should be maintained during import. Is there a particular reason why you would expect this or why it is problematic?

**Comment by edan-bainglass** [comment]
Both expected and considered problematic from a provenance point of view. I'd be somewhat confused a few months from now if presented with these PKs. Or maybe just concerned. At face value, seems like Child 2 ran last, when in fact it ran second.

**Comment by sphuber** [comment]
The pk is never guaranteed to be ordered chronologically. That is what the `ctime` is for on the nodes. This certainly is not a bug. Maybe it can be unexpected, but then we simply have to document that pks are not necessarily chronological

**Comment by edan-bainglass** [comment]
I see. I'll make a note regarding documentation. Thanks @sphuber.
