### ISSUE TITLE
Better error when user tries to submit workflow without rabbitmq broker

### ISSUE THREAD

**Issue by danielhollas** [aiidateam/aiida-core#6374]
When a user creates a profile with `verdi presto` without rabbitmq broker, and tries to submit a Workflow to a daemon via `submit` they will be greeted with this assert

```
    113     runner = manager.get_manager().get_runner()
    114     assert runner.persister is not None, 'runner does not have a persister'
--> 115     assert runner.controller is not None, 'runner does not have a controller'
    116 
    117     process_inited = instantiate_process(runner, process, **inputs)

AssertionError: runner does not have a controller
```

Since this will likely become a common problem for newcommers, we should provide a clear error message.

Should be done as a follow-up (or part of #6351)

**Comment by mbercx** [comment]
Good point @danielhollas! Also note that even in the basic tutorial we have a section where we submit to the daemon:

https://aiida.readthedocs.io/projects/aiida-core/en/stable/intro/tutorial.html#submitting-to-the-daemon

Maybe we should also add a warning here that this will only work in case they have a RabbitMQ broker configured.

Ideally they'd also be able to reconfigure the _same_ profile to use a RabbitMQ broker, but I _suppose_ that'd be beyond the scope of this issue. 😇
