### ISSUE TITLE
Compression of files support

### ISSUE THREAD

**Issue by aiida-bot** [aiidateam/aiida-core#64]
Originally reported by: **Andrea Cepellotti (Bitbucket: [acepellotti](https://bitbucket.org/acepellotti), GitHub: [cepellotti](https://github.com/cepellotti))**

----------------------------------------

Either always compress big files or add other management command to compress.

----------------------------------------
- Bitbucket: https://bitbucket.org/aiida_team/aiida_core/issue/64

**Comment by sphuber** [comment]
This is part of a bigger issue of the implementation of the file repository #335
