### ISSUE TITLE
CLI: Make output file for `verdi <subcommend(s)> export` optional 

### ISSUE THREAD

**Issue by agoscinski** [aiidateam/aiida-core#6414]
And, more general, some idea for the future: We could also make the `OUTPUT_FILE` optional, and use `f{label}-setup/config.yaml` as default (also for the code export), as this is probably how people would usually name the output file?

_Originally posted by @GeigerJ2 in https://github.com/aiidateam/aiida-core/pull/6389#discussion_r1600976545_

**Comment by GeigerJ2** [comment]
Should be closed by #6486.
