### ISSUE TITLE
Bring docker CI tests back for PRs from forked repo

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#6449]
https://github.com/aiidateam/aiida-core/pull/6396 refactoring docker CI by not upload the artifact but directly push image to ghcr.io registry, which accelerate the CI time a lot. 
However, push to ghcr.io requires the write permission of `GITHUB_TOKEN` which is not available for the PR from forked repo. Thus it unfortunately cut the feature to have the built image tested from forked repo which can grab some issue as manifested and fixed in https://github.com/aiidateam/aiida-core/pull/6445

**Comment by sphuber** [comment]
@unkcpz If you implement this, would that make #6446 obsolete?

**Comment by unkcpz** [comment]
Yes, but I may not able to do it now. So maybe finish #6446 and keep this issue open?
