### ISSUE TITLE
Allow for environment variables in the execution line in job scripts.

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida-core#648]
Currently AiiDA writes everything in the execution line for safety reasons in quotes ' '.
This does not allow for the usage of any environment variables within the execution line.
On the cluster of our university they enforce one to use environment variables, for example $MPIEXEC  for some execution command plus options, depending what resources you get this might change.

So far I hacked it. But it might be a good idea, maybe to check if the first char in any term of the execution line contains a '$' and then leave out the quotes.

Are there any reasons why this should not be allowed for?

**Comment by broeder-j** [comment]
So far. My 'hack' is to add an if to aiida.common.util escape_for_bash(string), return bash variables without any quotes in the bash script/shell.
```
    escaped_quotes = str_to_escape.replace("'", """'"'"'""")
    if '$' in escaped_quotes:# variable
        return '{}'.format(escaped_quotes)
    return "'{}'".format(escaped_quotes)
```
For my purposes it works. 
Since I do not know why quotes are enforced, I also do not know if this is a 'good' solution. Also should this be only for $string or any string with a $? Please comment. Martin and Giovanni wrote that code part. But I guess Nicolas also, since he talked to me about it at one point.

**Comment by broeder-j** [comment]
escape_for_bash is used by a lot of other things in aiida and the change above breaks in my case that the produced datatype from my calculation was the base type. I did not understand why. But 
```
    escaped_quotes = str_to_escape.replace("'", """'"'"'""")
    if escaped_quotes.startswith('$'):# variable
        return '{}'.format(escaped_quotes)
    return "'{}'".format(escaped_quotes)

```
does not break this. and still works for the use of env variables

**Comment by sphuber** [comment]
This is now supported. The `Computer` and `Code` can be configured with `use_double_quotes = True` and then arguments are quoted with double quotes, allowing variable expansion
