### ISSUE TITLE
The transport plugin should be responsible for determining the maximum number of times a transport task can be tried, instead of `aiida` profile.

### ISSUE THREAD

**Issue by khsrali** [aiidateam/aiida-core#6487]
Trial attempts may be ineffective in certain transport plugins, such as `aiida-firecrest`. 
If I understood correctly this option can be set to zero for the profile in `src/aiida/manage/configuration/config`.

```python
    transport__task_maximum_attempts: int = Field(
        5, description='Maximum number of transport task attempts before a Process is Paused.'
    )
```

However, it would be preferable to leave it in the hands of the transport plugin, as multiple transport plugins (including SSH) may coexist in the same profile.

**Comment by khsrali** [comment]
I thought the main idea of exponential backup was to avoid being banned from HPC by sending too many requests.

In `FirecREST` they have a similar concept, rate-limit, but it's handled [internally](https://github.com/eth-cscs/pyfirecrest/blob/0cfdc3e6acc803620b46b03ad3ce22a14625623d/firecrest/BasicClient.py#L81) by `pyfirecrest`  which `aiida-firecrest` depends on.

I understand and agree that still there are other things could fail, like internet connection, FirecREST server being done temporarily. However, this doesn't need to be *exponential*. 

So I think it make sense if the backoff mechanism (series of seconds 1, 2, 4, 8, 16 or 1,1,1,1) would be set from the transport plugin / computer settings.

**Comment by sphuber** [comment]
> I thought the main idea of exponential backup was to avoid being banned from HPC by sending too many requests.

No, that is the `safe_interval` setting which is set on the transport. The EBM is done for all `CalcJob`s and is to ensure that an exception in a transport operation that is due to a transient problem (such as connection problems) doesn't except the entire process. So this has nothing to do with rate limiting

**Comment by khsrali** [comment]
Alright, I think we already set `safe_interval=0` in `aiida-firecrest`,
So I think we can close here.
Thanks a lot @sphuber for clearing that up,
