### ISSUE TITLE
Support backward compatibility for `manage.tests.pytest_fixture`

### ISSUE THREAD

**Issue by unkcpz** [aiidateam/aiida-core#6490]
Got error:

```
E     aiida.common.exceptions.MissingEntryPointErro: Entry point 'core.rabbitmq' not found in group 'aiida.brokers'
```

after start using `main` and running test while I still using `manage.tests.pytest_fixture`. Using `tools.pytest_fixtures` solve the issue.
But since it is said deprecated in v3, it is better to make the old one still work.

**Comment by sphuber** [comment]
What is the full stack trace? From which fixture is the error coming?

**Comment by unkcpz** [comment]
Emm... I cannot reproduce it after I reinstall `aiida-core`. I guess the issue was happened because the entry point was not updated after I checkout to main branch.
