### ISSUE TITLE
Docs: Systematically verify and update redirects

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-core#6508]
As just discussed with @giovannipizzi, @agoscinski, and @khsrali, this is to record the task of systematically checking the [redirects](https://github.com/aiidateam/aiida-core/blob/main/docs/source/redirects.txt) for old RTD pages of 0.x, 1.x, and 2.x versions, as old, broken links are often still highly ranked Google search results.

This could possibly be done as part of the documentation overhaul planned for the coding week, if the time allows.

Though, if we also have the time and decide to significantly update the documentation (such as has recently been done with the installation section[^1]), then this should be done afterward, of course. To be discussed.

There have been similar issues in the past (e.g. #5035, #5694), but these were closed without fully solving the problem.

[^1]: Actually, right now, the top Google results for "aiida core installation" are broken, so I'll open a PR to fix this ASAP.

**Comment by khsrali** [comment]
To see an example of this, just google: "aiida tab completion"
shows results from version 1.0.1 and 0.12.1

How to fix this?

**Comment by GeigerJ2** [comment]
I think fixing the Google search results will be difficult. Maybe we can fiddle with some SEO :D 
Though, would be great if at least most (all) redirects work.

**Comment by khsrali** [comment]
It's difficult, but absolutely necessarily to do. That's how many people search for features..
I'll open a separate issue on this
