### ISSUE TITLE
Add `verdi storage version|status`

### ISSUE THREAD

**Issue by danielhollas** [aiidateam/aiida-core#6547]
> For your use case [in AiiDAlab container deployment], I imagine it would be even better if there would simply be an endpoint that would check whether the storage is up to date or needs migrating. I think we could either add this to `verdi storage version` and have it actually validate the storage and return a specific exit code if it needs to be migrated, or we could add `verdi storage status` or something like that. These commands wouldn't have to check whether the daemon is running so could be made faster.

_Originally posted by @sphuber in https://github.com/aiidateam/aiida-core/issues/6546#issuecomment-2247076753_

**Comment by danielhollas** [comment]
@sphuber I like the idea of a new command instead of adding an extra logic to `verdi storage migrate`. Do you think this is something that could get into a patch release so that @superstar54 et al could you it for the QeApp demo server?

I think this might cut around 1.5s from the container startup (i.e. 10%). cc @giovannipizzi

**Comment by sphuber** [comment]
> @sphuber I like the idea of a new command instead of adding an extra logic to verdi storage migrate. Do you think this is something that could get into a patch release so that @superstar54 et al could you it for the QeApp demo server?

Could do yeah

**Comment by danielhollas** [comment]
Wait, is that a British "could do"? :thinking: :smile: 

![image](https://github.com/user-attachments/assets/202e13b1-5be3-4dcc-8437-d3e5f9226fbc)
