### ISSUE TITLE
Check if `Code` executable path exists and for execute permissions on `verdi code create`

### ISSUE THREAD

**Issue by GeigerJ2** [aiidateam/aiida-core#6629]
As discussed with @npaulish.

Related to #6597, but failing even earlier to make it more user-friendly.

**Comment by sphuber** [comment]
Note that we intentionally removed this check some time ago when creating a code and moved it to a separate command because it requires a transport which may not always be available when creating a code. And we don't want to block code creation just because there is no transport (temporarily).

**Comment by GeigerJ2** [comment]
Ah, OK, thanks @sphuber for the background information. Which command is that? Because iirc, before my PR #6597, `verdi code test`, where I would have expected this to happen, wouldn't check for that. For me, it's also fine to just keep this check at `verdi code test`, though.

**Comment by sphuber** [comment]
Sure, my point was just to not add the test to the code creation, but just add it to `verdi code test`. That checks the executable exists. You can simply add the executable check to that.
