### ISSUE TITLE
Provide deprecation path for `AIIDA_CONFIG_FOLDER`

### ISSUE THREAD

**Issue by khsrali** [aiidateam/aiida-core#6656]
Regarding merged PR https://github.com/aiidateam/aiida-core/pull/6610, I believe we still need to support  `AIIDA_CONFIG_FOLDER` within a deprecation path.

`aiida-workgraph` and ` aiida-pythonjob` now fail, because they used to use the public method `AIIDA_CONFIG_FOLDER`.

**Comment by unkcpz** [comment]
The ` AIIDA_CONFIG_FOLDER` was never recommended as public APIs. IMO, the deprecation warnings should only put for public APIs.
Instead of provide deprecation path, if it is necessary to expose it as public API, we should do that first.

**Comment by unkcpz** [comment]
There are exposed API for getting the config path

```python
from aiida.manage import get_config
config = get _config()
config_path = config.dirpath
```
