### ISSUE TITLE
Dependency `typing_extensions` used in the code based but not pinned.

### ISSUE THREAD

**Issue by khsrali** [aiidateam/aiida-core#6663]
`typing_extensions` is used here https://github.com/aiidateam/aiida-core/blob/0f0b88a39ff670fb452678c9b47ef6978e075005/src/aiida/engine/processes/functions.py#L56 but it's not listed as dependecies..

**Comment by unkcpz** [comment]
I think this makes sense and it is the correct way to do it. But I see your point, and I think we need in `pyproject.toml` add something like:

```toml
typing_extensions = [{ version = '*', python = "< 3.10" }]
```
