### ISSUE TITLE
Use general function for deleting AiiDA file repository

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-core#695]
One of the things that the `profile_delete` function in [aiida/cmdline/commands/profile.py](https://github.com/aiidateam/aiida_core/blob/develop/aiida/cmdline/commands/profile.py) needs to remove is the aiida file repository.

Once we support different modes of file storage (file system/object store/...) we should call the general-purpose function here.

**Comment by giovannipizzi** [comment]
Adding back to 2.0 just to make sure the delete-profile functionality does the right thing with the new-style repository

**Comment by sphuber** [comment]
Just checked that it does in fact still do the right thing, but I will take the opportunity to refactor and improve the code a bit.
