### ISSUE TITLE
DB transition from backend django to backend SQLA

### ISSUE THREAD

**Issue by waychal** [aiidateam/aiida-core#800]
Write a transition script to convert django database using AiiDA v0.10.0 to SQLA database

**Comment by waychal** [comment]
There is some inconsistency between django and sqla models because of its default behaviour. For example, django by default adds not null constraint to every column in table if it is not defined explicitly and SQLA allows null values by default in columns.
Due to this reason, SQLA backend needs migration to add not null constraint for columns. Also there is uuid type column present only in SQLA and not in Django.

Transitions scripts are available here (created branch from fix_export_import): https://github.com/waychal/aiida_core/tree/issue_800_backend_transition/aiida/backends/transitions

**Comment by waychal** [comment]
I have attached sql dumps for:
- db created with sqla profile (orig_db_sqla.sql)
- db created with django profile (orig_db_dj.sql)
- transition db from dj (v0.10.0) to sqla (v0.10.0) (transition_from_010dj_to_010sqla.sql)

[dumps.zip](https://github.com/aiidateam/aiida_core/files/1398288/dumps.zip)

**Comment by chrisjsewell** [comment]
closed in #5330
