### ISSUE TITLE
Code mpirunable/serial attribute

### ISSUE THREAD

**Issue by broeder-j** [aiidateam/aiida-core#970]
Maybe it makes sense to give a Code object an attribute if it is serial or mpi runable.
(and if code is not mpi runable, a calculation using that code should always have use_mpi=False.)

Because in general if one starts a serial version with mpirun usually some processes will crash, but not all and maybe the job/process will not be killed/terminated until out of wall time. This is something that probable cannot be tested by the code itself. But it is very easy for an AiiDA user to make this mistake, just use the wrong code and you have zombied all your wall time with powerful workflows.

What do you think?

**Comment by sphuber** [comment]
Closing this as this was implemented in v2.3, [see here](https://github.com/aiidateam/aiida-core/blob/main/CHANGELOG.md#controlling-usage-of-mpi)
